'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),fsp=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {createStaticHandler,createHttpServer,GameServer}=require('../server');
const WebSocket=require('ws');
const {AccountStore,ACCOUNT_PROGRESS_KEYS}=require('../account-store');
const client=require('../account-client');

function request(port,method,url,body,cookie,headers={}){return new Promise((resolve,reject)=>{const raw=body===undefined?'':JSON.stringify(body),req=http.request({host:'127.0.0.1',port,method,path:url,headers:{'content-type':'application/json','content-length':Buffer.byteLength(raw),...(cookie?{cookie}:{}),...headers}},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString()),cookie:res.headers['set-cookie']?.[0]?.split(';')[0],setCookie:res.headers['set-cookie']?.[0]}))});req.on('error',reject);req.end(raw)})}
async function fixture(t,fileContent){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-account-')),accountFile=path.join(directory,'accounts.json');if(fileContent!==undefined)fs.writeFileSync(accountFile,fileContent);const server=http.createServer(createStaticHandler({accountFile}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return{port:server.address().port,accountFile}}
const register=(port,login,email=`${login}@example.com`)=>request(port,'POST','/api/account/register',{login,email,password:'12345678'});

test('browser and server use the same explicit account progress allowlist',()=>assert.deepEqual(client.ACCOUNT_PROGRESS_KEYS,ACCOUNT_PROGRESS_KEYS));

test('registration starts empty and account progress never leaks between accounts',async t=>{const{port}=await fixture(t),a=await register(port,'kontoA'),payload={'swarmfall-stats':'{"coins":500}','swarmfall-achievements-v1':'["boss_1"]','swarmfall-unlocked':'["warrior"]','swarmfall-save-v1':'{"mode":"singleplayer"}'};assert.equal((await request(port,'PUT','/api/account/progress',{progress:payload,expectedRevision:0},a.cookie)).status,200);const b=await register(port,'kontoB');assert.deepEqual(b.body.progress,{});assert.equal(b.body.revision,0);const meB=await request(port,'GET','/api/account/me',undefined,b.cookie);assert.deepEqual(meB.body.progress,{});const loginA=await request(port,'POST','/api/account/login',{identifier:'kontoA',password:'12345678'});assert.deepEqual(loginA.body.progress,payload)});

test('fresh account reset removes coins, achievements, unlocks and save but preserves device identity',()=>{const values=new Map([['swarmfall-stats','{"coins":500}'],['swarmfall-achievements-v1','["boss_1"]'],['swarmfall-unlocked','["warrior"]'],['swarmfall-save-v1','save'],['swarmfall-installation-id','DEVICE-A'],['swarmfall-debug-collision','1']]),storage={getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};client.applyProgress(storage,{});assert.equal(values.get('swarmfall-installation-id'),'DEVICE-A');assert.equal(values.get('swarmfall-debug-collision'),'1');for(const key of ACCOUNT_PROGRESS_KEYS)assert.equal(values.has(key),false,key)});

test('only explicit progression keys persist while device keys are rejected',async t=>{const{port}=await fixture(t),account=await register(port,'keys'),progress=Object.fromEntries(ACCOUNT_PROGRESS_KEYS.map(key=>[key,`value:${key}`]));progress['swarmfall-installation-id']='DEVICE-A';progress['swarmfall-debug-multiplayer']='1';progress['swarmfall-language']='en';const saved=await request(port,'PUT','/api/account/progress',{progress,expectedRevision:0},account.cookie);assert.equal(saved.status,200);const me=await request(port,'GET','/api/account/me',undefined,account.cookie);assert.deepEqual(me.body.progress,Object.fromEntries(ACCOUNT_PROGRESS_KEYS.map(key=>[key,`value:${key}`])))});

test('two-device stale revision returns a typed 409 conflict',async t=>{const{port}=await fixture(t),deviceA=await register(port,'conflict'),deviceB=await request(port,'POST','/api/account/login',{identifier:'conflict',password:'12345678'});assert.equal(deviceB.body.revision,0);const newer=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'{"coins":10}'},expectedRevision:0},deviceA.cookie);assert.equal(newer.body.revision,1);const stale=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'{"coins":1}'},expectedRevision:0},deviceB.cookie);assert.equal(stale.status,409);assert.equal(stale.body.code,'REVISION_CONFLICT');assert.equal(stale.body.revision,1)});

test('single-flight client sync queues the newest snapshot without reverting it',async()=>{let state='old',active=0,maxActive=0,calls=[],release;const first=new Promise(resolve=>release=resolve),controller=new client.SyncController({getSnapshot:()=>({'swarmfall-stats':state}),send:async(progress,revision)=>{active++;maxActive=Math.max(maxActive,active);calls.push({progress,revision});if(calls.length===1)await first;active--;return{revision:revision+1}}});controller.initialize(0);controller.markDirty();await new Promise(resolve=>setImmediate(resolve));state='new';controller.markDirty();release();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(maxActive,1);assert.deepEqual(calls,[{progress:{'swarmfall-stats':'old'},revision:0},{progress:{'swarmfall-stats':'new'},revision:1}])});

test('offline autosave failure stays dirty without an immediate retry loop',async()=>{let calls=0,retryCallback,statuses=[],controller=new client.SyncController({getSnapshot:()=>({}),send:async()=>{calls++;throw new Error('offline')},onState:state=>statuses.push(state),setTimer:callback=>{retryCallback=callback;return 1},clearTimer:()=>{}});controller.initialize(0);controller.markDirty();while(controller.inFlight)await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);assert.equal(controller.dirty,true);assert.equal(typeof retryCallback,'function');assert.equal(statuses.at(-1),'error')});

test('a later retry saves the dirty snapshot and advances revision',async()=>{let calls=0,retryCallback,statuses=[],controller=new client.SyncController({getSnapshot:()=>({'swarmfall-stats':'latest'}),send:async(progress,revision)=>{calls++;if(calls===1)throw new Error('offline');return{revision:revision+1}},onState:state=>statuses.push(state),setTimer:callback=>{retryCallback=callback;return 1},clearTimer:()=>{}});controller.initialize(4);controller.markDirty();while(controller.inFlight)await new Promise(resolve=>setImmediate(resolve));assert.equal(controller.dirty,true);retryCallback();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,2);assert.equal(controller.revision,5);assert.equal(statuses.at(-1),'saved')});

test('multiplayer reconciliation advances revision before the next autosave',async()=>{const calls=[],local={'swarmfall-stats':'old'},controller=new client.SyncController({getSnapshot:()=>({...local}),onReconcile:update=>Object.assign(local,update.progress),send:async(progress,revision)=>{calls.push({progress,revision});return{revision:revision+1}}});controller.initialize(4);assert.equal(controller.reconcile({revision:5,progress:{'swarmfall-stats':'authoritative'}}),true);controller.markDirty();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls[0].revision,5);assert.equal(calls[0].progress['swarmfall-stats'],'authoritative');assert.equal(controller.revision,6)});

test('in-flight PUT racing settlement rebases without a false conflict',async()=>{let rejectFirst,calls=[],local={'swarmfall-modes':'["normal"]','swarmfall-stats':'old'},controller=new client.SyncController({getSnapshot:()=>({...local}),onReconcile:update=>Object.assign(local,update.progress),send:(progress,revision)=>{calls.push({progress,revision});if(calls.length===1)return new Promise((resolve,reject)=>rejectFirst=reject);return Promise.resolve({revision:revision+1})}});controller.initialize(4);controller.markDirty();await new Promise(resolve=>setImmediate(resolve));controller.reconcile({revision:5,progress:{'swarmfall-stats':'settled'}});const conflict=new Error('conflict');conflict.code='REVISION_CONFLICT';conflict.revision=5;rejectFirst(conflict);while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(calls.map(call=>call.revision),[4,5]);assert.equal(calls[1].progress['swarmfall-modes'],'["normal"]');assert.equal(calls[1].progress['swarmfall-stats'],'settled');assert.equal(controller.enabled,true);assert.equal(controller.revision,6)});

test('concurrent writes for different accounts are serialized without lost data',async t=>{const{port}=await fixture(t),a=await register(port,'parallelA'),b=await register(port,'parallelB'),[saveA,saveB]=await Promise.all([request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'A'},expectedRevision:0},a.cookie),request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'B'},expectedRevision:0},b.cookie)]);assert.equal(saveA.status,200);assert.equal(saveB.status,200);const[meA,meB]=await Promise.all([request(port,'GET','/api/account/me',undefined,a.cookie),request(port,'GET','/api/account/me',undefined,b.cookie)]);assert.equal(meA.body.progress['swarmfall-stats'],'A');assert.equal(meB.body.progress['swarmfall-stats'],'B')});

test('a corrupted existing account file returns controlled error and is never overwritten',async t=>{const corrupted='{ definitely not json',fixtureData=await fixture(t,corrupted),response=await register(fixtureData.port,'cannotwrite');assert.equal(response.status,503);assert.equal(response.body.code,'ACCOUNT_STORE_CORRUPTED');assert.equal(await fsp.readFile(fixtureData.accountFile,'utf8'),corrupted)});

test('failed persistence leaves AccountStore memory and revision unchanged',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'account-cow-')),file=path.join(directory,'accounts.json');t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));class FailingStore extends AccountStore{async persist(data){if(this.fail)throw new Error('disk full');return super.persist(data)}}const store=new FailingStore(file);await store.mutate(data=>data.users.push({id:'u',progress:{'swarmfall-stats':'before'},revision:2}));store.fail=true;await assert.rejects(store.mutate(data=>{data.users[0].revision=3;data.users[0].progress['swarmfall-stats']='ghost'}),/disk full/);const current=await store.read(data=>structuredClone(data.users[0]));assert.equal(current.revision,2);assert.equal(current.progress['swarmfall-stats'],'before');const disk=JSON.parse(await fsp.readFile(file,'utf8'));assert.equal(disk.users[0].revision,2)});

test('expired session has a typed response and matching custom client message',async t=>{const initial=await fixture(t),account=await register(initial.port,'expired'),database=JSON.parse(await fsp.readFile(initial.accountFile,'utf8'));for(const session of Object.values(database.sessions))session.expiresAt=0;await fsp.writeFile(initial.accountFile,JSON.stringify(database));await new Promise(resolve=>initial.port&&resolve());const secondServer=http.createServer(createStaticHandler({accountFile:initial.accountFile}));await new Promise(resolve=>secondServer.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>secondServer.close(resolve)));const response=await request(secondServer.address().port,'GET','/api/account/me',undefined,account.cookie);assert.equal(response.status,401);assert.equal(response.body.code,'SESSION_EXPIRED');assert.match(client.MESSAGES.expired,/Sesja wygasła/)});

test('custom validation covers empty and malformed fields without native bubbles',()=>{assert.match(client.validate('login',{identifier:'',password:''}),/login/);assert.match(client.validate('login',{identifier:'?',password:'12345678'}),/Login musi/);assert.match(client.validate('register',{login:'',email:'',password:''}),/Wpisz login/);assert.match(client.validate('register',{login:'?',email:'x',password:'12345678'}),/Login musi/);assert.match(client.validate('register',{login:'valid',email:'',password:'12345678'}),/Wpisz adres/);assert.match(client.validate('register',{login:'valid',email:'bad',password:'12345678'}),/prawidłowy/);assert.match(client.validate('register',{login:'valid',email:'a@b.pl',password:'1'}),/8 znaków/);const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.equal((html.match(/<form class="account-form[^>]*novalidate/g)||[]).length,2);assert.doesNotMatch(html,/<form class="account-form[^>]*\srequired/)});

test('account tabs hide the inactive form and authenticated boot starts neutral',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),css=fs.readFileSync(path.join(__dirname,'..','style.css'),'utf8'),source=fs.readFileSync(path.join(__dirname,'..','account-client.js'),'utf8');assert.match(html,/account-modal auth-loading/);assert.equal((html.match(/<form class="account-form hidden"/g)||[]).length,1);assert.match(css,/\.account-form\.hidden\{display:none\}/);assert.match(css,/\.auth-loading \.account-form/);assert.match(source,/forms\.forEach\(form=>form\.classList\.toggle\('hidden'/);assert.doesNotMatch(source,/Konto utworzone\.|Zalogowano\./)});

test('network and server failures have safe custom messages',()=>{assert.equal(client.MESSAGES.network,'Brak połączenia z siecią.');assert.equal(client.MESSAGES.server,'Serwer kont jest chwilowo niedostępny.');for(const value of Object.values(client.MESSAGES))assert.doesNotMatch(value,/Failed to fetch|TypeError|ECONN|stack/i)});

test('account client passes the Node syntax check',()=>{const result=spawnSync(process.execPath,['--check',path.join(__dirname,'..','account-client.js')],{encoding:'utf8'});assert.equal(result.status,0,result.stderr)});

test('password bounds, secure cookies and auth rate limiting are enforced',async t=>{const{port}=await fixture(t);assert.equal((await request(port,'POST','/api/account/register',{login:'short',email:'s@example.com',password:'1234567'})).status,400);assert.equal((await request(port,'POST','/api/account/register',{login:'longpass',email:'l@example.com',password:'x'.repeat(129)})).status,400);const secure=await request(port,'POST','/api/account/register',{login:'secure',email:'secure@example.com',password:'12345678'},null,{'x-forwarded-proto':'https'});assert.match(secure.setCookie,/HttpOnly/);assert.match(secure.setCookie,/SameSite=Strict/);assert.match(secure.setCookie,/Secure/);let last;for(let i=0;i<9;i++)last=await request(port,'POST','/api/account/login',{identifier:'none',password:'12345678'});assert.equal(last.status,429)});

function waitMessage(socket,type){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`timeout: ${type}`)),2000),listener=raw=>{const message=JSON.parse(raw);if(message.type!==type)return;clearTimeout(timer);socket.off('message',listener);resolve(message)};socket.on('message',listener)})}
async function sendWait(socket,payload,type){const waiting=waitMessage(socket,type);socket.send(JSON.stringify(payload));return waiting}
test('WebSocket session settles authoritative multiplayer stats once across reconnect',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-mp-account-')),accountFile=path.join(directory,'accounts.json'),runtime=createHttpServer(new GameServer(),{accountFile});await new Promise(resolve=>runtime.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>runtime.server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const port=runtime.server.address().port,account=await register(port,'mpreward'),url=`ws://127.0.0.1:${port}`;let socket=new WebSocket(url,{headers:{Cookie:account.cookie}});await new Promise(resolve=>socket.once('open',resolve));const hello=await sendWait(socket,{type:'hello',installationId:'device-a',unlocked:[],maps:['ruins']},'helloAck');await sendWait(socket,{type:'createLobby'},'lobbyState');const lobby=[...runtime.core.lobbies.values()][0];runtime.core.start(lobby);socket.close();await new Promise(resolve=>socket.once('close',resolve));socket=new WebSocket(url,{headers:{Cookie:account.cookie}});await new Promise(resolve=>socket.once('open',resolve));await sendWait(socket,{type:'hello',installationId:'device-a',unlocked:[],maps:['ruins'],resume:{playerId:hello.playerId,reconnectToken:hello.reconnectToken}},'helloAck');const player=lobby.game.players[hello.playerId];player.coins=7;player.kills=11;lobby.game.time=125;player.alive=false;assert.equal(runtime.core.endIfDefeated(lobby),true);await lobby.game.settlementPromise;lobby.game.settlementPromise=null;await runtime.core.settleMatchProgress(lobby);const me=await request(port,'GET','/api/account/me',undefined,account.cookie),stats=JSON.parse(me.body.progress['swarmfall-stats']);assert.equal(stats.coins,7);assert.equal(stats.totalKills,11);assert.equal(stats.bestKills,11);assert.equal(stats.totalTime,125);assert.equal(stats.bestTime,125);assert.equal(stats.characterGames.scout,1);socket.close()});

test('unauthenticated multiplayer result cannot update an account',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-mp-anon-')),accountFile=path.join(directory,'accounts.json'),runtime=createHttpServer(new GameServer(),{accountFile});await new Promise(resolve=>runtime.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>runtime.server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const port=runtime.server.address().port,account=await register(port,'protected'),clientConnection=runtime.core.addClient(()=>{});runtime.core.handle(clientConnection,{type:'hello',installationId:'anonymous',unlocked:[],maps:['ruins']});runtime.core.handle(clientConnection,{type:'createLobby'});const lobby=runtime.core.lobbies.get(clientConnection.lobby);runtime.core.start(lobby);const player=lobby.game.players[clientConnection.playerId];player.coins=999;player.kills=999;player.alive=false;runtime.core.endIfDefeated(lobby);await lobby.game.settlementPromise;const me=await request(port,'GET','/api/account/me',undefined,account.cookie);assert.deepEqual(me.body.progress,{})});

test('failed multiplayer settlement retries and awards exactly once',async()=>{let calls=0,awards=0,settled=false;const store={settleMultiplayerMatch:async()=>{calls++;if(calls===1)throw new Error('temporary');if(settled)return{applied:false,reason:'duplicate',revision:1};settled=true;awards++;return{applied:true,revision:1,progress:{'swarmfall-stats':'{}'}}}},core=new GameServer(()=>1000,()=>.5,store,{settlementRetryDelays:[1]}),player={id:'p',accountUserId:'u',coins:3,kills:4,character:'scout'},lobby={game:{matchId:'match',time:20,players:{p:player}}};await core.settleMatchProgress(lobby);assert.equal(calls,2);assert.equal(awards,1);lobby.game.settlementPromise=null;await core.settleMatchProgress(lobby);assert.equal(awards,1)});
