'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),fsp=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {createStaticHandler,createHttpServer,GameServer,SlidingWindowLimiter}=require('../server');
const WebSocket=require('ws');
const {AccountStore,ACCOUNT_PROGRESS_KEYS}=require('../account-store');
const client=require('../account-client');

function request(port,method,url,body,cookie,headers={}){return new Promise((resolve,reject)=>{const raw=body===undefined?'':JSON.stringify(body),req=http.request({host:'127.0.0.1',port,method,path:url,headers:{'content-type':'application/json','content-length':Buffer.byteLength(raw),...(cookie?{cookie}:{}),...headers}},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString()),cookie:res.headers['set-cookie']?.[0]?.split(';')[0],setCookie:res.headers['set-cookie']?.[0]}))});req.on('error',reject);req.end(raw)})}
async function fixture(t,fileContent,handlerOptions={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-account-')),accountFile=path.join(directory,'accounts.json');if(fileContent!==undefined)fs.writeFileSync(accountFile,fileContent);const server=http.createServer(createStaticHandler({accountFile,...handlerOptions}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return{port:server.address().port,accountFile}}
const register=(port,login,email=`${login}@example.com`)=>request(port,'POST','/api/account/register',{login,email,password:'12345678'});

test('browser and server use the same explicit account progress allowlist',()=>assert.deepEqual(client.ACCOUNT_PROGRESS_KEYS,ACCOUNT_PROGRESS_KEYS));

test('fresh visit without cookie is unauthenticated without an error message',async t=>{const{port}=await fixture(t),response=await request(port,'GET','/api/account/me');assert.equal(response.status,401);assert.equal(response.body.code,'NOT_AUTHENTICATED');assert.deepEqual(client.authFailureState(response.body.code),{showLogin:true,message:''})});

test('registration starts empty and account progress never leaks between accounts',async t=>{const{port}=await fixture(t),a=await register(port,'kontoA'),payload={'swarmfall-stats':'{"coins":500}','swarmfall-achievements-v1':'["boss_1"]','swarmfall-unlocked':'["warrior"]','swarmfall-save-v1':'{"mode":"singleplayer"}'};assert.equal((await request(port,'PUT','/api/account/progress',{progress:payload,expectedRevision:0},a.cookie)).status,200);const b=await register(port,'kontoB');assert.ok(a.body.user.id);assert.ok(b.body.user.id);assert.notEqual(a.body.user.id,b.body.user.id);assert.deepEqual(b.body.progress,{});assert.equal(b.body.revision,0);const meB=await request(port,'GET','/api/account/me',undefined,b.cookie);assert.deepEqual(meB.body.progress,{});const loginA=await request(port,'POST','/api/account/login',{identifier:'kontoA',password:'12345678'});assert.equal(loginA.body.user.id,a.body.user.id);const meA=await request(port,'GET','/api/account/me',undefined,loginA.cookie);assert.equal(meA.body.user.id,a.body.user.id);assert.deepEqual(loginA.body.progress,{'swarmfall-save-v1':payload['swarmfall-save-v1']})});

test('fresh account reset removes coins, achievements, unlocks and save but preserves device identity',()=>{const values=new Map([['swarmfall-stats','{"coins":500}'],['swarmfall-achievements-v1','["boss_1"]'],['swarmfall-unlocked','["warrior"]'],['swarmfall-save-v1','save'],['swarmfall-installation-id','DEVICE-A'],['swarmfall-debug-collision','1']]),storage={getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};client.applyProgress(storage,{});assert.equal(values.get('swarmfall-installation-id'),'DEVICE-A');assert.equal(values.get('swarmfall-debug-collision'),'1');for(const key of ACCOUNT_PROGRESS_KEYS)assert.equal(values.has(key),false,key)});

test('account reconciliation updates authoritative coins without deleting local-only single-player progress',()=>{const values=new Map([['swarmfall-stats','{"coins":35}'],['swarmfall-singleplayer-stats-v1','{"totalKills":12,"coins":0}'],['swarmfall-singleplayer-achievements-v1','["boss_1"]'],['swarmfall-singleplayer-modes','["normal"]']]),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};client.applyProgress(storage,{'swarmfall-stats':'{"coins":10}'});assert.equal(values.get('swarmfall-stats'),'{"coins":10}');assert.equal(values.get('swarmfall-singleplayer-stats-v1'),'{"totalKills":12,"coins":0}');assert.equal(values.get('swarmfall-singleplayer-achievements-v1'),'["boss_1"]');assert.equal(values.get('swarmfall-singleplayer-modes'),'["normal"]')});

test('only explicit progression keys persist while device keys are rejected',async t=>{const{port}=await fixture(t),account=await register(port,'keys'),progress=Object.fromEntries(ACCOUNT_PROGRESS_KEYS.map(key=>[key,`value:${key}`]));progress['swarmfall-installation-id']='DEVICE-A';progress['swarmfall-debug-multiplayer']='1';progress['swarmfall-language']='en';const saved=await request(port,'PUT','/api/account/progress',{progress,expectedRevision:0},account.cookie);assert.equal(saved.status,200);const me=await request(port,'GET','/api/account/me',undefined,account.cookie);assert.deepEqual(me.body.progress,Object.fromEntries(['swarmfall-save-v1','swarmfall-character','swarmfall-map','swarmfall-mode'].map(key=>[key,`value:${key}`])))});

test('two-device stale revision returns a typed 409 conflict',async t=>{const{port}=await fixture(t),deviceA=await register(port,'conflict'),deviceB=await request(port,'POST','/api/account/login',{identifier:'conflict',password:'12345678'});assert.equal(deviceB.body.revision,0);const newer=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'{"coins":10}'},expectedRevision:0},deviceA.cookie);assert.equal(newer.body.revision,1);const stale=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'{"coins":1}'},expectedRevision:0},deviceB.cookie);assert.equal(stale.status,409);assert.equal(stale.body.code,'REVISION_CONFLICT');assert.equal(stale.body.revision,1)});

test('authenticated mutation limiter allows normal traffic, bounds spam and recovers',async t=>{let now=0;const mutationLimiter=new SlidingWindowLimiter({limit:3,windowMs:100,now:()=>now}),{port}=await fixture(t,undefined,{mutationLimiter}),account=await register(port,'mutationlimit');for(let revision=0;revision<3;revision++){const response=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-save-v1':String(revision)},expectedRevision:revision},account.cookie);assert.equal(response.status,200)}for(let requestIndex=0;requestIndex<20;requestIndex++){const blocked=await request(port,'POST','/api/account/progression',{expectedRevision:3,operation:{id:`spam-${requestIndex}`,type:'awardCurrency',payload:{amount:1}}},account.cookie);assert.equal(blocked.status,429);assert.equal(blocked.body.code,'RATE_LIMITED')}assert.equal(mutationLimiter.buckets.get(account.body.user.id).length,3);now=101;const recovered=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-save-v1':'recovered'},expectedRevision:3},account.cookie);assert.equal(recovered.status,200)});

test('180/min mutation limit admits intensive legal autosaves and rejects the next mutation',async t=>{const{port}=await fixture(t),account=await register(port,'legalburst');let revision=0;for(let index=0;index<180;index++){const response=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-save-v1':String(index)},expectedRevision:revision},account.cookie);assert.equal(response.status,200,response.body.code);revision=response.body.revision}const blocked=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-save-v1':'blocked'},expectedRevision:revision},account.cookie);assert.equal(blocked.status,429);assert.equal(blocked.body.code,'RATE_LIMITED')});
test('single-flight client sync queues the newest snapshot without reverting it',async()=>{let state='old',active=0,maxActive=0,calls=[],release;const first=new Promise(resolve=>release=resolve),controller=new client.SyncController({getSnapshot:()=>({'swarmfall-stats':state}),send:async(progress,revision)=>{active++;maxActive=Math.max(maxActive,active);calls.push({progress,revision});if(calls.length===1)await first;active--;return{revision:revision+1}}});controller.initialize(0);controller.markDirty();await new Promise(resolve=>setImmediate(resolve));state='new';controller.markDirty();release();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(maxActive,1);assert.deepEqual(calls,[{progress:{'swarmfall-stats':'old'},revision:0},{progress:{'swarmfall-stats':'new'},revision:1}])});

test('offline autosave failure stays dirty without an immediate retry loop',async()=>{let calls=0,retryCallback,statuses=[],controller=new client.SyncController({getSnapshot:()=>({}),send:async()=>{calls++;throw new Error('offline')},onState:state=>statuses.push(state),setTimer:callback=>{retryCallback=callback;return 1},clearTimer:()=>{}});controller.initialize(0);controller.markDirty();while(controller.inFlight)await new Promise(resolve=>setImmediate(resolve));await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);assert.equal(controller.dirty,true);assert.equal(typeof retryCallback,'function');assert.equal(statuses.at(-1),'error')});

test('a later retry saves the dirty snapshot and advances revision',async()=>{let calls=0,retryCallback,statuses=[],controller=new client.SyncController({getSnapshot:()=>({'swarmfall-stats':'latest'}),send:async(progress,revision)=>{calls++;if(calls===1)throw new Error('offline');return{revision:revision+1}},onState:state=>statuses.push(state),setTimer:callback=>{retryCallback=callback;return 1},clearTimer:()=>{}});controller.initialize(4);controller.markDirty();while(controller.inFlight)await new Promise(resolve=>setImmediate(resolve));assert.equal(controller.dirty,true);retryCallback();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,2);assert.equal(controller.revision,5);assert.equal(statuses.at(-1),'saved')});

test('multiplayer reconciliation advances revision before the next autosave',async()=>{const calls=[],local={'swarmfall-stats':'old'},controller=new client.SyncController({getSnapshot:()=>({...local}),onReconcile:update=>Object.assign(local,update.progress),send:async(progress,revision)=>{calls.push({progress,revision});return{revision:revision+1}}});controller.initialize(4);assert.equal(controller.reconcile({revision:5,progress:{'swarmfall-stats':'authoritative'}}),true);controller.markDirty();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(calls[0].revision,5);assert.equal(calls[0].progress['swarmfall-stats'],'authoritative');assert.equal(controller.revision,6)});

test('in-flight PUT racing settlement rebases without a false conflict',async()=>{let rejectFirst,calls=[],local={'swarmfall-modes':'["normal"]','swarmfall-stats':'old'},controller=new client.SyncController({getSnapshot:()=>({...local}),onReconcile:update=>Object.assign(local,update.progress),send:(progress,revision)=>{calls.push({progress,revision});if(calls.length===1)return new Promise((resolve,reject)=>rejectFirst=reject);return Promise.resolve({revision:revision+1})}});controller.initialize(4);controller.markDirty();await new Promise(resolve=>setImmediate(resolve));controller.reconcile({revision:5,progress:{'swarmfall-stats':'settled'}});const conflict=new Error('conflict');conflict.code='REVISION_CONFLICT';conflict.revision=5;rejectFirst(conflict);while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(calls.map(call=>call.revision),[4,5]);assert.equal(calls[1].progress['swarmfall-modes'],'["normal"]');assert.equal(calls[1].progress['swarmfall-stats'],'settled');assert.equal(controller.enabled,true);assert.equal(controller.revision,6)});

test('concurrent writes for different accounts are serialized without lost data',async t=>{const{port}=await fixture(t),a=await register(port,'parallelA'),b=await register(port,'parallelB'),[saveA,saveB]=await Promise.all([request(port,'PUT','/api/account/progress',{progress:{'swarmfall-save-v1':'A'},expectedRevision:0},a.cookie),request(port,'PUT','/api/account/progress',{progress:{'swarmfall-save-v1':'B'},expectedRevision:0},b.cookie)]);assert.equal(saveA.status,200);assert.equal(saveB.status,200);const[meA,meB]=await Promise.all([request(port,'GET','/api/account/me',undefined,a.cookie),request(port,'GET','/api/account/me',undefined,b.cookie)]);assert.equal(meA.body.progress['swarmfall-save-v1'],'A');assert.equal(meB.body.progress['swarmfall-save-v1'],'B')});

test('a corrupted existing account file returns controlled error and is never overwritten',async t=>{const corrupted='{ definitely not json',fixtureData=await fixture(t,corrupted),response=await register(fixtureData.port,'cannotwrite');assert.equal(response.status,503);assert.equal(response.body.code,'ACCOUNT_STORE_CORRUPTED');assert.equal(await fsp.readFile(fixtureData.accountFile,'utf8'),corrupted)});

test('failed persistence leaves AccountStore memory and revision unchanged',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'account-cow-')),file=path.join(directory,'accounts.json');t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));class FailingStore extends AccountStore{async persist(data){if(this.fail)throw new Error('disk full');return super.persist(data)}}const store=new FailingStore(file);await store.mutate(data=>data.users.push({id:'u',progress:{'swarmfall-stats':'before'},revision:2}));store.fail=true;await assert.rejects(store.mutate(data=>{data.users[0].revision=3;data.users[0].progress['swarmfall-stats']='ghost'}),/disk full/);const current=await store.read(data=>structuredClone(data.users[0]));assert.equal(current.revision,2);assert.equal(current.progress['swarmfall-stats'],'before');const disk=JSON.parse(await fsp.readFile(file,'utf8'));assert.equal(disk.users[0].revision,2)});

test('transient account disk failure is retryable and preserves the semantic operation id',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'account-retry-')),file=path.join(directory,'accounts.json'),store=new AccountStore(file),{port}=await fixture(t,undefined,{accountStore:store}),account=await register(port,'diskretry');t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));await store.mutate(data=>{const user=data.users.find(candidate=>candidate.login==='diskretry');user.progress['swarmfall-stats']='{"coins":30}'});const persist=store.persist.bind(store);let fail=true;store.persist=async data=>{if(fail){fail=false;const error=new Error('disk unavailable');error.code='ACCOUNT_STORE_WRITE_FAILED';throw error}return persist(data)};const operation={id:'stable-disk-operation',type:'purchaseCharacter',payload:{character:'warrior'}},first=await request(port,'POST','/api/account/progression',{expectedRevision:0,operation},account.cookie);assert.equal(first.status,503);assert.equal(first.body.code,'ACCOUNT_STORE_WRITE_FAILED');const retry=await request(port,'POST','/api/account/progression',{expectedRevision:0,operation},account.cookie);assert.equal(retry.status,200);assert.equal(retry.body.revision,1);const duplicate=await request(port,'POST','/api/account/progression',{expectedRevision:1,operation},account.cookie);assert.equal(duplicate.status,200);assert.equal(duplicate.body.duplicate,true);assert.deepEqual(JSON.parse(duplicate.body.progress['swarmfall-unlocked']),['warrior'])});
test('expired session has a typed response and matching custom client message',async t=>{const initial=await fixture(t),account=await register(initial.port,'expired'),database=JSON.parse(await fsp.readFile(initial.accountFile,'utf8'));for(const session of Object.values(database.sessions))session.expiresAt=0;await fsp.writeFile(initial.accountFile,JSON.stringify(database));await new Promise(resolve=>initial.port&&resolve());const secondServer=http.createServer(createStaticHandler({accountFile:initial.accountFile}));await new Promise(resolve=>secondServer.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>secondServer.close(resolve)));const response=await request(secondServer.address().port,'GET','/api/account/me',undefined,account.cookie);assert.equal(response.status,401);assert.equal(response.body.code,'SESSION_EXPIRED');assert.deepEqual(client.authFailureState(response.body.code),{showLogin:true,message:client.MESSAGES.expired});const cleaned=JSON.parse(await fsp.readFile(initial.accountFile,'utf8'));assert.deepEqual(cleaned.sessions,{})});

test('custom validation covers empty and malformed fields without native bubbles',()=>{assert.match(client.validate('login',{identifier:'',password:''}),/login/);assert.match(client.validate('login',{identifier:'?',password:'12345678'}),/Login musi/);assert.match(client.validate('register',{login:'',email:'',password:''}),/Wpisz login/);assert.match(client.validate('register',{login:'?',email:'x',password:'12345678'}),/Login musi/);assert.match(client.validate('register',{login:'valid',email:'',password:'12345678'}),/Wpisz adres/);assert.match(client.validate('register',{login:'valid',email:'bad',password:'12345678'}),/prawidłowy/);assert.match(client.validate('register',{login:'valid',email:'a@b.pl',password:'1'}),/8 znaków/);const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.equal((html.match(/<form class="account-form[^>]*novalidate/g)||[]).length,2);assert.doesNotMatch(html,/<form class="account-form[^>]*\srequired/)});

test('account tabs hide the inactive form and authenticated boot starts neutral',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),css=fs.readFileSync(path.join(__dirname,'..','style.css'),'utf8'),source=fs.readFileSync(path.join(__dirname,'..','account-client.js'),'utf8');assert.match(html,/account-modal auth-loading/);assert.equal((html.match(/<form class="account-form hidden"/g)||[]).length,1);assert.match(css,/\.account-form\.hidden\{display:none\}/);assert.match(css,/\.auth-loading \.account-form/);assert.match(source,/forms\.forEach\(form=>form\.classList\.toggle\('hidden'/);assert.doesNotMatch(source,/Konto utworzone\.|Zalogowano\./)});

test('network and server failures have safe custom messages',()=>{assert.equal(client.MESSAGES.network,'Brak połączenia z siecią.');assert.equal(client.MESSAGES.server,'Serwer kont jest chwilowo niedostępny.');for(const value of Object.values(client.MESSAGES))assert.doesNotMatch(value,/Failed to fetch|TypeError|ECONN|stack/i)});

test('account client passes the Node syntax check',()=>{const result=spawnSync(process.execPath,['--check',path.join(__dirname,'..','account-client.js')],{encoding:'utf8'});assert.equal(result.status,0,result.stderr)});

test('password bounds, secure cookies and auth rate limiting are enforced',async t=>{const{port}=await fixture(t);assert.equal((await request(port,'POST','/api/account/register',{login:'short',email:'s@example.com',password:'1234567'})).status,400);assert.equal((await request(port,'POST','/api/account/register',{login:'longpass',email:'l@example.com',password:'x'.repeat(129)})).status,400);const secure=await request(port,'POST','/api/account/register',{login:'secure',email:'secure@example.com',password:'12345678'},null,{'x-forwarded-proto':'https'});assert.match(secure.setCookie,/HttpOnly/);assert.match(secure.setCookie,/SameSite=Strict/);assert.doesNotMatch(secure.setCookie,/; Secure/);let last;for(let i=0;i<9;i++)last=await request(port,'POST','/api/account/login',{identifier:'none',password:'12345678'});assert.equal(last.status,429)});

function waitMessage(socket,type){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`timeout: ${type}`)),2000),listener=raw=>{const message=JSON.parse(raw);if(message.type!==type)return;clearTimeout(timer);socket.off('message',listener);resolve(message)};socket.on('message',listener)})}
async function sendWait(socket,payload,type){const waiting=waitMessage(socket,type);socket.send(JSON.stringify(payload));return waiting}
test('WebSocket session settles authoritative multiplayer stats once across reconnect',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-mp-account-')),accountFile=path.join(directory,'accounts.json'),runtime=createHttpServer(new GameServer(),{accountFile});await new Promise(resolve=>runtime.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>runtime.server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const port=runtime.server.address().port,account=await register(port,'mpreward'),url=`ws://127.0.0.1:${port}`;let socket=new WebSocket(url,{headers:{Cookie:account.cookie}});await new Promise(resolve=>socket.once('open',resolve));const hello=await sendWait(socket,{type:'hello',installationId:'device-a',unlocked:[],maps:['ruins']},'helloAck');await sendWait(socket,{type:'createLobby'},'lobbyState');const lobby=[...runtime.core.lobbies.values()][0];runtime.core.start(lobby);socket.close();await new Promise(resolve=>socket.once('close',resolve));socket=new WebSocket(url,{headers:{Cookie:account.cookie}});await new Promise(resolve=>socket.once('open',resolve));await sendWait(socket,{type:'hello',installationId:'device-a',unlocked:[],maps:['ruins'],resume:{playerId:hello.playerId,reconnectToken:hello.reconnectToken}},'helloAck');const player=lobby.game.players[hello.playerId];player.coins=7;player.kills=11;lobby.game.time=125;player.alive=false;assert.equal(runtime.core.endIfDefeated(lobby),true);await lobby.game.settlementPromise;lobby.game.settlementPromise=null;await runtime.core.settleMatchProgress(lobby);const me=await request(port,'GET','/api/account/me',undefined,account.cookie),stats=JSON.parse(me.body.progress['swarmfall-stats']);assert.equal(stats.coins,7);assert.equal(stats.totalKills,11);assert.equal(stats.bestKills,11);assert.equal(stats.totalTime,125);assert.equal(stats.bestTime,125);assert.equal(stats.characterGames.scout,1);socket.close()});

test('unauthenticated multiplayer result cannot update an account',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-mp-anon-')),accountFile=path.join(directory,'accounts.json'),runtime=createHttpServer(new GameServer(),{accountFile});await new Promise(resolve=>runtime.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>runtime.server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const port=runtime.server.address().port,account=await register(port,'protected'),clientConnection=runtime.core.addClient(()=>{});runtime.core.handle(clientConnection,{type:'hello',installationId:'anonymous',unlocked:[],maps:['ruins']});runtime.core.handle(clientConnection,{type:'createLobby'});const lobby=runtime.core.lobbies.get(clientConnection.lobby);runtime.core.start(lobby);const player=lobby.game.players[clientConnection.playerId];player.coins=999;player.kills=999;player.alive=false;runtime.core.endIfDefeated(lobby);await lobby.game.settlementPromise;const me=await request(port,'GET','/api/account/me',undefined,account.cookie);assert.deepEqual(me.body.progress,{})});

test('failed multiplayer settlement retries and awards exactly once',async()=>{let calls=0,awards=0,settled=false;const store={settleMultiplayerMatch:async()=>{calls++;if(calls===1)throw new Error('temporary');if(settled)return{applied:false,reason:'duplicate',revision:1};settled=true;awards++;return{applied:true,revision:1,progress:{'swarmfall-stats':'{}'}}}},core=new GameServer(()=>1000,()=>.5,store,{settlementRetryDelays:[1]}),player={id:'p',accountUserId:'u',coins:3,kills:4,character:'scout'},lobby={game:{matchId:'match',time:20,players:{p:player}}};await core.settleMatchProgress(lobby);assert.equal(calls,2);assert.equal(awards,1);lobby.game.settlementPromise=null;await core.settleMatchProgress(lobby);assert.equal(awards,1)});

test('mid-match leave freezes authoritative time, coins and kills until later settlement',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-leave-time-')),accountFile=path.join(directory,'accounts.json'),runtime=createHttpServer(new GameServer(),{accountFile});await new Promise(resolve=>runtime.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>runtime.server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const port=runtime.server.address().port,account=await register(port,'leavetime'),token=account.cookie.slice('swarm_session='.length),identity=await runtime.accountStore.accountForToken(token),out=[],a=runtime.core.addClient(message=>out.push(message),identity.id),b=runtime.core.addClient(()=>{});runtime.core.handle(a,{type:'hello',installationId:'a',unlocked:[],maps:['ruins']});runtime.core.handle(a,{type:'createLobby'});const code=a.lobby;runtime.core.handle(b,{type:'hello',installationId:'b',unlocked:[],maps:['ruins']});runtime.core.handle(b,{type:'joinLobby',code});const lobby=runtime.core.lobbies.get(code);lobby.players.find(player=>player.id===b.playerId).ready=true;runtime.core.start(lobby);const playerA=lobby.game.players[a.playerId];lobby.game.time=120;playerA.coins=9;playerA.kills=13;runtime.core.handle(a,{type:'leaveLobby'});playerA.coins=999;playerA.kills=999;lobby.game.time=600;lobby.game.players[b.playerId].alive=false;runtime.core.endIfDefeated(lobby);await lobby.game.settlementPromise;lobby.game.settlementPromise=null;await runtime.core.settleMatchProgress(lobby);const me=await request(port,'GET','/api/account/me',undefined,account.cookie),stats=JSON.parse(me.body.progress['swarmfall-stats']);assert.equal(stats.totalTime,120);assert.equal(stats.coins,9);assert.equal(stats.totalKills,13);assert.equal(stats.characterGames.scout,1)});

test('grace-expired multiplayer player is archived and settled exactly once at disconnect time',async t=>{let now=1000;const directory=fs.mkdtempSync(path.join(os.tmpdir(),'expired-settlement-')),store=new AccountStore(path.join(directory,'accounts.json'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));await store.mutate(data=>data.users.push({id:'account-a',revision:0,progress:{}}));const core=new GameServer(()=>now,()=>.5,store),a=core.addClient(()=>{},'account-a'),b=core.addClient(()=>{});core.handle(a,{type:'hello',installationId:'expired-a',unlocked:[],maps:['ruins']});now+=1000;core.handle(a,{type:'createLobby'});now+=1000;core.handle(b,{type:'hello',installationId:'expired-b',unlocked:[],maps:['ruins']});now+=1000;core.handle(b,{type:'joinLobby',code:a.lobby});const lobby=core.lobbies.get(a.lobby);core.start(lobby);const player=lobby.game.players[a.playerId];lobby.game.time=75;player.coins=8;player.kills=12;core.disconnect(a);lobby.game.time=300;now+=16000;core.cleanup();assert.equal(lobby.game.players[a.playerId],undefined);assert.equal(lobby.game.settlementArchive[a.playerId].settlementSnapshot.time,75);lobby.game.players[b.playerId].alive=false;assert.equal(core.endIfDefeated(lobby),true);await lobby.game.settlementPromise;lobby.game.settlementPromise=null;await core.settleMatchProgress(lobby);const user=await store.read(data=>structuredClone(data.users[0])),stats=JSON.parse(user.progress['swarmfall-stats']);assert.equal(stats.coins,8);assert.equal(stats.totalKills,12);assert.equal(stats.totalTime,75);assert.equal(stats.characterGames.scout,1);assert.equal(user.settledMatches.length,1)});

test('settlement before cleanup uses the disconnect-time snapshot exactly once',async t=>{let now=1000;const directory=fs.mkdtempSync(path.join(os.tmpdir(),'early-settlement-')),store=new AccountStore(path.join(directory,'accounts.json'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));await store.mutate(data=>data.users.push({id:'account-a',revision:0,progress:{}}));const core=new GameServer(()=>now,()=>.5,store),a=core.addClient(()=>{},'account-a'),b=core.addClient(()=>{});core.handle(a,{type:'hello',installationId:'early-a',unlocked:[],maps:['ruins']});now+=1000;core.handle(a,{type:'createLobby'});now+=1000;core.handle(b,{type:'hello',installationId:'early-b',unlocked:[],maps:['ruins']});now+=1000;core.handle(b,{type:'joinLobby',code:a.lobby});const lobby=core.lobbies.get(a.lobby);core.start(lobby);const player=lobby.game.players[a.playerId];lobby.game.time=75;player.coins=8;player.kills=12;core.disconnect(a);lobby.game.time=300;player.coins=99;player.kills=99;player.alive=false;lobby.game.players[b.playerId].alive=false;assert.equal(core.endIfDefeated(lobby),true);await lobby.game.settlementPromise;lobby.game.settlementPromise=null;await core.settleMatchProgress(lobby);const user=await store.read(data=>structuredClone(data.users[0])),stats=JSON.parse(user.progress['swarmfall-stats']);assert.equal(stats.coins,8);assert.equal(stats.totalKills,12);assert.equal(stats.totalTime,75);assert.equal(stats.characterGames.scout,1);assert.equal(user.settledMatches.length,1)});

test('reconnect within grace clears the provisional settlement snapshot and does not settle early',async()=>{let now=1000,calls=0;const store={settleMultiplayerMatch:async()=>{calls++;return{applied:true,revision:1,progress:{}}}},core=new GameServer(()=>now,()=>.5,store),a=core.addClient(()=>{},'account-a');core.handle(a,{type:'hello',installationId:'grace-a',unlocked:[],maps:['ruins']});now+=1000;core.handle(a,{type:'createLobby'});const lobby=core.lobbies.get(a.lobby);core.start(lobby);const session=core.sessionsByPlayerId.get(a.playerId),player=lobby.game.players[a.playerId];lobby.game.time=20;player.coins=4;core.disconnect(a);assert.ok(player.disconnectSettlementSnapshot);now+=14000;const replacement=core.addClient(()=>{},'account-a');core.handle(replacement,{type:'hello',installationId:'grace-a-reconnect',resume:{playerId:a.playerId,reconnectToken:session.reconnectToken},unlocked:[],maps:['ruins']});core.cleanup();assert.equal(calls,0);assert.equal(lobby.game.settlementArchive[a.playerId],undefined);assert.equal(player.disconnectSettlementSnapshot,undefined);assert.equal(lobby.players.find(member=>member.id===a.playerId).connected,true)});

test('forged PUT cannot grant multiplayer entitlements',async t=>{const{port}=await fixture(t),account=await register(port,'forgedentitlements'),forged={'swarmfall-stats':'{"coins":999999}','swarmfall-achievements-v1':'["map_1"]','swarmfall-unlocked':'["warrior","druid"]'};const saved=await request(port,'PUT','/api/account/progress',{progress:forged,expectedRevision:0},account.cookie);assert.equal(saved.status,200);assert.deepEqual(saved.body.progress,{});const me=await request(port,'GET','/api/account/me',undefined,account.cookie);assert.deepEqual(me.body.progress,{})});

test('public progression accepts purchases but rejects self-awarded rewards',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'safe-progress-')),store=new AccountStore(path.join(directory,'accounts.json')),{port}=await fixture(t,undefined,{accountStore:store}),account=await register(port,'legalprogress');t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));await store.mutate(data=>{const user=data.users.find(candidate=>candidate.login==='legalprogress');user.progress['swarmfall-stats']='{"coins":30}'});for(const[type,payload]of[['awardCurrency',{amount:100}],['unlockAchievement',{id:'boss_1'}],['awardSingleplayerResult',{time:600,kills:500,character:'scout'}],['completeMap',{map:'ruins',mode:'normal'}]]){const response=await request(port,'POST','/api/account/progression',{expectedRevision:0,operation:{id:`forged-${type}`,type,payload}},account.cookie);assert.equal(response.status,403);assert.equal(response.body.code,'UNTRUSTED_PROGRESSION')}const purchase=await request(port,'POST','/api/account/progression',{expectedRevision:0,operation:{id:'purchase-warrior',type:'purchaseCharacter',payload:{character:'warrior'}}},account.cookie);assert.equal(purchase.status,200);assert.equal(purchase.body.revision,1);assert.equal(JSON.parse(purchase.body.progress['swarmfall-stats']).coins,0);assert.deepEqual(JSON.parse(purchase.body.progress['swarmfall-unlocked']),['warrior'])});

test('stale purchase reconciles then fails without changing authoritative coins or unlocks',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'stale-purchase-')),store=new AccountStore(path.join(directory,'accounts.json')),{port}=await fixture(t,undefined,{accountStore:store}),deviceA=await register(port,'stalebuyer'),deviceB=await request(port,'POST','/api/account/login',{identifier:'stalebuyer',password:'12345678'});t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));await store.mutate(data=>{const user=data.users.find(candidate=>candidate.login==='stalebuyer');user.progress['swarmfall-stats']='{"coins":60}'});const spent=await request(port,'POST','/api/account/progression',{expectedRevision:0,operation:{id:'device-a-warrior',type:'purchaseCharacter',payload:{character:'warrior'}}},deviceA.cookie);assert.equal(spent.status,200);assert.equal(JSON.parse(spent.body.progress['swarmfall-stats']).coins,30);const stale=await request(port,'POST','/api/account/progression',{expectedRevision:0,operation:{id:'device-b-druid',type:'purchaseCharacter',payload:{character:'druid'}}},deviceB.cookie);assert.equal(stale.status,409);assert.equal(stale.body.code,'REVISION_CONFLICT');assert.equal(JSON.parse(stale.body.progress['swarmfall-stats']).coins,30);const retry=await request(port,'POST','/api/account/progression',{expectedRevision:stale.body.revision,operation:{id:'device-b-druid',type:'purchaseCharacter',payload:{character:'druid'}}},deviceB.cookie);assert.equal(retry.status,400);assert.equal(retry.body.code,'INSUFFICIENT_COINS');const current=await request(port,'GET','/api/account/me',undefined,deviceB.cookie);assert.equal(current.body.revision,1);assert.equal(JSON.parse(current.body.progress['swarmfall-stats']).coins,30);assert.deepEqual(JSON.parse(current.body.progress['swarmfall-unlocked']),['warrior'])});
test('identical progress reconciliation performs no localStorage writes',()=>{const values=new Map([['swarmfall-stats','{"coins":5}'],['swarmfall-map','ruins']]),writes=[],storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>{writes.push(['set',key]);values.set(key,value)},removeItem:key=>{writes.push(['remove',key]);values.delete(key)}};const progress={'swarmfall-stats':'{"coins":5}','swarmfall-map':'ruins'};assert.equal(client.applyProgress(storage,progress),0);assert.deepEqual(writes,[]);progress['swarmfall-map']='toxic';assert.equal(client.applyProgress(storage,progress),1);assert.deepEqual(writes,[['set','swarmfall-map']])});

test('semantic reconcile preserves newer pending client-owned character while applying server-owned state',()=>{const values=new Map([['swarmfall-character','druid'],['swarmfall-stats','{"coins":10}']]),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};client.applyProgress(storage,{'swarmfall-character':'scout','swarmfall-stats':'{"coins":3}'},client.CLIENT_PROGRESS_KEY_SET);assert.equal(values.get('swarmfall-character'),'druid');assert.equal(values.get('swarmfall-stats'),'{"coins":3}')});

test('pending debounce is immediately visible and a write during mutation flushes the newest snapshot',async()=>{let state='first',release,calls=[],controller=new client.SyncController({getSnapshot:()=>({'swarmfall-save-v1':state}),send:async(progress,revision)=>{calls.push({progress,revision});if(calls.length===1)await new Promise(resolve=>release=resolve);return{revision:revision+1}}});controller.initialize(4);controller.markPending();assert.equal(controller.dirty,true);const settling=controller.settlePending();await new Promise(resolve=>setImmediate(resolve));state='latest';controller.markPending();release();await settling;await controller.settlePending();assert.deepEqual(calls.map(call=>call.progress['swarmfall-save-v1']),['first','latest']);assert.deepEqual(calls.map(call=>call.revision),[4,5]);assert.equal(controller.revision,6)});

test('logout flushes a dirty change even before the debounce timer expires',()=>{const source=fs.readFileSync(path.join(__dirname,'..','account-client.js'),'utf8');assert.match(source,/markPending\(\);clearTimeout\(syncTimer\);syncTimer=setTimeout\(\(\)=>sync\.retryNow\(\),350\)/);assert.match(source,/accountLogoutBtn'\)\.onclick=async\(\)=>\{clearTimeout\(syncTimer\);if\(sync\.dirty\|\|sync\.inFlight\)await sync\.settlePending\(\)/)});

test('outbox integration has no fixed polling or account timer',()=>{const accountSource=fs.readFileSync(path.join(__dirname,'..','account-client.js'),'utf8'),outboxSource=fs.readFileSync(path.join(__dirname,'..','progress-outbox.js'),'utf8');assert.doesNotMatch(accountSource,/while\s*\([^)]*sync\.inFlight[^)]*\)[\s\S]{0,120}setTimeout/);assert.doesNotMatch(accountSource,/setInterval\s*\(/);assert.doesNotMatch(outboxSource,/setInterval\s*\(/);assert.match(outboxSource,/MAX_OPERATIONS\s*=\s*100/)});

test('progress API converts a synchronous full-queue throw into a rejected Promise',async()=>{const error=Object.assign(new Error('full'),{code:'OUTBOX_FULL'}),outbox={enqueue(){throw error}};let promise;assert.doesNotThrow(()=>{promise=client.enqueueProgress(outbox,'awardCurrency',{amount:1})});assert.equal(typeof promise.then,'function');await assert.rejects(promise,candidate=>candidate===error)});

test('enqueue callbacks report persistence rejection without a false durable acknowledgement',async()=>{const error=new Error('quota'),events=[],outbox={enqueue(){throw error}};const promise=client.enqueueProgress(outbox,'awardCurrency',{amount:1},()=>events.push('enqueued'),candidate=>events.push(candidate));await assert.rejects(promise,candidate=>candidate===error);assert.deepEqual(events,[error])});

test('operation retry controller uses one bounded exponential timer and Retry-After',()=>{const scheduled=[],cleared=[],runs=[],controller=client.createRetryController({run:()=>runs.push('run'),setTimer:(callback,delay)=>{scheduled.push({callback,delay});return scheduled.length},clearTimer:id=>cleared.push(id)});assert.equal(controller.schedule({}),true);assert.equal(controller.schedule({}),false);assert.equal(scheduled[0].delay,5000);scheduled[0].callback();assert.equal(controller.schedule({}),true);assert.equal(scheduled[1].delay,10000);scheduled[1].callback();assert.equal(controller.schedule({retryAfterMs:30000}),true);assert.equal(scheduled[2].delay,30000);controller.reset();scheduled[2].callback();assert.equal(controller.schedule({}),true);assert.equal(scheduled[3].delay,5000);controller.cancel();assert.deepEqual(runs,['run','run','run']);assert.ok(cleared.length>0)});

test('autosave failure does not deadlock pending progression sequencing',async()=>{let retryCallback,autosaveCalls=0,progressionRan=false,controller=new client.SyncController({getSnapshot:()=>({}),send:async()=>{autosaveCalls++;throw new Error('offline')},setTimer:callback=>{retryCallback=callback;return 1},clearTimer:()=>{}});controller.initialize(0);controller.markDirty();await controller.settlePending();progressionRan=true;assert.equal(progressionRan,true);assert.equal(controller.inFlight,false);assert.equal(controller.dirty,true);assert.equal(typeof retryCallback,'function');assert.equal(autosaveCalls,1)});
