'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),fsp=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {createStaticHandler}=require('../server');
const {ACCOUNT_PROGRESS_KEYS}=require('../account-store');
const client=require('../account-client');

function request(port,method,url,body,cookie,headers={}){return new Promise((resolve,reject)=>{const raw=body===undefined?'':JSON.stringify(body),req=http.request({host:'127.0.0.1',port,method,path:url,headers:{'content-type':'application/json','content-length':Buffer.byteLength(raw),...(cookie?{cookie}:{}),...headers}},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString()),cookie:res.headers['set-cookie']?.[0]?.split(';')[0],setCookie:res.headers['set-cookie']?.[0]}))});req.on('error',reject);req.end(raw)})}
async function fixture(t,fileContent){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'swarm-account-')),accountFile=path.join(directory,'accounts.json');if(fileContent!==undefined)fs.writeFileSync(accountFile,fileContent);const server=http.createServer(createStaticHandler({accountFile}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return{port:server.address().port,accountFile}}
const register=(port,login,email=`${login}@example.com`)=>request(port,'POST','/api/account/register',{login,email,password:'12345678'});

test('browser and server use the same explicit account progress allowlist',()=>assert.deepEqual(client.ACCOUNT_PROGRESS_KEYS,ACCOUNT_PROGRESS_KEYS));

test('registration starts empty and account progress never leaks between accounts',async t=>{const{port}=await fixture(t),a=await register(port,'kontoA'),payload={'swarmfall-stats':'{"coins":500}','swarmfall-achievements-v1':'["boss_1"]','swarmfall-unlocked':'["warrior"]','swarmfall-save-v1':'{"mode":"singleplayer"}'};assert.equal((await request(port,'PUT','/api/account/progress',{progress:payload,expectedRevision:0},a.cookie)).status,200);const b=await register(port,'kontoB');assert.deepEqual(b.body.progress,{});assert.equal(b.body.revision,0);const meB=await request(port,'GET','/api/account/me',undefined,b.cookie);assert.deepEqual(meB.body.progress,{});const loginA=await request(port,'POST','/api/account/login',{identifier:'kontoA',password:'12345678'});assert.deepEqual(loginA.body.progress,payload)});

test('fresh account reset removes coins, achievements, unlocks and save but preserves device identity',()=>{const values=new Map([['swarmfall-stats','{"coins":500}'],['swarmfall-achievements-v1','["boss_1"]'],['swarmfall-unlocked','["warrior"]'],['swarmfall-save-v1','save'],['swarmfall-installation-id','DEVICE-A'],['swarmfall-debug-collision','1']]),storage={getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};client.applyProgress(storage,{});assert.equal(values.get('swarmfall-installation-id'),'DEVICE-A');assert.equal(values.get('swarmfall-debug-collision'),'1');for(const key of ACCOUNT_PROGRESS_KEYS)assert.equal(values.has(key),false,key)});

test('only explicit progression keys persist while device keys are rejected',async t=>{const{port}=await fixture(t),account=await register(port,'keys'),progress=Object.fromEntries(ACCOUNT_PROGRESS_KEYS.map(key=>[key,`value:${key}`]));progress['swarmfall-installation-id']='DEVICE-A';progress['swarmfall-debug-multiplayer']='1';progress['swarmfall-language']='en';const saved=await request(port,'PUT','/api/account/progress',{progress,expectedRevision:0},account.cookie);assert.equal(saved.status,200);const me=await request(port,'GET','/api/account/me',undefined,account.cookie);assert.deepEqual(me.body.progress,Object.fromEntries(ACCOUNT_PROGRESS_KEYS.map(key=>[key,`value:${key}`])))});

test('two-device stale revision returns a typed 409 conflict',async t=>{const{port}=await fixture(t),deviceA=await register(port,'conflict'),deviceB=await request(port,'POST','/api/account/login',{identifier:'conflict',password:'12345678'});assert.equal(deviceB.body.revision,0);const newer=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'{"coins":10}'},expectedRevision:0},deviceA.cookie);assert.equal(newer.body.revision,1);const stale=await request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'{"coins":1}'},expectedRevision:0},deviceB.cookie);assert.equal(stale.status,409);assert.equal(stale.body.code,'REVISION_CONFLICT');assert.equal(stale.body.revision,1)});

test('single-flight client sync queues the newest snapshot without reverting it',async()=>{let state='old',active=0,maxActive=0,calls=[],release;const first=new Promise(resolve=>release=resolve),controller=new client.SyncController({getSnapshot:()=>({'swarmfall-stats':state}),send:async(progress,revision)=>{active++;maxActive=Math.max(maxActive,active);calls.push({progress,revision});if(calls.length===1)await first;active--;return{revision:revision+1}}});controller.initialize(0);controller.markDirty();await new Promise(resolve=>setImmediate(resolve));state='new';controller.markDirty();release();while(controller.inFlight||controller.dirty)await new Promise(resolve=>setImmediate(resolve));assert.equal(maxActive,1);assert.deepEqual(calls,[{progress:{'swarmfall-stats':'old'},revision:0},{progress:{'swarmfall-stats':'new'},revision:1}])});

test('concurrent writes for different accounts are serialized without lost data',async t=>{const{port}=await fixture(t),a=await register(port,'parallelA'),b=await register(port,'parallelB'),[saveA,saveB]=await Promise.all([request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'A'},expectedRevision:0},a.cookie),request(port,'PUT','/api/account/progress',{progress:{'swarmfall-stats':'B'},expectedRevision:0},b.cookie)]);assert.equal(saveA.status,200);assert.equal(saveB.status,200);const[meA,meB]=await Promise.all([request(port,'GET','/api/account/me',undefined,a.cookie),request(port,'GET','/api/account/me',undefined,b.cookie)]);assert.equal(meA.body.progress['swarmfall-stats'],'A');assert.equal(meB.body.progress['swarmfall-stats'],'B')});

test('a corrupted existing account file returns controlled error and is never overwritten',async t=>{const corrupted='{ definitely not json',fixtureData=await fixture(t,corrupted),response=await register(fixtureData.port,'cannotwrite');assert.equal(response.status,503);assert.equal(response.body.code,'ACCOUNT_STORE_CORRUPTED');assert.equal(await fsp.readFile(fixtureData.accountFile,'utf8'),corrupted)});

test('expired session has a typed response and matching custom client message',async t=>{const initial=await fixture(t),account=await register(initial.port,'expired'),database=JSON.parse(await fsp.readFile(initial.accountFile,'utf8'));for(const session of Object.values(database.sessions))session.expiresAt=0;await fsp.writeFile(initial.accountFile,JSON.stringify(database));await new Promise(resolve=>initial.port&&resolve());const secondServer=http.createServer(createStaticHandler({accountFile:initial.accountFile}));await new Promise(resolve=>secondServer.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>secondServer.close(resolve)));const response=await request(secondServer.address().port,'GET','/api/account/me',undefined,account.cookie);assert.equal(response.status,401);assert.equal(response.body.code,'SESSION_EXPIRED');assert.match(client.MESSAGES.expired,/Sesja wygasła/)});

test('custom validation covers empty and malformed fields without native bubbles',()=>{assert.match(client.validate('login',{identifier:'',password:''}),/login/);assert.match(client.validate('login',{identifier:'?',password:'12345678'}),/Login musi/);assert.match(client.validate('register',{login:'',email:'',password:''}),/Wpisz login/);assert.match(client.validate('register',{login:'?',email:'x',password:'12345678'}),/Login musi/);assert.match(client.validate('register',{login:'valid',email:'',password:'12345678'}),/Wpisz adres/);assert.match(client.validate('register',{login:'valid',email:'bad',password:'12345678'}),/prawidłowy/);assert.match(client.validate('register',{login:'valid',email:'a@b.pl',password:'1'}),/8 znaków/);const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.equal((html.match(/<form class="account-form[^>]*novalidate/g)||[]).length,2);assert.doesNotMatch(html,/<form class="account-form[^>]*\srequired/)});

test('network and server failures have safe custom messages',()=>{assert.equal(client.MESSAGES.network,'Brak połączenia z siecią.');assert.equal(client.MESSAGES.server,'Serwer kont jest chwilowo niedostępny.');for(const value of Object.values(client.MESSAGES))assert.doesNotMatch(value,/Failed to fetch|TypeError|ECONN|stack/i)});

test('account client passes the Node syntax check',()=>{const result=spawnSync(process.execPath,['--check',path.join(__dirname,'..','account-client.js')],{encoding:'utf8'});assert.equal(result.status,0,result.stderr)});

test('password bounds, secure cookies and auth rate limiting are enforced',async t=>{const{port}=await fixture(t);assert.equal((await request(port,'POST','/api/account/register',{login:'short',email:'s@example.com',password:'1234567'})).status,400);assert.equal((await request(port,'POST','/api/account/register',{login:'longpass',email:'l@example.com',password:'x'.repeat(129)})).status,400);const secure=await request(port,'POST','/api/account/register',{login:'secure',email:'secure@example.com',password:'12345678'},null,{'x-forwarded-proto':'https'});assert.match(secure.setCookie,/HttpOnly/);assert.match(secure.setCookie,/SameSite=Strict/);assert.match(secure.setCookie,/Secure/);let last;for(let i=0;i<9;i++)last=await request(port,'POST','/api/account/login',{identifier:'none',password:'12345678'});assert.equal(last.status,429)});
