'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nav=require('../nav-prewarm-policy');

test('timed-out idle callback never prewarms during combat but may build in menu',()=>{const timedOut={didTimeout:true,timeRemaining:()=>50};assert.equal(nav.canBuild({running:true,paused:false,deadline:timedOut}),false);assert.equal(nav.canBuild({running:false,paused:false,deadline:timedOut}),true);assert.equal(nav.canBuild({running:true,paused:true,deadline:timedOut}),true)});
test('active combat requires a real twelve millisecond idle budget',()=>{assert.equal(nav.canBuild({running:true,paused:false,deadline:{didTimeout:false,timeRemaining:()=>11.9}}),false);assert.equal(nav.canBuild({running:true,paused:false,deadline:{didTimeout:false,timeRemaining:()=>12}}),true)});

test('asset gate waits for real image readiness and reports real progress',async()=>{const image={complete:false,naturalWidth:0,decode:async()=>{image.complete=true;image.naturalWidth=128}},window={SwarmHeroAssets:{scout:{images:{idle:image}}},enemySpriteVisuals:{sheets:{}}};vm.runInNewContext(fs.readFileSync(require.resolve('../asset-gate.js'),'utf8'),{window,setTimeout,Promise,Error});const progress=[];await window.SwarmAssets.waitForRequired({character:'scout',map:'toxic'},{onProgress:value=>progress.push(value.progress)});assert.equal(progress[0],0);assert.equal(progress.at(-1),1)});

test('failed required asset blocks entry and manual retry can succeed',async()=>{let succeeds=false;const image={complete:false,naturalWidth:0,decode:async()=>{if(!succeeds)throw Error('offline');image.complete=true;image.naturalWidth=128}},window={SwarmHeroAssets:{scout:{images:{idle:image}}},enemySpriteVisuals:{sheets:{}}};vm.runInNewContext(fs.readFileSync(require.resolve('../asset-gate.js'),'utf8'),{window,setTimeout,Promise,Error});await assert.rejects(window.SwarmAssets.retryFailed({character:'scout',map:'toxic'}));succeeds=true;await assert.doesNotReject(window.SwarmAssets.retryFailed({character:'scout',map:'toxic'}))});

test('legacy render fallbacks are absent for custom heroes, Ruins and enemies',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),enemies=fs.readFileSync(require.resolve('../enemy-visuals.js'),'utf8');assert.doesNotMatch(game,/else drawCharacterModel|if\(!spriteDrawn\).*drawCharacterModel/);assert.match(game,/if\(chosenMap==='ruins'\)\{window\.SwarmMapVisuals\?\.drawCrate/);assert.match(game,/if\(chosenMap!=='ruins'\)\{const bg=/);assert.doesNotMatch(enemies,/if\(drawMobSprite[\s\S]*toxicBoss\(/);assert.match(game,/t\('assets\.loadingMap'\)/)});
test('Druid readiness includes all six prepared frames for every effect sheet',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8');assert.match(game,/SCOUT_ASSET_VERSION='4',WARRIOR_ASSET_VERSION='4',DRUID_ASSET_VERSION='3'/);assert.match(game,/druidVisuals\.prepared=key=>druidEffectFrames\[key\]\?\.length===6/)});

function readyImage(){return{complete:true,naturalWidth:64,decode:async()=>{}}}
function gateWindow({preview=()=>true}={}){const image=readyImage(),entry=()=>({image:readyImage(),loaded:true});return{SwarmHeroAssets:{scout:{images:{idle:image}},druid:{images:{idle:image,qEffect:image},prepared:key=>key==='qEffect'}},SwarmMapVisuals:{_assetState:{ground:{image,ready:true}},getRuinsStaticPreview:preview},enemySpriteVisuals:{requiredByMap:{ruins:['melee','boss_titan'],toxic:['melee','toxic','toxic_boss_spore','toxic_boss_fog','toxic_boss_core']},sheets:{melee:{model:entry()},boss_titan:{model:entry()},toxic:{model:entry()},toxic_boss_spore:{model:entry()},toxic_boss_fog:{model:entry()},toxic_boss_core:{model:entry()}}}}}
function loadGate(window){vm.runInNewContext(fs.readFileSync(require.resolve('../asset-gate.js'),'utf8'),{window,setTimeout,Promise,Error,Set,Object});return window.SwarmAssets}

test('multiplayer gate deduplicates and requires every lobby character including prepared Druid',async()=>{let prepared=false;const window=gateWindow();window.SwarmHeroAssets.druid.prepared=()=>prepared;const gate=loadGate(window),entries=gate.collect({map:'ruins',character:'scout',characters:['scout','druid','druid']});assert.equal(entries.filter(entry=>entry.label==='scout idle').length,1);assert.ok(entries.some(entry=>entry.label==='druid qEffect'));assert.equal(entries.find(entry=>entry.label==='druid qEffect prepared').ready(),false);await assert.rejects(gate.waitForRequired({map:'ruins',characters:['scout','druid']}));prepared=true;await assert.doesNotReject(gate.retryFailed({map:'ruins',characters:['scout','druid']}))});

test('derived preview waits for image dependencies and has no independent retry timeout',async()=>{let built=false;const window=gateWindow({preview:()=>built}),image=window.SwarmMapVisuals._assetState.ground.image;window.SwarmMapVisuals._assetState.ground.ready=false;image.complete=false;image.naturalWidth=0;image.decode=()=>new Promise(resolve=>setTimeout(()=>{image.complete=true;image.naturalWidth=64;window.SwarmMapVisuals._assetState.ground.ready=true;built=true;resolve()},60));await assert.doesNotReject(loadGate(window).waitForRequired({map:'ruins'}));assert.equal(built,true)});

test('manual retry reevaluates derived preview after its image dependency succeeds',async()=>{let succeeds=false,built=false;const window=gateWindow({preview:()=>built}),image=window.SwarmMapVisuals._assetState.ground.image;window.SwarmMapVisuals._assetState.ground.ready=false;image.complete=false;image.naturalWidth=0;image.decode=async()=>{if(!succeeds)throw Error('offline');image.complete=true;image.naturalWidth=64;window.SwarmMapVisuals._assetState.ground.ready=true;built=true};const gate=loadGate(window);await assert.rejects(gate.retryFailed({map:'ruins'}));succeeds=true;await assert.doesNotReject(gate.retryFailed({map:'ruins'}));assert.equal(built,true)});

test('enemy requirements are map-specific and unrelated failures do not block Ruins',async()=>{const window=gateWindow(),gate=loadGate(window),ruins=gate.collect({map:'ruins'}).map(entry=>entry.label),toxic=gate.collect({map:'toxic'}).map(entry=>entry.label);assert.ok(ruins.includes('boss_titan model'));assert.ok(!ruins.some(label=>label.startsWith('toxic_boss_')));assert.ok(toxic.includes('toxic model'));assert.ok(toxic.includes('toxic_boss_spore model'));window.enemySpriteVisuals.sheets.toxic_boss_spore.model.loaded=false;window.enemySpriteVisuals.sheets.toxic_boss_spore.model.image.complete=false;window.enemySpriteVisuals.sheets.toxic_boss_spore.model.image.naturalWidth=0;window.enemySpriteVisuals.sheets.toxic_boss_spore.model.image.decode=async()=>{throw Error('broken')};await assert.doesNotReject(gate.waitForRequired({map:'ruins'}))});

test('multiplayer start commits the gated lobby map and has one draw definition',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),multiplayer=fs.readFileSync(require.resolve('../multiplayer.js'),'utf8');assert.match(multiplayer,/new Set\(lobby\.players\.map\(member=>member\.character\)/);assert.match(game,/startCore\(\{map:selection\.map,character:selection\.character\}\)/);assert.match(game,/chosenMap=map;chosenCharacter=character;setupMap\(map\)/);assert.equal((game.match(/function draw\(\)/g)||[]).length,1)});

test('a completed preparing gate is a cache hit when gameStarted verifies assets again',async()=>{let decodes=0;const image={complete:false,naturalWidth:0,decode:async()=>{decodes++;image.complete=true;image.naturalWidth=64}},window={SwarmHeroAssets:{scout:{images:{idle:image}}},enemySpriteVisuals:{requiredByMap:{toxic:[]},sheets:{}}},gate=loadGate(window);await gate.waitForRequired({map:'toxic',character:'scout'});await gate.waitForRequired({map:'toxic',character:'scout'});assert.equal(decodes,1)});

test('hero runtime sheets load on demand while startup requests portraits only',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),gate=fs.readFileSync(require.resolve('../asset-gate.js'),'utf8');assert.match(game,/preloadScoutVisuals\(\['portrait'\]\)/);assert.match(game,/preloadWarriorVisuals\(\['portrait'\]\)/);assert.match(game,/preloadDruidVisuals\(\['portrait'\]\)/);assert.match(game,/druidVisuals\.ensure=\(\)=>preloadDruidVisuals\(\)/);assert.match(gate,/group\?\.ensure\?\.\(\)/)})
