'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nav=require('../nav-prewarm-policy');

test('timed-out idle callback never prewarms during combat but may build in menu',()=>{const timedOut={didTimeout:true,timeRemaining:()=>50};assert.equal(nav.canBuild({running:true,paused:false,deadline:timedOut}),false);assert.equal(nav.canBuild({running:false,paused:false,deadline:timedOut}),true);assert.equal(nav.canBuild({running:true,paused:true,deadline:timedOut}),true)});
test('active combat requires a real twelve millisecond idle budget',()=>{assert.equal(nav.canBuild({running:true,paused:false,deadline:{didTimeout:false,timeRemaining:()=>11.9}}),false);assert.equal(nav.canBuild({running:true,paused:false,deadline:{didTimeout:false,timeRemaining:()=>12}}),true)});

test('asset gate waits for real image readiness and reports real progress',async()=>{const image={complete:false,naturalWidth:0,decode:async()=>{image.complete=true;image.naturalWidth=128}},window={SwarmHeroAssets:{scout:{images:{idle:image}}},enemySpriteVisuals:{sheets:{}}};vm.runInNewContext(fs.readFileSync(require.resolve('../asset-gate.js'),'utf8'),{window,setTimeout,Promise,Error});const progress=[];await window.SwarmAssets.waitForRequired({character:'scout',map:'toxic'},{onProgress:value=>progress.push(value.progress)});assert.equal(progress[0],0);assert.equal(progress.at(-1),1)});

test('failed required asset blocks entry and manual retry can succeed',async()=>{let succeeds=false;const image={complete:false,naturalWidth:0,decode:async()=>{if(!succeeds)throw Error('offline');image.complete=true;image.naturalWidth=128}},window={SwarmHeroAssets:{scout:{images:{idle:image}}},enemySpriteVisuals:{sheets:{}}};vm.runInNewContext(fs.readFileSync(require.resolve('../asset-gate.js'),'utf8'),{window,setTimeout,Promise,Error});await assert.rejects(window.SwarmAssets.retryFailed({character:'scout',map:'toxic'}));succeeds=true;await assert.doesNotReject(window.SwarmAssets.retryFailed({character:'scout',map:'toxic'}))});

test('legacy render fallbacks are absent for custom heroes, Ruins and enemies',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),enemies=fs.readFileSync(require.resolve('../enemy-visuals.js'),'utf8');assert.doesNotMatch(game,/else drawCharacterModel|if\(!spriteDrawn\).*drawCharacterModel/);assert.match(game,/if\(chosenMap==='ruins'\)\{window\.SwarmMapVisuals\?\.drawCrate/);assert.match(game,/if\(chosenMap!=='ruins'\)\{const bg=/);assert.doesNotMatch(enemies,/if\(drawMobSprite[\s\S]*toxicBoss\(/);assert.match(game,/ŁADOWANIE MAPY…/)});
test('Druid readiness includes all six prepared frames for every effect sheet',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8');assert.match(game,/SCOUT_ASSET_VERSION='4',WARRIOR_ASSET_VERSION='4',DRUID_ASSET_VERSION='3'/);assert.match(game,/prepared:key=>druidEffectFrames\[key\]\?\.length===6/)});
