'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const collision=require('../shared-collision'),maps=require('../shared-map-data'),{blocked:serverBlocked,GameServer}=require('../server');

for(const mapId of['ruins','toxic'])test(`${mapId} shared collision handles open space, rocks, walls and border clearance`,()=>{const map=maps[mapId],open=mapId==='ruins'?{x:1500,y:1100}:{x:1500,y:1100},rock=map.terrain.find(item=>item.type==='rock'),wall=map.terrain.find(item=>item.type==='wall'),r=15,rr=collision.rockCollisionRadius(rock);assert.equal(collision.blocked(mapId,open.x,open.y,r),false);assert.equal(collision.blocked(mapId,rock.x,rock.y,r),true);assert.equal(collision.blocked(mapId,rock.x+rr+r+1,rock.y,r),false);assert.equal(collision.blocked(mapId,rock.x+rr+r-1,rock.y,r),true);assert.equal(collision.blocked(mapId,wall.x+wall.w/2,wall.y+wall.h/2,r),true);assert.equal(collision.circleRectCollision(wall.x-10.7,wall.y-10.7,r,wall),false);assert.equal(collision.circleRectCollision(wall.x-10.5,wall.y-10.5,r,wall),true);const[a,b]=map.shape,mid={x:(a[0]+b[0])/2,y:(a[1]+b[1])/2},inside={x:mid.x,y:mid.y+10};assert.equal(collision.pointInPolygon(inside.x,inside.y,map.shape),true);assert.equal(collision.blocked(mapId,inside.x,inside.y,r),true)});

test('water collision includes circle overlap outside the polygon',()=>{const water=maps.ruins.terrain.find(item=>item.type==='water'),[a,b]=water.points,mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2,length=Math.hypot(b[0]-a[0],b[1]-a[1]),nx=-(b[1]-a[1])/length,ny=(b[0]-a[0])/length;let sign=collision.pointInPolygon(mx+nx*2,my+ny*2,water.points)?-1:1;const near={x:mx+nx*sign*14,y:my+ny*sign*14},far={x:mx+nx*sign*17,y:my+ny*sign*17};assert.equal(collision.pointInPolygon(near.x,near.y,water.points),false);assert.equal(collision.blocked('ruins',near.x,near.y,15),true);assert.equal(collision.blocked('ruins',far.x,far.y,15),false)});

test('shared swept movement slides and cannot tunnel through thin walls',()=>{const slide=collision.moveCircleWithCollision('ruins',800,430,15,100,-100);assert.equal(collision.blocked('ruins',slide.x,slide.y,15),false);assert.ok(Math.hypot(slide.movedX,slide.movedY)>20);const dash=collision.moveCircleWithCollision('ruins',1750,900,15,300,0);assert.equal(collision.blocked('ruins',dash.x,dash.y,15),false);assert.ok(dash.x<1830-15);const charger=collision.moveCircleWithCollision('ruins',1750,900,30,430*.55,0);assert.ok(charger.x<1830-30);const core=new GameServer(()=>1000,()=>.5),player={id:'p',x:2100,y:900,alive:true},lobby={map:'ruins',players:[{id:'p',connected:true}],game:{players:{p:player}}},enemy={id:'charger',type:'charger',ai:'charger',x:1750,y:900,r:30,hp:50,attack:1,special:1,charging:.55,chargeX:1,chargeY:0,speed:100,damage:0};core.tickEnemy(lobby,enemy,.55);assert.ok(enemy.x<1830-30);assert.equal(collision.blocked('ruins',enemy.x,enemy.y,enemy.r),false)});

test('server and browser runtimes use the same collision source for sampled points',()=>{assert.equal(serverBlocked,collision.blocked);for(const mapId of['ruins','toxic'])for(const radius of[4,13,15,30])for(let x=45;x<3000;x+=137)for(let y=45;y<2200;y+=131)assert.equal(serverBlocked(mapId,x,y,radius),collision.blocked(mapId,x,y,radius));const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),multiplayer=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8');assert.match(game,/SwarmCollision\.blocked\(chosenMap/);assert.match(game,/SwarmCollision\.moveCircleWithCollision/);assert.match(multiplayer,/SwarmCollision\.moveCircleWithCollision/)});
