'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const collision=require('../shared-collision'),maps=require('../shared-map-data');
const distance=result=>Math.hypot(result.movedX,result.movedY);
function bestLegalCandidate(mapId,x,y,r,dx,dy){const requested=Math.hypot(dx,dy),angle=Math.atan2(dy,dx);let best=null;for(const scale of[1,.75,.5,.25])for(let degrees=5;degrees<=90;degrees+=5)for(const sign of[-1,1]){const candidateAngle=angle+sign*degrees*Math.PI/180,cx=Math.cos(candidateAngle)*requested*scale,cy=Math.sin(candidateAngle)*requested*scale;if(!collision.blocked(mapId,x+cx,y+cy,r)&&(!best||Math.hypot(cx,cy)>best.length))best={dx:cx,dy:cy,length:Math.hypot(cx,cy),degrees:sign*degrees}}return best}
function assertProgress(mapId,x,y,r,dx,dy,label){const requested=Math.hypot(dx,dy),best=bestLegalCandidate(mapId,x,y,r,dx,dy),result=collision.moveCircleWithCollision(mapId,x,y,r,dx,dy);assert.equal(collision.blocked(mapId,result.x,result.y,r),false,`${label}: illegal result`);assert.ok(distance(result)<=requested+1e-8,`${label}: movement grew`);assert.deepEqual(result,collision.moveCircleWithCollision(mapId,x,y,r,dx,dy),`${label}: nondeterministic`);if(collision.blocked(mapId,x+dx,y+dy,r)&&best&&best.length>=requested*.25)assert.ok(distance(result)>=best.length*.35,`${label}: ${JSON.stringify({mapId,x,y,r,dx,dy,result,best})}`);return{best,result}}

test('known corner regressions require meaningful progress when a legal tangent exists',()=>{for(const [index,c] of [
  {map:'ruins',x:1551.4454460330307,y:1194.733024686575,dx:-2.383356633001603,dy:14.035813712911198},
  {map:'ruins',x:250.34843916073442,y:599.737593755126,dx:4.488422230342554,dy:-11.477462217499676},
  {map:'toxic',x:2254.109020140022,y:118.88550769537687,dx:-.36468281706461725,dy:-4.113687544891984}
].entries())assertProgress(c.map,c.x,c.y,15,c.dx,c.dy,`known-${index}`)});

test('all Ruins water vertices require progress at four clearances',()=>{let generated=0,tangents=0;for(const water of maps.ruins.terrain.filter(item=>item.type==='water'))for(const vertex of water.points)for(const clearance of[.25,.5,.75,1.5])for(let degree=0;degree<360;degree+=15){const angle=degree*Math.PI/180,ux=Math.cos(angle),uy=Math.sin(angle),x=vertex[0]+ux*(15+clearance),y=vertex[1]+uy*(15+clearance);if(collision.blocked('ruins',x,y,15))continue;generated++;const check=assertProgress('ruins',x,y,15,-uy*7-ux*2,ux*7-uy*2,`water-${vertex}-${clearance}-${degree}`);if(check.best)tangents++}assert.ok(generated>300);assert.ok(tangents>100)});

test('rock circumference progresses clockwise and counter-clockwise',()=>{let cases=0;for(const rock of maps.ruins.terrain.filter(item=>item.type==='rock')){const c=collision.rockCollider('ruins',rock);for(const clearance of[.25,.75,1.5])for(let degree=0;degree<360;degree+=10)for(const direction of[-1,1]){const angle=degree*Math.PI/180,ux=Math.cos(angle),uy=Math.sin(angle),x=c.x+ux*(c.radius+15+clearance),y=c.y+uy*(c.radius+15+clearance);if(collision.blocked('ruins',x,y,15))continue;assertProgress('ruins',x,y,15,-ux*2-uy*6*direction,-uy*2+ux*6*direction,`rock-${c.variant}-${degree}-${direction}`);cases++}}assert.ok(cases>500)});

test('pure contact velocity is allocation-free and independent of normal order',()=>{const solve=(values,dx=-3,dy=-2)=>Array.from(collision.solveContactVelocity(dx,dy,new Float64Array(values),values.length/2,new Float64Array(2)));assert.deepEqual(solve([1,0]),[0,-2]);assert.deepEqual(solve([1,0,0,1]),[0,0]);assert.deepEqual(solve([0,1,1,0]),[0,0]);assert.deepEqual(solve([1,0,1,0]),[0,-2]);assert.deepEqual(solve([1,0,.999999,.000001]),solve([.999999,.000001,1,0]));assert.deepEqual(solve([1,0,-1,0],-3,2),[0,2])});

test('wall corners preserve progress whenever a nearby legal direction exists',()=>{let cases=0;for(const wall of maps.ruins.terrain.filter(item=>item.type==='wall'))for(const [sx,sy] of [[-1,-1],[1,-1],[-1,1],[1,1]]){const x=(sx<0?wall.x:wall.x+wall.w)+sx*15.75,y=(sy<0?wall.y:wall.y+wall.h)+sy*15.75;if(collision.blocked('ruins',x,y,15))continue;for(const [tx,ty] of [[-sy*7,sx*7],[-sy*7+sx*-2,sx*7+sy*-2],[-sy*5+sx*-4,sx*5+sy*-4]]){assertProgress('ruins',x,y,15,tx,ty,`wall-${wall.x}-${wall.y}-${sx}-${sy}`);cases++}}assert.ok(cases>=12)});

test('mixed contact constraints distinguish a feasible tangent from a real dead end',()=>{const mixed=new Float64Array([1,0,0,1,.999999,.000001]);const dead=collision.solveContactVelocity(-8,-8,mixed,3,new Float64Array(2));assert.ok(Math.hypot(...dead)<1e-8);const tangent=collision.solveContactVelocity(-8,8,mixed,3,new Float64Array(2));assert.ok(Math.hypot(...tangent)>1)});

test('20000 randomized movements require progress when a nearby legal tangent exists',()=>{let seed=0x70a6e55,checked=0,tangentCases=0;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/0x100000000);for(let attempt=0;attempt<70000&&checked<20000;attempt++){const mapId=attempt%2?'ruins':'toxic',r=8+random()*22,x=30+random()*2940,y=30+random()*2140;if(collision.blocked(mapId,x,y,r))continue;const angle=random()*Math.PI*2,length=2+random()*14,dx=Math.cos(angle)*length,dy=Math.sin(angle)*length,best=bestLegalCandidate(mapId,x,y,r,dx,dy),result=collision.moveCircleWithCollision(mapId,x,y,r,dx,dy),actual=distance(result);assert.equal(collision.blocked(mapId,result.x,result.y,r),false);assert.ok(actual<=length+1e-8);if(collision.blocked(mapId,x+dx,y+dy,r)&&best&&best.length>=length*.25){tangentCases++;assert.ok(actual>=best.length*.35,JSON.stringify({mapId,x,y,r,dx,dy,result,best}))}checked++}assert.equal(checked,20000);assert.ok(tangentCases>100)});

test('100-tick held-input detector rejects permanent sticking at water, rock and wall contacts',()=>{const rock=maps.ruins.terrain.find(item=>item.type==='rock'),rc=collision.rockCollider('ruins',rock),scenarios=[{name:'water',x:1551.4454460330307,y:1194.733024686575,dx:-2.383356633001603,dy:14.035813712911198},{name:'rock',x:rc.x+rc.radius+15.75,y:rc.y,dx:-2,dy:6},{name:'wall',x:1814.25,y:1092.25,dx:9,dy:-1}];for(const scenario of scenarios){let{x,y}=scenario,total=0,zeroRun=0,maxZeroRun=0,tangentTicks=0;for(let tick=0;tick<100;tick++){const best=bestLegalCandidate('ruins',x,y,15,scenario.dx,scenario.dy),result=collision.moveCircleWithCollision('ruins',x,y,15,scenario.dx,scenario.dy),moved=distance(result);assert.equal(collision.blocked('ruins',result.x,result.y,15),false);if(best&&best.length>=Math.hypot(scenario.dx,scenario.dy)*.25){tangentTicks++;zeroRun=moved<.05?zeroRun+1:0;maxZeroRun=Math.max(maxZeroRun,zeroRun)}else zeroRun=0;total+=moved;x=result.x;y=result.y}assert.ok(maxZeroRun<=3,`${scenario.name} stuck ${maxZeroRun} ticks`);assert.ok(!tangentTicks||total>10,`${scenario.name} total ${total}`)}});
