'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,activeUpgradePlayers}=require('../server');

function setup(count=2){let now=1000;const core=new GameServer(()=>now,()=>.5),messages=new Map(),clients=[];for(let i=0;i<count;i++){const list=[];messages.set(i,list);const client=core.addClient(message=>list.push(message));core.handle(client,{type:'hello',installationId:`p${i}`,unlocked:[],maps:['ruins']});now+=2000;if(i===0)core.handle(client,{type:'createLobby'});else core.handle(client,{type:'joinLobby',code:clients[0].lobby});clients.push(client)}const lobby=core.lobbies.get(clients[0].lobby);lobby.players.forEach(member=>member.ready=true);now+=2000;core.start(lobby);lobby.game.waveBreak=999;return{core,lobby,clients,messages,advance(ms){now+=ms}}}

test('dead teammate neither receives nor blocks a level-up',()=>{const h=setup(),[a,b]=h.clients,g=h.lobby.game,dead=g.players[a.playerId];h.core.damagePlayer(h.lobby,dead,dead.hp+1,null,'test');assert.equal(g.ended,false);assert.equal(dead.alive,false);assert.equal(g.players[b.playerId].alive,true);g.xp=g.nextXp;h.core.tick(h.lobby,.04);assert.deepEqual(activeUpgradePlayers(h.lobby).map(member=>member.id),[b.playerId]);assert.deepEqual(dead.offer,[]);assert.equal(h.messages.get(0).some(message=>message.type==='levelUp'),false);assert.equal(h.messages.get(1).some(message=>message.type==='levelUp'),true);const choice=g.players[b.playerId].offer[0];h.advance(300);h.core.handle(b,{type:'upgradeChoice',choice});assert.equal(g.paused,false)});

test('dead player cannot choose or reroll an upgrade',()=>{const h=setup(),a=h.clients[0],p=h.lobby.game.players[a.playerId];p.offer=['item-speed','item-power'];h.lobby.game.paused=true;h.lobby.game.levelRound=1;h.core.damagePlayer(h.lobby,p,p.hp+1,null,'test');const afterDeath=JSON.stringify({items:p.items,offer:p.offer});h.advance(300);h.core.handle(a,{type:'upgradeChoice',choice:'item-speed'});h.advance(300);h.core.handle(a,{type:'rerollUpgrade',index:0});assert.equal(JSON.stringify({items:p.items,offer:p.offer}),afterDeath);assert.deepEqual(p.items,{})});

test('four-player level-up waits only for the two living players',()=>{const h=setup(4),g=h.lobby.game;for(const client of h.clients.slice(0,2)){const p=g.players[client.playerId];h.core.damagePlayer(h.lobby,p,p.hp+1,null,'test')}g.xp=g.nextXp;h.core.tick(h.lobby,.04);for(const client of h.clients.slice(2)){h.advance(300);h.core.handle(client,{type:'upgradeChoice',choice:g.players[client.playerId].offer[0]})}assert.equal(g.paused,false)});

test('last death wins over level-up in the same tick',()=>{const h=setup(1),p=h.lobby.game.players[h.clients[0].playerId];h.lobby.game.xp=h.lobby.game.nextXp;h.core.damagePlayer(h.lobby,p,p.hp+1,null,'test');h.core.tick(h.lobby,.04);assert.equal(h.lobby.game.ended,true);assert.equal(h.lobby.game.paused,false);assert.equal(h.messages.get(0).filter(message=>message.type==='gameOver').length,1);assert.equal(h.messages.get(0).some(message=>message.type==='levelUp'),false)});
test('projectile death inside tick wins over level-up in that tick',()=>{const h=setup(1),g=h.lobby.game,p=g.players[h.clients[0].playerId];g.xp=g.nextXp;g.pauseRequests.add(p.id);g.enemyBullets.push({id:'lethal',x:p.x,y:p.y,vx:0,vy:0,r:8,life:1,damage:p.hp+1});h.core.tick(h.lobby,.04);assert.equal(g.ended,true);assert.equal(g.paused,false);assert.equal(g.manualPaused,false);assert.equal(g.upgradePaused,false);assert.equal(g.pauseRequests.size,0);assert.equal(g.level,1);assert.deepEqual(p.offer,[]);assert.equal(h.messages.get(0).filter(message=>message.type==='gameOver').length,1);assert.equal(h.messages.get(0).some(message=>message.type==='levelUp'),false)});
