'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const utils=require('../multiplayer-client-utils'),collision=require('../shared-collision'),{GameServer,multiplayerDifficultyScale,MIN_ENEMY_SPAWN_DISTANCE,DATA}=require('../server');

function lobbyWith(count,map='ruins',random=()=>.5){let now=1000;const core=new GameServer(()=>now,random),players=Array.from({length:count},(_,i)=>({id:`p${i}`,name:`P${i}`,character:'scout',connected:true,host:i===0,ready:true,choiceRound:0})),lobby={code:'STABLE',map,createdAt:now,updatedAt:now,players,game:null};core.lobbies.set(lobby.code,lobby);core.start(lobby);return{core,lobby,g:lobby.game,advance(ms){now+=ms},now:()=>now}}

test('midpoint ping clock sync separates client and server clocks and smooths jitter',()=>{let clientNow=1050;const clock=utils.createClockSync({now:()=>clientNow,weight:.2}),first=clock.observe({clientTime:950,serverTime:5000,receivedAt:1050});assert.equal(first.rtt,100);assert.equal(first.offset,4000);assert.equal(clock.estimatedServerNow(),5050);clientNow=1150;const second=clock.observe({clientTime:1090,serverTime:5100,receivedAt:1150});assert.equal(second.rtt,92);assert.ok(second.offset>=3996&&second.offset<4000);assert.ok(clock.estimatedServerNow()>=5146&&clock.estimatedServerNow()<5150)});

test('prediction after server snapshot generation survives later delivery across RTT and jitter',()=>{for(const rtt of[20,50,100,150,250])for(const jitter of[0,20,40]){const serverClock=1000,oneWay=rtt/2+jitter,clientOffset=3700,arrivalClient=serverClock+clientOffset+oneWay,predictionClient=1030+clientOffset,state=utils.createPredictionState(),options={mapId:'ruins',radius:15,speed:180,collision};let position={x:1500,y:1100};position=utils.predictInput(state,position,{seq:4,dx:1,dy:0,predictedAt:predictionClient-clientOffset},.01,options);const result=utils.reconcileSnapshot(state,position,{tick:8,serverTime:serverClock,x:1500,y:1100,lastProcessedInputSeq:4},options);assert.ok(arrivalClient>=predictionClient||oneWay<=30);assert.equal(state.pending.length,1);assert.ok(result.target.x>1500)}});

test('party scaling has exact stable values and preserves one-player balance',()=>{const expected=[[1,1,1,1,1],[1.45,1.15,1.35,1.6,.9],[1.9,1.28,1.7,2.3,.82],[2.35,1.4,2.05,3.1,.75]];for(let count=1;count<=4;count++){const scale=multiplayerDifficultyScale(count),h=lobbyWith(count),director=h.core.directorState(h.lobby);assert.deepEqual([scale.pressure,scale.normalHp,scale.bossHp,scale.xpRequirement,scale.spawnCadence],expected[count-1]);assert.equal(h.g.partySize,count);assert.equal(h.g.nextXp,Math.round(24*scale.xpRequirement));assert.equal(director.size,Math.round(6*scale.pressure))}});

test('normal and boss HP scale separately without scaling damage',()=>{for(let count=1;count<=4;count++){const h=lobbyWith(count,'ruins',(()=>{let seed=count;return()=>((seed=seed*1664525+1013904223>>>0)/2**32)})()),scale=multiplayerDifficultyScale(count);assert.ok(h.core.spawnEnemy(h.lobby,'melee')>0);assert.ok(h.core.spawnEnemy(h.lobby,'boss')>0);const normal=h.g.enemies.find(e=>e.type==='melee'),boss=h.g.enemies.find(e=>e.type==='boss');assert.equal(normal.maxHp,DATA.enemies.melee.hp*scale.normalHp);assert.equal(boss.maxHp,DATA.enemies.boss.hp*scale.bossHp);assert.equal(normal.damage,DATA.enemies.melee.damage);assert.equal(boss.damage,DATA.enemies.boss.damage)}});

test('accepted spawns on both maps are legal and distant from every living player',()=>{for(const map of['ruins','toxic']){let seed=42;const h=lobbyWith(4,map,()=>((seed=seed*1664525+1013904223>>>0)/2**32)),points=[[400,800],[1500,1100],[2600,700],[900,1800]];Object.values(h.g.players).forEach((p,i)=>Object.assign(p,{x:points[i][0],y:points[i][1]}));for(let i=0;i<100;i++)h.core.spawnEnemy(h.lobby,i%7===0?'swarm':'melee');assert.ok(h.g.enemies.length>20);for(const enemy of h.g.enemies){assert.equal(collision.blocked(map,enemy.x,enemy.y,enemy.r),false);for(const player of Object.values(h.g.players))assert.ok(Math.hypot(enemy.x-player.x,enemy.y-player.y)>=MIN_ENEMY_SPAWN_DISTANCE)}}});

test('spawn progress uses server timestamps and reconnect does not restart old enemies',()=>{assert.equal(utils.spawnProgress(1000,1000,.35),0);assert.ok(utils.spawnProgress(1000,1175,.35)>.49&&utils.spawnProgress(1000,1175,.35)<.51);assert.equal(utils.spawnProgress(1000,1350,.35),1);assert.equal(utils.spawnProgress(1000,10000,.35),1)});

test('authoritative spawn state is snapshotted and blocks AI during telegraph',()=>{let seed=7;const h=lobbyWith(1,'ruins',()=>((seed=seed*1664525+1013904223>>>0)/2**32));assert.equal(h.core.spawnEnemy(h.lobby,'melee'),1);const enemy=h.g.enemies[0],start={x:enemy.x,y:enemy.y};assert.equal(enemy.spawnedAt,h.now());assert.equal(enemy.spawnDuration,.35);h.g.directorPhase=0;h.g.waveBreak=999;let snapshot;h.core.broadcast=(lobby,type,data)=>{if(type==='gameState')snapshot=data.state};h.advance(60);h.core.tick(h.lobby,.06);assert.deepEqual({x:enemy.x,y:enemy.y},start);assert.equal(snapshot.enemies[0].spawnedAt,enemy.spawnedAt);assert.equal(snapshot.enemies[0].spawnDuration,.35);h.advance(300);h.core.tickEnemy(h.lobby,enemy,1/30);assert.ok(Math.hypot(enemy.x-start.x,enemy.y-start.y)>0)});

test('retargeted flow fields use distinct target domains and stuck recovery invalidates only the active target',()=>{const h=lobbyWith(2),[a,b]=Object.values(h.g.players);Object.assign(a,{x:600,y:600});Object.assign(b,{x:2400,y:1600});const e={id:'nav',x:800,y:900,r:13,lastNavX:800,lastNavY:900,stuckTime:.79};const first=h.core.flowField(h.lobby,a,e.r),second=h.core.flowField(h.lobby,b,e.r);assert.notEqual(first.key,second.key);assert.ok(first.key.includes(`:${a.id}:`)&&second.key.includes(`:${b.id}:`));h.core.updateEnemyStuck(h.lobby,e,b,.02,e.x,e.y,true);assert.equal([...h.core.flowFields.keys()].some(key=>key.includes(`:${b.id}:`)),false);assert.equal(h.core.flowFields.has(first.key),true);assert.equal(e.navBias,1)});

test('four-player retarget stress keeps 24 enemies legal and making progress',()=>{const h=lobbyWith(4),points=[[400,800],[1500,1100],[2600,700],[900,1800]],enemyPoints=[];Object.values(h.g.players).forEach((p,i)=>Object.assign(p,{x:points[i][0],y:points[i][1],hp:1e9}));for(let x=250;x<2850&&enemyPoints.length<24;x+=260)for(let y=250;y<2050&&enemyPoints.length<24;y+=240)if(!collision.blocked('ruins',x,y,13))enemyPoints.push([x,y]);h.g.enemies=enemyPoints.map(([x,y],i)=>({id:`e${i}`,type:'melee',ai:'melee',x,y,hp:100,maxHp:100,r:13,speed:90,damage:0,xp:0,spawnedAt:0,spawnDuration:.35}));const starts=new Map(h.g.enemies.map(e=>[e.id,{x:e.x,y:e.y}]));h.advance(1000);for(let tick=0;tick<1800;tick++){if(tick%150===0){const rotated=points.slice(tick/150%4).concat(points.slice(0,tick/150%4));Object.values(h.g.players).forEach((p,i)=>Object.assign(p,{x:rotated[i][0],y:rotated[i][1]}))}h.advance(1000/30);for(const enemy of h.g.enemies){h.core.tickEnemy(h.lobby,enemy,1/30);assert.equal(collision.blocked('ruins',enemy.x,enemy.y,enemy.r),false)}}for(const enemy of h.g.enemies){const start=starts.get(enemy.id);assert.ok(Math.hypot(enemy.x-start.x,enemy.y-start.y)>40,enemy.id)}});
