'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const FreshRun=require('../fresh-run-state');

test('fresh singleplayer state replaces dirty multiplayer run-local data',()=>{const dirty={elapsed:123,spawnClock:9,shotClock:4,screenShake:8,directorPhase:2,waveNumber:7,waveRemaining:30,player:{x:900,y:500,xp:300,level:7,kills:42,invuln:5,staleBuff:10},skills:{q:{cd:3},e:{cd:4},r:{cd:20}},items:{power:6},augments:{glass_cannon:1},enemies:[{}],bullets:[{}],enemyBullets:[{}],orbs:[{}],loot:[{}],particles:[{}],rings:[{}],playerEchoes:[{}],damageNumbers:[{}]},fresh=FreshRun.create({world:{w:3000,h:2200},character:{hp:110,speed:235},mode:'hard',random:()=>0});Object.assign(dirty,fresh);assert.equal(dirty.elapsed,0);assert.equal(dirty.spawnClock,0);assert.equal(dirty.shotClock,0);assert.equal(dirty.screenShake,0);assert.equal(dirty.directorPhase,-1);assert.equal(dirty.waveNumber,0);assert.equal(dirty.waveRemaining,0);assert.deepEqual(dirty.player,{x:1500,y:1100,r:15,speed:235,hp:110,maxHp:110,xp:0,level:1,nextXp:24,kills:0,invuln:0});assert.deepEqual(dirty.skills,{q:{cd:0,max:5},e:{cd:0,max:9},r:{cd:0,max:28}});for(const key of['enemies','bullets','enemyBullets','orbs','loot','particles','rings','playerEchoes','damageNumbers'])assert.deepEqual(dirty[key],[]);assert.deepEqual([...dirty.runKillTypes],[]);assert.deepEqual(dirty.upgradeOfferKeys,[]);assert.deepEqual(dirty.upgradeRerolled,[])});

test('multiplayer preserves a Continue save while explicit New Game removes it',()=>{const storage=new Map([['swarmfall-save-v1','valid-singleplayer-save']]),begin=intent=>{const policy=FreshRun.startPolicy(intent);if(policy.clearSingleplayerSave)storage.delete('swarmfall-save-v1');return policy};assert.equal(begin('multiplayer').clearSingleplayerSave,false);assert.equal(storage.get('swarmfall-save-v1'),'valid-singleplayer-save');assert.equal(storage.has('swarmfall-save-v1'),true,'Continue remains available after returning to menu');assert.equal(begin('singleplayer').clearSingleplayerSave,true);assert.equal(storage.has('swarmfall-save-v1'),false)});

test('New Game uses the fresh reset while Continue and multiplayer preserve the save',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),multiplayerRuntime=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8'),multiplayerLobby=fs.readFileSync(require.resolve('../multiplayer.js'),'utf8'),reset=game.slice(game.indexOf('function resetSingleplayerRunState'),game.indexOf('function startCore')),start=game.slice(game.indexOf('function start(intent)'),game.indexOf('function enemyAt')),startCore=game.slice(game.indexOf('function startCore'),game.indexOf('function enemyAt')),continueCore=game.slice(game.indexOf('function continueGameCore'),game.indexOf('\nfunction saveStats'));assert.match(game,/startBtn'\)\.onclick=\(\)=>start\('singleplayer'\)/);assert.match(start,/if\(policy\.clearSingleplayerSave\)clearGameSave\(\)/);assert.doesNotMatch(startCore,/clearGameSave/);assert.match(multiplayerLobby,/SwarmGameStart\.multiplayer\(\)/);assert.doesNotMatch(multiplayerLobby,/startBtn'\)\.click\(\)/);assert.match(reset,/Object\.keys\(items\)/);assert.match(reset,/Object\.keys\(augments\)/);assert.match(reset,/Object\.keys\(player\)/);assert.match(reset,/setupMap\(map\)/);assert.doesNotMatch(continueCore,/resetSingleplayerRunState|clearGameSave/);for(const key of['swarmfall-multiplayer-session','swarmfall-lobby-map','swarmfall-lobby-characters'])assert.match(multiplayerRuntime,new RegExp(`removeItem\\('${key}'\\)`))});
