'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {GameServer}=require('../server');

function activeMatch(count=1){let now=1000;const core=new GameServer(()=>now,()=>.5),clients=[],messages=[];for(let i=0;i<count;i++){const out=[];messages.push(out);const client=core.addClient(message=>out.push(message));core.handle(client,{type:'hello',installationId:`reload-${i}`,unlocked:['warrior','druid'],maps:['ruins']});now+=1000;if(i===0)core.handle(client,{type:'createLobby'});else core.handle(client,{type:'joinLobby',code:clients[0].lobby});clients.push(client)}const lobby=core.lobbies.get(clients[0].lobby);core.start(lobby);lobby.game.waveBreak=999;return{core,clients,messages,lobby,advance(ms){now+=ms}}}
function reconnect(h,index){const old=h.clients[index],session=h.core.sessionsByPlayerId.get(old.playerId),out=[],replacement=h.core.addClient(message=>out.push(message));h.advance(250);h.core.handle(replacement,{type:'hello',installationId:`reload-resumed-${index}`,resume:{playerId:old.playerId,reconnectToken:session.reconnectToken},unlocked:['warrior','druid'],maps:['ruins']});return{replacement,out}}

test('single player full reconnect preserves the complete authoritative run and resumes time and input',()=>{const h=activeMatch(),g=h.lobby.game,old=h.clients[0],p=g.players[old.playerId];p.hp=p.stats.maxHp=100000;for(let i=0;i<900;i++){h.advance(40);h.core.tick(h.lobby,.04)}p.x=873;p.y=641;p.hp=63;p.stats.maxHp=100;g.xp=19;g.level=3;p.items={power:2,rapid:1};p.augments=['glass_cannon'];p.buildVersion=4;p.stats.cooldowns.qReadyAt=42000;const saved={time:g.time,x:p.x,y:p.y,hp:p.hp,xp:g.xp,level:g.level,items:{...p.items},augments:[...p.augments]},matchId=g.matchId,cooldown=p.stats.cooldowns.qReadyAt;h.core.disconnect(old);assert.equal(g.networkPaused,true);const {replacement,out}=reconnect(h,0),types=out.map(message=>message.type),gameState=out.find(message=>message.type==='gameState');assert.ok(gameState,JSON.stringify(out));const snapshot=gameState.state,mine=snapshot.players.find(player=>player.id===old.playerId),finalPauseIndex=types.lastIndexOf('pauseState');assert.ok(types.indexOf('helloAck')<types.indexOf('gameStarted'));assert.ok(types.indexOf('gameStarted')<types.indexOf('gameState'));assert.ok(types.indexOf('gameState')<finalPauseIndex);assert.equal(g.matchId,matchId);assert.deepEqual({time:snapshot.time,x:mine.x,y:mine.y,hp:mine.hp,xp:snapshot.xp,level:snapshot.level,items:mine.items,augments:mine.augments},saved);assert.equal(mine.cooldowns.qReadyAt,cooldown+250);assert.equal(g.networkPaused,false);assert.equal(g.paused,false);const beforeTime=g.time,beforeX=p.x;h.advance(100);h.core.handle(replacement,{type:'playerInput',right:true,aim:0,inputSeq:1});h.core.tick(h.lobby,.1);assert.ok(g.time>beforeTime);assert.ok(p.x>beforeX)});

test('two-player reconnect does not pause the connected teammate or replace either authoritative player',()=>{const h=activeMatch(2),g=h.lobby.game,[a,b]=h.clients,pa=g.players[a.playerId],pb=g.players[b.playerId],authoritative={x:pa.x,y:pa.y};const id=g.matchId,time=g.time;h.core.disconnect(a);assert.equal(g.networkPaused,false);h.advance(300);h.core.handle(b,{type:'playerInput',left:true,aim:0,inputSeq:1});h.core.tick(h.lobby,.2);assert.ok(g.time>time);const teammateX=pb.x;assert.notEqual(teammateX,authoritative.x);const {replacement,out}=reconnect(h,0),mine=out.find(message=>message.type==='gameState').state.players.find(player=>player.id===a.playerId);assert.equal(g.matchId,id);assert.deepEqual({x:mine.x,y:mine.y},authoritative);const ax=pa.x,bx=pb.x;h.advance(300);h.core.handle(replacement,{type:'playerInput',left:true,aim:0,inputSeq:1});h.core.handle(b,{type:'playerInput',left:true,aim:0,inputSeq:2});h.core.tick(h.lobby,.1);assert.ok(pa.x<ax);assert.ok(pb.x<bx)});

test('multiplayer browser boot starts one non-destructive loop before authoritative state is consumed',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),runtime=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8'),start=game.slice(game.indexOf('function start(intent)'),game.indexOf('function continueGame()')),multiplayerCore=game.slice(game.indexOf('function startMultiplayerCore'),game.indexOf('function startCore')),loopGuard=game.slice(game.indexOf('function ensureGameLoop'),game.indexOf('function startMultiplayerCore'));assert.match(start,/if\(intent==='multiplayer'\).*startMultiplayerCore/s);assert.doesNotMatch(multiplayerCore,/resetSingleplayerRunState|startDirectorPhase|saveGame/);assert.match(multiplayerCore,/ensureGameLoop\(\)/);assert.match(loopGuard,/if\(gameLoopStarted\)return false/);assert.equal((game.match(/requestAnimationFrame\(loop\)/g)||[]).length,2);assert.match(runtime,/currentMatchId=null/);assert.match(runtime,/message\.type==='gameStarted'/);assert.match(runtime,/message\.type==='gameState'/);assert.ok(runtime.indexOf("message.type==='gameStarted'")<runtime.indexOf("message.type==='gameState'"))});

test('debug multiplayer flag is restricted to logging and metrics, not lifecycle transitions',()=>{const game=fs.readFileSync(require.resolve('../game.js'),'utf8'),lobby=fs.readFileSync(require.resolve('../multiplayer.js'),'utf8'),runtime=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8');for(const source of[game,lobby,runtime]){for(const match of source.matchAll(/if\(debugPerformance\)|if\(localStorage\.getItem\('swarmfall-debug-multiplayer'\)==='1'\)/g)){const tail=source.slice(match.index,match.index+240);assert.doesNotMatch(tail,/startMultiplayerCore|resetMatchRuntime|currentMatchId=|networkPaused|socket\.send\([^)]*playerInput/)}}});
