'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createControlChannel,shouldApplyHelloAck}=require('../multiplayer-socket-state');
const ack=(generation=1,id=`connection-${generation}`)=>({type:'helloAck',playerId:'player-a',reconnectToken:'secret',connectionId:id,connectionGeneration:generation,lastProcessedInputSeq:generation*10,lastAbilityInputSeq:generation});
test('late consumer can synchronously read and replay the current helloAck',()=>{const channel=createControlChannel(),message=ack();channel.beginConnection();channel.publish(message);assert.equal(channel.getHandshakeState(),'authenticated');assert.deepEqual(channel.getLastHelloAck(),message);const received=[];channel.on(event=>received.push(event));assert.deepEqual(received,[message])});
test('consumer registered before helloAck receives the same handshake',()=>{const channel=createControlChannel(),received=[];channel.beginConnection();channel.on(event=>received.push(event));const message=ack();channel.publish(message);assert.deepEqual(received,[message]);assert.deepEqual(channel.getLastHelloAck(),message)});
test('helloAck replay and listener delivery are safe to apply exactly once',()=>{const channel=createControlChannel(),message=ack();let applied=null,count=0;const consume=next=>{if(shouldApplyHelloAck(applied,next)){applied=next;count++}};channel.beginConnection();channel.publish(message);consume(channel.getLastHelloAck());channel.on(consume);assert.equal(count,1)});
test('new generation replaces old ACK and a late old ACK cannot overwrite it',()=>{const first=ack(1),second=ack(2),applied=[];for(const message of[first,second,first])if(shouldApplyHelloAck(applied.at(-1),message))applied.push(message);assert.deepEqual(applied,[first,second])});
test('begin reconnect and resume rejection invalidate stale handshake state',()=>{const channel=createControlChannel();channel.beginConnection();channel.publish(ack());channel.beginConnection();assert.equal(channel.getHandshakeState(),'pending');assert.equal(channel.getLastHelloAck(),null);channel.publish({type:'resumeRejected'});assert.equal(channel.getHandshakeState(),'rejected');assert.equal(channel.getLastHelloAck(),null)});
