'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const mechanics=require('../shared-mechanics'),{GameServer,DATA}=require('../server'),{createPredictionState,predictInput}=require('../multiplayer-client-utils'),collision=require('../shared-collision');
test('last physical direction press wins and key repeat does not steal priority',()=>{const keys={},input=mechanics.createMovementResolver(keys);input.keyDown('a');assert.equal(input.resolve().dx,-1);input.keyDown('d');assert.equal(input.resolve().dx,1);input.keyDown('a',true);assert.equal(input.resolve().dx,1);input.keyUp('d');assert.equal(input.resolve().dx,-1);input.keyUp('a');input.keyDown('d');input.keyDown('a');assert.equal(input.resolve().dx,-1);input.keyUp('a');input.keyUp('d');input.keyDown('w');input.keyDown('s');assert.equal(input.resolve().dy,1);input.keyUp('s');assert.equal(input.resolve().dy,-1);input.keyUp('w');input.keyDown('s');input.keyDown('w');assert.equal(input.resolve().dy,-1)});
test('resolved diagonal is identical for prediction and unambiguous network flags',()=>{const keys={},input=mechanics.createMovementResolver(keys);input.keyDown('a');input.keyDown('d');input.keyDown('w');const resolved=input.resolve();assert.deepEqual(resolved,{dx:1,dy:-1,left:false,right:true,up:true,down:false});const state=createPredictionState(),start={x:1500,y:1100},predicted=predictInput(state,start,{seq:1,dx:resolved.dx,dy:resolved.dy},1/30,{mapId:'ruins',radius:15,speed:210,collision});assert.ok(predicted.x>start.x&&predicted.y<start.y);assert.deepEqual({left:resolved.left,right:resolved.right,up:resolved.up,down:resolved.down},{left:false,right:true,up:true,down:false})});
function match(character='scout'){let now=1000;const core=new GameServer(()=>now,()=>.99),client=core.addClient(()=>{});core.handle(client,{type:'hello',installationId:`cooldown-${character}`,unlocked:['warrior','druid'],maps:['ruins']});now+=1000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);lobby.players[0].character=character;core.start(lobby);const p=lobby.game.players[client.playerId],enemy={id:'target',type:'brute',x:p.x+40,y:p.y,r:20,hp:1000,maxHp:1000,speed:0,damage:0};lobby.game.enemies=[enemy];return{core,client,lobby,p,enemy,advance(ms){now+=ms}}}
for(const ability of['q','e','r'])test(`normal ${ability.toUpperCase()} cooldown rejects a second cast without side effects`,()=>{const h=match(),first=h.core.castAbility(h.lobby,h.p,ability,0);assert.equal(first,true);const before={abilitySeq:h.p.abilitySeq,lastAbility:h.p.lastAbility,readyAt:h.p.stats.cooldowns[`${ability}ReadyAt`],hp:h.p.hp,x:h.p.x,y:h.p.y,enemyHp:h.enemy.hp,bullets:h.lobby.game.bullets.length};assert.equal(h.core.castAbility(h.lobby,h.p,ability,0),false);assert.deepEqual({abilitySeq:h.p.abilitySeq,lastAbility:h.p.lastAbility,readyAt:h.p.stats.cooldowns[`${ability}ReadyAt`],hp:h.p.hp,x:h.p.x,y:h.p.y,enemyHp:h.enemy.hp,bullets:h.lobby.game.bullets.length},before)});
test('Blood Price bypass requires sufficient HP and preserves its existing cost',()=>{const accepted=match();accepted.p.augments.push('blood_price');assert.equal(accepted.core.castAbility(accepted.lobby,accepted.p,'q',0),true);const hp=accepted.p.hp;assert.equal(accepted.core.castAbility(accepted.lobby,accepted.p,'q',0),true);assert.equal(accepted.p.hp,hp-accepted.p.stats.maxHp*.12);const rejected=match();rejected.p.augments.push('blood_price');assert.equal(rejected.core.castAbility(rejected.lobby,rejected.p,'e',0),true);rejected.p.hp=rejected.p.stats.maxHp*.12+1;const seq=rejected.p.abilitySeq,ready=rejected.p.stats.cooldowns.eReadyAt;assert.equal(rejected.core.castAbility(rejected.lobby,rejected.p,'e',0),false);assert.equal(rejected.p.abilitySeq,seq);assert.equal(rejected.p.stats.cooldowns.eReadyAt,ready)});
test('Druid R intentionally resets authoritative Q and E cooldowns',()=>{const h=match('druid');assert.equal(h.core.castAbility(h.lobby,h.p,'q',0),true);assert.equal(h.core.castAbility(h.lobby,h.p,'e',0),true);assert.ok(h.p.stats.cooldowns.qReadyAt>h.core.now());assert.ok(h.p.stats.cooldowns.eReadyAt>h.core.now());assert.equal(h.core.castAbility(h.lobby,h.p,'r',0),true);assert.ok(h.p.stats.cooldowns.qReadyAt<=h.core.now());assert.ok(h.p.stats.cooldowns.eReadyAt<=h.core.now())});
test('distinct input sequences during cooldown are rejected and never execute later',()=>{const h=match();h.core.handle(h.client,{type:'abilityPress',ability:'q',aim:0,seq:1});const abilitySeq=h.p.abilitySeq,bullets=h.lobby.game.bullets.length;h.advance(100);h.core.handle(h.client,{type:'abilityPress',ability:'q',aim:0,seq:2});h.advance(100);h.core.handle(h.client,{type:'abilityPress',ability:'q',aim:0,seq:3});assert.equal(h.p.abilitySeq,abilitySeq);assert.equal(h.lobby.game.bullets.length,bullets);assert.equal(h.p.lastAbilityInputSeq,3);h.advance(DATA.characters.scout.abilities.q.cooldown*1000+1);h.core.tick(h.lobby,.01);assert.equal(h.p.abilitySeq,abilitySeq);assert.equal(h.lobby.game.bullets.length,bullets);h.core.handle(h.client,{type:'abilityPress',ability:'q',aim:0,seq:3});assert.equal(h.p.abilitySeq,abilitySeq)});
test('client cooldown guard never sends early and allows only valid Blood Price bypass',()=>{const now=1000,readyAt=2000;assert.equal(mechanics.canAttemptAbility({readyAt,now,hp:100,maxHp:100}),false);assert.equal(mechanics.canAttemptAbility({readyAt,now,hasBloodPrice:true,hp:100,maxHp:100}),true);assert.equal(mechanics.canAttemptAbility({readyAt,now,hasBloodPrice:true,hp:13,maxHp:100}),false);assert.equal(mechanics.canAttemptAbility({readyAt:1050,now,hp:100,maxHp:100}),false);assert.equal(mechanics.canAttemptAbility({readyAt:1000,now,hp:100,maxHp:100}),true)});
test('movement clear releases held keys and resets old priority after focus loss',()=>{const keys={},input=mechanics.createMovementResolver(keys);input.keyDown('a');input.keyDown('d');input.clear();assert.deepEqual(input.resolve(),{dx:0,dy:0,left:false,right:false,up:false,down:false});input.keyDown('a');input.keyDown('d');assert.equal(input.resolve().dx,1)});
