'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer}=require('../server');

function pair(){let now=1000;const core=new GameServer(()=>now,()=>.5),out=[[],[]],clients=out.map(messages=>core.addClient(message=>messages.push(message)));for(let i=0;i<2;i++){core.handle(clients[i],{type:'hello',installationId:`life-${i}`,unlocked:[],maps:['ruins']});now+=1000;if(!i)core.handle(clients[i],{type:'createLobby'});else core.handle(clients[i],{type:'joinLobby',code:clients[0].lobby})}const lobby=core.lobbies.get(clients[0].lobby);lobby.players[1].ready=true;now+=1000;return{core,clients,lobby,out,advance(ms){now+=ms}}}

test('each start has a unique matchId and a peer return produces a clean second match',()=>{const h=pair();h.core.handle(h.clients[0],{type:'startGame'});const first=h.lobby.game.matchId;assert.ok(first);h.lobby.game.players[h.clients[0].playerId].items.power=4;h.lobby.game.ended=true;h.advance(1000);h.core.handle(h.clients[1],{type:'returnToLobby'});assert.equal(h.lobby.game,null);assert.equal(h.out.every(messages=>messages.some(message=>message.type==='lobbyState'&&!message.lobby.started&&message.lobby.matchId===null)),true);h.lobby.players[1].ready=true;h.advance(1000);h.core.handle(h.clients[0],{type:'startGame'});assert.notEqual(h.lobby.game.matchId,first);assert.deepEqual(h.lobby.game.players[h.clients[0].playerId].items,{});assert.equal(h.out.every(messages=>messages.some(message=>message.type==='gameStarted'&&message.matchId===h.lobby.game.matchId)),true)});

test('leaveLobby confirms removal, migrates host, and rejects create/join during a match',()=>{const h=pair();h.core.handle(h.clients[0],{type:'leaveLobby'});assert.equal(h.clients[0].lobby,'');assert.ok(h.out[0].some(message=>message.type==='leftLobby'));assert.equal(h.lobby.players[0].id,h.clients[1].playerId);assert.equal(h.lobby.players[0].host,true);h.advance(1000);h.core.handle(h.clients[1],{type:'startGame'});const players=Object.keys(h.lobby.game.players);h.advance(2000);h.core.handle(h.clients[1],{type:'createLobby'});assert.deepEqual(Object.keys(h.lobby.game.players),players);assert.equal(h.clients[1].lobby,h.lobby.code)});

test('a disconnected ready guest blocks start until reconnect',()=>{const h=pair();h.core.disconnect(h.clients[1]);h.advance(1000);h.core.handle(h.clients[0],{type:'startGame'});assert.equal(h.lobby.game,null);const session=h.core.sessionsByPlayerId.get(h.clients[1].playerId),replacement=h.core.addClient(()=>{});h.advance(1000);h.core.handle(replacement,{type:'hello',installationId:'replacement',resume:{playerId:h.clients[1].playerId,reconnectToken:session.reconnectToken},unlocked:[],maps:['ruins']});h.advance(1000);h.core.handle(h.clients[0],{type:'startGame'});assert.ok(h.lobby.game)});

test('network pause preserves match and resumes it when the first player reconnects',()=>{const h=pair();h.core.handle(h.clients[0],{type:'startGame'});const id=h.lobby.game.matchId,tick=h.lobby.game.tick,sessions=h.clients.map(c=>h.core.sessionsByPlayerId.get(c.playerId));h.core.disconnect(h.clients[0]);h.core.disconnect(h.clients[1]);h.core.tick(h.lobby,.5);assert.equal(h.lobby.game.tick,tick);assert.equal(h.lobby.game.networkPaused,true);const replacement=h.core.addClient(()=>{});h.advance(1000);h.core.handle(replacement,{type:'hello',installationId:'resume-first',resume:{playerId:h.clients[0].playerId,reconnectToken:sessions[0].reconnectToken},unlocked:[],maps:['ruins']});assert.equal(h.lobby.game.matchId,id);assert.equal(h.lobby.game.networkPaused,false);h.core.tick(h.lobby,.5);assert.equal(h.lobby.game.tick,tick+1)});

test('dead spectator reconnect cannot release network pause held for disconnected living player',()=>{const h=pair();h.core.handle(h.clients[0],{type:'startGame'});const g=h.lobby.game,id=g.matchId,a=g.players[h.clients[0].playerId],sessions=h.clients.map(c=>h.core.sessionsByPlayerId.get(c.playerId));h.core.damagePlayer(h.lobby,a,a.hp+1,null,'test');h.core.disconnect(h.clients[1]);assert.equal(g.networkPaused,true);h.core.disconnect(h.clients[0]);const deadReconnect=h.core.addClient(()=>{});h.advance(1000);h.core.handle(deadReconnect,{type:'hello',installationId:'dead-resume',resume:{playerId:h.clients[0].playerId,reconnectToken:sessions[0].reconnectToken},unlocked:[],maps:['ruins']});assert.equal(g.networkPaused,true);const livingReconnect=h.core.addClient(()=>{});h.advance(1000);h.core.handle(livingReconnect,{type:'hello',installationId:'living-resume',resume:{playerId:h.clients[1].playerId,reconnectToken:sessions[1].reconnectToken},unlocked:[],maps:['ruins']});assert.equal(g.networkPaused,false);assert.equal(g.matchId,id)});

test('disconnected player is frozen against projectiles and hazards until reconnect',()=>{const h=pair();h.core.handle(h.clients[0],{type:'startGame'});const g=h.lobby.game,a=g.players[h.clients[0].playerId],hp=a.hp,session=h.core.sessionsByPlayerId.get(a.id);h.core.disconnect(h.clients[0]);g.enemyBullets.push({id:'frozen-hit',x:a.x,y:a.y,vx:0,vy:0,r:8,life:1,damage:25});g.hazards.push({id:'frozen-hazard',type:'trap',x:a.x,y:a.y,r:30,life:2});h.core.tickProjectiles(h.lobby,.01);h.core.tickPickups(h.lobby,1);assert.equal(a.hp,hp);const replacement=h.core.addClient(()=>{});h.advance(1000);h.core.handle(replacement,{type:'hello',installationId:'hp-resume',resume:{playerId:a.id,reconnectToken:session.reconnectToken},unlocked:[],maps:['ruins']});assert.equal(g.players[a.id].hp,hp)});

test('every emitted match control carries the active matchId',()=>{const h=pair();h.core.handle(h.clients[0],{type:'startGame'});const g=h.lobby.game,p=g.players[h.clients[0].playerId];g.xp=g.nextXp;h.core.tick(h.lobby,.04);h.advance(1000);h.core.handle(h.clients[0],{type:'upgradeChoice',choice:p.offer[0]});const scoped=new Set(['gameStarted','gameState','gameOver','pauseState','levelUp','levelResume','upgradeWaiting','upgradeOffer','upgradeAccepted']);for(const message of h.out.flat().filter(message=>scoped.has(message.type)))assert.equal(message.type==='gameState'?message.state.matchId:message.matchId,g.matchId,message.type)});
