'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,applyUpgrade,DATA}=require('../server'),mechanics=require('../shared-mechanics');
function match(character='scout'){let now=1000;const core=new GameServer(()=>now,()=>.99),client=core.addClient(()=>{});core.handle(client,{type:'hello',installationId:`parity-${character}`,unlocked:['warrior','druid'],maps:['ruins']});now+=1000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);lobby.players[0].character=character;core.start(lobby);return{core,lobby,p:lobby.game.players[client.playerId],g:lobby.game}}
function attack(h){h.p.input={received:true,aim:0};h.p.shot=0;h.core.tickPlayer(h.lobby,h.p,.01)}
test('fresh magnet and unrelated stat refresh preserve the single-player baseline',()=>{const h=match(),before=h.p.stats.magnet;assert.equal(before,105);applyUpgrade(h.p,'augment-gambler');assert.equal(h.p.stats.magnet,before);const expected={damage:DATA.characters.scout.damage,fireRate:DATA.characters.scout.fireRate,speed:DATA.characters.scout.speed,maxHp:DATA.characters.scout.hp,projectileSpeed:DATA.characters.scout.projectileSpeed,projectileSize:4,projectileLife:1.3,projectiles:1,pierce:0,critChance:.1,critDamage:1.8,lifesteal:0,thorns:0,powder:0,totem:0,vault:0};for(const[key,value]of Object.entries(expected))assert.equal(h.p.stats[key],value,key)});
test('magnet levels one and six use the shared single-player formula',()=>{const one=match();applyUpgrade(one.p,'item-magnet');assert.equal(one.p.stats.magnet,105*Math.pow(1.32,1));const six=match();for(let level=0;level<6;level++)applyUpgrade(six.p,'item-magnet');assert.equal(mechanics.itemPower(six.p.items,'magnet'),8.1);assert.equal(six.p.stats.magnet,mechanics.magnetRadius({magnet:6}))});
test('Warrior attacks once without Second Chamber and twice when it is ready',()=>{const single=match('warrior'),enemySingle={id:'single',type:'melee',x:single.p.x+40,y:single.p.y,r:15,hp:200,maxHp:200};single.g.enemies=[enemySingle];attack(single);assert.equal(200-enemySingle.hp,DATA.characters.warrior.damage);assert.equal(single.p.attackSeq,1);const double=match('warrior'),enemyDouble={...enemySingle,id:'double',hp:200};double.g.enemies=[enemyDouble];applyUpgrade(double.p,'augment-second_chamber');attack(double);assert.equal(200-enemyDouble.hp,DATA.characters.warrior.damage*2);assert.equal(double.p.attackSeq,1);assert.equal(double.p.secondChamber,4)});
test('Warrior Second Chamber cooldown and Totem synergy match single-player',()=>{const h=match('warrior'),enemy={id:'cooldown',type:'melee',x:h.p.x+40,y:h.p.y,r:15,hp:300,maxHp:300};h.g.enemies=[enemy];applyUpgrade(h.p,'augment-second_chamber');attack(h);const afterDouble=enemy.hp;attack(h);assert.equal(afterDouble-enemy.hp,DATA.characters.warrior.damage);const totem=match('warrior'),totemEnemy={...enemy,id:'totem',hp:300};totem.g.enemies=[totemEnemy];applyUpgrade(totem.p,'item-totem');applyUpgrade(totem.p,'augment-second_chamber');totem.p.stillTime=2;attack(totem);assert.equal(totem.p.totemReady,true);assert.equal(totem.p.secondChamber,2)});
test('Warrior Second Chamber is safe without a target and opens a crate only once',()=>{const empty=match('warrior');applyUpgrade(empty.p,'augment-second_chamber');assert.doesNotThrow(()=>attack(empty));assert.equal(empty.p.attackSeq,1);assert.equal(empty.p.secondChamber,4);const h=match('warrior'),crate={id:'near',x:h.p.x+35,y:h.p.y,hp:28,maxHp:28,opened:false,hitSeq:0};h.g.crates=[crate];applyUpgrade(h.p,'augment-second_chamber');attack(h);assert.equal(crate.opened,true);assert.equal(crate.hp,0);assert.equal(crate.hitSeq,2);assert.equal(h.g.loot.length,1);h.p.shot=0;h.p.secondChamber=0;attack(h);assert.equal(crate.hitSeq,2);assert.equal(h.g.loot.length,1)});
