'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,applyUpgrade,DATA}=require('../server');
function match(character='scout'){let now=1000;const core=new GameServer(()=>now),messages=[],client=core.addClient(m=>messages.push(m));core.handle(client,{type:'hello',clientId:'host',unlocked:['warrior','druid'],maps:['ruins','toxic']});now+=2000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);lobby.players[0].character=character;core.start(lobby);return{core,lobby,g:lobby.game,p:lobby.game.players.host,client,messages,advance:n=>now+=n}}
function enemy(type,x,y){const d=DATA.enemies[type];return{id:type,type,ai:d.ai,x,y,hp:d.hp,maxHp:d.hp,r:d.r,speed:d.speed,damage:d.damage,xp:d.xp,attack:0,special:0}}
test('all enemy types have explicit authoritative AI data',()=>{for(const type of['melee','brute','shooter','charger','exploder','swarm','toxic','trapper','boss'])assert.ok(DATA.enemies[type].ai)});
test('shooter creates a server-owned projectile',()=>{const h=match(),e=enemy('shooter',h.p.x+300,h.p.y);h.g.enemies=[e];h.core.tickEnemy(h.lobby,e,.04);assert.equal(h.g.enemyBullets.length,1);assert.equal(h.g.enemyBullets[0].ownerId,e.id)});
test('charger enters charge behavior and moves authoritatively',()=>{const h=match(),e=enemy('charger',h.p.x+200,h.p.y);h.g.enemies=[e];h.core.tickEnemy(h.lobby,e,.04);assert.ok(e.charging>0);const x=e.x;h.core.tickEnemy(h.lobby,e,.04);assert.notEqual(e.x,x)});
test('exploder deals AoE and is consumed',()=>{const h=match(),e=enemy('exploder',h.p.x+10,h.p.y);h.g.enemies=[e];const hp=h.p.hp;h.core.tickEnemy(h.lobby,e,.04);assert.ok(h.p.hp<hp);assert.equal(e.hp,0)});
test('boss spawns at the authoritative timer',()=>{const h=match();h.g.time=300;h.g.bossAt=300;h.g.spawn=99;h.core.tick(h.lobby,.04);assert.ok(h.g.enemies.some(e=>e.type==='boss'))});
test('kill attribution follows lethal projectile owner',()=>{const h=match(),e=enemy('melee',h.p.x+10,h.p.y);e.hp=1;h.g.enemies=[e];h.core.damageEnemy(h.lobby,e,5,h.p,'projectile');assert.equal(h.p.kills,1);assert.equal(e.lastHit.ownerId,h.p.id)});
test('crit is rolled server-side and increases projectile damage',()=>{const h=match(),old=Math.random;Math.random=()=>0;try{h.core.firePlayer(h.lobby,h.p,0,false);assert.ok(h.g.bullets[0].damage>h.p.stats.damage);assert.equal(h.g.bullets[0].crit,true)}finally{Math.random=old}});
test('lifesteal, thorns and regeneration are server authoritative',()=>{const h=match();h.p.hp=50;applyUpgrade(h.p,'item-lifesteal');const e=enemy('melee',h.p.x+10,h.p.y);e.hp=.1;h.core.damageEnemy(h.lobby,e,2,h.p,'projectile');assert.ok(h.p.hp>50);applyUpgrade(h.p,'item-spikes');const before=e.hp=20;h.core.tickEnemy(h.lobby,e,.04);assert.ok(e.hp<before);applyUpgrade(h.p,'item-bottle');const hp=h.p.hp;h.core.tickPlayer(h.lobby,h.p,1);assert.ok(h.p.hp>hp)});
test('multishot and pierce are applied to server projectiles',()=>{const h=match();applyUpgrade(h.p,'item-multi');applyUpgrade(h.p,'item-blade');h.core.firePlayer(h.lobby,h.p,0,false);assert.equal(h.g.bullets.length,2);assert.equal(h.g.bullets[0].pierce,1)});
test('orb magnet movement and pickup grant XP only on collection',()=>{const h=match();h.g.orbs=[{id:'o',x:h.p.x+50,y:h.p.y,value:7}];const before=h.g.xp;h.core.tickPickups(h.lobby,.3);h.core.tickPickups(h.lobby,.3);assert.equal(h.g.orbs.length,0);assert.equal(h.g.xp,before+7)});
test('magnet upgrade increases authoritative pickup radius',()=>{const h=match(),before=h.p.stats.magnet;applyUpgrade(h.p,'item-magnet');assert.ok(h.p.stats.magnet>before)});
test('projectiles damage crates, open them and create loot',()=>{const h=match(),c=h.g.crates[0];h.g.bullets=[{id:'b',ownerId:h.p.id,x:c.x,y:c.y,vx:0,vy:0,r:4,life:1,damage:99,pierce:0}];h.core.tickProjectiles(h.lobby,.01);assert.equal(c.opened,true);assert.equal(h.g.loot.length,1)});
test('loot pickup is resolved by server',()=>{const h=match();h.p.hp=20;h.g.loot=[{id:'l',x:h.p.x,y:h.p.y,type:'health',value:35}];h.core.tickPickups(h.lobby,.04);assert.ok(h.p.hp>20);assert.equal(h.g.loot.length,0)});
test('ability cooldown blocks repeated use and blood price pays HP',()=>{const h=match();h.g.enemies=[enemy('melee',h.p.x+50,h.p.y)];h.core.castAbility(h.lobby,h.p,'e',0);const cd=h.p.stats.cooldowns.e,hp=h.p.hp;h.core.castAbility(h.lobby,h.p,'e',0);assert.equal(h.p.stats.cooldowns.e,cd);assert.equal(h.p.hp,hp);h.p.augments.push('blood_price');h.core.castAbility(h.lobby,h.p,'e',0);assert.ok(h.p.hp<hp)});
test('death, last chance and game over follow server state',()=>{const h=match();h.p.augments.push('last_chance');h.core.damagePlayer(h.lobby,h.p,999,null,'test');assert.equal(h.p.hp,1);assert.equal(h.p.alive,true);h.core.damagePlayer(h.lobby,h.p,999,null,'test');assert.equal(h.p.alive,false);h.core.tick(h.lobby,.04);assert.equal(h.g.ended,true);assert.ok(h.messages.some(m=>m.type==='gameOver'))});
test('return to lobby clears match and resets ready',()=>{const h=match();h.g.ended=true;h.advance(1000);h.core.handle(h.client,{type:'returnToLobby'});assert.equal(h.lobby.game,null);assert.equal(h.lobby.players[0].ready,true)});
test('disconnected level player does not block and reconnect keeps offer',()=>{const h=match();h.g.paused=true;h.g.levelRound=2;h.lobby.players[0].choiceRound=0;h.p.offer=['item-power'];h.core.disconnect(h.client);h.advance(5000);const replacement=h.core.addClient(()=>{});h.core.handle(replacement,{type:'hello',clientId:'host',unlocked:[],maps:['ruins']});assert.deepEqual(h.g.players.host.offer,['item-power']);h.core.disconnect(replacement);h.advance(16000);h.core.cleanup();assert.equal(h.core.lobbies.has(h.lobby.code),false)});
test('host disconnect during game does not stop simulation authority',()=>{const h=match(),tick=h.g.tick;h.core.disconnect(h.client);h.core.tick(h.lobby,.04);assert.equal(h.g.tick,tick+1)});
test('client cannot submit authoritative state fields',()=>{const h=match(),snapshot={x:h.p.x,hp:h.p.hp,xp:h.g.xp,cd:h.p.stats.cooldowns.q};h.advance(100);h.core.handle(h.client,{type:'playerInput',aim:0,x:9999,hp:9999,xp:9999,damage:9999,crit:true,cooldown:0});assert.deepEqual({x:h.p.x,hp:h.p.hp,xp:h.g.xp,cd:h.p.stats.cooldowns.q},snapshot);h.advance(300);h.g.paused=true;h.g.levelRound=1;h.p.offer=['item-speed'];h.core.handle(h.client,{type:'upgradeChoice',choice:'item-power'});assert.equal(h.p.items.power,undefined)});
