'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {smoothRtt,pingQuality,reconcilePosition,copyLobbyCode}=require('../multiplayer-client-utils');
const {GameServer,blocked}=require('../server');
function match(random=()=>.5){let now=1000;const messages=[],core=new GameServer(()=>now,random),client=core.addClient(message=>messages.push(message));core.handle(client,{type:'hello',installationId:'ux',unlocked:[],maps:['ruins']});now+=1000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);core.start(lobby);return{core,client,lobby,g:lobby.game,p:lobby.game.players[client.playerId],messages,advance:n=>now+=n}}

test('application ping is rate limited and RTT helpers smooth and classify samples',()=>{const h=match();h.advance(1000);h.core.handle(h.client,{type:'ping',id:1,clientTime:123});assert.deepEqual(h.messages.at(-1),{type:'pong',id:1,clientTime:123,serverTime:3000});h.core.handle(h.client,{type:'ping',id:2,clientTime:124});assert.equal(h.messages.some(m=>m.type==='pong'&&m.id===2),false);assert.equal(smoothRtt(50,100),60);assert.deepEqual([pingQuality(40),pingQuality(80),pingQuality(150)],['good','medium','bad'])});
test('copy lobby code uses clipboard and falls back to a temporary textarea',async()=>{let value='';assert.equal(await copyLobbyCode('ABC234',{clipboard:{writeText:async text=>value=text}}),true);assert.equal(value,'ABC234');let selected=false,removed=false;const area={style:{},setAttribute(){},select(){selected=true},remove(){removed=true}},document={body:{appendChild(){}},createElement:()=>area,execCommand:command=>command==='copy'};assert.equal(await copyLobbyCode('XYZ789',{clipboard:{writeText:async()=>{throw Error('denied')}},document}),true);assert.equal(area.value,'XYZ789');assert.equal(selected&&removed,true);assert.equal(await copyLobbyCode('NOPE',{clipboard:null,document:null}),false)});
test('prediction reconciliation is packet-count independent and bounded',()=>{for(const fps of[20,60,144])for(const latency of[50,100,150]){let position={x:0,y:0};const speed=210,duration=3;for(let i=0;i<fps*duration;i++)position.x+=speed/fps;const authoritative={x:speed*(duration-latency/1000),y:0},next=reconcilePosition(position,authoritative);assert.ok(Number.isFinite(next.x));assert.ok(Math.abs(next.x-authoritative.x)<Math.abs(position.x-authoritative.x));const diagonal=reconcilePosition({x:30,y:30},{x:25,y:25});assert.equal(diagonal.snapped,false)}assert.deepEqual(reconcilePosition({x:500,y:0},{x:0,y:0}),{x:0,y:0,snapped:true})});
test('server enemy steers around an L wall without entering its collider',()=>{const h=match(()=>.5),e={id:'path',type:'melee',ai:'melee',x:790,y:330,hp:99,maxHp:99,r:13,speed:90,damage:0,xp:0,shot:1};h.p.x=1300;h.p.y=700;h.g.enemies=[e];const start=Math.hypot(e.x-h.p.x,e.y-h.p.y);for(let i=0;i<600;i++){h.core.tickEnemy(h.lobby,e,1/30);assert.equal(blocked('ruins',e.x,e.y,e.r),false)}assert.ok(Math.hypot(e.x-h.p.x,e.y-h.p.y)<start-100)});
test('crate opens once, persists in snapshots and coin pickup is authoritative',()=>{const h=match(()=>0),c=h.g.crates[0];h.g.bullets=[{id:'crate-shot',ownerId:h.p.id,x:c.x,y:c.y,vx:0,vy:0,r:4,life:1,damage:999,pierce:0}];h.core.tickProjectiles(h.lobby,.01);assert.equal(c.hp,0);assert.equal(c.opened,true);assert.equal(h.g.loot.length,1);h.core.openCrate(h.g,c);assert.equal(h.g.loot.length,1);const coin=h.g.loot[0];assert.equal(coin.type,'coin');coin.x=h.p.x;coin.y=h.p.y;h.core.tickPickups(h.lobby,.01);assert.equal(h.p.coins,1);h.core.currentConnection(h.p.id).send=m=>h.messages.push(m);h.core.tick(h.lobby,.06);const state=h.messages.findLast(m=>m.type==='gameState').state;assert.equal(state.crates[0].opened,true);assert.equal(state.players.find(p=>p.id===h.p.id).coins,1)});
test('shooter facing is authoritative and exploder emits one visual event with one damage',()=>{const h=match(),d=require('../shared-game-data').enemies;const shooter={id:'s',type:'shooter',ai:'shooter',x:1000,y:1000,hp:40,maxHp:40,r:d.shooter.r,speed:0,damage:0,xp:0,shot:1};h.g.enemies=[shooter];h.p.x=900;h.p.y=1000;h.core.tickEnemy(h.lobby,shooter,.01);assert.ok(Math.abs(Math.abs(shooter.facing)-Math.PI)<.01);h.p.x=1100;h.core.tickEnemy(h.lobby,shooter,.01);assert.ok(Math.abs(shooter.facing)<.01);const exploder={id:'x',type:'exploder',ai:'exploder',x:h.p.x,y:h.p.y,hp:20,maxHp:20,r:d.exploder.r,speed:0,damage:10,xp:0,attack:0};h.g.enemies=[exploder];const hp=h.p.hp;h.core.tickEnemy(h.lobby,exploder,.01);assert.equal(h.p.hp,hp);h.core.tickEnemy(h.lobby,exploder,.55);assert.equal(h.p.hp,hp-10);assert.equal(h.g.explosions.length,1);assert.equal(h.g.explosionSeq,1)});
