'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const mechanics=require('../shared-mechanics'),utils=require('../multiplayer-client-utils'),collision=require('../shared-collision'),{GameServer}=require('../server');
const movementOptions={mapId:'ruins',radius:15,speed:180,collision};

test('snapshot keeps same-sequence prediction slices that happened after snapshot time',()=>{const state=utils.createPredictionState();let position={x:1500,y:1100};position=utils.predictInput(state,position,{seq:7,dx:-1,dy:0,predictedAt:970},.02,movementOptions);position=utils.predictInput(state,position,{seq:7,dx:1,dy:0,predictedAt:1010},.02,movementOptions);const result=utils.reconcileSnapshot(state,position,{tick:1,serverTime:1000,x:1496.4,y:1100,lastProcessedInputSeq:7},movementOptions);assert.equal(state.pending.length,1);assert.equal(state.pending[0].dx,1);assert.ok(result.target.x>1496.4)});

function cadence({fps,rtt,jitter,changeAt=.5,duration=1.5,startInput={dx:-1,dy:0},endInput={dx:1,dy:0},inputAt}){const frameMs=1000/fps,inputMs=40,snapshotMs=50,serverStep=1000/30,state=utils.createPredictionState();let client={x:1500,y:1100},server={x:1500,y:1100},local={...startInput},serverInput={dx:0,dy:0},seq=0,ack=0,tick=0,nextInput=0,nextSnapshot=0,nextServer=0,lastClient={...client},maxPending=0;const inputs=[],snapshots=[],afterChange=[];for(let now=0;now<=duration*1000+frameMs;now+=frameMs){local=inputAt?inputAt(now/1000):now>=changeAt*1000?{...endInput}:{...startInput};while(now>=nextInput){inputs.push({at:nextInput+rtt/2,seq:++seq,input:{...local}});nextInput+=inputMs}for(const packet of inputs.filter(packet=>!packet.done&&packet.at<=now)){packet.done=true;serverInput=packet.input;ack=packet.seq}while(now>=nextServer){const length=Math.hypot(serverInput.dx,serverInput.dy)||1,moved=collision.moveCircleWithCollision('ruins',server.x,server.y,15,serverInput.dx/length*180/30,serverInput.dy/length*180/30);server={x:moved.x,y:moved.y};tick++;nextServer+=serverStep}while(now>=nextSnapshot){const skew=jitter&&((tick%3)-1)*jitter,snapshot={tick,serverTime:nextSnapshot,x:server.x,y:server.y,lastProcessedInputSeq:ack};snapshots.push({at:Math.max(now,nextSnapshot+rtt/2+skew),snapshot});nextSnapshot+=snapshotMs}for(const delivery of snapshots.filter(item=>!item.done&&item.at<=now)){delivery.done=true;client=utils.reconcileSnapshot(state,client,delivery.snapshot,{...movementOptions,movement:local}).position}client=utils.predictInput(state,client,{seq,dx:local.dx,dy:local.dy,predictedAt:now},frameMs/1000,movementOptions);if(now>=changeAt*1000){const length=Math.hypot(endInput.dx,endInput.dy)||1;afterChange.push((client.x-lastClient.x)*endInput.dx/length+(client.y-lastClient.y)*endInput.dy/length)}lastClient={...client};maxPending=Math.max(maxPending,state.pending.length);assert.ok(Number.isFinite(client.x)&&Number.isFinite(client.y));assert.equal(collision.blocked('ruins',client.x,client.y,15),false)}return{client,server,afterChange,maxPending,seq}}

test('real 25 Hz input and 20 Hz snapshots keep A/D and W/S corrections bounded without a directional clamp',()=>{const transitions=[[{dx:-1,dy:0},{dx:1,dy:0},'A-D'],[{dx:1,dy:0},{dx:-1,dy:0},'D-A'],[{dx:0,dy:-1},{dx:0,dy:1},'W-S'],[{dx:0,dy:1},{dx:0,dy:-1},'S-W']];for(const fps of[60,144])for(const rtt of[20,50,100,150])for(const jitter of[0,20,40])for(const changeAt of[.481,.499,.501,.519])for(const[startInput,endInput,label]of transitions){const result=cadence({fps,rtt,jitter,changeAt,duration:1.1,startInput,endInput});assert.ok(Math.min(...result.afterChange)>-5,`${label} correction jumped`);assert.ok(result.afterChange.reduce((sum,value)=>sum+value,0)>25,`${label} made no forward progress`);assert.ok(result.maxPending<80);assert.ok(result.seq>=27&&result.seq<=29)}});

test('ten-second held movement cadence stays bounded through scheduled direction changes',()=>{const result=cadence({fps:60,rtt:80,jitter:20,duration:10,inputAt:time=>time<2?{dx:1,dy:0}:time<4?{dx:-1,dy:0}:{dx:1,dy:0}});assert.ok(Math.hypot(result.client.x-result.server.x,result.client.y-result.server.y)<50);assert.ok(result.maxPending<40);assert.ok(result.seq>=250&&result.seq<=252)});

test('direction resolver remains held across an unpaused pause consensus update',()=>{const keys={},input=mechanics.createMovementResolver(keys);input.keyDown('d');const pauseState={paused:false,requested:1,required:2};if(pauseState.paused)input.clear();assert.equal(input.resolve().right,true);assert.deepEqual({left:input.resolve().left,right:input.resolve().right},{left:false,right:true})});

function serverMatch(character){let now=1000;const core=new GameServer(()=>now,()=>.99),messages=[],client=core.addClient(message=>messages.push(message));core.handle(client,{type:'hello',installationId:`movement-${character}`,unlocked:['warrior','druid'],maps:['ruins']});now+=1000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);lobby.players[0].character=character;core.start(lobby);return{core,client,lobby,p:lobby.game.players[client.playerId],advance(ms){now+=ms}}}

test('Q E and R do not clear authoritative held movement for any character',()=>{for(const character of['scout','warrior','druid'])for(const ability of['q','e','r']){const h=serverMatch(character);h.advance(100);h.core.handle(h.client,{type:'playerInput',inputSeq:1,left:false,right:true,up:false,down:false,aim:0});const before=h.p.x;h.core.tickPlayer(h.lobby,h.p,.5);h.advance(100);h.core.handle(h.client,{type:'abilityPress',ability,aim:0,seq:1});assert.equal(h.p.input.right,true,`${character} ${ability}`);const afterCast=h.p.x;h.core.tickPlayer(h.lobby,h.p,.5);assert.ok(h.p.x>afterCast||character==='warrior'&&ability==='e'&&h.p.x>before,`${character} ${ability}`)}});

test('per-ability rate limit accepts Q then E in 30 ms but same-Q spam casts once',()=>{const h=serverMatch('scout');h.advance(100);h.core.handle(h.client,{type:'abilityPress',ability:'q',aim:0,seq:1});h.advance(30);h.core.handle(h.client,{type:'abilityPress',ability:'e',aim:0,seq:2});assert.equal(h.p.abilitySeq,2);for(let seq=3;seq<8;seq++){h.advance(81);h.core.handle(h.client,{type:'abilityPress',ability:'q',aim:0,seq})}assert.equal(h.p.abilitySeq,2)});
