'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../multiplayer-startup');

function lifecycle(){const startup=create(),runtime={active:false,overlayHidden:false,loopStarts:0,assetLoads:0,events:[],state:{hp:100,maxHp:100,level:1,xp:0,time:0},sent:[]},apply=packet=>{runtime.state={...packet};runtime.active=true};return{startup,runtime,apply,control(type){runtime.events.push(type)},prepare(matchId){runtime.events.push('gamePreparing');runtime.assetLoads++;startup.preparing();runtime.events.push('assetsReady');return{type:'assetsReady',matchId}},start(matchId,{prepared}){runtime.events.push('gameStarted');startup.started(matchId);if(!prepared)runtime.assetLoads++;runtime.overlayHidden=true;if(!runtime.loopStarts)runtime.loopStarts++},ready(matchId){startup.runtimeReady(matchId,apply)},snapshot(state){runtime.events.push('gameState');startup.authoritative(state.matchId,state,apply)},input(){if(runtime.active)runtime.sent.push({type:'playerInput',right:true})}}}

test('normal client lifecycle gates assets once then applies first authoritative state and input',()=>{const h=lifecycle(),matchId='normal-match';h.control('helloAck');h.control('lobbyState');assert.deepEqual(h.prepare(matchId),{type:'assetsReady',matchId});h.start(matchId,{prepared:true});h.ready(matchId);h.control('pauseState');h.snapshot({matchId,hp:73,maxHp:130,level:4,xp:17,time:42,x:811,y:377});h.input();assert.deepEqual(h.runtime.state,{matchId,hp:73,maxHp:130,level:4,xp:17,time:42,x:811,y:377});assert.deepEqual(h.runtime.events,['helloAck','lobbyState','gamePreparing','assetsReady','gameStarted','pauseState','gameState']);assert.equal(h.runtime.assetLoads,1);assert.equal(h.runtime.loopStarts,1);assert.equal(h.runtime.overlayHidden,true);assert.equal(h.runtime.active,true);assert.deepEqual(h.runtime.sent,[{type:'playerInput',right:true}])});

test('full-page reconnect gates assets once and replays the latest buffered authoritative state',()=>{const h=lifecycle(),matchId='resume-match';h.start(matchId,{prepared:false});h.snapshot({matchId,hp:80,maxHp:130,level:4,xp:16,time:41,x:700,y:300});h.snapshot({matchId,hp:73,maxHp:130,level:4,xp:17,time:42,x:811,y:377});assert.equal(h.runtime.state.hp,100);h.ready(matchId);h.input();assert.equal(h.runtime.assetLoads,1);assert.equal(h.runtime.loopStarts,1);assert.equal(h.runtime.overlayHidden,true);assert.deepEqual(h.runtime.state,{matchId,hp:73,maxHp:130,level:4,xp:17,time:42,x:811,y:377});assert.deepEqual(h.runtime.sent,[{type:'playerInput',right:true}])});
