'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {GameServer}=require('../server');
function setup(){let now=1000;const core=new GameServer(()=>now),out=new Map();function connect(id){const messages=[];out.set(id,messages);const client=core.addClient(message=>messages.push(message));core.handle(client,{type:'hello',installationId:id,unlocked:['druid','warrior'],maps:['ruins']});now+=1000;return client}const host=connect('host');core.handle(host,{type:'createLobby'});const guest=connect('guest');core.handle(guest,{type:'joinLobby',code:host.lobby});const lobby=core.lobbies.get(host.lobby);lobby.players.find(player=>player.id===guest.playerId).ready=true;now+=1000;core.handle(host,{type:'startGame'});return{core,out,host,guest,lobby,advance(ms){now+=ms}}}
function ready(h,client,id=h.lobby.preparing.matchId){h.advance(400);h.core.handle(client,{type:'assetsReady',matchId:id})}
test('slow client holds simulation until host and guest are asset-ready',()=>{const h=setup(),id=h.lobby.preparing.matchId;assert.equal(h.lobby.game,null);h.core.tick(h.lobby,10);assert.equal(h.lobby.game,null);ready(h,h.host);assert.equal(h.lobby.game,null);assert.equal(h.out.get('host').some(message=>message.type==='gameStarted'),false);ready(h,h.guest);assert.equal(h.lobby.game.time,0);assert.equal(h.lobby.game.matchId,id);assert.equal(h.out.get('host').filter(message=>message.type==='gameStarted').length,1)});
test('host is required and duplicate or stale readiness is harmless',()=>{const h=setup(),id=h.lobby.preparing.matchId;ready(h,h.guest,'stale-match');assert.equal(h.lobby.preparing.readyPlayerIds.size,0);ready(h,h.guest,id);ready(h,h.guest,id);assert.equal(h.lobby.preparing.readyPlayerIds.size,1);assert.equal(h.lobby.game,null);ready(h,h.host,id);assert.ok(h.lobby.game)});
test('disconnect removes an unready player from the preparing requirement',()=>{const h=setup();ready(h,h.host);assert.equal(h.lobby.game,null);h.core.disconnect(h.guest);assert.ok(h.lobby.game);assert.equal(h.lobby.game.time,0)});
test('reconnected player must acknowledge the same preparation on its new connection',()=>{const h=setup(),id=h.lobby.preparing.matchId,session=h.core.sessionsByPlayerId.get(h.guest.playerId);ready(h,h.guest,id);assert.equal(h.lobby.preparing.readyPlayerIds.has(h.guest.playerId),true);h.core.disconnect(h.guest);assert.equal(h.lobby.preparing.readyPlayerIds.has(h.guest.playerId),false);const messages=[],replacement=h.core.addClient(message=>messages.push(message));h.advance(400);h.core.handle(replacement,{type:'hello',installationId:'guest-reconnect',resume:{playerId:h.guest.playerId,reconnectToken:session.reconnectToken},unlocked:['druid','warrior'],maps:['ruins']});assert.ok(messages.some(message=>message.type==='gamePreparing'&&message.matchId===id));ready(h,replacement,id);assert.equal(h.lobby.game,null);ready(h,h.host,id);assert.ok(h.lobby.game);assert.equal(h.lobby.game.matchId,id)});
test('client re-acks ready assets on a new connection generation without restarting its gate',()=>{const client=fs.readFileSync(require.resolve('../multiplayer.js'),'utf8'),runtime=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8');assert.match(client,/assetsReadySentGeneration===generation/);assert.match(client,/preparingId===matchId&&!manual\)\{if\(localAssetsReady\)acknowledgeAssetsReady\(matchId\);return\}/);assert.match(client,/acknowledgeAssetsReady\(matchId\)/);assert.match(client,/data\.type==='gameStarted'\)launchGame/);assert.match(client,/OCZEKIWANIE NA POZOSTAŁYCH GRACZY/);assert.match(runtime,/message\.type==='gamePreparing'\)\{multiplayerMode=true;resetMatchRuntime\(\);currentMatchId=null;return\}/)});
test('player omitted when preparation starts without them cannot resume the active match',()=>{const h=setup(),guestId=h.guest.playerId,session=h.core.sessionsByPlayerId.get(guestId);ready(h,h.host);h.core.disconnect(h.guest);assert.ok(h.lobby.game);assert.equal(h.lobby.game.players[guestId],undefined);const messages=[],replacement=h.core.addClient(message=>messages.push(message));h.advance(400);h.core.handle(replacement,{type:'hello',installationId:'guest-too-late',resume:{playerId:guestId,reconnectToken:session.reconnectToken},unlocked:['druid','warrior'],maps:['ruins']});assert.equal(replacement.state,'closed');assert.ok(messages.some(message=>message.type==='resumeRejected'&&message.reason==='matchAlreadyStarted'));assert.equal(messages.some(message=>message.type==='helloAck'||message.type==='gameStarted'||message.type==='pauseState'),false);assert.equal(h.lobby.players.some(member=>member.id===guestId&&member.connected),false);assert.equal(h.lobby.game.players[guestId],undefined)});
test('an existing authoritative game player still resumes the active match normally',()=>{const h=setup(),guestId=h.guest.playerId,session=h.core.sessionsByPlayerId.get(guestId);ready(h,h.host);ready(h,h.guest);const matchId=h.lobby.game.matchId;assert.ok(h.lobby.game.players[guestId]);h.core.disconnect(h.guest);const messages=[],replacement=h.core.addClient(message=>messages.push(message));h.advance(400);h.core.handle(replacement,{type:'hello',installationId:'guest-active-resume',resume:{playerId:guestId,reconnectToken:session.reconnectToken},unlocked:['druid','warrior'],maps:['ruins']});assert.equal(replacement.state,'authenticated');assert.ok(messages.some(message=>message.type==='helloAck'));assert.ok(messages.some(message=>message.type==='gameStarted'&&message.matchId===matchId));assert.ok(messages.some(message=>message.type==='pauseState'&&message.matchId===matchId));assert.ok(h.lobby.game.players[guestId]);assert.equal(h.lobby.game.matchId,matchId)});
test('client clears preparing storage and reports a late-match resume rejection',()=>{const client=fs.readFileSync(require.resolve('../multiplayer.js'),'utf8'),runtime=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8');assert.match(client,/data\.type==='resumeRejected'[\s\S]*preparingId=null;localAssetsReady=false;assetsReadySentGeneration=0/);assert.match(client,/sessionStorage\.removeItem\('swarmfall-lobby-characters'\)/);assert.match(client,/byId\('assetLoading'\)\.classList\.add\('hidden'\)/);assert.match(runtime,/reason==='matchAlreadyStarted'/);assert.match(runtime,/MECZ ROZPOCZĄŁ SIĘ BEZ CIEBIE/)});
