'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {GameServer}=require('../server');
function setup(){let now=1000;const core=new GameServer(()=>now),out=new Map();function connect(id){const messages=[];out.set(id,messages);const client=core.addClient(message=>messages.push(message));core.handle(client,{type:'hello',installationId:id,unlocked:['druid','warrior'],maps:['ruins']});now+=1000;return client}const host=connect('host');core.handle(host,{type:'createLobby'});const guest=connect('guest');core.handle(guest,{type:'joinLobby',code:host.lobby});const lobby=core.lobbies.get(host.lobby);lobby.players.find(player=>player.id===guest.playerId).ready=true;now+=1000;core.handle(host,{type:'startGame'});return{core,out,host,guest,lobby,advance(ms){now+=ms}}}
function ready(h,client,id=h.lobby.preparing.matchId){h.advance(400);h.core.handle(client,{type:'assetsReady',matchId:id})}
test('slow client holds simulation until host and guest are asset-ready',()=>{const h=setup(),id=h.lobby.preparing.matchId;assert.equal(h.lobby.game,null);h.core.tick(h.lobby,10);assert.equal(h.lobby.game,null);ready(h,h.host);assert.equal(h.lobby.game,null);assert.equal(h.out.get('host').some(message=>message.type==='gameStarted'),false);ready(h,h.guest);assert.equal(h.lobby.game.time,0);assert.equal(h.lobby.game.matchId,id);assert.equal(h.out.get('host').filter(message=>message.type==='gameStarted').length,1)});
test('host is required and duplicate or stale readiness is harmless',()=>{const h=setup(),id=h.lobby.preparing.matchId;ready(h,h.guest,'stale-match');assert.equal(h.lobby.preparing.readyPlayerIds.size,0);ready(h,h.guest,id);ready(h,h.guest,id);assert.equal(h.lobby.preparing.readyPlayerIds.size,1);assert.equal(h.lobby.game,null);ready(h,h.host,id);assert.ok(h.lobby.game)});
test('disconnect removes an unready player from the preparing requirement',()=>{const h=setup();ready(h,h.host);assert.equal(h.lobby.game,null);h.core.disconnect(h.guest);assert.ok(h.lobby.game);assert.equal(h.lobby.game.time,0)});
test('client prepares assets before gameStarted and keeps gameplay launch separate',()=>{const client=fs.readFileSync(require.resolve('../multiplayer.js'),'utf8'),runtime=fs.readFileSync(require.resolve('../multiplayer-game.js'),'utf8');assert.match(client,/data\.type==='gamePreparing'\)prepareGame/);assert.match(client,/send\('assetsReady',\{matchId\}\)/);assert.match(client,/data\.type==='gameStarted'\)launchGame/);assert.match(client,/OCZEKIWANIE NA POZOSTAŁYCH GRACZY/);assert.match(runtime,/message\.type==='gamePreparing'\)\{multiplayerMode=true;resetMatchRuntime\(\);currentMatchId=null;return\}/)});
