'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer}=require('../server');
function world(){let now=1000;const core=new GameServer(()=>now,()=>.5),messages=new Map();function connect(name,resume){const out=[],connection=core.addClient(message=>out.push(message));messages.set(name,out);core.handle(connection,{type:'hello',installationId:name,resume,unlocked:['warrior','druid'],maps:['ruins']});return{connection,out,ack:out.find(message=>message.type==='helloAck')}}function advance(ms){now+=ms}return{core,connect,advance,messages,get now(){return now}}}
function twoPlayers(){const h=world(),a=h.connect('install-a');h.advance(2000);h.core.handle(a.connection,{type:'createLobby'});const b=h.connect('install-b');h.advance(1000);h.core.handle(b.connection,{type:'joinLobby',code:a.connection.lobby});h.advance(300);h.core.handle(b.connection,{type:'playerReady',ready:true});h.advance(600);h.core.handle(a.connection,{type:'startGame'});return{...h,a,b,lobby:h.core.lobbies.get(a.connection.lobby)}}
test('server assigns separate player, connection and reconnect identities',()=>{const h=world(),a=h.connect('install-a');assert.ok(a.ack.playerId);assert.ok(a.ack.connectionId);assert.ok(a.ack.reconnectToken);assert.notEqual(a.ack.playerId,a.ack.connectionId);assert.notEqual(a.ack.playerId,a.ack.reconnectToken);assert.equal(a.connection.state,'authenticated')});
test('atomic reconnect supersedes old socket and late old close is ignored',()=>{const h=twoPlayers(),player=h.lobby.game.players[h.b.ack.playerId];player.lastProcessedInputSeq=40;player.lastAbilityInputSeq=7;let superseded=false;h.b.connection.supersede=()=>superseded=true;const replacement=h.connect('install-b-reload',{playerId:h.b.ack.playerId,reconnectToken:h.b.ack.reconnectToken});assert.equal(superseded,true);assert.equal(h.b.connection.state,'superseded');assert.equal(replacement.ack.connectionGeneration,h.b.ack.connectionGeneration+1);assert.equal(replacement.ack.lastProcessedInputSeq,40);assert.equal(replacement.ack.lastAbilityInputSeq,7);player.input={right:true,aim:0,received:true};assert.equal(h.core.disconnect(h.b.connection),false);assert.equal(h.lobby.players.find(p=>p.id===player.id).connected,true);assert.equal(player.input.right,true);h.advance(100);h.core.handle(h.b.connection,{type:'playerInput',left:true,aim:0,inputSeq:41});assert.notEqual(player.input.left,true);h.core.handle(replacement.connection,{type:'playerInput',right:true,aim:0,inputSeq:41});assert.equal(player.input.right,true)});
test('two players retain independent ownership through 120 seconds and a reconnect',()=>{const h=twoPlayers(),aId=h.a.ack.playerId,bId=h.b.ack.playerId,aPlayer=h.lobby.game.players[aId],bPlayer=h.lobby.game.players[bId];let bConnection=h.b.connection,bAck=h.b.ack;for(let second=1;second<=120;second++){h.advance(1000);h.core.handle(h.a.connection,{type:'playerInput',right:true,aim:0,inputSeq:second});h.core.handle(bConnection,{type:'playerInput',down:true,aim:Math.PI/2,inputSeq:second});if(second%10===0){h.core.handle(h.a.connection,{type:'abilityPress',ability:'q',aim:0,seq:second/10});h.core.handle(bConnection,{type:'abilityPress',ability:'q',aim:Math.PI/2,seq:second/10})}h.core.tickPlayer(h.lobby,aPlayer,1/30);h.core.tickPlayer(h.lobby,bPlayer,1/30);assert.equal(aPlayer.input.right,true);assert.equal(aPlayer.input.down,false);assert.equal(bPlayer.input.down,true);assert.equal(bPlayer.input.right,false);if(second===40){const replacement=h.connect('install-b-reload',{playerId:bId,reconnectToken:bAck.reconnectToken});h.core.disconnect(bConnection);bConnection=replacement.connection;bAck=replacement.ack}}assert.equal(h.lobby.game.players[aId],aPlayer);assert.equal(h.lobby.game.players[bId],bPlayer);assert.notEqual(aId,bId)});
test('pending or superseded connections cannot mutate any player',()=>{const h=twoPlayers(),orphan=h.core.addClient(()=>{}),a=h.lobby.game.players[h.a.ack.playerId],b=h.lobby.game.players[h.b.ack.playerId],before=[a.x,b.x,a.abilitySeq,b.abilitySeq];h.core.handle(orphan,{type:'playerInput',right:true,aim:0,inputSeq:1});h.core.handle(orphan,{type:'abilityPress',ability:'q',aim:0,seq:1});assert.deepEqual([a.x,b.x,a.abilitySeq,b.abilitySeq],before)});
test('client classification never includes authoritative local player as remote',()=>{const {classifyPlayers}=require('../multiplayer-visual-state'),players=[{id:'a'},{id:'b'}];const first=classifyPlayers(players,'a');assert.equal(first.local.id,'a');assert.deepEqual(first.remote.map(player=>player.id),['b']);assert.equal(first.valid,true);const missing=classifyPlayers(players,'gone');assert.equal(missing.local,null);assert.equal(missing.valid,false)});
test('reload resumes movement and ability sequences above server acknowledgements',()=>{const {resumeSequences}=require('../multiplayer-visual-state'),next=resumeSequences(0,0,{lastProcessedInputSeq:1000,lastAbilityInputSeq:50});assert.deepEqual(next,{inputSeq:1000,abilityInputSeq:50});assert.equal(++next.inputSeq,1001);assert.equal(++next.abilityInputSeq,51)});
test('invalid reconnect token is rejected and cannot become gameplay-active',()=>{const h=twoPlayers(),out=[],attacker=h.core.addClient(message=>out.push(message));h.core.handle(attacker,{type:'hello',installationId:'attacker',resume:{playerId:h.a.ack.playerId,reconnectToken:'not-the-token'},unlocked:[],maps:['ruins']});assert.equal(attacker.state,'closed');assert.ok(out.some(message=>message.type==='resumeRejected'));const before=h.lobby.game.players[h.a.ack.playerId].input;h.core.handle(attacker,{type:'playerInput',right:true,aim:0,inputSeq:999});assert.equal(h.lobby.game.players[h.a.ack.playerId].input,before)});
