'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,applyUpgrade,DATA}=require('../server');
function setup(character='scout',rng=()=>.5){let now=1000;const core=new GameServer(()=>now,rng),messages=[],client=core.addClient(m=>messages.push(m));core.handle(client,{type:'hello',installationId:'host',unlocked:['warrior','druid'],maps:['ruins','toxic']});now+=2000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);lobby.players[0].character=character;core.start(lobby);return{core,lobby,g:lobby.game,p:lobby.game.players[client.playerId],client,messages,advance:n=>now+=n}}
function foe(h,type='melee',distance=60){const d=DATA.enemies[type],e={id:`${type}-1`,type,ai:d.ai,x:h.p.x+distance,y:h.p.y,hp:d.hp,maxHp:d.hp,r:d.r,speed:d.speed,damage:d.damage,xp:d.xp};h.g.enemies=[e];return e}
test('Scout attack and Q/E/R have authoritative results',()=>{const h=setup(),e=foe(h,'brute',80);h.core.firePlayer(h.lobby,h.p,0,false);assert.equal(h.g.bullets.length,1);h.core.castAbility(h.lobby,h.p,'q',0);assert.equal(h.g.bullets.length,6);const x=e.x,hp=e.hp;h.core.castAbility(h.lobby,h.p,'e',0);assert.ok(e.hp<hp&&e.x>x);h.p.stats.cooldowns.rReadyAt=0;h.core.castAbility(h.lobby,h.p,'r',0);assert.ok(e.hp<=0);assert.ok(h.p.stats.cooldowns.rReadyAt>0)});
test('Warrior attack and Q/E/R are melee, healing, teleport and buff',()=>{const h=setup('warrior'),e=foe(h,'brute',70);h.p.hp=50;h.p.input={aim:0,received:true};h.p.shot=0;h.core.tickPlayer(h.lobby,h.p,.01);assert.ok(e.hp<e.maxHp&&h.p.hp>50);const hp=e.hp;h.core.castAbility(h.lobby,h.p,'q',0);assert.ok(e.hp<hp);const x=h.p.x;h.core.castAbility(h.lobby,h.p,'e',0);assert.ok(h.p.x>x);h.core.castAbility(h.lobby,h.p,'r',0);assert.equal(h.p.powerBuff,9)});
test('Druid uses piercing boomerang and team Q/E/R support',()=>{const h=setup('druid'),stats={...h.p.stats,cooldowns:{q:0,e:0,r:0}},ally={...h.p,id:'ally',x:h.p.x+20,hp:20,stats,items:{},augments:[],input:{},alive:true};h.g.players.ally=ally;h.p.hp=30;h.core.firePlayer(h.lobby,h.p,0,false);assert.equal(h.g.bullets[0].kind,'boomerang');assert.ok(h.g.bullets[0].pierce>=3);h.core.castAbility(h.lobby,h.p,'q',0);assert.ok(ally.hp>20);h.core.castAbility(h.lobby,h.p,'e',0);assert.equal(ally.speedBuff,6);h.core.castAbility(h.lobby,h.p,'r',0);assert.equal(ally.hp,ally.stats.maxHp);assert.equal(h.p.stats.cooldowns.qReadyAt,3000)});
test('executor and giant hunter alter actual target damage',()=>{const normal=setup(),low=foe(normal,'brute');low.hp=15;normal.p.augments.push('executor');assert.ok(normal.core.damageEnemy(normal.lobby,low,10,normal.p,'test')>10);const giant=setup(),boss=foe(giant,'boss');giant.p.augments.push('giant_hunter');assert.ok(giant.core.damageEnemy(giant.lobby,boss,10,giant.p,'test')>10)});
test('glass cannon, parasite and greed curse affect authoritative outcomes',()=>{const h=setup();const hp=h.p.stats.maxHp,damage=h.p.stats.damage;applyUpgrade(h.p,'augment-glass_cannon');assert.ok(h.p.stats.maxHp<hp&&h.p.stats.damage>damage);h.p.augments.push('parasite');h.p.hp=20;h.core.heal(h.p,20);assert.equal(h.p.hp,30);h.p.augments.push('greed_curse');h.core.spawnEnemy(h.lobby,'melee');assert.equal(h.g.enemies[0].hp,DATA.enemies.melee.hp*1.2)});
test('perfectionist, recycling, second chamber and gambler are consumed by simulation',()=>{const h=setup();h.p.augments.push('perfectionist','second_chamber','gambler');h.p.perfectionTime=40;h.core.tickPlayer(h.lobby,h.p,.01);assert.equal(h.p.perfectionStacks,2);h.p.shot=0;h.p.secondChamber=0;h.p.input={aim:0,received:true};h.core.tickPlayer(h.lobby,h.p,.01);assert.ok(h.g.bullets.length>=2);assert.equal(h.core.offer(h.p).length,2);h.p.augments.push('recycling');h.g.xp=h.g.nextXp+10;h.g.spawn=99;h.core.tick(h.lobby,.01);assert.equal(h.g.xp,6)});
test('every item mutates authoritative combat or utility state',()=>{for(const id of Object.keys(DATA.items)){const h=setup(),before=JSON.stringify({stats:h.p.stats,cooldownScale:h.p.cooldownScale}),ok=applyUpgrade(h.p,`item-${id}`);assert.equal(ok,true,id);assert.equal(h.p.items[id],1,id);assert.notEqual(JSON.stringify({stats:h.p.stats,cooldownScale:h.p.cooldownScale}),before,`${id} must have a server-side effect`)}});
test('powder, totem and vault have observable simulation effects',()=>{const h=setup('scout',()=>0);applyUpgrade(h.p,'item-powder');applyUpgrade(h.p,'item-totem');applyUpgrade(h.p,'item-vault');h.p.stillTime=2;const a=foe(h,'melee',40),d=DATA.enemies.melee,b={id:'b',type:'melee',ai:'melee',x:a.x+20,y:a.y,hp:d.hp,maxHp:d.hp,r:d.r,speed:0,damage:d.damage,xp:d.xp};h.g.enemies.push(b);a.hp=1;h.core.damageEnemy(h.lobby,a,5,h.p,'test');assert.ok(b.hp<b.maxHp);h.core.tickPickups(h.lobby,60);assert.ok(h.p.coins>=2)});
test('server-side reroll is one-use and remains server generated',()=>{const h=setup('scout',()=>.2);h.g.paused=true;h.g.levelRound=1;h.lobby.players[0].choiceRound=0;h.p.offer=['item-speed','item-vital','item-power'];h.advance(500);h.core.handle(h.client,{type:'rerollUpgrade',index:0});const first=h.p.offer[0];assert.notEqual(first,'item-speed');h.advance(500);h.core.handle(h.client,{type:'rerollUpgrade',index:0});assert.equal(h.p.offer[0],first);assert.ok(h.messages.some(m=>m.type==='upgradeOffer'))});
test('second match starts in same lobby with clean state',()=>{const h=setup();h.g.ended=true;h.advance(1000);h.core.handle(h.client,{type:'returnToLobby'});assert.equal(h.lobby.game,null);h.advance(1000);h.core.start(h.lobby);assert.ok(h.lobby.game);assert.equal(h.lobby.game.level,1);assert.equal(h.lobby.game.enemies.length,0)});
test('multi-player enemies retarget a living nearest player',()=>{const h=setup(),e=foe(h,'melee',300),stats={...h.p.stats,cooldowns:{q:0,e:0,r:0}};h.g.players.ally={...h.p,id:'ally',x:e.x+20,y:e.y,hp:100,stats,input:{},alive:true};h.core.tickEnemy(h.lobby,e,.01);assert.equal(e.targetId,'ally');h.g.players.ally.alive=false;h.core.tickEnemy(h.lobby,e,.01);assert.equal(e.targetId,h.p.id)});
test('each player aim produces projectiles at its own authoritative angle',()=>{const h=setup(),stats={...h.p.stats,cooldowns:{q:0,e:0,r:0}},ally={...h.p,id:'ally',stats,input:{received:true,aim:Math.PI/2},items:{},augments:[],alive:true,shot:0};h.g.players.ally=ally;h.p.input={received:true,aim:0};h.p.shot=0;h.core.tickPlayer(h.lobby,h.p,.01);h.core.tickPlayer(h.lobby,ally,.01);const first=h.g.bullets.find(b=>b.ownerId===h.p.id),second=h.g.bullets.find(b=>b.ownerId==='ally');assert.ok(first.vx>0&&Math.abs(first.vy)<1);assert.ok(second.vy>0&&Math.abs(second.vx)<1)});
test('level pause lasts until every connected player chooses',()=>{const h=setup(),messages=[],client=h.core.addClient(m=>messages.push(m));h.advance(1000);h.core.handle(client,{type:'hello',installationId:'ally',unlocked:[],maps:['ruins']});h.lobby.players.push({id:client.playerId,name:'Ally',host:false,ready:true,character:'scout',connected:true,choiceRound:0});client.lobby=h.lobby.code;const stats={...h.p.stats,cooldowns:{q:0,e:0,r:0}};h.g.players[client.playerId]={...h.p,id:client.playerId,stats,items:{},augments:[],offer:['item-speed'],input:{},alive:true};h.g.paused=true;h.g.levelRound=1;h.p.offer=['item-power'];h.lobby.players[0].choiceRound=0;h.advance(500);h.core.handle(h.client,{type:'upgradeChoice',choice:'item-power'});assert.equal(h.g.paused,true);h.advance(500);h.core.handle(client,{type:'upgradeChoice',choice:'item-speed'});assert.equal(h.g.paused,false);assert.ok(messages.some(m=>m.type==='levelResume'))});
test('Scout and Druid projectile kinds survive authoritative snapshots',()=>{const scout=setup('scout');scout.core.firePlayer(scout.lobby,scout.p,0,false);assert.equal(scout.g.bullets[0].kind,'scoutBullet');assert.equal(scout.g.bullets[0].r,4);assert.equal(scout.g.bullets[0].life,1.3);scout.core.castAbility(scout.lobby,scout.p,'q',0);assert.equal(scout.g.bullets[1].kind,'scoutQ');scout.core.tick(scout.lobby,1 / 30);scout.core.tick(scout.lobby,1 / 30);const snapshot=scout.messages.findLast(message=>message.type==='gameState');assert.ok(snapshot.state.bullets.some(b=>b.kind==='scoutBullet'));assert.ok(snapshot.state.bullets.some(b=>b.kind==='scoutQ'));const druid=setup('druid');druid.core.firePlayer(druid.lobby,druid.p,0,false);assert.equal(druid.g.bullets[0].kind,'boomerang');assert.equal(druid.g.bullets[0].r,10);assert.equal(druid.g.bullets[0].life,2.1)});
test('multiplayer director follows single-player wave phases and paced encounters',()=>{const h=setup('scout',()=>0);h.core.tick(h.lobby,.04);assert.equal(h.g.directorPhase,0);assert.equal(h.g.waveTitle,'NAPŁYW');assert.equal(h.g.waveRemaining,6);assert.equal(h.g.enemies.length,0);h.g.waveBreak=0;h.g.spawn=0;h.core.tick(h.lobby,.04);assert.equal(h.g.enemies[0].type,'melee');assert.equal(h.g.waveRemaining,5);h.g.time=120;h.core.tick(h.lobby,.04);assert.equal(h.g.directorPhase,1);assert.equal(h.g.waveTitle,'OSTRZAŁ');assert.equal(h.g.waveRemaining,7)});
test('enemy snapshots and renderer use one maxHp field with full spawn health',()=>{const h=setup();h.core.spawnEnemy(h.lobby,'brute');const enemy=h.g.enemies[0];assert.equal(enemy.hp,enemy.maxHp);const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'..','game.js'),'utf8');assert.doesNotMatch(source,/\be\.(?:max)\b/);assert.match(source,/e\.hp\/e\.maxHp/)});
