'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,blocked,DATA}=require('../server'),collision=require('../shared-collision');
const {createPredictionState,predictInput,reconcileSnapshot}=require('../multiplayer-client-utils');
function nav(start,target,type='melee'){const core=new GameServer(()=>1000,()=>.5),p={id:'target',...target,alive:true,hp:100,maxHp:100,stats:{thorns:0},input:{}},lobby={map:'ruins',players:[{id:p.id,connected:true}],game:{players:{[p.id]:p},enemyBullets:[],hazards:[],explosions:[],explosionSeq:0}},d=DATA.enemies[type],enemy={id:`${type}-nav`,...start,type,ai:d.ai,r:d.r,speed:d.speed,damage:0,hp:100,maxHp:100,attack:0,special:2};return{core,p,lobby,enemy}}
function simulate(h,ticks=600){const start=Math.hypot(h.enemy.x-h.p.x,h.enemy.y-h.p.y);let moved=0;for(let i=0;i<ticks;i++){const x=h.enemy.x,y=h.enemy.y;h.core.tickEnemy(h.lobby,h.enemy,1/30);moved+=Math.hypot(h.enemy.x-x,h.enemy.y-y);assert.equal(blocked(h.lobby.map,h.enemy.x,h.enemy.y,h.enemy.r),false)}return{start,end:Math.hypot(h.enemy.x-h.p.x,h.enemy.y-h.p.y),moved}}

test('flow fields route real server enemies around L/U corners, rock and water',()=>{for(const scenario of[{name:'L wall',start:{x:790,y:330},target:{x:1300,y:700}},{name:'U/local minimum',start:{x:1000,y:700},target:{x:1300,y:300}},{name:'rock',start:{x:1350,y:470},target:{x:1710,y:470}},{name:'water',start:{x:100,y:400},target:{x:800,y:300}}]){const h=nav(scenario.start,scenario.target),result=simulate(h);assert.ok(result.end<result.start*.35,scenario.name);assert.ok(result.moved>150,scenario.name);assert.ok((h.enemy.stuckTime||0)<.9,scenario.name)}});
test('shooter recovers LOS and fires while charger pathfinds then cannot tunnel',()=>{const shooter=nav({x:1100,y:500},{x:1300,y:500},'shooter'),result=simulate(shooter);assert.ok(result.moved>100);assert.equal(shooter.core.hasClearPath(shooter.lobby,shooter.enemy,shooter.p,4),true);assert.ok(shooter.lobby.game.enemyBullets.length>0);const charger=nav({x:790,y:330},{x:1300,y:700},'charger');charger.enemy.special=999;simulate(charger,300);assert.ok(Math.hypot(charger.enemy.x-charger.p.x,charger.enemy.y-charger.p.y)<250);charger.enemy.x=1750;charger.enemy.y=900;charger.p.x=2100;charger.p.y=900;charger.enemy.charging=.55;charger.enemy.chargeX=1;charger.enemy.chargeY=0;charger.core.tickEnemy(charger.lobby,charger.enemy,.55);assert.ok(charger.enemy.x<1830-charger.enemy.r)});
test('twenty enemies reuse one cached flow field',()=>{const h=nav({x:790,y:330},{x:1300,y:700});h.lobby.game.players.target=h.p;const enemies=Array.from({length:20},(_,i)=>({...h.enemy,id:`enemy-${i}`,x:790-(i%5)*3,y:330+Math.floor(i/5)*3}));for(let tick=0;tick<120;tick++)for(const enemy of enemies)h.core.tickEnemy(h.lobby,enemy,1/30);assert.equal(h.core.flowFieldBuilds,1);assert.ok(enemies.every(enemy=>!blocked('ruins',enemy.x,enemy.y,enemy.r)))});

test('reconciliation replays unacked fixed slices, rejects stale ticks and hard-corrects dash',()=>{const state=createPredictionState();let position={x:1500,y:1100};for(let i=1;i<=6;i++)position=predictInput(state,position,{seq:i,dx:1,dy:0},1/30,{mapId:'ruins',radius:15,speed:210,collision});const before={...position},fresh=reconcileSnapshot(state,position,{tick:10,x:1514,y:1100,lastProcessedInputSeq:2},{mapId:'ruins',radius:15,collision});assert.equal(fresh.applied,true);assert.equal(state.pending.every(slice=>slice.seq>2),true);assert.ok(fresh.target.x>1514);const stale=reconcileSnapshot(state,fresh.position,{tick:9,x:100,y:100,lastProcessedInputSeq:6},{mapId:'ruins',radius:15,collision});assert.equal(stale.stale,true);assert.deepEqual(stale.position,fresh.position);const dash=reconcileSnapshot(state,fresh.position,{tick:11,x:1750,y:1100,lastProcessedInputSeq:6},{mapId:'ruins',radius:15,collision,confirmedDash:true});assert.equal(dash.hard,true);assert.equal(dash.position.x,dash.target.x);assert.ok(before.x>1500)});
test('prediction harness stays finite and bounded across FPS, latency, jitter and direction changes',()=>{for(const fps of[20,60,144])for(const rtt of[50,100,150])for(const jitter of[20,40]){const state=createPredictionState();let client={x:1500,y:1100},server={x:1500,y:1100},seq=0,tick=0;for(let frame=0;frame<fps*5;frame++){const time=frame/fps,phase=Math.floor(time/.2)%4,input=phase===0?{dx:1,dy:0}:phase===1?{dx:1,dy:1}:phase===2?{dx:0,dy:0}:{dx:-1,dy:0};seq++;client=predictInput(state,client,{seq,...input},1/fps,{mapId:'ruins',radius:15,speed:210,collision});const authoritative=collision.moveCircleWithCollision('ruins',server.x,server.y,15,input.dx*210/fps/(Math.hypot(input.dx,input.dy)||1),input.dy*210/fps/(Math.hypot(input.dx,input.dy)||1));server={x:authoritative.x,y:authoritative.y};const cadence=Math.max(1,Math.round(fps*((rtt+(frame%2?jitter:-jitter))/1000)));if(frame%cadence===0){tick++;const ack=Math.max(0,seq-Math.round(fps*rtt/1000));client=reconcileSnapshot(state,client,{tick,x:server.x,y:server.y,lastProcessedInputSeq:ack},{mapId:'ruins',radius:15,collision}).position}assert.ok(Number.isFinite(client.x)&&Number.isFinite(client.y));assert.equal(collision.blocked('ruins',client.x,client.y,15),false)}assert.ok(Math.hypot(client.x-server.x,client.y-server.y)<120)}});

test('exploder authoritative arming state damages once, cancels on death and snapshots progress',()=>{const h=nav({x:1510,y:1100},{x:1500,y:1100},'exploder'),e=h.enemy,g=h.lobby.game,hp=h.p.hp;h.core.tickEnemy(h.lobby,e,.01);assert.equal(e.state,'arming');assert.equal(h.p.hp,hp);h.core.tickEnemy(h.lobby,e,.275);assert.ok(e.armingProgress>=.49&&e.armingProgress<=.51);assert.equal(h.p.hp,hp);h.core.tickEnemy(h.lobby,e,.275);assert.equal(e.state,'exploded');assert.equal(h.p.hp,hp-e.damage);assert.equal(g.explosionSeq,1);h.core.tickEnemy(h.lobby,e,1);assert.equal(h.p.hp,hp-e.damage);assert.equal(g.explosionSeq,1);const cancelled=nav({x:1510,y:1100},{x:1500,y:1100},'exploder');cancelled.core.tickEnemy(cancelled.lobby,cancelled.enemy,.01);cancelled.enemy.hp=0;cancelled.core.tickEnemy(cancelled.lobby,cancelled.enemy,1);assert.equal(cancelled.p.hp,100);assert.equal(cancelled.lobby.game.explosionSeq,0);let now=1000,snapshot;const core=new GameServer(()=>now,()=>.5),client=core.addClient(message=>{if(message.type==='gameState')snapshot=message});core.handle(client,{type:'hello',installationId:'snapshot',unlocked:[],maps:['ruins']});now+=1000;core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);core.start(lobby);const d=DATA.enemies.exploder,armed={id:'armed',type:'exploder',ai:'exploder',x:1000,y:1000,hp:20,maxHp:20,r:d.r,speed:0,damage:d.damage,xp:d.xp,state:'arming',armingTime:.275,armingDuration:.55,armingProgress:.5,phase:0};lobby.game.enemies=[armed];lobby.game.snapshotClock=.05;lobby.game.spawn=99;core.tick(lobby,.001);const enemy=snapshot.state.enemies.find(item=>item.id==='armed');assert.equal(enemy.state,'arming');assert.ok(enemy.armingProgress>.5)});

test('fixed prediction covers five-second holds, diagonal motion and wall/corner sliding at every FPS',()=>{for(const fps of[20,60,144])for(const input of[{dx:1,dy:0},{dx:1,dy:1}]){const state=createPredictionState();let position={x:1400,y:1000};for(let frame=0;frame<fps*5;frame++)position=predictInput(state,position,{seq:frame+1,...input},1/fps,{mapId:'ruins',radius:15,speed:100,collision});assert.ok(Math.hypot(position.x-1400,position.y-1000)>250);assert.equal(collision.blocked('ruins',position.x,position.y,15),false)}const wallState=createPredictionState();let wall={x:800,y:430};for(let i=0;i<180;i++)wall=predictInput(wallState,wall,{seq:i+1,dx:1,dy:-1},1/60,{mapId:'ruins',radius:15,speed:120,collision});assert.equal(collision.blocked('ruins',wall.x,wall.y,15),false);assert.ok(Math.hypot(wall.x-800,wall.y-430)>20)});
test('after stop and collision correction reconciliation converges without illegal replay',()=>{const state=createPredictionState();let position={x:800,y:430};for(let i=0;i<30;i++)position=predictInput(state,position,{seq:i+1,dx:1,dy:-1},1/30,{mapId:'ruins',radius:15,speed:180,collision});const authoritative={x:position.x-20,y:position.y};for(let tick=1;tick<=30;tick++)position=reconcileSnapshot(state,position,{tick,x:authoritative.x,y:authoritative.y,lastProcessedInputSeq:999},{mapId:'ruins',radius:15,collision}).position;assert.ok(Math.hypot(position.x-authoritative.x,position.y-authoritative.y)<2);assert.equal(collision.blocked('ruins',position.x,position.y,15),false)});
