'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer}=require('../server');

function setup(count=2){let now=1000;const core=new GameServer(()=>now,()=>.5),clients=[],messages=[];for(let i=0;i<count;i++){const out=[];messages.push(out);const client=core.addClient(message=>out.push(message));core.handle(client,{type:'hello',installationId:`pause-${i}`,unlocked:[],maps:['ruins']});now+=2000;if(i===0)core.handle(client,{type:'createLobby'});else core.handle(client,{type:'joinLobby',code:clients[0].lobby});clients.push(client)}const lobby=core.lobbies.get(clients[0].lobby);lobby.players.forEach(member=>member.ready=true);now+=2000;core.handle(clients[0],{type:'startGame'});lobby.game.waveBreak=999;return{core,lobby,clients,messages,send(client,message){now+=400;core.handle(client,message)},advance(ms){now+=ms},now:()=>now}}
const lastPause=messages=>messages.filter(message=>message.type==='pauseState').at(-1);

test('two living players pause by consensus and either can globally resume',()=>{const h=setup(),[a,b]=h.clients,g=h.lobby.game;h.send(a,{type:'pauseRequest',requested:true});assert.equal(g.manualPaused,false);assert.deepEqual(lastPause(h.messages[0]),{type:'pauseState',matchId:g.matchId,paused:false,upgradePaused:false,pauseReason:null,requested:1,required:2,requesterIds:[a.playerId]});h.send(b,{type:'pauseRequest',requested:true});assert.equal(g.manualPaused,true);const time=g.time,x=g.players[a.playerId].x;g.players[a.playerId].stats.cooldowns.qReadyAt=10000;h.core.tick(h.lobby,.5);assert.equal(g.time,time);assert.equal(g.players[a.playerId].x,x);h.send(b,{type:'resumeGame'});assert.equal(g.manualPaused,false);assert.equal(g.pauseRequests.size,0);assert.equal(g.players[a.playerId].stats.cooldowns.qReadyAt,10400);assert.equal(lastPause(h.messages[0]).paused,false);assert.equal(lastPause(h.messages[1]).paused,false)});

test('pause request can be withdrawn before consensus',()=>{const h=setup(),a=h.clients[0],g=h.lobby.game;h.send(a,{type:'pauseRequest',requested:true});h.send(a,{type:'pauseRequest',requested:false});assert.equal(g.manualPaused,false);assert.equal(g.pauseRequests.size,0);assert.equal(lastPause(h.messages[0]).requested,0)});

test('three and four player matches require every living connected vote',()=>{for(const count of[3,4]){const h=setup(count),g=h.lobby.game;for(const client of h.clients.slice(0,-1))h.send(client,{type:'pauseRequest',requested:true});assert.equal(g.manualPaused,false);assert.equal(lastPause(h.messages[0]).requested,count-1);assert.equal(lastPause(h.messages[0]).required,count);h.send(h.clients.at(-1),{type:'pauseRequest',requested:true});assert.equal(g.manualPaused,true)}});

test('dead players do not vote and disconnect recalculates consensus',()=>{const h=setup(3),[a,b,c]=h.clients,g=h.lobby.game;h.core.damagePlayer(h.lobby,g.players[c.playerId],g.players[c.playerId].hp+1,null,'test');h.send(a,{type:'pauseRequest',requested:true});h.send(b,{type:'pauseRequest',requested:true});assert.equal(lastPause(h.messages[0]).required,2);assert.equal(g.manualPaused,true);h.send(a,{type:'resumeGame'});h.send(a,{type:'pauseRequest',requested:true});g.players[c.playerId].alive=true;h.send(b,{type:'pauseRequest',requested:true});assert.equal(g.manualPaused,false);h.core.disconnect(c);assert.equal(g.manualPaused,true)});

test('upgrade pause clears pending manual requests and resumes cleanly',()=>{const h=setup(),a=h.clients[0],g=h.lobby.game;h.send(a,{type:'pauseRequest',requested:true});g.xp=g.nextXp;h.core.tick(h.lobby,.04);assert.equal(g.upgradePaused,true);assert.equal(g.manualPaused,false);assert.equal(g.pauseRequests.size,0);assert.equal(g.paused,true)});
test('rapid true then false pause state is accepted authoritatively',()=>{const h=setup(),a=h.clients[0],g=h.lobby.game;h.core.handle(a,{type:'pauseRequest',requested:true});h.advance(100);h.core.handle(a,{type:'pauseRequest',requested:false});assert.equal(g.pauseRequests.has(a.playerId),false);assert.equal(g.manualPaused,false);assert.equal(lastPause(h.messages[0]).requested,0)});
test('entering pause clears held server input and resume does not move without new input',()=>{const h=setup(),[a,b]=h.clients,g=h.lobby.game,p=g.players[a.playerId];h.send(a,{type:'playerInput',right:true,aim:0,inputSeq:1});assert.equal(p.input.right,true);h.send(a,{type:'pauseRequest',requested:true});h.send(b,{type:'pauseRequest',requested:true});assert.deepEqual(p.input,{});const x=p.x;h.send(a,{type:'resumeGame'});h.core.tick(h.lobby,.2);assert.equal(p.x,x)});
test('upgrade pause freezes cooldown and publishes a fresh unpaused pauseState',()=>{const h=setup(),g=h.lobby.game,p=g.players[h.clients[0].playerId];p.stats.cooldowns.qReadyAt=h.now()+5000;const before=p.stats.cooldowns.qReadyAt;g.xp=g.nextXp;h.core.tick(h.lobby,.04);h.advance(10000);for(const client of h.clients){h.advance(300);h.core.handle(client,{type:'upgradeChoice',choice:g.players[client.playerId].offer[0]})}assert.equal(g.paused,false);assert.equal(p.stats.cooldowns.qReadyAt,before+10600);const latest=lastPause(h.messages[0]);assert.equal(latest.paused,false);assert.equal(latest.upgradePaused,false);assert.equal(latest.pauseReason,null)});
test('disconnecting pending upgrader emits exactly one levelResume to waiting teammate',()=>{const h=setup(),[a,b]=h.clients,g=h.lobby.game;g.xp=g.nextXp;h.core.tick(h.lobby,.04);h.advance(300);h.core.handle(a,{type:'upgradeChoice',choice:g.players[a.playerId].offer[0]});const before=h.messages[0].filter(message=>message.type==='levelResume').length;h.core.disconnect(b);assert.equal(h.messages[0].filter(message=>message.type==='levelResume').length,before+1);assert.equal(g.upgradePaused,false);assert.equal(g.paused,false)});
test('reconnect during manual pause receives authoritative pauseState',()=>{const h=setup(),[a,b]=h.clients,g=h.lobby.game;h.send(a,{type:'pauseRequest',requested:true});h.send(b,{type:'pauseRequest',requested:true});const out=[],replacement=h.core.addClient(message=>out.push(message)),session=h.core.sessionsByPlayerId.get(a.playerId);h.advance(100);h.core.handle(replacement,{type:'hello',installationId:'resume',resume:{playerId:a.playerId,reconnectToken:session.reconnectToken},unlocked:[],maps:['ruins']});const state=out.find(message=>message.type==='pauseState');assert.equal(g.manualPaused,true);assert.equal(state.paused,true);assert.equal(state.pauseReason,'manual')});
test('upgrade reconnect before choice restores the existing offer',()=>{const h=setup(),a=h.clients[0],g=h.lobby.game;g.xp=g.nextXp;h.core.tick(h.lobby,.04);const offer=[...g.players[a.playerId].offer],session=h.core.sessionsByPlayerId.get(a.playerId);h.core.disconnect(a);const out=[],replacement=h.core.addClient(message=>out.push(message));h.advance(100);h.core.handle(replacement,{type:'hello',installationId:'upgrade-resume',resume:{playerId:a.playerId,reconnectToken:session.reconnectToken},unlocked:[],maps:['ruins']});assert.ok(out.some(message=>message.type==='gameStarted'));assert.ok(out.some(message=>message.type==='pauseState'&&message.upgradePaused));assert.deepEqual(out.find(message=>message.type==='levelUp').offer,offer);assert.equal(out.some(message=>message.type==='upgradeWaiting'),false)});
test('upgrade reconnect after choice restores waiting without duplicate cards',()=>{const h=setup(),a=h.clients[0],g=h.lobby.game;g.xp=g.nextXp;h.core.tick(h.lobby,.04);h.advance(300);h.core.handle(a,{type:'upgradeChoice',choice:g.players[a.playerId].offer[0]});const session=h.core.sessionsByPlayerId.get(a.playerId);h.core.disconnect(a);const out=[],replacement=h.core.addClient(message=>out.push(message));h.advance(100);h.core.handle(replacement,{type:'hello',installationId:'waiting-resume',resume:{playerId:a.playerId,reconnectToken:session.reconnectToken},unlocked:[],maps:['ruins']});assert.ok(out.some(message=>message.type==='gameStarted'));assert.ok(out.some(message=>message.type==='pauseState'&&message.upgradePaused));assert.ok(out.some(message=>message.type==='upgradeWaiting'));assert.equal(out.some(message=>message.type==='levelUp'),false)});
