'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {AccountStore,mergeClientProgress,applyProgressOperation}=require('../account-store');
const {SlidingWindowLimiter,originAllowed,clientIp,requestIsHttps,cookieHeader,accountEntitlements}=require('../server');
const stats=progress=>JSON.parse(progress['swarmfall-stats']||'{}');
const operation=(id,type,payload={})=>({id,type,payload});

test('ordinary client sync cannot forge server-owned progression',()=>{const current={'swarmfall-stats':'{"coins":7}','swarmfall-achievements-v1':'["boss_1"]','swarmfall-unlocked':'[]','swarmfall-modes':'[]','swarmfall-save-v1':'old'},forged={'swarmfall-stats':'{"coins":999999}','swarmfall-achievements-v1':'["map_1","unknown"]','swarmfall-unlocked':'["warrior","druid"]','swarmfall-modes':'["nightmare"]','swarmfall-save-v1':'new'};const merged=mergeClientProgress(current,forged);assert.equal(stats(merged).coins,7);assert.deepEqual(JSON.parse(merged['swarmfall-achievements-v1']),['boss_1']);assert.deepEqual(JSON.parse(merged['swarmfall-unlocked']),[]);assert.deepEqual(JSON.parse(merged['swarmfall-modes']),[]);assert.equal(merged['swarmfall-save-v1'],'new')});

test('validated single-player achievement, map and purchase operations are monotonic',()=>{let progress={'swarmfall-stats':'{"coins":30}'};progress=applyProgressOperation(progress,operation('operation-achievement','unlockAchievement',{id:'boss_1'}));assert.deepEqual(JSON.parse(progress['swarmfall-achievements-v1']),['boss_1']);assert.equal(stats(progress).coins,35);progress=applyProgressOperation(progress,operation('operation-purchase','purchaseCharacter',{character:'warrior'}));assert.deepEqual(JSON.parse(progress['swarmfall-unlocked']),['warrior']);assert.equal(stats(progress).coins,10);progress=applyProgressOperation(progress,operation('operation-map','completeMap',{map:'ruins',mode:'normal'}));assert.ok(JSON.parse(progress['swarmfall-achievements-v1']).includes('map_1'));assert.ok(JSON.parse(progress['swarmfall-modes']).includes('normal'));assert.deepEqual(accountEntitlements(progress),{unlocked:['scout','warrior'],maps:['ruins','toxic']})});

test('progress operations reject unknown ids, impossible purchase and arbitrary coin award',()=>{assert.throws(()=>applyProgressOperation({},operation('unknown-achievement','unlockAchievement',{id:'unknown'})),/INVALID_PROGRESSION/);assert.throws(()=>applyProgressOperation({},operation('poor-purchase','purchaseCharacter',{character:'druid'})),/INSUFFICIENT_COINS/);assert.throws(()=>applyProgressOperation({},operation('forged-coins','awardCurrency',{amount:999999})),/INVALID_PROGRESSION/)});

test('single-player operations are revision-safe and idempotent',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'progress-ops-')),file=path.join(directory,'accounts.json'),store=new AccountStore(file);t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));await store.mutate(data=>data.users.push({id:'u',revision:0,progress:{'swarmfall-stats':'{"coins":30}'}}));const first=await store.applySingleplayerOperation('u',0,operation('purchase-warrior','purchaseCharacter',{character:'warrior'}));assert.equal(first.revision,1);const duplicate=await store.applySingleplayerOperation('u',0,operation('purchase-warrior','purchaseCharacter',{character:'warrior'}));assert.equal(duplicate.duplicate,true);assert.equal(duplicate.revision,1);await assert.rejects(store.applySingleplayerOperation('u',0,operation('achievement-boss','unlockAchievement',{id:'boss_1'})),error=>error.code==='REVISION_CONFLICT'&&error.revision===1);const second=await store.applySingleplayerOperation('u',1,operation('achievement-boss','unlockAchievement',{id:'boss_1'}));assert.equal(second.revision,2);assert.equal(stats(second.progress).coins,10)});

test('sliding limiter prunes expired unique keys while retaining active limits',()=>{let now=0;const limiter=new SlidingWindowLimiter({limit:2,windowMs:100,now:()=>now,sweepEvery:4});for(let i=0;i<20;i++)limiter.take(`ip-${i}`);assert.equal(limiter.buckets.size,20);now=101;for(let i=0;i<4;i++)limiter.take('active');assert.ok(limiter.buckets.size<=2);now=150;assert.equal(limiter.take('active'),true)});

test('origin allowlist is strict in production and local-only by default',()=>{assert.equal(originAllowed(undefined,'https://game.example'),true);assert.equal(originAllowed('https://game.example','https://game.example'),true);assert.equal(originAllowed('http://localhost:8080','https://game.example'),false);assert.equal(originAllowed('https://evil.example','https://game.example'),false);assert.equal(originAllowed('http://localhost:8080',''),true);assert.equal(originAllowed('https://evil.example',''),false)});

test('forwarded address and protocol require trusted proxy mode',()=>{const req={headers:{'x-forwarded-for':'203.0.113.9','x-forwarded-proto':'https'},socket:{remoteAddress:'127.0.0.1',encrypted:false}};assert.equal(clientIp(req,false),'127.0.0.1');assert.equal(clientIp(req,true),'203.0.113.9');assert.equal(requestIsHttps(req,false),false);assert.equal(requestIsHttps(req,true),true);assert.doesNotMatch(cookieHeader(req,'token',60,false),/; Secure/);assert.match(cookieHeader(req,'token',60,true),/; Secure/)});

test('build slot CSS preserves square slot and icon geometry',()=>{const css=fs.readFileSync(path.join(__dirname,'..','style.css'),'utf8');assert.match(css,/\.item-slot,\.augment-slot\{aspect-ratio:1\/1;height:auto/);assert.match(css,/\.slot>\.item-svg,\.slot>\.augment-svg\{[^}]*aspect-ratio:1\/1/);assert.match(css,/max-width:72%;max-height:72%/)});

test('production WebSocket allowlist rejects an unlisted browser origin with 403',async t=>{const WebSocket=require('ws'),{createHttpServer,GameServer}=require('../server'),directory=fs.mkdtempSync(path.join(os.tmpdir(),'origin-policy-')),runtime=createHttpServer(new GameServer(),{accountFile:path.join(directory,'accounts.json'),allowedOrigins:'https://game.example'});await new Promise(resolve=>runtime.server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>runtime.server.close(resolve)));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const socket=new WebSocket(`ws://127.0.0.1:${runtime.server.address().port}`,{headers:{Origin:'http://localhost:8080'}});const status=await new Promise((resolve,reject)=>{socket.once('unexpected-response',(_,response)=>resolve(response.statusCode));socket.once('open',()=>reject(new Error('unlisted origin connected')));socket.once('error',()=>{})});assert.equal(status,403)});
