'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {SAVE_LIMITS,limitSaveCollections,validateSingleplayerSave,isReconnectSession,startupFlow}=require('../save-state');
const valid={mode:'singleplayer',version:3,elapsed:10,chosenCharacter:'scout',chosenMap:'ruins',player:{x:10,y:20,hp:80,maxHp:100},enemies:[],bullets:[],orbs:[]};
test('only valid singleplayer saves activate Continue',()=>{assert.equal(validateSingleplayerSave(valid),true);assert.equal(validateSingleplayerSave({...valid,mode:'multiplayer'}),false);assert.equal(validateSingleplayerSave({...valid,player:{hp:NaN}}),false);assert.equal(validateSingleplayerSave({broken:true}),false)});
test('save validation rejects non-finite, unsupported and structurally dangerous state',()=>{assert.equal(validateSingleplayerSave({...valid,player:{...valid.player,x:Infinity}}),false);assert.equal(validateSingleplayerSave({...valid,chosenMap:'missing'}),false);assert.equal(validateSingleplayerSave({...valid,chosenCharacter:'boss'}),false);assert.equal(validateSingleplayerSave({...valid,version:2}),false);assert.equal(validateSingleplayerSave({...valid,enemies:[{x:1}]}),false);assert.equal(validateSingleplayerSave({...valid,enemies:Array.from({length:451},()=>({x:1,y:1}))}),false)});
test('startup reconnect requires code, player id and token',()=>{const complete={code:'ABC234',playerId:'p1',reconnectToken:'secret'};assert.equal(isReconnectSession(complete),true);assert.equal(startupFlow(complete,valid),'multiplayer-reconnect');for(const key of['code','playerId','reconnectToken']){const incomplete={...complete};delete incomplete[key];assert.equal(isReconnectSession(incomplete),false);assert.equal(startupFlow(incomplete,valid),'singleplayer-continue')}assert.equal(startupFlow(null,{broken:true}),'fresh-menu')});
test('Endless and the complete save shape at collection limits remain valid',()=>{const entity=()=>({x:10,y:20,r:4}),save={...valid,chosenMode:'endless'};for(const[key,limit]of Object.entries(SAVE_LIMITS))save[key]=Array.from({length:limit},entity);save.eventHistory=Array(SAVE_LIMITS.eventHistory).fill('hunt');save.upgradeOfferKeys=['item-power','item-speed','augment-executor'];save.upgradeRerolled=[0,1,2];save.runKillTypes=Array(SAVE_LIMITS.runKillTypes).fill('melee');assert.equal(validateSingleplayerSave(save),true);assert.equal(startupFlow(null,save),'singleplayer-continue')});
test('the save serializer bounds every collection to validator limits',()=>{const entity=()=>({x:10,y:20}),oversized={...valid};for(const[key,limit]of Object.entries(SAVE_LIMITS))oversized[key]=Array.from({length:limit+20},entity);oversized.eventHistory=Array(SAVE_LIMITS.eventHistory+20).fill('hunt');oversized.upgradeOfferKeys=Array(SAVE_LIMITS.upgradeOfferKeys+2).fill('item-power');oversized.upgradeRerolled=Array(SAVE_LIMITS.upgradeRerolled+2).fill(0);oversized.runKillTypes=Array(SAVE_LIMITS.runKillTypes+20).fill('melee');const serialized=limitSaveCollections(oversized);for(const[key,limit]of Object.entries(SAVE_LIMITS))assert.ok(serialized[key].length<=limit,key);assert.equal(validateSingleplayerSave(serialized),true)});
