'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,applyUpgrade}=require('../server');
function harness(){let now=1000;const core=new GameServer(()=>now),out=new Map();const client=id=>{const messages=[];const c=core.addClient(m=>messages.push(m));core.handle(c,{type:'hello',clientId:id,unlocked:['warrior','druid'],maps:['ruins','toxic']});out.set(id,messages);return c};return{core,client,out,advance:ms=>now+=ms}}
function create(h,id='host'){const c=h.client(id);h.advance(2000);h.core.handle(c,{type:'createLobby'});return c}
function join(h,code,id){const c=h.client(id);h.advance(1000);h.core.handle(c,{type:'joinLobby',code});return c}
test('create lobby',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);assert.match(lobby.code,/^[A-Z2-9]{6}$/);assert.equal(lobby.players[0].host,true)});
test('join lobby and enforce four-player limit',()=>{const h=harness(),host=create(h),code=host.lobby;join(h,code,'p2');join(h,code,'p3');join(h,code,'p4');const fifth=join(h,code,'p5');assert.equal(h.core.lobbies.get(code).players.length,4);assert.equal(fifth.lobby,'');assert.equal(h.out.get('p5').at(-1).type,'joinError')});
test('ready gates start and server starts after everyone is ready',()=>{const h=harness(),host=create(h),guest=join(h,host.lobby,'guest');h.advance(600);h.core.handle(host,{type:'startGame'});assert.equal(h.core.lobbies.get(host.lobby).game,null);h.advance(300);h.core.handle(guest,{type:'playerReady',ready:true});h.advance(600);h.core.handle(host,{type:'startGame'});assert.ok(h.core.lobbies.get(host.lobby).game)});
test('host migrates after disconnect grace period',()=>{const h=harness(),host=create(h),guest=join(h,host.lobby,'guest'),code=host.lobby;h.core.disconnect(host);h.advance(16000);h.core.cleanup();assert.equal(h.core.lobbies.get(code).players[0].id,guest.id);assert.equal(h.core.lobbies.get(code).players[0].host,true)});
test('reconnect restores the same player and match state',()=>{const h=harness(),host=create(h),code=host.lobby;h.core.handle(host,{type:'startGame'});const x=h.core.lobbies.get(code).game.players[host.id].x;h.core.disconnect(host);h.advance(5000);const replacement=h.core.addClient(()=>{});h.core.handle(replacement,{type:'hello',clientId:'host',unlocked:[],maps:['ruins']});assert.equal(replacement.lobby,code);assert.equal(h.core.lobbies.get(code).game.players.host.x,x)});
test('movement is input-driven, finite and collision constrained',()=>{const h=harness(),host=create(h),code=host.lobby;h.core.handle(host,{type:'startGame'});h.advance(100);h.core.handle(host,{type:'playerInput',right:true,aim:0});const p=h.core.lobbies.get(code).game.players.host,before=p.x;h.core.tick(h.core.lobbies.get(code),.04);assert.ok(p.x>before);h.advance(100);h.core.handle(host,{type:'playerInput',right:true,aim:NaN});assert.notEqual(h.out.get('host').at(-1).type,'gameState')});
test('damage and HP are calculated server-side',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.handle(host,{type:'startGame'});const g=lobby.game,p=g.players.host;g.enemies=[{id:'enemy',type:'melee',x:p.x+20,y:p.y,hp:34,maxHp:34,r:13,speed:0,damage:9,xp:3}];h.advance(100);h.core.handle(host,{type:'playerInput',aim:0});for(let i=0;i<5;i++)h.core.tick(lobby,.04);assert.ok(g.enemies.length===0||g.enemies[0].hp<34);assert.ok(p.hp<100)});
test('upgrade must be offered and changes authoritative stats',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.handle(host,{type:'startGame'});const p=lobby.game.players.host;lobby.game.paused=true;lobby.game.levelRound=1;lobby.players[0].choiceRound=0;p.offer=['item-power'];const before=p.stats.damage;h.advance(300);h.core.handle(host,{type:'upgradeChoice',choice:'item-power'});assert.ok(p.stats.damage>before);assert.equal(p.items.power,1);assert.equal(lobby.players[0].choiceRound,1);assert.equal(applyUpgrade(p,'item-not-real'),false)});
test('cleanup removes abandoned lobbies and stale clients',()=>{const h=harness(),host=create(h),code=host.lobby;h.core.disconnect(host);h.advance(16000);h.core.cleanup();assert.equal(h.core.lobbies.has(code),false);assert.equal(h.core.clients.has('host'),false)});
test('malformed and spammed messages cannot mutate state',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);const map=lobby.map;h.core.handle(host,null);h.core.handle(host,{type:'selectMap',map:'toxic'});h.core.handle(host,{type:'selectMap',map:'ruins'});assert.equal(lobby.map,'toxic');h.advance(300);h.core.handle(host,{type:'playerInput',aim:Infinity,up:true});assert.equal(h.out.get('host').at(-1).type,'error')});
