'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {GameServer,applyUpgrade}=require('../server');
function harness(){let now=1000;const core=new GameServer(()=>now),out=new Map();const client=id=>{const messages=[];const c=core.addClient(m=>messages.push(m));core.handle(c,{type:'hello',installationId:id,unlocked:['warrior','druid'],maps:['ruins','toxic']});out.set(id,messages);return c};return{core,client,out,advance:ms=>now+=ms}}
function create(h,id='host'){const c=h.client(id);h.advance(2000);h.core.handle(c,{type:'createLobby'});return c}
function join(h,code,id){const c=h.client(id);h.advance(1000);h.core.handle(c,{type:'joinLobby',code});return c}
test('create lobby',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);assert.match(lobby.code,/^[A-Z2-9]{6}$/);assert.equal(lobby.players[0].host,true)});
test('join lobby and enforce four-player limit',()=>{const h=harness(),host=create(h),code=host.lobby;join(h,code,'p2');join(h,code,'p3');join(h,code,'p4');const fifth=join(h,code,'p5');assert.equal(h.core.lobbies.get(code).players.length,4);assert.equal(fifth.lobby,'');assert.equal(h.out.get('p5').at(-1).type,'joinError')});
test('ready gates preparation and assets gate the actual start',()=>{const h=harness(),host=create(h),guest=join(h,host.lobby,'guest'),lobby=h.core.lobbies.get(host.lobby);h.advance(600);h.core.handle(host,{type:'startGame'});assert.equal(lobby.preparing,undefined);h.advance(300);h.core.handle(guest,{type:'playerReady',ready:true});h.advance(600);h.core.handle(host,{type:'startGame'});const matchId=lobby.preparing.matchId;assert.equal(lobby.game,null);h.advance(300);h.core.handle(host,{type:'assetsReady',matchId});h.advance(300);h.core.handle(guest,{type:'assetsReady',matchId});assert.ok(lobby.game)});
test('host migrates after disconnect grace period',()=>{const h=harness(),host=create(h),guest=join(h,host.lobby,'guest'),code=host.lobby;h.core.disconnect(host);h.advance(16000);h.core.cleanup();assert.equal(h.core.lobbies.get(code).players[0].id,guest.playerId);assert.equal(h.core.lobbies.get(code).players[0].host,true)});
test('reconnect restores the same player and match state',()=>{const h=harness(),host=create(h),code=host.lobby;h.core.start(h.core.lobbies.get(host.lobby));const x=h.core.lobbies.get(code).game.players[host.playerId].x;h.core.disconnect(host);h.advance(5000);const replacement=h.core.addClient(()=>{});h.core.handle(replacement,{type:'hello',installationId:'host-reload',resume:{playerId:host.playerId,reconnectToken:h.core.sessionsByPlayerId.get(host.playerId).reconnectToken},unlocked:[],maps:['ruins']});assert.equal(replacement.lobby,code);assert.equal(h.core.lobbies.get(code).game.players[host.playerId].x,x)});
test('reconnect receives the full authoritative versioned build',()=>{const h=harness(),host=create(h),code=host.lobby,lobby=h.core.lobbies.get(code);h.core.start(lobby);const p=lobby.game.players[host.playerId];for(const key of['item-power','item-speed','item-vital','augment-executor','augment-gambler'])assert.equal(applyUpgrade(p,key),true);assert.equal(p.buildVersion,5);const token=h.core.sessionsByPlayerId.get(host.playerId).reconnectToken;h.core.disconnect(host);h.advance(1000);const messages=[],replacement=h.core.addClient(message=>messages.push(message));h.core.handle(replacement,{type:'hello',installationId:'build-resume',resume:{playerId:host.playerId,reconnectToken:token},unlocked:[],maps:['ruins']});h.core.tick(lobby,.06);const mine=messages.findLast(message=>message.type==='gameState').state.players.find(player=>player.id===host.playerId);assert.equal(mine.buildVersion,5);assert.deepEqual(mine.items,{power:1,speed:1,vital:1});assert.deepEqual(mine.augments,['executor','gambler']);assert.equal(mine.hp,p.hp);assert.equal(mine.maxHp,p.stats.maxHp)});
test('movement is input-driven, finite and collision constrained',()=>{const h=harness(),host=create(h),code=host.lobby;h.core.start(h.core.lobbies.get(host.lobby));h.advance(100);h.core.handle(host,{type:'playerInput',right:true,aim:0,inputSeq:1});const p=h.core.lobbies.get(code).game.players[host.playerId],before=p.x;h.core.tick(h.core.lobbies.get(code),.04);assert.ok(p.x>before);h.advance(100);h.core.handle(host,{type:'playerInput',right:true,aim:NaN,inputSeq:2});assert.notEqual(h.out.get('host').at(-1).type,'gameState')});
test('damage and HP are calculated server-side',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.start(h.core.lobbies.get(host.lobby));const g=lobby.game,p=g.players[host.playerId];g.enemies=[{id:'enemy',type:'melee',x:p.x+20,y:p.y,hp:34,maxHp:34,r:13,speed:0,damage:9,xp:3}];h.advance(100);h.core.handle(host,{type:'playerInput',aim:0,inputSeq:1});for(let i=0;i<5;i++)h.core.tick(lobby,.04);assert.ok(g.enemies.length===0||g.enemies[0].hp<34);assert.ok(p.hp<100)});
test('upgrade must be offered and changes authoritative stats',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.start(h.core.lobbies.get(host.lobby));const p=lobby.game.players[host.playerId];lobby.game.paused=true;lobby.game.levelRound=1;lobby.players[0].choiceRound=0;p.offer=['item-power'];const before=p.stats.damage;h.advance(300);h.core.handle(host,{type:'upgradeChoice',choice:'item-power'});assert.ok(p.stats.damage>before);assert.equal(p.items.power,1);assert.equal(p.buildVersion,1);assert.equal(lobby.players[0].choiceRound,1);assert.equal(applyUpgrade(p,'item-not-real'),false);assert.equal(p.buildVersion,1)});
test('cleanup removes abandoned lobbies and stale clients',()=>{const h=harness(),host=create(h),code=host.lobby;h.core.disconnect(host);h.advance(16000);h.core.cleanup();assert.equal(h.core.lobbies.has(code),false);assert.equal(h.core.sessionsByPlayerId.has(host.playerId),false)});
test('malformed and spammed messages cannot mutate state',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);const map=lobby.map;h.core.handle(host,null);h.core.handle(host,{type:'selectMap',map:'toxic'});h.core.handle(host,{type:'selectMap',map:'ruins'});assert.equal(lobby.map,'ruins');h.advance(300);h.core.handle(host,{type:'playerInput',aim:Infinity,up:true});assert.equal(h.out.get('host').at(-1).type,'error')});
test('abilityPress is edge-triggered, monotonic and cooldown-authoritative',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.start(h.core.lobbies.get(host.lobby));const p=lobby.game.players[host.playerId];h.advance(100);h.core.handle(host,{type:'playerInput',aim:0,inputSeq:1});h.advance(100);h.core.handle(host,{type:'abilityPress',ability:'q',aim:0,seq:1});assert.equal(p.abilitySeq,1);const ready=p.stats.cooldowns.qReadyAt;h.advance(100);h.core.handle(host,{type:'abilityPress',ability:'q',aim:0,seq:1});assert.equal(p.abilitySeq,1);h.advance(100);h.core.handle(host,{type:'abilityPress',ability:'q',aim:0,seq:0});assert.equal(p.abilitySeq,1);h.advance(5100);h.core.handle(host,{type:'abilityPress',ability:'q',aim:0,seq:2});assert.equal(p.abilitySeq,2);assert.ok(p.stats.cooldowns.qReadyAt>ready)});
test('held movement packets cannot retrigger abilities',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.start(h.core.lobbies.get(host.lobby));const p=lobby.game.players[host.playerId];for(let seq=1;seq<=20;seq++){h.advance(100);h.core.handle(host,{type:'playerInput',aim:0,inputSeq:seq,q:true});h.core.tick(lobby,.1)}assert.equal(p.abilitySeq,0)});
test('upgrade applies only after validation and emits authoritative acknowledgement',()=>{const h=harness(),host=create(h),lobby=h.core.lobbies.get(host.lobby);h.core.start(h.core.lobbies.get(host.lobby));const p=lobby.game.players[host.playerId];lobby.game.paused=true;lobby.game.levelRound=1;p.offer=['item-speed'];const before=p.stats.speed;h.advance(300);h.core.handle(host,{type:'upgradeChoice',choice:'item-power'});assert.equal(p.stats.speed,before);h.advance(300);h.core.handle(host,{type:'upgradeChoice',choice:'item-speed'});assert.ok(p.stats.speed>before);assert.ok(h.out.get('host').some(message=>message.type==='upgradeAccepted'))});
test('non-host return after game over restores lobby for everyone',()=>{const h=harness(),host=create(h),guest=h.core.addClient(message=>{const list=h.out.get('guest')||[];list.push(message);h.out.set('guest',list)});h.advance(1000);h.core.handle(guest,{type:'hello',installationId:'guest',unlocked:[],maps:['ruins']});h.advance(1000);h.core.handle(guest,{type:'joinLobby',code:host.lobby});const lobby=h.core.lobbies.get(host.lobby);lobby.players.find(p=>p.id===guest.playerId).ready=true;h.advance(1000);h.core.start(h.core.lobbies.get(host.lobby));lobby.game.ended=true;h.advance(1000);h.core.handle(guest,{type:'returnToLobby'});assert.equal(lobby.game,null);assert.equal(lobby.players.length,2);assert.ok(h.out.get('host').some(message=>message.type==='lobbyState'&&!message.lobby.started));h.advance(1000);lobby.players.find(p=>p.id===guest.playerId).ready=true;h.core.start(h.core.lobbies.get(host.lobby));assert.ok(lobby.game)});

test('authenticated account logins are authoritative lobby names and survive host migration',()=>{const core=new GameServer(()=>1000,()=>.5),host=core.addClient(()=>{},{id:'account-a',login:'Alpha',progress:{}}),guest=core.addClient(()=>{},{id:'account-b',login:'Beta',progress:{}});core.handle(host,{type:'hello',installationId:'a',name:'admin',unlocked:[],maps:['ruins']});core.handle(host,{type:'createLobby'});core.handle(guest,{type:'hello',installationId:'b',name:'spoofed',unlocked:[],maps:['ruins']});core.handle(guest,{type:'joinLobby',code:host.lobby});const lobby=core.lobbies.get(host.lobby);assert.deepEqual(lobby.players.map(player=>player.name),['Alpha','Beta']);core.leave(host,true);assert.equal(lobby.players[0].name,'Beta');assert.equal(lobby.players[0].host,true)});

test('authenticated account progress controls multiplayer character and map entitlements',()=>{const {accountEntitlements}=require('../server');assert.deepEqual(accountEntitlements({'swarmfall-unlocked':'["warrior","druid"]','swarmfall-achievements-v1':'["map_1"]'}),{unlocked:['scout','warrior','druid'],maps:['ruins','toxic']});assert.deepEqual(accountEntitlements({'swarmfall-unlocked':'invalid','swarmfall-achievements-v1':'[]'}),{unlocked:['scout'],maps:['ruins','toxic']});const core=new GameServer(()=>1000,()=>.5),client=core.addClient(()=>{},{id:'secure',login:'Secure',progress:{}});core.handle(client,{type:'hello',installationId:'secure',unlocked:['warrior','druid'],maps:['ruins','toxic']});assert.deepEqual(client.unlocked,['scout']);assert.deepEqual(client.maps,['ruins','toxic']);const paid=core.addClient(()=>{},{id:'paid',login:'Paid',progress:{'swarmfall-unlocked':'[\"warrior\"]'}});core.handle(paid,{type:'hello',installationId:'paid',unlocked:['druid'],maps:[]});core.handle(paid,{type:'createLobby'});const lobby=core.lobbies.get(paid.lobby);core.handle(paid,{type:'selectCharacter',character:'warrior'});core.handle(paid,{type:'selectMap',map:'toxic'});assert.equal(lobby.players[0].character,'warrior');assert.equal(lobby.map,'toxic');core.handle(paid,{type:'selectCharacter',character:'druid'});assert.equal(lobby.players[0].character,'warrior')});

test('anonymous hello cannot forge character or map entitlements',()=>{const messages=[],core=new GameServer(()=>1000,()=>.5),client=core.addClient(message=>messages.push(message));core.handle(client,{type:'hello',installationId:'forger',unlocked:['warrior','druid'],maps:['ruins','toxic']});assert.deepEqual(client.unlocked,['scout']);assert.deepEqual(client.maps,['ruins']);assert.deepEqual(messages.find(message=>message.type==='helloAck').entitlements,{unlocked:['scout'],maps:['ruins']});core.handle(client,{type:'createLobby'});const lobby=core.lobbies.get(client.lobby);core.handle(client,{type:'selectCharacter',character:'warrior'});core.handle(client,{type:'selectMap',map:'toxic'});assert.equal(lobby.players[0].character,'scout');assert.equal(lobby.map,'ruins')});
