'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const collision=require('../shared-collision'),{GameServer,DATA,isEnemyActive}=require('../server');
function match(character='scout'){let now=1000;const core=new GameServer(()=>now,()=>.99),member={id:'p',name:'P',character,connected:true,host:true,ready:true,choiceRound:0},lobby={code:'SPAWN',map:'ruins',createdAt:now,updatedAt:now,players:[member],game:null};core.start(lobby);const p=lobby.game.players.p;return{core,lobby,g:lobby.game,p,now:()=>now,advance:ms=>now+=ms}}
function enemy(h,{x=h.p.x+40,y=h.p.y,active=false,id='e'}={}){return{id,type:'melee',ai:'melee',x,y,hp:100,maxHp:100,r:13,speed:90,damage:0,xp:0,spawnedAt:active?h.now()-1000:h.now(),spawnDuration:.35}}

test('spawning enemy is absent from projectile collision, pierce and splash resolution',()=>{const h=match(),telegraph=enemy(h),active=enemy(h,{x:h.p.x+52,active:true,id:'active'});h.p.items.lens=3;h.g.enemies=[telegraph,active];h.g.bullets=[{id:'b',ownerId:h.p.id,x:telegraph.x,y:telegraph.y,vx:0,vy:0,r:20,life:1,damage:20,baseDamage:20,pierce:0,hitCount:0,originX:h.p.x,originY:h.p.y,critRoll:1}];h.core.tickProjectiles(h.lobby,0);assert.equal(telegraph.hp,100);assert.ok(active.hp<100);assert.equal(h.g.bullets.length,0);assert.equal(isEnemyActive(telegraph,h.now()),false)});

test('spawning enemy cannot detonate splash onto a nearby active enemy',()=>{const h=match(),telegraph=enemy(h),active=enemy(h,{x:h.p.x+75,active:true,id:'active'});h.p.items.lens=3;h.g.enemies=[telegraph,active];h.g.bullets=[{id:'b',ownerId:h.p.id,x:telegraph.x,y:telegraph.y,vx:0,vy:0,r:4,life:1,damage:20,baseDamage:20,pierce:0,hitCount:0,originX:h.p.x,originY:h.p.y,critRoll:1}];h.core.tickProjectiles(h.lobby,0);assert.equal(telegraph.hp,100);assert.equal(active.hp,100);assert.equal(h.g.bullets[0].pierce,0);assert.equal(h.g.bullets[0].hitCount,0)});

test('Warrior cannot target or heal from telegraph but hits it after activation',()=>{const h=match('warrior'),e=enemy(h);h.g.enemies=[e];h.p.hp=50;assert.equal(h.core.performWarriorAttack(h.lobby,h.p,0),false);assert.equal(e.hp,100);assert.equal(h.p.hp,50);h.advance(350);assert.equal(h.core.performWarriorAttack(h.lobby,h.p,0),true);assert.ok(e.hp<100);assert.ok(h.p.hp>50)});

test('Scout E neither damages nor knocks back spawning enemy',()=>{const h=match('scout'),e=enemy(h),before={x:e.x,y:e.y,hp:e.hp};h.g.enemies=[e];assert.equal(h.core.castAbility(h.lobby,h.p,'e',0),true);assert.deepEqual({x:e.x,y:e.y,hp:e.hp},before);h.advance(9000);h.p.stats.cooldowns.eReadyAt=0;assert.equal(h.core.castAbility(h.lobby,h.p,'e',0),true);assert.ok(e.hp<before.hp);assert.ok(e.x>before.x)});

test('forced flow invalidation is bounded across a simultaneous stuck group',()=>{const h=match(),target=h.p,enemies=Array.from({length:24},(_,i)=>({id:`e${i}`,x:790,y:330+i*.1,r:13,navWindowTime:.79,navExpected:80,navActual:2,navUseful:0}));h.core.flowField(h.lobby,target,13);const builds=h.core.flowFieldBuilds;for(const e of enemies){h.core.updateEnemyStuck(h.lobby,e,target,.02,2,.05,0);h.core.flowField(h.lobby,target,13)}assert.equal(h.core.metrics.forcedInvalidations,1);assert.equal(h.core.flowFieldBuilds-builds,1);h.advance(351);enemies[0].navWindowTime=.79;enemies[0].navExpected=80;enemies[0].navActual=2;h.core.updateEnemyStuck(h.lobby,enemies[0],target,.02,2,.05,0);assert.equal(h.core.metrics.forcedInvalidations,2)});

test('wall-follow steering keeps rolling speed while target moves along an L-wall',()=>{const h=match(),e={id:'wall',type:'melee',ai:'melee',x:790,y:330,hp:100,maxHp:100,r:13,speed:90,damage:0,xp:0,spawnedAt:0,spawnDuration:.35},windows=[];Object.assign(h.p,{x:1300,y:500,hp:1e6});h.g.enemies=[e];h.advance(1000);let from={x:e.x,y:e.y};for(let tick=1;tick<=450;tick++){h.p.y=500+tick/450*210;h.advance(1000/30);h.core.tickEnemy(h.lobby,e,1/30);assert.equal(collision.blocked('ruins',e.x,e.y,e.r),false);if(tick%90===0){const moved=Math.hypot(e.x-from.x,e.y-from.y);windows.push(moved);from={x:e.x,y:e.y}}}assert.ok(windows.slice(0,3).every(distance=>distance>15),windows);assert.ok(Math.hypot(e.x-h.p.x,e.y-h.p.y)<180)});
