'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {update,sample,damageFlash,upgradePauseUiState}=require('../multiplayer-visual-state');
const player=(overrides={})=>({id:'p2',x:10,y:20,character:'scout',name:'Guest',hp:100,maxHp:100,alive:true,facing:0,attackSeq:0,abilitySeq:0,...overrides});
test('new remote player starts idle with the correct character and no position glitch',()=>{const cache=new Map();update(cache,[player({character:'warrior'})],1000);const visual=sample(cache.get('p2'),1000);assert.equal(visual.character,'warrior');assert.equal(visual.animation,'idle');assert.equal(visual.x,10);assert.equal(visual.y,20)});
test('movement derives run animation but authoritative aim controls facing',()=>{const cache=new Map();update(cache,[player()],1000);const original=cache.get('p2');original.animationTime=2;update(cache,[player({x:30,y:20,facing:Math.PI})],1100);assert.equal(cache.get('p2'),original);assert.equal(original.animation,'run');assert.equal(original.targetFacing,Math.PI);assert.equal(original.animationTime,2)});
test('idle snapshot smoothly follows server facing while animation time advances locally',()=>{const cache=new Map();update(cache,[player()],1000);sample(cache.get('p2'),1050);update(cache,[player({facing:Math.PI/2})],1100);const visual=sample(cache.get('p2'),1150);assert.equal(visual.animation,'idle');assert.ok(visual.facing>0&&visual.facing<Math.PI/2);assert.ok(visual.animationTime>0)});
test('attack and ability sequences trigger visual-only timers',()=>{const cache=new Map();update(cache,[player()],1000);update(cache,[player({attackSeq:1,abilitySeq:1,lastAbility:'q'})],1100);const visual=sample(cache.get('p2'),1150);assert.ok(visual.attackAnim>0);assert.equal(visual.abilityActive,true);assert.equal(visual.lastAbility,'q')});
test('remote attack locks the authoritative attack angle for the whole slash',()=>{const cache=new Map();update(cache,[player({character:'warrior',facing:0})],1000);update(cache,[player({character:'warrior',facing:Math.PI/2,attackSeq:1})],1100);update(cache,[player({character:'warrior',facing:Math.PI,attackSeq:1})],1140);const visual=sample(cache.get('p2'),1150);assert.ok(visual.attackAnim>0);assert.equal(visual.attackAngle,Math.PI/2)});
test('missing players are removed while reconnect creates a clean persistent state',()=>{const cache=new Map();update(cache,[player()],1000);update(cache,[],1100);assert.equal(cache.has('p2'),false);update(cache,[player({x:80,character:'druid'})],1200);const visual=sample(cache.get('p2'),1200);assert.equal(visual.x,80);assert.equal(visual.character,'druid')});
test('interpolation samples between snapshots and clamps after lag',()=>{const cache=new Map();update(cache,[player({x:0})],1000);update(cache,[player({x:80})],1100);assert.equal(sample(cache.get('p2'),1140).x,40);assert.equal(sample(cache.get('p2'),1400).x,80)});

test('enemy damage flash is derived from authoritative HP decrease',()=>{assert.equal(damageFlash({hp:20},{hp:12}),.12);assert.equal(damageFlash({hp:12},{hp:12}),0)});
test('entity interpolation continues from the rendered position without snapshot rollback',()=>{const {updateEntities,sampleEntities}=require('../multiplayer-visual-state'),cache=new Map();updateEntities(cache,[{id:'e',x:0,y:0}],1000);updateEntities(cache,[{id:'e',x:40,y:0}],1040);const before=sampleEntities(cache,1060,72)[0].x;updateEntities(cache,[{id:'e',x:80,y:0}],1080);const after=sampleEntities(cache,1080,72)[0].x;assert.equal(after,before);assert.ok(sampleEntities(cache,1100,72)[0].x>after)});
test('dead player becomes spectator and camera selects nearest living teammate',()=>{const {selectSpectatorTarget,gameplayEnabled}=require('../multiplayer-visual-state'),players=[{id:'mine',x:0,y:0,alive:false},{id:'far',x:200,y:0,alive:true},{id:'near',x:30,y:0,alive:true}];assert.equal(selectSpectatorTarget(players,'mine',players[0]).id,'near');assert.equal(gameplayEnabled({isDead:true}),false);assert.equal(gameplayEnabled({isDead:false}),true)});
test('spectator target is absent only when no teammate remains alive',()=>{const {selectSpectatorTarget}=require('../multiplayer-visual-state');assert.equal(selectSpectatorTarget([{id:'mine',x:0,y:0,alive:false},{id:'ally',x:1,y:1,alive:false}],'mine'),null)});
test('angle interpolation uses the shortest arc across PI boundary',()=>{const {lerpAngle}=require('../multiplayer-visual-state'),value=lerpAngle(Math.PI-.1,-Math.PI+.1,.5);assert.ok(Math.abs(Math.abs(value)-Math.PI)<.02)});
test('spectator target remains stable until it dies',()=>{const {selectSpectatorTarget}=require('../multiplayer-visual-state'),players=[{id:'mine',x:0,y:0,alive:false},{id:'first',x:50,y:0,alive:true},{id:'near',x:5,y:0,alive:true}];assert.equal(selectSpectatorTarget(players,'mine',players[0],'first').id,'first');players[1].alive=false;assert.equal(selectSpectatorTarget(players,'mine',players[0],'first').id,'near')});
test('dead players cannot participate in upgrades and HUD marks them dead',()=>{const {canParticipateInUpgrade,teamHudData}=require('../multiplayer-visual-state'),alive=player(),dead=player({id:'dead',hp:42,alive:false});assert.equal(canParticipateInUpgrade(alive),true);assert.equal(canParticipateInUpgrade(dead),false);const rows=teamHudData([alive,dead],alive.id);assert.equal(rows[0].local,true);assert.equal(rows[0].ratio,1);assert.equal(rows[1].hp,0);assert.equal(rows[1].ratio,0);assert.equal(rows[1].status,'DEAD')});
test('facing interpolation is frame-rate independent over equal elapsed time',()=>{const run=steps=>{const cache=new Map();update(cache,[player({facing:0})],0);sample(cache.get('p2'),0);update(cache,[player({facing:Math.PI})],1);for(let i=1;i<=steps;i++)sample(cache.get('p2'),i*100/steps);return cache.get('p2').facing};const values=[run(6),run(12),run(24)];assert.ok(Math.max(...values)-Math.min(...values)<1e-9)});
test('camera exponential follow is frame-rate independent',()=>{const {cameraFollowStep}=require('../multiplayer-visual-state'),run=steps=>{let value=0;for(let i=0;i<steps;i++)value=cameraFollowStep(value,100,8,.1/steps);return value};assert.ok(Math.abs(run(6)-run(24))<1e-9)});
test('neutral paused input is never added to prediction queue',()=>{const {shouldQueueInput}=require('../multiplayer-visual-state');assert.equal(shouldQueueInput(true,false),true);assert.equal(shouldQueueInput(false,false),false);assert.equal(shouldQueueInput(true,true),false)});
test('other player pause request shows status without disabling local gameplay',()=>{const {pauseUiState,gameplayEnabled}=require('../multiplayer-visual-state'),view=pauseUiState({paused:false,requested:1,required:2,requesterIds:['other']},'mine');assert.equal(view.showStatus,true);assert.equal(view.showModal,false);assert.equal(view.localRequested,false);assert.equal(gameplayEnabled({isDead:false,serverPaused:false,localMenuOpen:view.showModal}),true)});
test('upgrade modal stays intact under the real local multiplayer menu layer',()=>{const {setLocalMenuLayer,localMenuPresentation}=require('../multiplayer-visual-state'),classes=initial=>{const values=new Set(initial);return{contains:value=>values.has(value),toggle(value,force){force?values.add(value):values.delete(value)}}},pauseModal={classList:classes(['hidden'])},levelModal={classList:classes([]),offer:['item-power','item-speed','augment-executor']},offer=levelModal.offer.slice(),buttons=localMenuPresentation(false);assert.equal(setLocalMenuLayer(pauseModal,true),true);assert.equal(pauseModal.classList.contains('hidden'),false);assert.equal(pauseModal.classList.contains('multiplayer-menu-open'),true);assert.equal(levelModal.classList.contains('hidden'),false);assert.equal(buttons.resume,'WRÓĆ DO GRY');assert.equal(buttons.quit,'OPUŚĆ MULTIPLAYER');assert.match(fs.readFileSync(require.resolve('../style.css'),'utf8'),/\.pause-modal\.multiplayer-menu-open\{z-index:40/);assert.equal(setLocalMenuLayer(pauseModal,false),false);assert.equal(pauseModal.classList.contains('hidden'),true);assert.equal(levelModal.classList.contains('hidden'),false);assert.deepEqual(levelModal.offer,offer)});
test('upgrade pause blocks pause menu and cooldown freeze end is idempotent',()=>{const {canTogglePauseMenu,cooldownFreezeShift}=require('../multiplayer-visual-state');assert.equal(canTogglePauseMenu({upgradePaused:true}),false);assert.equal(canTogglePauseMenu({pauseReason:'upgrade'}),false);assert.equal(canTogglePauseMenu({levelModalOpen:true}),false);assert.equal(canTogglePauseMenu({}),true);assert.equal(cooldownFreezeShift(100,300),200);assert.equal(cooldownFreezeShift(0,300),0)});

test('authoritative unpaused snapshot clears a missed multiplayer upgrade modal idempotently',()=>{const stale=upgradePauseUiState({paused:false,upgradePaused:false,pauseReason:null},true);assert.equal(stale.clearStaleUpgrade,true);assert.equal(stale.gameplayEnabled,true);assert.equal(upgradePauseUiState({paused:false,upgradePaused:false},false).clearStaleUpgrade,false);assert.equal(upgradePauseUiState({paused:true,upgradePaused:true},true).clearStaleUpgrade,false)});

test('dead remote actors are excluded and local multiplayer actor exposes a draw guard',()=>{const {classifyPlayers}=require('../multiplayer-visual-state'),players=[{id:'local',alive:false},{id:'remote',alive:false}],state=classifyPlayers(players,'local');assert.equal(state.local.alive,false);assert.equal(state.remote.filter(player=>player.alive!==false).length,0);const source=require('node:fs').readFileSync(require.resolve('../multiplayer-game.js'),'utf8');assert.match(source,/function shouldDrawLocalPlayer\(\)\{return!multiplayerMode\|\|!isDead\}/);assert.match(source,/if\(message\.type==='levelUp'&&!isDead/)});

test('Scout idle is still while Q and ability waves use visual-only sizing',()=>{const source=fs.readFileSync(require.resolve('../game.js'),'utf8');assert.match(source,/SCOUT_Q_SIZE=24,SCOUT_Q_FPS=15/);assert.match(source,/key==='walk'\?loopFrame\(animationTime,SCOUT_WALK_FPS,6\):0/);assert.match(source,/scoutE[^\n]+diameter=Math\.max\(16,r\.r\*2\)/);assert.match(source,/scoutR[^\n]+diameter=Math\.max\(24,r\.r\*2\)/);assert.doesNotMatch(source,/SCOUT_(?:E|R)_MAX_DIAMETER/)});
test('Warrior body and slash share one six-frame attack clock at separate sizes',()=>{const source=fs.readFileSync(require.resolve('../game.js'),'utf8');assert.match(source,/attackEffect:'warrior_attack_effect\.png'/);assert.match(source,/WARRIOR_ATTACK_EFFECT_SIZE=230/);assert.match(source,/frame=onceFrame\(1-attackAnim\/WARRIOR_ATTACK_DURATION,6\)/);assert.match(source,/drawWarriorCharacter[^\n]+WARRIOR_RENDER_SIZE/);assert.match(source,/drawWarriorAttackEffect[^\n]+WARRIOR_ATTACK_EFFECT_SIZE/)});
