'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {update,sample,damageFlash}=require('../multiplayer-visual-state');
const player=(overrides={})=>({id:'p2',x:10,y:20,character:'scout',name:'Guest',hp:100,maxHp:100,alive:true,facing:0,attackSeq:0,abilitySeq:0,...overrides});
test('new remote player starts idle with the correct character and no position glitch',()=>{const cache=new Map();update(cache,[player({character:'warrior'})],1000);const visual=sample(cache.get('p2'),1000);assert.equal(visual.character,'warrior');assert.equal(visual.animation,'idle');assert.equal(visual.x,10);assert.equal(visual.y,20)});
test('movement derives run animation and facing without replacing cached state',()=>{const cache=new Map();update(cache,[player()],1000);const original=cache.get('p2');original.animationTime=2;update(cache,[player({x:30,y:20})],1100);assert.equal(cache.get('p2'),original);assert.equal(original.animation,'run');assert.equal(original.facing,0);assert.equal(original.animationTime,2)});
test('idle snapshot preserves server facing while animation time advances locally',()=>{const cache=new Map();update(cache,[player()],1000);sample(cache.get('p2'),1050);update(cache,[player({facing:Math.PI/2})],1100);const visual=sample(cache.get('p2'),1150);assert.equal(visual.animation,'idle');assert.equal(visual.facing,Math.PI/2);assert.ok(visual.animationTime>0)});
test('attack and ability sequences trigger visual-only timers',()=>{const cache=new Map();update(cache,[player()],1000);update(cache,[player({attackSeq:1,abilitySeq:1,lastAbility:'q'})],1100);const visual=sample(cache.get('p2'),1150);assert.ok(visual.attackAnim>0);assert.equal(visual.abilityActive,true);assert.equal(visual.lastAbility,'q')});
test('missing players are removed while reconnect creates a clean persistent state',()=>{const cache=new Map();update(cache,[player()],1000);update(cache,[],1100);assert.equal(cache.has('p2'),false);update(cache,[player({x:80,character:'druid'})],1200);const visual=sample(cache.get('p2'),1200);assert.equal(visual.x,80);assert.equal(visual.character,'druid')});
test('interpolation samples between snapshots and clamps after lag',()=>{const cache=new Map();update(cache,[player({x:0})],1000);update(cache,[player({x:80})],1100);assert.equal(sample(cache.get('p2'),1140).x,40);assert.equal(sample(cache.get('p2'),1400).x,80)});

test('enemy damage flash is derived from authoritative HP decrease',()=>{assert.equal(damageFlash({hp:20},{hp:12}),.12);assert.equal(damageFlash({hp:12},{hp:12}),0)});
test('entity interpolation continues from the rendered position without snapshot rollback',()=>{const {updateEntities,sampleEntities}=require('../multiplayer-visual-state'),cache=new Map();updateEntities(cache,[{id:'e',x:0,y:0}],1000);updateEntities(cache,[{id:'e',x:40,y:0}],1040);const before=sampleEntities(cache,1060,72)[0].x;updateEntities(cache,[{id:'e',x:80,y:0}],1080);const after=sampleEntities(cache,1080,72)[0].x;assert.equal(after,before);assert.ok(sampleEntities(cache,1100,72)[0].x>after)});
test('dead player becomes spectator and camera selects nearest living teammate',()=>{const {selectSpectatorTarget,gameplayEnabled}=require('../multiplayer-visual-state'),players=[{id:'mine',x:0,y:0,alive:false},{id:'far',x:200,y:0,alive:true},{id:'near',x:30,y:0,alive:true}];assert.equal(selectSpectatorTarget(players,'mine',players[0]).id,'near');assert.equal(gameplayEnabled({isDead:true}),false);assert.equal(gameplayEnabled({isDead:false}),true)});
test('spectator target is absent only when no teammate remains alive',()=>{const {selectSpectatorTarget}=require('../multiplayer-visual-state');assert.equal(selectSpectatorTarget([{id:'mine',x:0,y:0,alive:false},{id:'ally',x:1,y:1,alive:false}],'mine'),null)});
