(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.SwarmAccountCore=api;api.start(root)}})(typeof globalThis!=='undefined'?globalThis:this,()=>{
  'use strict';
  const ACCOUNT_PROGRESS_KEYS=Object.freeze(['swarmfall-stats','swarmfall-achievements-v1','swarmfall-unlocked','swarmfall-modes','swarmfall-nightmare-cosmetic','swarmfall-save-v1','swarmfall-character','swarmfall-map','swarmfall-mode']);
  const ACCOUNT_PROGRESS_KEY_SET=new Set(ACCOUNT_PROGRESS_KEYS),LOGIN_PATTERN=/^[a-zA-Z0-9_.-]{3,24}$/,EMAIL_PATTERN=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const MESSAGES=Object.freeze({emptyIdentifier:'Wpisz login lub adres e-mail.',emptyLogin:'Wpisz login.',invalidLogin:'Login musi mieć od 3 do 24 znaków i może zawierać litery, cyfry, kropkę, myślnik lub podkreślenie.',emptyEmail:'Wpisz adres e-mail.',invalidEmail:'Podaj prawidłowy adres e-mail.',emptyPassword:'Wpisz hasło.',shortPassword:'Hasło musi mieć minimum 8 znaków.',longPassword:'Hasło może mieć maksymalnie 128 znaków.',taken:'Login lub e-mail jest już zajęty.',credentials:'Nieprawidłowy login/e-mail lub hasło.',network:'Brak połączenia z siecią.',server:'Serwer kont jest chwilowo niedostępny.',saving:'ZAPISYWANIE…',saved:'ZAPISANO',saveError:'OFFLINE / NIE ZAPISANO',conflict:'KONFLIKT ZAPISU',expired:'Sesja wygasła. Zaloguj się ponownie.',created:'Konto utworzone.',loggedIn:'Zalogowano.',loggedOut:'Wylogowano.'});
  function validate(form,values){const password=String(values.password||'');if(form==='login'){const identifier=String(values.identifier||'').trim();if(!identifier)return MESSAGES.emptyIdentifier;if(identifier.includes('@')?(!EMAIL_PATTERN.test(identifier)||identifier.length>120):!LOGIN_PATTERN.test(identifier))return identifier.includes('@')?MESSAGES.invalidEmail:MESSAGES.invalidLogin}if(form==='register'){const login=String(values.login||'').trim(),email=String(values.email||'').trim();if(!login)return MESSAGES.emptyLogin;if(!LOGIN_PATTERN.test(login))return MESSAGES.invalidLogin;if(!email)return MESSAGES.emptyEmail;if(!EMAIL_PATTERN.test(email)||email.length>120)return MESSAGES.invalidEmail}if(!password)return MESSAGES.emptyPassword;if(password.length<8)return MESSAGES.shortPassword;if(password.length>128)return MESSAGES.longPassword;return''}
  function snapshot(storage){return Object.fromEntries(ACCOUNT_PROGRESS_KEYS.flatMap(key=>{const value=storage.getItem(key);return value===null?[]:[[key,value]]}))}
  function applyProgress(storage,progress){for(const key of ACCOUNT_PROGRESS_KEYS)storage.removeItem(key);for(const[key,value]of Object.entries(progress||{}))if(ACCOUNT_PROGRESS_KEY_SET.has(key)&&typeof value==='string')storage.setItem(key,value)}
  class SyncController{
    constructor({send,getSnapshot,onState,onConflict,onExpired,retryDelay=4000,setTimer=setTimeout,clearTimer=clearTimeout}){this.send=send;this.getSnapshot=getSnapshot;this.onState=onState||(()=>{});this.onConflict=onConflict||(()=>{});this.onExpired=onExpired||(()=>{});this.retryDelay=retryDelay;this.setTimer=setTimer;this.clearTimer=clearTimer;this.revision=0;this.inFlight=false;this.dirty=false;this.enabled=false;this.retryTimer=null}
    initialize(revision){this.revision=revision;this.enabled=true}
    markDirty(){if(!this.enabled)return;this.dirty=true;if(this.retryTimer){this.clearTimer(this.retryTimer);this.retryTimer=null}if(!this.inFlight)this.flush()}
    retryNow(){if(!this.enabled||!this.dirty)return;if(this.retryTimer){this.clearTimer(this.retryTimer);this.retryTimer=null}if(!this.inFlight)this.flush()}
    scheduleRetry(){if(this.retryTimer||!this.enabled)return;this.retryTimer=this.setTimer(()=>{this.retryTimer=null;this.retryNow()},this.retryDelay)}
    async flush(){if(!this.enabled||this.inFlight||!this.dirty)return;this.dirty=false;this.inFlight=true;this.onState('saving');const progress=this.getSnapshot(),expectedRevision=this.revision;try{const result=await this.send(progress,expectedRevision);this.revision=result.revision;this.onState('saved')}catch(error){if(error.code==='REVISION_CONFLICT'){this.enabled=false;this.onState('conflict');this.onConflict(error)}else if(error.code==='SESSION_EXPIRED'){this.enabled=false;this.onState('expired');this.onExpired(error)}else{this.dirty=true;this.onState('error');this.scheduleRetry()}}finally{this.inFlight=false;if(this.enabled&&this.dirty&&!this.retryTimer)this.flush()}}
  }
  function start(window){
    const document=window.document,storage=window.localStorage,overlay=document.getElementById('accountModal'),forms=[...overlay.querySelectorAll('.account-form')],message=document.getElementById('accountMessage'),identity=document.getElementById('accountIdentity'),status=identity.querySelector('b'),loginLabel=identity.querySelector('small');let user=null,applying=false,syncTimer=0;
    function showMessage(text,type='error'){message.textContent=text;message.dataset.type=type}
    function showStatus(state){const map={saving:MESSAGES.saving,saved:MESSAGES.saved,error:MESSAGES.saveError,conflict:MESSAGES.conflict,expired:MESSAGES.saveError};status.textContent=map[state]||MESSAGES.saveError;identity.dataset.state=state}
    async function api(route,options={}){let response;try{response=await window.fetch(`/api/account/${route}`,{credentials:'same-origin',headers:{'content-type':'application/json'},...options})}catch{const error=new Error(window.navigator.onLine===false?MESSAGES.network:MESSAGES.server);error.code=window.navigator.onLine===false?'NETWORK_OFFLINE':'SERVER_UNAVAILABLE';throw error}const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.code==='SESSION_EXPIRED'?MESSAGES.expired:data.code==='ACCOUNT_TAKEN'?MESSAGES.taken:data.code==='INVALID_CREDENTIALS'?MESSAGES.credentials:data.code==='REVISION_CONFLICT'?MESSAGES.conflict:response.status>=500?MESSAGES.server:(data.error||MESSAGES.server));error.code=data.code||'REQUEST_FAILED';error.revision=data.revision;throw error}return data}
    const sync=new SyncController({send:(progress,expectedRevision)=>api('progress',{method:'PUT',body:JSON.stringify({progress,expectedRevision})}),getSnapshot:()=>snapshot(storage),onState:showStatus,onConflict:()=>showMessage('Konflikt zapisu: nowszy postęp istnieje na innym urządzeniu.'),onExpired:()=>{showMessage(MESSAGES.expired);document.body.classList.add('account-locked');overlay.classList.remove('hidden')}});
    window.addEventListener('online',()=>sync.retryNow());
    function apply(data,notice){applying=true;applyProgress(storage,data.progress);applying=false;user=data.user;sync.initialize(data.revision);loginLabel.textContent=user.login;showStatus('saved');identity.classList.remove('hidden');overlay.classList.add('hidden');document.body.classList.remove('account-locked');window.sessionStorage.setItem('swarmfall-account-notice',notice);window.sessionStorage.setItem('swarmfall-cloud-loaded',`${user.login}:${data.revision}`);window.location.reload()}
    function switchForm(name){forms.forEach(form=>form.classList.toggle('hidden',form.dataset.form!==name));overlay.querySelectorAll('[data-account-tab]').forEach(button=>button.classList.toggle('active',button.dataset.accountTab===name));showMessage('')}
    const nativeSet=window.Storage.prototype.setItem,nativeRemove=window.Storage.prototype.removeItem;
    window.Storage.prototype.setItem=function(key,value){nativeSet.call(this,key,value);if(this===storage&&!applying&&ACCOUNT_PROGRESS_KEY_SET.has(String(key))){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync.markDirty(),350)}};
    window.Storage.prototype.removeItem=function(key){nativeRemove.call(this,key);if(this===storage&&!applying&&ACCOUNT_PROGRESS_KEY_SET.has(String(key))){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync.markDirty(),350)}};
    overlay.querySelectorAll('[data-account-tab]').forEach(button=>button.onclick=()=>switchForm(button.dataset.accountTab));
    forms.forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const kind=form.dataset.form,submit=form.querySelector('[type=submit]'),values=Object.fromEntries(new window.FormData(form)),validation=validate(kind,values);if(validation)return showMessage(validation);submit.disabled=true;showMessage(kind==='register'?'Tworzenie konta…':'Logowanie…','info');try{const data=await api(kind==='register'?'register':'login',{method:'POST',body:JSON.stringify(values)});apply(data,kind==='register'?MESSAGES.created:MESSAGES.loggedIn)}catch(error){showMessage(error.message)}finally{submit.disabled=false}}));
    document.getElementById('accountLogoutBtn').onclick=async()=>{if(sync.dirty)await sync.flush();await api('logout',{method:'POST',body:'{}'}).catch(()=>{});user=null;window.sessionStorage.removeItem('swarmfall-cloud-loaded');window.sessionStorage.setItem('swarmfall-account-notice',MESSAGES.loggedOut);window.location.reload()};
    document.getElementById('customDialogClose').onclick=()=>document.getElementById('customDialog').classList.add('hidden');window.SwarmAccount={sync:()=>sync.markDirty(),dialog(text,title='INFORMACJA'){document.getElementById('customDialogTitle').textContent=title;document.getElementById('customDialogText').textContent=text;document.getElementById('customDialog').classList.remove('hidden')}};
    const notice=window.sessionStorage.getItem('swarmfall-account-notice');if(notice){window.SwarmAccount.dialog(notice,'KONTO');window.sessionStorage.removeItem('swarmfall-account-notice')}
    api('me').then(data=>{const marker=`${data.user.login}:${data.revision}`;if(window.sessionStorage.getItem('swarmfall-cloud-loaded')!==marker)return apply(data,notice||MESSAGES.loggedIn);user=data.user;sync.initialize(data.revision);loginLabel.textContent=user.login;showStatus('saved');identity.classList.remove('hidden');overlay.classList.add('hidden');document.body.classList.remove('account-locked')}).catch(error=>{showMessage(error.code==='SESSION_EXPIRED'?MESSAGES.expired:error.message);document.body.classList.add('account-locked');overlay.classList.remove('hidden')});
  }
  return{ACCOUNT_PROGRESS_KEYS,MESSAGES,validate,snapshot,applyProgress,SyncController,start};
});
