(function(root,factory){const i18n=typeof module==='object'&&module.exports?require('./i18n'):root.SwarmI18n,api=factory(i18n);if(typeof module==='object'&&module.exports)module.exports=api;else{root.SwarmAccountCore=api;api.start(root)}})(typeof globalThis!=='undefined'?globalThis:this,i18n=>{
  'use strict';
  const ACCOUNT_PROGRESS_KEYS=Object.freeze(['swarmfall-stats','swarmfall-achievements-v1','swarmfall-unlocked','swarmfall-modes','swarmfall-nightmare-cosmetic','swarmfall-save-v1','swarmfall-character','swarmfall-map','swarmfall-mode']);
  const ACCOUNT_PROGRESS_KEY_SET=new Set(ACCOUNT_PROGRESS_KEYS),LOGIN_PATTERN=/^[a-zA-Z0-9_.-]{3,24}$/,EMAIL_PATTERN=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const MESSAGE_KEYS=Object.freeze({emptyIdentifier:'errors.emptyIdentifier',emptyLogin:'errors.emptyLogin',invalidLogin:'errors.invalidLogin',emptyEmail:'errors.emptyEmail',invalidEmail:'errors.invalidEmail',emptyPassword:'errors.emptyPassword',shortPassword:'errors.shortPassword',longPassword:'errors.longPassword',taken:'errors.taken',credentials:'errors.credentials',network:'errors.network',server:'errors.server',saving:'account.saving',saved:'account.saved',saveError:'account.saveError',conflict:'account.conflict',expired:'errors.expired',loggedOut:'account.loggedOut'}),MESSAGES={};for(const[name,key]of Object.entries(MESSAGE_KEYS))Object.defineProperty(MESSAGES,name,{enumerable:true,get:()=>i18n.t(key)});Object.freeze(MESSAGES);
  function validate(form,values){const password=String(values.password||'');if(form==='login'){const identifier=String(values.identifier||'').trim();if(!identifier)return MESSAGES.emptyIdentifier;if(identifier.includes('@')?(!EMAIL_PATTERN.test(identifier)||identifier.length>120):!LOGIN_PATTERN.test(identifier))return identifier.includes('@')?MESSAGES.invalidEmail:MESSAGES.invalidLogin}if(form==='register'){const login=String(values.login||'').trim(),email=String(values.email||'').trim();if(!login)return MESSAGES.emptyLogin;if(!LOGIN_PATTERN.test(login))return MESSAGES.invalidLogin;if(!email)return MESSAGES.emptyEmail;if(!EMAIL_PATTERN.test(email)||email.length>120)return MESSAGES.invalidEmail}if(!password)return MESSAGES.emptyPassword;if(password.length<8)return MESSAGES.shortPassword;if(password.length>128)return MESSAGES.longPassword;return''}
  function snapshot(storage){return Object.fromEntries(ACCOUNT_PROGRESS_KEYS.flatMap(key=>{const value=storage.getItem(key);return value===null?[]:[[key,value]]}))}
  function applyProgress(storage,progress){for(const key of ACCOUNT_PROGRESS_KEYS)storage.removeItem(key);for(const[key,value]of Object.entries(progress||{}))if(ACCOUNT_PROGRESS_KEY_SET.has(key)&&typeof value==='string')storage.setItem(key,value)}
  function authFailureState(code){return code==='NOT_AUTHENTICATED'?{showLogin:true,message:''}:code==='SESSION_EXPIRED'?{showLogin:true,message:MESSAGES.expired}:{showLogin:false,message:null}}
  class SyncController{
    constructor({send,getSnapshot,onState,onConflict,onExpired,onReconcile,retryDelay=4000,setTimer=setTimeout,clearTimer=clearTimeout}){this.send=send;this.getSnapshot=getSnapshot;this.onState=onState||(()=>{});this.onConflict=onConflict||(()=>{});this.onExpired=onExpired||(()=>{});this.onReconcile=onReconcile||(()=>{});this.retryDelay=retryDelay;this.setTimer=setTimer;this.clearTimer=clearTimer;this.revision=0;this.inFlight=false;this.dirty=false;this.enabled=false;this.retryTimer=null}
    initialize(revision){this.revision=revision;this.enabled=true}
    markDirty(){if(!this.enabled)return;this.dirty=true;if(this.retryTimer){this.clearTimer(this.retryTimer);this.retryTimer=null}if(!this.inFlight)this.flush()}
    retryNow(){if(!this.enabled||!this.dirty)return;if(this.retryTimer){this.clearTimer(this.retryTimer);this.retryTimer=null}if(!this.inFlight)this.flush()}
    scheduleRetry(){if(this.retryTimer||!this.enabled)return;this.retryTimer=this.setTimer(()=>{this.retryTimer=null;this.retryNow()},this.retryDelay)}
    reconcile(update){if(!this.enabled||!Number.isSafeInteger(update?.revision)||update.revision<=this.revision)return false;this.revision=update.revision;this.onReconcile(update);return true}
    async flush(){if(!this.enabled||this.inFlight||!this.dirty)return;this.dirty=false;this.inFlight=true;this.onState('saving');const progress=this.getSnapshot(),expectedRevision=this.revision;try{const result=await this.send(progress,expectedRevision);this.revision=Math.max(this.revision,result.revision);this.onState('saved')}catch(error){if(error.code==='REVISION_CONFLICT'&&error.progress){this.reconcile({revision:error.revision,progress:error.progress});this.dirty=true}else if(error.code==='REVISION_CONFLICT'&&this.revision>=error.revision){this.dirty=true}else if(error.code==='REVISION_CONFLICT'){this.enabled=false;this.onState('conflict');this.onConflict(error)}else if(error.code==='SESSION_EXPIRED'){this.enabled=false;this.onState('expired');this.onExpired(error)}else{this.dirty=true;this.onState('error');this.scheduleRetry()}}finally{this.inFlight=false;if(this.enabled&&this.dirty&&!this.retryTimer)this.flush()}}
  }
  function start(window){
    const document=window.document,storage=window.localStorage,overlay=document.getElementById('accountModal'),forms=[...overlay.querySelectorAll('.account-form')],message=document.getElementById('accountMessage'),identity=document.getElementById('accountIdentity'),loginLabel=identity.querySelector('small');let user=null,applying=false,syncTimer=0;
    function showMessage(text,type='error'){message.textContent=text;message.dataset.type=type}
    function showStatus(state){identity.dataset.state=state}
    async function api(route,options={}){let response;try{response=await window.fetch(`/api/account/${route}`,{credentials:'same-origin',headers:{'content-type':'application/json'},...options})}catch{const error=new Error(window.navigator.onLine===false?MESSAGES.network:MESSAGES.server);error.code=window.navigator.onLine===false?'NETWORK_OFFLINE':'SERVER_UNAVAILABLE';throw error}const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.code==='SESSION_EXPIRED'?MESSAGES.expired:data.code==='ACCOUNT_TAKEN'?MESSAGES.taken:data.code==='INVALID_CREDENTIALS'?MESSAGES.credentials:data.code==='REVISION_CONFLICT'?MESSAGES.conflict:response.status>=500?MESSAGES.server:(data.error||MESSAGES.server));error.code=data.code||'REQUEST_FAILED';error.revision=data.revision;error.progress=data.progress;throw error}return data}
    const sync=new SyncController({send:(progress,expectedRevision)=>api('progress',{method:'PUT',body:JSON.stringify({progress,expectedRevision})}),getSnapshot:()=>snapshot(storage),onState:showStatus,onConflict:()=>showMessage(i18n.t('errors.conflictDetail')),onExpired:()=>showLogin(MESSAGES.expired),onReconcile:update=>{applying=true;for(const[key,value]of Object.entries(update.progress||{}))if(ACCOUNT_PROGRESS_KEY_SET.has(key)&&typeof value==='string')storage.setItem(key,value);applying=false;showStatus('saved');window.dispatchEvent(new CustomEvent('swarm-account-progress',{detail:update}))}});
    window.addEventListener('online',()=>sync.retryNow());
    function showLogin(error=''){overlay.classList.remove('auth-loading');overlay.setAttribute('aria-busy','false');switchForm('login');showMessage(error);document.body.classList.add('account-locked');overlay.classList.remove('hidden')}
    function apply(data){applying=true;applyProgress(storage,data.progress);applying=false;user=data.user;sync.initialize(data.revision);loginLabel.textContent=user.login;showStatus('saved');identity.classList.remove('hidden');overlay.classList.add('hidden');overlay.classList.remove('auth-loading');overlay.setAttribute('aria-busy','false');document.body.classList.remove('account-locked');window.sessionStorage.setItem('swarmfall-cloud-loaded',`${user.login}:${data.revision}`);window.location.reload()}
    function switchForm(name){forms.forEach(form=>form.classList.toggle('hidden',form.dataset.form!==name));overlay.querySelectorAll('[data-account-tab]').forEach(button=>button.classList.toggle('active',button.dataset.accountTab===name));showMessage('')}
    const nativeSet=window.Storage.prototype.setItem,nativeRemove=window.Storage.prototype.removeItem;
    window.Storage.prototype.setItem=function(key,value){nativeSet.call(this,key,value);if(this===storage&&!applying&&ACCOUNT_PROGRESS_KEY_SET.has(String(key))){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync.markDirty(),350)}};
    window.Storage.prototype.removeItem=function(key){nativeRemove.call(this,key);if(this===storage&&!applying&&ACCOUNT_PROGRESS_KEY_SET.has(String(key))){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync.markDirty(),350)}};
    overlay.querySelectorAll('[data-account-tab]').forEach(button=>button.onclick=()=>switchForm(button.dataset.accountTab));
    forms.forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const kind=form.dataset.form,submit=form.querySelector('[type=submit]'),values=Object.fromEntries(new window.FormData(form)),validation=validate(kind,values);if(validation)return showMessage(validation);submit.disabled=true;showMessage(i18n.t(kind==='register'?'account.creating':'account.loggingIn'),'info');try{apply(await api(kind==='register'?'register':'login',{method:'POST',body:JSON.stringify(values)}))}catch(error){showMessage(error.message)}finally{submit.disabled=false}}));
    document.getElementById('accountLogoutBtn').onclick=async()=>{if(sync.dirty)await sync.flush();await api('logout',{method:'POST',body:'{}'}).catch(()=>{});user=null;window.sessionStorage.removeItem('swarmfall-cloud-loaded');window.sessionStorage.setItem('swarmfall-account-notice',MESSAGES.loggedOut);window.location.reload()};
    document.getElementById('customDialogClose').onclick=()=>document.getElementById('customDialog').classList.add('hidden');window.SwarmAccount={sync:()=>sync.markDirty(),reconcileServerProgress:update=>sync.reconcile(update),dialog(text,title=i18n.t('account.info')){document.getElementById('customDialogTitle').textContent=title;document.getElementById('customDialogText').textContent=text;document.getElementById('customDialog').classList.remove('hidden')}};
    const notice=window.sessionStorage.getItem('swarmfall-account-notice');if(notice){window.SwarmAccount.dialog(notice,i18n.t('account.accountTitle'));window.sessionStorage.removeItem('swarmfall-account-notice')}
    api('me').then(data=>{const marker=`${data.user.login}:${data.revision}`;if(window.sessionStorage.getItem('swarmfall-cloud-loaded')!==marker)return apply(data);user=data.user;sync.initialize(data.revision);loginLabel.textContent=user.login;showStatus('saved');identity.classList.remove('hidden');overlay.classList.add('hidden');overlay.classList.remove('auth-loading');overlay.setAttribute('aria-busy','false');document.body.classList.remove('account-locked')}).catch(error=>{const failure=authFailureState(error.code);if(failure.showLogin)showLogin(failure.message);else{document.getElementById('accountLoading').querySelector('b').textContent=error.message;showStatus('error')}});
  }
  return{ACCOUNT_PROGRESS_KEYS,MESSAGES,validate,snapshot,applyProgress,authFailureState,SyncController,start};
});
