(function(root,factory){const node=typeof module==='object'&&module.exports,i18n=node?require('./i18n'):root.SwarmI18n,outbox=node?require('./progress-outbox'):root.SwarmProgressOutbox,api=factory(i18n,outbox);if(node)module.exports=api;else{root.SwarmAccountCore=api;api.start(root)}})(typeof globalThis!=='undefined'?globalThis:this,(i18n,outboxApi)=>{
  'use strict';
  const ACCOUNT_PROGRESS_KEYS=Object.freeze(['swarmfall-stats','swarmfall-achievements-v1','swarmfall-unlocked','swarmfall-modes','swarmfall-nightmare-cosmetic','swarmfall-save-v1','swarmfall-character','swarmfall-map','swarmfall-mode']);
  const ACCOUNT_PROGRESS_KEY_SET=new Set(ACCOUNT_PROGRESS_KEYS),LOGIN_PATTERN=/^[a-zA-Z0-9_.-]{3,24}$/,EMAIL_PATTERN=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const MESSAGE_KEYS=Object.freeze({emptyIdentifier:'errors.emptyIdentifier',emptyLogin:'errors.emptyLogin',invalidLogin:'errors.invalidLogin',emptyEmail:'errors.emptyEmail',invalidEmail:'errors.invalidEmail',emptyPassword:'errors.emptyPassword',shortPassword:'errors.shortPassword',longPassword:'errors.longPassword',taken:'errors.taken',credentials:'errors.credentials',network:'errors.network',server:'errors.server',saving:'account.saving',saved:'account.saved',saveError:'account.saveError',conflict:'account.conflict',expired:'errors.expired',loggedOut:'account.loggedOut'}),MESSAGES={};for(const[name,key]of Object.entries(MESSAGE_KEYS))Object.defineProperty(MESSAGES,name,{enumerable:true,get:()=>i18n.t(key)});Object.freeze(MESSAGES);
  function validateKey(form,values){const password=String(values.password||'');if(form==='login'){const identifier=String(values.identifier||'').trim();if(!identifier)return MESSAGE_KEYS.emptyIdentifier;if(identifier.includes('@')?(!EMAIL_PATTERN.test(identifier)||identifier.length>120):!LOGIN_PATTERN.test(identifier))return identifier.includes('@')?MESSAGE_KEYS.invalidEmail:MESSAGE_KEYS.invalidLogin}if(form==='register'){const login=String(values.login||'').trim(),email=String(values.email||'').trim();if(!login)return MESSAGE_KEYS.emptyLogin;if(!LOGIN_PATTERN.test(login))return MESSAGE_KEYS.invalidLogin;if(!email)return MESSAGE_KEYS.emptyEmail;if(!EMAIL_PATTERN.test(email)||email.length>120)return MESSAGE_KEYS.invalidEmail}if(!password)return MESSAGE_KEYS.emptyPassword;if(password.length<8)return MESSAGE_KEYS.shortPassword;if(password.length>128)return MESSAGE_KEYS.longPassword;return''}
  function validate(form,values){const key=validateKey(form,values);return key?i18n.t(key):''}
  function createMessageController(onRender,translate=i18n.t,subscribe=i18n.onChange){let current=null;const render=()=>onRender(current?current.key?translate(current.key,current.params):current.raw:'',current?.type||'error');const unsubscribe=subscribe(render);return{showKey(key,params={},type='error'){current={key,params,type};render()},showRaw(raw,type='error'){current={raw:String(raw||''),type};render()},clear(){current=null;render()},refresh:render,current:()=>current,destroy:unsubscribe}}
  function responseMessageKey(code,status){return code==='SESSION_EXPIRED'?MESSAGE_KEYS.expired:code==='ACCOUNT_TAKEN'?MESSAGE_KEYS.taken:code==='INVALID_CREDENTIALS'?MESSAGE_KEYS.credentials:code==='REVISION_CONFLICT'?MESSAGE_KEYS.conflict:status>=500?MESSAGE_KEYS.server:null}
  function snapshot(storage){return Object.fromEntries(ACCOUNT_PROGRESS_KEYS.flatMap(key=>{const value=storage.getItem(key);return value===null?[]:[[key,value]]}))}
  function applyProgress(storage,progress){let writes=0;for(const key of ACCOUNT_PROGRESS_KEYS){const next=typeof progress?.[key]==='string'?progress[key]:null,current=storage.getItem(key);if(next===current)continue;if(next===null)storage.removeItem(key);else storage.setItem(key,next);writes++}return writes}
  function enqueueProgress(outbox,type,payload){try{return Promise.resolve(outbox.enqueue(type,payload))}catch(error){return Promise.reject(error)}}
  function createRetryController({run,setTimer=setTimeout,clearTimer=clearTimeout,minDelay=5000,maxDelay=60000}){let timer=null,delay=minDelay;return{schedule(error){if(timer)return false;const wait=Math.min(maxDelay,Math.max(delay,Number(error?.retryAfterMs)||0));delay=Math.min(maxDelay,delay*2);timer=setTimer(()=>{timer=null;run()},wait);return true},reset(){delay=minDelay},cancel(){if(timer)clearTimer(timer);timer=null;delay=minDelay},expedite(){this.cancel();run()},state(){return{pending:Boolean(timer),delay}}}}
  function authFailureState(code){return code==='NOT_AUTHENTICATED'?{showLogin:true,message:''}:code==='SESSION_EXPIRED'?{showLogin:true,message:MESSAGES.expired}:{showLogin:false,message:null}}
  function initialSessionFailureState(error){const network=error?.code==='NETWORK_OFFLINE';return{titleKey:network?'account.networkUnavailableTitle':'account.serverUnavailableTitle',descriptionKey:network?'errors.network':'account.sessionCheckFailed'}}
  function createInitialSessionController({request,onChecking,onLogin,onError,onSuccess}){let inFlight=null;async function check(){if(inFlight)return inFlight;onChecking();inFlight=(async()=>{try{onSuccess(await request())}catch(error){if(error?.code==='NOT_AUTHENTICATED')onLogin(null);else if(error?.code==='SESSION_EXPIRED')onLogin({key:MESSAGE_KEYS.expired});else onError(initialSessionFailureState(error),error)}})();try{await inFlight}finally{inFlight=null}}return{check,retry:check,isPending:()=>Boolean(inFlight)}}
  class SyncController{
    constructor({send,getSnapshot,onState,onConflict,onExpired,onReconcile,retryDelay=4000,setTimer=setTimeout,clearTimer=clearTimeout}){this.send=send;this.getSnapshot=getSnapshot;this.onState=onState||(()=>{});this.onConflict=onConflict||(()=>{});this.onExpired=onExpired||(()=>{});this.onReconcile=onReconcile||(()=>{});this.retryDelay=retryDelay;this.setTimer=setTimer;this.clearTimer=clearTimer;this.revision=0;this.inFlight=false;this.dirty=false;this.enabled=false;this.retryTimer=null;this.idleWaiters=[]}
    initialize(revision){this.revision=revision;this.enabled=true}
    markDirty(){if(!this.enabled)return;this.dirty=true;if(this.retryTimer){this.clearTimer(this.retryTimer);this.retryTimer=null}if(!this.inFlight)this.flush()}
    retryNow(){if(!this.enabled||!this.dirty)return;if(this.retryTimer){this.clearTimer(this.retryTimer);this.retryTimer=null}if(!this.inFlight)this.flush()}
    scheduleRetry(){if(this.retryTimer||!this.enabled)return;this.retryTimer=this.setTimer(()=>{this.retryTimer=null;this.retryNow()},this.retryDelay)}
    reconcile(update){if(!this.enabled||!Number.isSafeInteger(update?.revision)||update.revision<=this.revision)return false;this.revision=update.revision;this.onReconcile(update);return true}
    async settlePending(){if(this.dirty&&!this.inFlight)void this.flush();if(this.inFlight)await new Promise(resolve=>this.idleWaiters.push(resolve));if(this.inFlight||this.dirty&&!this.retryTimer)return this.settlePending()}
    async flush(){if(!this.enabled||this.inFlight||!this.dirty)return;this.dirty=false;this.inFlight=true;this.onState('saving');const progress=this.getSnapshot(),expectedRevision=this.revision;try{const result=await this.send(progress,expectedRevision);if(result.progress)this.reconcile(result);else this.revision=Math.max(this.revision,result.revision);this.onState('saved')}catch(error){if(error.code==='REVISION_CONFLICT'&&error.progress){this.reconcile({revision:error.revision,progress:error.progress});this.dirty=true}else if(error.code==='REVISION_CONFLICT'&&this.revision>=error.revision){this.dirty=true}else if(error.code==='REVISION_CONFLICT'){this.enabled=false;this.onState('conflict');this.onConflict(error)}else if(error.code==='SESSION_EXPIRED'){this.enabled=false;this.onState('expired');this.onExpired(error)}else{this.dirty=true;this.onState('error');this.scheduleRetry()}}finally{this.inFlight=false;for(const resolve of this.idleWaiters.splice(0))resolve();if(this.enabled&&this.dirty&&!this.retryTimer)this.flush()}}
  }
  function start(window){
    const document=window.document,storage=window.localStorage,overlay=document.getElementById('accountModal'),forms=[...overlay.querySelectorAll('.account-form')],message=document.getElementById('accountMessage'),identity=document.getElementById('accountIdentity'),loginLabel=identity.querySelector('small'),initialError=document.getElementById('accountInitialError'),initialErrorTitle=document.getElementById('accountInitialErrorTitle'),initialErrorText=document.getElementById('accountInitialErrorText'),initialRetry=document.getElementById('accountInitialRetry');let user=null,applying=false,syncTimer=0,initialErrorState=null;
    const messages=createMessageController((text,type)=>{message.textContent=text;message.dataset.type=type});
    function showStatus(state){identity.dataset.state=state}
    function renderInitialError(){if(!initialErrorState)return;initialErrorTitle.textContent=i18n.t(initialErrorState.titleKey);initialErrorText.textContent=i18n.t(initialErrorState.descriptionKey)}
    i18n.onChange(renderInitialError);
    function showAccountChecking(){initialErrorState=null;initialError.classList.add('hidden');overlay.classList.remove('account-initial-error-active','hidden');overlay.classList.add('auth-loading');overlay.setAttribute('aria-busy','true');document.body.classList.add('account-locked')}
    function showAccountInitialError(state){initialErrorState=state;renderInitialError();initialError.classList.remove('hidden');overlay.classList.remove('auth-loading','hidden');overlay.classList.add('account-initial-error-active');overlay.setAttribute('aria-busy','false');document.body.classList.add('account-locked')}
    async function api(route,options={}){let response;try{response=await window.fetch(`/api/account/${route}`,{credentials:'same-origin',headers:{'content-type':'application/json'},...options})}catch{const offline=window.navigator.onLine===false,error=new Error(i18n.t(offline?MESSAGE_KEYS.network:MESSAGE_KEYS.server));error.code=offline?'NETWORK_OFFLINE':'SERVER_UNAVAILABLE';error.messageKey=offline?MESSAGE_KEYS.network:MESSAGE_KEYS.server;throw error}const data=await response.json().catch(()=>({}));if(!response.ok){const messageKey=responseMessageKey(data.code,response.status),error=new Error(messageKey?i18n.t(messageKey):(data.error||MESSAGES.server));error.code=data.code||'REQUEST_FAILED';error.status=response.status;const retryAfter=response.headers?.get?.('retry-after');if(retryAfter){const seconds=Number(retryAfter),date=Date.parse(retryAfter);error.retryAfterMs=Math.min(60000,Math.max(1000,Number.isFinite(seconds)?seconds*1000:Number.isFinite(date)?date-Date.now():0))}error.messageKey=messageKey;error.revision=data.revision;error.progress=data.progress;throw error}return data}
    const sync=new SyncController({send:(progress,expectedRevision)=>api('progress',{method:'PUT',body:JSON.stringify({progress,expectedRevision})}),getSnapshot:()=>snapshot(storage),onState:showStatus,onConflict:()=>messages.showKey('errors.conflictDetail'),onExpired:()=>showLogin({key:MESSAGE_KEYS.expired}),onReconcile:update=>{applying=true;applyProgress(storage,update.progress);applying=false;showStatus('saved');window.dispatchEvent(new CustomEvent('swarm-account-progress',{detail:update}))}});
    let operationOutbox=null;const operationRetry=createRetryController({run:()=>void operationOutbox?.drain()});
    function ensureOutbox(){if(operationOutbox)return operationOutbox;if(!user?.id)throw new Error('Authenticated account id is required');const legacyKey=`${outboxApi.DEFAULT_KEY}:undefined`;if(storage.getItem(legacyKey)!==null)storage.removeItem(legacyKey);operationOutbox=outboxApi.createAndDrain({storage,accountId:user.id,createId:()=>window.crypto.randomUUID(),getRevision:()=>sync.revision,send:async operation=>{await sync.settlePending();return api('progression',{method:'POST',body:JSON.stringify({expectedRevision:sync.revision,operation})})},reconcile:update=>sync.reconcile(update),onRetryable:error=>operationRetry.schedule(error),onSuccess:()=>operationRetry.reset(),onAuth:error=>{operationRetry.cancel();showLogin(error.code==='SESSION_EXPIRED'?{key:MESSAGE_KEYS.expired}:null)}});return operationOutbox}
    window.addEventListener('online',()=>{sync.retryNow();operationRetry.expedite()});
    function showLogin(error=null){initialErrorState=null;initialError.classList.add('hidden');overlay.classList.remove('auth-loading','account-initial-error-active');overlay.setAttribute('aria-busy','false');switchForm('login');if(error?.key)messages.showKey(error.key,error.params||{},error.type);else if(error)messages.showRaw(error);document.body.classList.add('account-locked');overlay.classList.remove('hidden')}
    function apply(data){applying=true;applyProgress(storage,data.progress);applying=false;user=data.user;sync.initialize(data.revision);ensureOutbox();loginLabel.textContent=user.login;showStatus('saved');identity.classList.remove('hidden');initialErrorState=null;initialError.classList.add('hidden');overlay.classList.add('hidden');overlay.classList.remove('auth-loading','account-initial-error-active');overlay.setAttribute('aria-busy','false');document.body.classList.remove('account-locked');window.sessionStorage.setItem('swarmfall-cloud-loaded',`${user.login}:${data.revision}`);window.location.reload()}
    function switchForm(name){forms.forEach(form=>form.classList.toggle('hidden',form.dataset.form!==name));overlay.querySelectorAll('[data-account-tab]').forEach(button=>button.classList.toggle('active',button.dataset.accountTab===name));messages.clear()}
    const nativeSet=window.Storage.prototype.setItem,nativeRemove=window.Storage.prototype.removeItem;
    window.Storage.prototype.setItem=function(key,value){nativeSet.call(this,key,value);if(this===storage&&!applying&&ACCOUNT_PROGRESS_KEY_SET.has(String(key))){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync.markDirty(),350)}};
    window.Storage.prototype.removeItem=function(key){nativeRemove.call(this,key);if(this===storage&&!applying&&ACCOUNT_PROGRESS_KEY_SET.has(String(key))){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync.markDirty(),350)}};
    overlay.querySelectorAll('[data-account-tab]').forEach(button=>button.onclick=()=>switchForm(button.dataset.accountTab));
    forms.forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const kind=form.dataset.form,submit=form.querySelector('[type=submit]'),values=Object.fromEntries(new window.FormData(form)),validation=validateKey(kind,values);if(validation)return messages.showKey(validation);submit.disabled=true;messages.showKey(kind==='register'?'account.creating':'account.loggingIn',{},'info');try{apply(await api(kind==='register'?'register':'login',{method:'POST',body:JSON.stringify(values)}))}catch(error){if(error.messageKey)messages.showKey(error.messageKey);else messages.showRaw(error.message)}finally{submit.disabled=false}}));
    document.getElementById('accountLogoutBtn').onclick=async()=>{if(sync.dirty)await sync.flush();await api('logout',{method:'POST',body:'{}'}).catch(()=>{});user=null;operationOutbox?.cancel();operationOutbox=null;operationRetry.cancel();window.sessionStorage.removeItem('swarmfall-cloud-loaded');window.sessionStorage.setItem('swarmfall-account-notice',MESSAGE_KEYS.loggedOut);window.location.reload()};
    function progress(type,payload={}){try{return enqueueProgress(ensureOutbox(),type,payload)}catch(error){return Promise.reject(error)}}
    document.getElementById('customDialogClose').onclick=()=>document.getElementById('customDialog').classList.add('hidden');window.SwarmAccount={sync:()=>sync.markDirty(),progress,reconcileServerProgress:update=>sync.reconcile(update),dialog(text,title=i18n.t('account.info')){document.getElementById('customDialogTitle').textContent=title;document.getElementById('customDialogText').textContent=text;document.getElementById('customDialog').classList.remove('hidden')}};
    const notice=window.sessionStorage.getItem('swarmfall-account-notice');if(notice){window.SwarmAccount.dialog(i18n.has(notice)?i18n.t(notice):notice,i18n.t('account.accountTitle'));window.sessionStorage.removeItem('swarmfall-account-notice')}
    const initialSession=createInitialSessionController({request:()=>api('me'),onChecking:showAccountChecking,onLogin:showLogin,onError:showAccountInitialError,onSuccess:data=>{const marker=`${data.user.login}:${data.revision}`;if(window.sessionStorage.getItem('swarmfall-cloud-loaded')!==marker)return apply(data);user=data.user;sync.initialize(data.revision);ensureOutbox();loginLabel.textContent=user.login;showStatus('saved');identity.classList.remove('hidden');initialErrorState=null;initialError.classList.add('hidden');overlay.classList.add('hidden');overlay.classList.remove('auth-loading','account-initial-error-active');overlay.setAttribute('aria-busy','false');document.body.classList.remove('account-locked')}});initialRetry.onclick=()=>initialSession.retry();initialSession.check();
  }
  return{ACCOUNT_PROGRESS_KEYS,MESSAGES,enqueueProgress,createRetryController,validateKey,validate,createMessageController,responseMessageKey,snapshot,applyProgress,authFailureState,initialSessionFailureState,createInitialSessionController,SyncController,start};
});
