'use strict';
const fs = require('node:fs/promises'),
  path = require('node:path'),
  crypto = require('node:crypto');

const ACCOUNT_PROGRESS_KEYS = Object.freeze([
  'swarmfall-stats',
  'swarmfall-achievements-v1',
  'swarmfall-unlocked',
  'swarmfall-modes',
  'swarmfall-nightmare-cosmetic',
  'swarmfall-save-v1',
  'swarmfall-character',
  'swarmfall-map',
  'swarmfall-mode',
]);
const ACCOUNT_PROGRESS_KEY_SET=new Set(ACCOUNT_PROGRESS_KEYS);
const SERVER_PROGRESS_KEYS=new Set(['swarmfall-stats','swarmfall-achievements-v1','swarmfall-unlocked','swarmfall-modes','swarmfall-nightmare-cosmetic']);
const ACHIEVEMENT_IDS=new Set(['field_guide','boss_1','boss_2','boss_3','map_1','item_6','hard_clear','nightmare_clear']);
const ACHIEVEMENT_REWARDS={field_guide:3,boss_1:5,boss_2:10,boss_3:15,map_1:5,item_6:15,hard_clear:15,nightmare_clear:30};
const CHARACTER_COSTS={warrior:25,druid:30};
const MODE_IDS=new Set(['normal','hard','nightmare','endless']);

function emptyDatabase(){return{users:[],sessions:{}}}
function validDatabase(value){return Boolean(value&&Array.isArray(value.users)&&value.sessions&&typeof value.sessions==='object'&&!Array.isArray(value.sessions))}
function normalizeLogin(value){return String(value||'').trim().toLowerCase()}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(error,key)=>error?reject(error):resolve({salt,hash:key.toString('hex')})))}
function passwordMatches(password,user){return new Promise(resolve=>crypto.scrypt(password,user.passwordSalt,64,(error,key)=>{if(error)return resolve(false);try{resolve(crypto.timingSafeEqual(Buffer.from(user.passwordHash,'hex'),key))}catch{resolve(false)}}))}
function cleanProgress(progress){const cleaned=Object.fromEntries(Object.entries(progress||{}).filter(([key,value])=>ACCOUNT_PROGRESS_KEY_SET.has(key)&&typeof value==='string'&&value.length<800000));if(cleaned['swarmfall-stats'])cleaned['swarmfall-stats']=JSON.stringify(parseStats(cleaned['swarmfall-stats']));if(cleaned['swarmfall-achievements-v1'])cleaned['swarmfall-achievements-v1']=JSON.stringify(parseList(cleaned['swarmfall-achievements-v1'],ACHIEVEMENT_IDS));if(cleaned['swarmfall-unlocked'])cleaned['swarmfall-unlocked']=JSON.stringify(parseList(cleaned['swarmfall-unlocked'],new Set(Object.keys(CHARACTER_COSTS))));if(cleaned['swarmfall-modes'])cleaned['swarmfall-modes']=JSON.stringify(parseList(cleaned['swarmfall-modes'],MODE_IDS));if(cleaned['swarmfall-nightmare-cosmetic']!=='void-aura')delete cleaned['swarmfall-nightmare-cosmetic'];return cleaned}
function mergeClientProgress(current,incoming){const next=cleanProgress(incoming);for(const key of SERVER_PROGRESS_KEYS){if(Object.hasOwn(current||{},key))next[key]=current[key];else delete next[key]}return next}
const DEFAULT_STATS={bestTime:0,totalTime:0,bestKills:0,totalKills:0,coins:0,characterGames:{scout:0,warrior:0,druid:0}};
function parseStats(raw){let parsed={};try{parsed=JSON.parse(raw||'{}')}catch{}const number=key=>Number.isFinite(parsed[key])?Math.max(0,Math.floor(parsed[key])):0,games=parsed.characterGames||{};return{bestTime:number('bestTime'),totalTime:number('totalTime'),bestKills:number('bestKills'),totalKills:number('totalKills'),coins:number('coins'),characterGames:{scout:Number.isFinite(games.scout)?Math.max(0,Math.floor(games.scout)):0,warrior:Number.isFinite(games.warrior)?Math.max(0,Math.floor(games.warrior)):0,druid:Number.isFinite(games.druid)?Math.max(0,Math.floor(games.druid)):0}}}
function parseList(raw,allowed){let parsed=[];try{parsed=JSON.parse(raw||'[]')}catch{}return[...new Set(Array.isArray(parsed)?parsed.filter(value=>allowed.has(value)):[])]}
function writeStats(progress,stats){progress['swarmfall-stats']=JSON.stringify(stats)}
function progressionError(code){const error=new Error(code);error.code=code;return error}
function applyProgressOperation(progress,operation){progress=cleanProgress(progress);const type=operation?.type,payload=operation?.payload||{},stats=parseStats(progress['swarmfall-stats']),achievements=parseList(progress['swarmfall-achievements-v1'],ACHIEVEMENT_IDS),unlocked=parseList(progress['swarmfall-unlocked'],new Set(Object.keys(CHARACTER_COSTS))),modes=parseList(progress['swarmfall-modes'],MODE_IDS);
 if(type==='awardCurrency'){const amount=Math.floor(payload.amount);if(!Number.isFinite(amount)||amount<1||amount>100)throw progressionError('INVALID_PROGRESSION');stats.coins=Math.max(0,stats.coins)+amount;writeStats(progress,stats)}
 else if(type==='awardSingleplayerResult'){const time=Math.floor(payload.time),kills=Math.floor(payload.kills),character=String(payload.character||'scout');if(!Number.isFinite(time)||time<0||time>86400||!Number.isFinite(kills)||kills<0||kills>100000||!['scout','warrior','druid'].includes(character))throw progressionError('INVALID_PROGRESSION');stats.bestTime=Math.max(stats.bestTime,time);stats.totalTime=Math.max(0,stats.totalTime)+time;stats.bestKills=Math.max(stats.bestKills,kills);stats.totalKills=Math.max(0,stats.totalKills)+kills;stats.characterGames[character]=Math.max(0,stats.characterGames[character])+1;writeStats(progress,stats)}
 else if(type==='unlockAchievement'){const id=String(payload.id||'');if(!ACHIEVEMENT_IDS.has(id)||['map_1','hard_clear','nightmare_clear'].includes(id))throw progressionError('INVALID_PROGRESSION');if(!achievements.includes(id)){achievements.push(id);stats.coins=Math.max(0,stats.coins)+(ACHIEVEMENT_REWARDS[id]||0);progress['swarmfall-achievements-v1']=JSON.stringify(achievements);writeStats(progress,stats)}}
 else if(type==='purchaseCharacter'){const character=String(payload.character||''),cost=CHARACTER_COSTS[character];if(!cost)throw progressionError('INVALID_PROGRESSION');if(!unlocked.includes(character)){if(stats.coins<cost)throw progressionError('INSUFFICIENT_COINS');stats.coins-=cost;unlocked.push(character);progress['swarmfall-unlocked']=JSON.stringify(unlocked);writeStats(progress,stats)}}
 else if(type==='completeMap'){const map=String(payload.map||''),mode=String(payload.mode||'');if(!['ruins','toxic'].includes(map)||!MODE_IDS.has(mode)||map==='toxic'&&!achievements.includes('map_1')||mode==='hard'&&!modes.includes('normal')||mode==='nightmare'&&!modes.includes('hard')||mode==='endless'&&!modes.includes('normal'))throw progressionError('INVALID_PROGRESSION');if(!modes.includes(mode))modes.push(mode);progress['swarmfall-modes']=JSON.stringify(modes);const earned=[map==='ruins'?'map_1':null,mode==='hard'?'hard_clear':mode==='nightmare'?'nightmare_clear':null].filter(Boolean);for(const id of earned)if(!achievements.includes(id)){achievements.push(id);stats.coins+=ACHIEVEMENT_REWARDS[id]}if(earned.length){progress['swarmfall-achievements-v1']=JSON.stringify(achievements);writeStats(progress,stats)}if(mode==='nightmare')progress['swarmfall-nightmare-cosmetic']='void-aura'}
 else throw progressionError('INVALID_PROGRESSION');return progress}
function mergeMultiplayerStats(raw,result){let parsed={};try{parsed=JSON.parse(raw||'{}')}catch{}const stats={...DEFAULT_STATS,...parsed,characterGames:{...DEFAULT_STATS.characterGames,...parsed.characterGames}},time=Math.max(0,Math.floor(result.time||0)),kills=Math.max(0,Math.floor(result.kills||0)),coins=Math.max(0,Math.floor(result.coins||0)),character=['scout','warrior','druid'].includes(result.character)?result.character:'scout';stats.bestTime=Math.max(stats.bestTime||0,time);stats.totalTime=Math.max(0,stats.totalTime||0)+time;stats.bestKills=Math.max(stats.bestKills||0,kills);stats.totalKills=Math.max(0,stats.totalKills||0)+kills;stats.coins=Math.max(0,stats.coins||0)+coins;stats.characterGames[character]=Math.max(0,stats.characterGames[character]||0)+1;return JSON.stringify(stats)}

class AccountStore{
  constructor(file){this.file=file;this.data=null;this.queue=Promise.resolve()}
  async load(){if(this.data)return this.data;try{const raw=await fs.readFile(this.file,'utf8'),parsed=JSON.parse(raw);if(!validDatabase(parsed))throw new Error('Nieprawidłowa struktura bazy kont.');this.data=parsed;for(const user of this.data.users){user.progress=cleanProgress(user.progress);user.revision=Number.isSafeInteger(user.revision)&&user.revision>=0?user.revision:0}return this.data}catch(error){if(error.code==='ENOENT'){this.data=emptyDatabase();return this.data}const controlled=new Error('Baza kont jest uszkodzona lub niedostępna.');controlled.code='ACCOUNT_STORE_CORRUPTED';controlled.cause=error;throw controlled}}
  run(operation){const task=this.queue.then(async()=>operation(await this.load()));this.queue=task.catch(()=>{});return task}
  async persist(data){await fs.mkdir(path.dirname(this.file),{recursive:true});const temporary=`${this.file}.${process.pid}.${crypto.randomBytes(5).toString('hex')}.tmp`;await fs.writeFile(temporary,JSON.stringify(data));await fs.rename(temporary,this.file)}
  read(operation){return this.run(data=>operation(data))}
  mutate(operation){return this.run(async data=>{const draft=structuredClone(data),result=await operation(draft);await this.persist(draft);this.data=draft;return result})}
  accountForToken(token){if(!token)return Promise.resolve(null);const key=crypto.createHash('sha256').update(token).digest('hex');return this.read(data=>{const session=data.sessions[key];if(!session||session.expiresAt<Date.now())return null;const user=data.users.find(candidate=>candidate.id===session.userId);return user?{id:user.id,login:user.login,progress:cleanProgress(user.progress)}:null})}
  applySingleplayerOperation(userId,expectedRevision,operation){return this.mutate(data=>{const user=data.users.find(candidate=>candidate.id===userId);if(!user)throw progressionError('ACCOUNT_MISSING');const revision=user.revision||0,id=String(operation?.id||'');if(!/^[a-zA-Z0-9_-]{8,80}$/.test(id))throw progressionError('INVALID_PROGRESSION');user.appliedOperations=Array.isArray(user.appliedOperations)?user.appliedOperations:[];if(user.appliedOperations.includes(id))return{saved:true,duplicate:true,revision,progress:cleanProgress(user.progress)};if(expectedRevision!==revision){const error=progressionError('REVISION_CONFLICT');error.revision=revision;error.progress=cleanProgress(user.progress);throw error}user.progress=applyProgressOperation(user.progress,operation);user.appliedOperations.push(id);user.appliedOperations=user.appliedOperations.slice(-2000);user.revision=revision+1;user.lastRevisionKind='singleplayer-operation';return{saved:true,revision:user.revision,progress:cleanProgress(user.progress)}})}
  settleMultiplayerMatch(userId,matchId,result){return this.mutate(data=>{const user=data.users.find(candidate=>candidate.id===userId);if(!user)return{applied:false,reason:'account-missing'};user.settledMatches=Array.isArray(user.settledMatches)?user.settledMatches:[];const settlementKey=`${matchId}:${result.playerId}`;if(user.settledMatches.includes(settlementKey))return{applied:false,reason:'duplicate',revision:user.revision||0};user.progress=cleanProgress(user.progress);user.progress['swarmfall-stats']=mergeMultiplayerStats(user.progress['swarmfall-stats'],result);user.settledMatches.push(settlementKey);user.settledMatches=user.settledMatches.slice(-1000);user.revision=(user.revision||0)+1;user.lastRevisionKind='multiplayer-settlement';return{applied:true,revision:user.revision,progress:user.progress}})}
}

module.exports={AccountStore,ACCOUNT_PROGRESS_KEYS,ACCOUNT_PROGRESS_KEY_SET,SERVER_PROGRESS_KEYS,ACHIEVEMENT_IDS,CHARACTER_COSTS,normalizeLogin,hashPassword,passwordMatches,cleanProgress,mergeClientProgress,applyProgressOperation,mergeMultiplayerStats};
