(function(root){
  'use strict';
  const delays=[0,500,1500,3000];let generation=0;
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function imageReady(image){return Boolean(image?.complete&&image.naturalWidth>0)}
  async function load(entry,manual=false){if(entry.ready())return true;for(const delay of(manual?[0]:delays)){if(delay)await sleep(delay);if(entry.ready())return true;const image=entry.image;if(image&&image.complete&&!image.naturalWidth)image.src=image.src;try{await image?.decode?.()}catch{}if(entry.ready())return true}throw new Error(entry.label)}
  function collect({map,character,characters=[],menu=false}){const entries=[],seen=new Set();const add=(label,image,ready=()=>imageReady(image),kind='image')=>{if(!seen.has(label)){seen.add(label);entries.push({label,image,ready,kind})}};const heroes=root.SwarmHeroAssets;if(menu)for(const id of['scout','warrior','druid'])add(`${id} portrait`,heroes?.[id]?.images?.portrait,()=>imageReady(heroes?.[id]?.images?.portrait));for(const id of new Set([character,...characters].filter(Boolean))){const group=heroes?.[id];for(const[key,image]of Object.entries(group?.images||{})){add(`${id} ${key}`,image);if(id==='druid'&&key.endsWith('Effect'))add(`${id} ${key} prepared`,null,()=>Boolean(group.prepared?.(key)),'derived')}}if(map==='ruins'){for(const[key,entry]of Object.entries(root.SwarmMapVisuals?._assetState||{}))add(`ruins ${key}`,entry.image,()=>entry.ready&&imageReady(entry.image));add('ruins preview',null,()=>Boolean(root.SwarmMapVisuals?.getRuinsStaticPreview?.()),'derived')}const sheets=root.enemySpriteVisuals?.sheets||{},manifest=root.enemySpriteVisuals?.requiredByMap?.[map]||[];for(const type of manifest)for(const[name,entry]of Object.entries(sheets[type]||{}))add(`${type} ${name}`,entry.image,()=>entry.loaded&&imageReady(entry.image));return entries}
  async function waitForRequired(spec,{onProgress=()=>{},manual=false,token=++generation}={}){const entries=collect(spec),images=entries.filter(entry=>entry.kind==='image'),derived=entries.filter(entry=>entry.kind==='derived'),total=entries.length;let completed=entries.filter(entry=>entry.ready()).length;const report=status=>onProgress({completed,total,progress:total?completed/total:1,status});report('loading');const pending=images.filter(entry=>!entry.ready()).map(entry=>load(entry,manual).then(()=>{completed++;report('loading')}));const results=await Promise.allSettled(pending);if(token!==generation)throw Object.assign(new Error('cancelled'),{cancelled:true});if(results.some(result=>result.status==='rejected')){report('failed');throw new Error('required assets failed')}for(const entry of derived){if(!entry.ready()){report('failed');throw new Error(`derived asset failed: ${entry.label}`)}if(completed<total){completed++;report('loading')}}report('ready');return{token,total}}
  function cancel(){generation++}
  root.SwarmAssets={collect,waitForRequired,retryFailed:(spec,options)=>waitForRequired(spec,{...options,manual:true}),cancel,get generation(){return generation}};
})(window);
