(function(root){
  'use strict';
  const delays=[0,500,1500,3000];let generation=0;
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function imageReady(image){return Boolean(image?.complete&&image.naturalWidth>0)}
  async function load(entry,onSettled,manual=false){if(entry.ready())return true;for(const delay of(manual?[0]:delays)){if(delay)await sleep(delay);if(entry.ready())return true;const image=entry.image;if(image&&image.complete&&!image.naturalWidth)image.src=image.src;try{await image?.decode?.()}catch{}if(entry.ready())return true}onSettled?.();throw new Error(entry.label)}
  function collect({map,character,menu=false}){const entries=[];const add=(label,image,ready=()=>imageReady(image))=>entries.push({label,image,ready});const heroes=root.SwarmHeroAssets;if(menu)for(const id of['scout','warrior','druid'])add(`${id} portrait`,heroes?.[id]?.images?.portrait,()=>imageReady(heroes?.[id]?.images?.portrait));if(character){const group=heroes?.[character];for(const[key,image]of Object.entries(group?.images||{}))add(`${character} ${key}`,image,()=>imageReady(image)&&(character!=='druid'||!key.endsWith('Effect')||group.prepared?.(key)))}if(map==='ruins'){for(const[key,entry]of Object.entries(root.SwarmMapVisuals?._assetState||{}))add(`ruins ${key}`,entry.image,()=>entry.ready&&imageReady(entry.image));entries.push({label:'ruins preview',image:null,ready:()=>Boolean(root.SwarmMapVisuals?.getRuinsStaticPreview?.())})}for(const[type,names]of Object.entries(root.enemySpriteVisuals?.sheets||{}))for(const[name,entry]of Object.entries(names))add(`${type} ${name}`,entry.image,()=>entry.loaded&&imageReady(entry.image));return entries}
  async function waitForRequired(spec,{onProgress=()=>{},manual=false,token=++generation}={}){const entries=collect(spec),total=entries.length;let completed=entries.filter(entry=>entry.ready()).length;onProgress({completed,total,progress:total?completed/total:1,status:'loading'});const pending=entries.filter(entry=>!entry.ready()).map(entry=>load(entry,()=>{},manual).then(()=>{completed++;onProgress({completed,total,progress:completed/total,status:'loading'})}));const results=await Promise.allSettled(pending);if(token!==generation)throw Object.assign(new Error('cancelled'),{cancelled:true});const failed=results.filter(result=>result.status==='rejected');if(failed.length){onProgress({completed,total,progress:completed/total,status:'failed'});throw new Error('required assets failed')}onProgress({completed:total,total,progress:1,status:'ready'});return{token,total}}
  function cancel(){generation++}
  root.SwarmAssets={collect,waitForRequired,retryFailed:(spec,options)=>waitForRequired(spec,{...options,manual:true}),cancel,get generation(){return generation}};
})(window);
