const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const ui = Object.fromEntries(['timer','kills','level','healthText','healthBar','xpLevel','xpText','xpBar','slots','cards','startModal','levelModal','endModal','newLevel','endStats'].map(id=>[id,document.getElementById(id)]));
let W=0,H=0,dpr=1,last=0,running=false,paused=true,elapsed=0,spawnClock=0,shotClock=0,screenShake=0;
const keys={}, mouse={x:innerWidth*.7,y:innerHeight*.5};
const player={x:innerWidth/2,y:innerHeight/2,r:15,speed:250,hp:100,maxHp:100,xp:0,level:1,nextXp:24,kills:0,invuln:0};
let enemies=[],bullets=[],orbs=[],particles=[],rings=[];
const skills={q:{cd:0,max:5},e:{cd:0,max:9},r:{cd:0,max:28}};
const upgrades=[
  {id:'power',name:'Nadprzewodnik',icon:'ϟ',desc:'+25% obrażeń pocisków',color:'#51f6df'},
  {id:'rapid',name:'Nadpisanie',icon:'»',desc:'+18% szybkości ataku',color:'#4cc8ff'},
  {id:'speed',name:'Faza kinetyczna',icon:'◇',desc:'+12% prędkości ruchu',color:'#a06cff'},
  {id:'vital',name:'Rdzeń życia',icon:'♥',desc:'+20 maks. życia i leczenie',color:'#ff6688'},
  {id:'multi',name:'Rozszczepienie',icon:'Ψ',desc:'+1 dodatkowy pocisk',color:'#ffd467'},
  {id:'magnet',name:'Polaryzacja',icon:'⊙',desc:'+45% zasięgu zbierania',color:'#6df59d'},
  {id:'crit',name:'Pęknięcie',icon:'✦',desc:'+10% szansy na cios krytyczny',color:'#ff9657'}
];
const levels={};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;const c=document.querySelector('#crosshair');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'});
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(!paused&&['q','e','r'].includes(e.key.toLowerCase()))cast(e.key.toLowerCase())});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelector('#startBtn').onclick=start;document.querySelector('#restartBtn').onclick=()=>location.reload();
function start(){ui.startModal.classList.add('hidden');running=true;paused=false;last=performance.now();requestAnimationFrame(loop)}
function spawnEnemy(){const edge=Math.floor(Math.random()*4),pad=50;let x,y;if(edge===0){x=Math.random()*W;y=-pad}else if(edge===1){x=W+pad;y=Math.random()*H}else if(edge===2){x=Math.random()*W;y=H+pad}else{x=-pad;y=Math.random()*H}const brute=Math.random()<Math.min(.08+elapsed/300,.28);enemies.push({x,y,r:brute?24:13,hp:brute?65+elapsed*.5:22+elapsed*.25,max:brute?65+elapsed*.5:22+elapsed*.25,speed:brute?48:72+Math.min(elapsed,150)*.25,brute,hit:0})}
function shoot(){const a=Math.atan2(mouse.y-player.y,mouse.x-player.x),count=1+(levels.multi||0);for(let i=0;i<count;i++){const spread=(i-(count-1)/2)*.12;bullets.push({x:player.x,y:player.y,vx:Math.cos(a+spread)*570,vy:Math.sin(a+spread)*570,r:4,life:1.3,damage:14*(1+.25*(levels.power||0))})}burst(player.x+Math.cos(a)*22,player.y+Math.sin(a)*22,'#51f6df',4)}
function cast(k){const s=skills[k];if(s.cd>0)return;s.cd=s.max;if(k==='q'){const a=Math.atan2(mouse.y-player.y,mouse.x-player.x);for(let i=-2;i<=2;i++){const aa=a+i*.11;bullets.push({x:player.x,y:player.y,vx:Math.cos(aa)*720,vy:Math.sin(aa)*720,r:7,life:.7,damage:30,pierce:2})}screenShake=6}else if(k==='e'){rings.push({x:player.x,y:player.y,r:5,max:190,life:.5,color:'#4cc8ff'});enemies.forEach(e=>{if(dist(e,player)<190){e.hp-=35;const a=Math.atan2(e.y-player.y,e.x-player.x);e.x+=Math.cos(a)*70;e.y+=Math.sin(a)*70}});player.invuln=1}else{rings.push({x:player.x,y:player.y,r:10,max:500,life:1,color:'#b66cff'});enemies.forEach(e=>{if(dist(e,player)<500)e.hp-=110});screenShake=14;for(let i=0;i<60;i++)burst(player.x,player.y,i%2?'#a06cff':'#51f6df',1)}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function burst(x,y,color,n=8){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=Math.random()*120+25;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.3,color,size:Math.random()*3+1})}}
function update(dt){elapsed+=dt;player.invuln=Math.max(0,player.invuln-dt);Object.values(skills).forEach(s=>s.cd=Math.max(0,s.cd-dt));let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(dx,dy)||1,speed=player.speed*(1+.12*(levels.speed||0));player.x=Math.max(20,Math.min(W-20,player.x+dx/l*speed*dt));player.y=Math.max(85,Math.min(H-30,player.y+dy/l*speed*dt));shotClock-=dt;if(shotClock<=0){shoot();shotClock=.62/Math.pow(1.18,levels.rapid||0)}spawnClock-=dt;if(spawnClock<=0){spawnEnemy();spawnClock=Math.max(.22,.82-elapsed*.004)}
  bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt});
  enemies.forEach(e=>{const a=Math.atan2(player.y-e.y,player.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;e.hit=Math.max(0,e.hit-dt);if(dist(e,player)<e.r+player.r&&player.invuln<=0){player.hp-=e.brute?16:9;player.invuln=.55;screenShake=9;burst(player.x,player.y,'#ff5577',12)}});
  bullets.forEach(b=>enemies.forEach(e=>{if(b.life>0&&e.hp>0&&dist(b,e)<b.r+e.r&&e.hit<=0){let dmg=b.damage;if(Math.random()<.1*(levels.crit||0)){dmg*=2;burst(e.x,e.y,'#ffd467',9)}e.hp-=dmg;e.hit=.06;b.pierce=(b.pierce||0)-1;if(b.pierce<0)b.life=0;burst(e.x,e.y,'#58e9e0',4)}}));
  enemies.filter(e=>e.hp<=0).forEach(e=>{player.kills++;orbs.push({x:e.x,y:e.y,r:5,value:e.brute?6:3,vx:0,vy:0});burst(e.x,e.y,e.brute?'#b56cff':'#ff5577',14)});enemies=enemies.filter(e=>e.hp>0);
  const magnet=105*Math.pow(1.45,levels.magnet||0);orbs.forEach(o=>{const d=dist(o,player);if(d<magnet){const a=Math.atan2(player.y-o.y,player.x-o.x),v=200+(magnet-d)*4;o.x+=Math.cos(a)*v*dt;o.y+=Math.sin(a)*v*dt}if(d<player.r+10){o.dead=true;gainXp(o.value)}});orbs=orbs.filter(o=>!o.dead);
  particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95;p.life-=dt});particles=particles.filter(p=>p.life>0);rings.forEach(r=>{r.r+=(r.max-r.r)*9*dt;r.life-=dt});rings=rings.filter(r=>r.life>0);bullets=bullets.filter(b=>b.life>0);screenShake*=.87;if(player.hp<=0)gameOver();updateUI()}
function gainXp(n){player.xp+=n;burst(player.x,player.y,'#51f6df',3);if(player.xp>=player.nextXp){player.xp-=player.nextXp;player.level++;player.nextXp=Math.floor(player.nextXp*1.34);showLevelUp()}}
function showLevelUp(){paused=true;ui.newLevel.textContent=player.level;ui.levelModal.classList.remove('hidden');const owned=Object.keys(levels),available=upgrades.filter(u=>owned.length<5||levels[u.id]);const picks=[...available].sort(()=>Math.random()-.5).slice(0,3);ui.cards.innerHTML=picks.map(u=>`<button class="card" data-id="${u.id}" style="--card:${u.color}"><div class="rarity">${levels[u.id]?'EWOLUCJA':'NOWE ULEPSZENIE'}</div><div class="icon" style="color:${u.color}">${u.icon}</div><h3>${u.name}</h3><p>${u.desc}</p><span class="level">${levels[u.id]?'POZIOM '+(levels[u.id]+1):'POZIOM 1'}</span></button>`).join('');ui.cards.querySelectorAll('.card').forEach(c=>c.onclick=()=>choose(c.dataset.id))}
function choose(id){levels[id]=(levels[id]||0)+1;if(id==='vital'){player.maxHp+=20;player.hp=Math.min(player.maxHp,player.hp+30)}ui.levelModal.classList.add('hidden');paused=false;renderSlots()}
function renderSlots(){const entries=Object.entries(levels);ui.slots.innerHTML='';for(let i=0;i<5;i++){const el=document.createElement('div');el.className='slot'+(entries[i]?' filled':'');if(entries[i]){const u=upgrades.find(x=>x.id===entries[i][0]);el.style.color=u.color;el.innerHTML=`${u.icon}<b>LV ${entries[i][1]}</b>`}ui.slots.appendChild(el)}document.querySelector('.equipment p span').textContent=entries.length+' / 5'}renderSlots();
function updateUI(){ui.timer.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;ui.kills.textContent=player.kills;ui.level.textContent=ui.xpLevel.textContent=player.level;ui.healthText.textContent=`${Math.ceil(player.hp)} / ${player.maxHp}`;ui.healthBar.style.width=Math.max(0,player.hp/player.maxHp*100)+'%';ui.xpText.textContent=`${player.xp} / ${player.nextXp} XP`;ui.xpBar.style.width=player.xp/player.nextXp*100+'%';for(const [k,s] of Object.entries(skills)){const el=document.querySelector(`[data-key="${k.toUpperCase()}"]`);el.classList.toggle('cooldown',s.cd>0);el.querySelector('.cd').textContent=s.cd>0?s.cd.toFixed(s.cd<10?1:0):''}}
function gameOver(){running=false;paused=true;ui.endStats.textContent=`Przetrwano ${ui.timer.textContent} • ${player.kills} eliminacji • poziom ${player.level}`;ui.endModal.classList.remove('hidden')}
function draw(){ctx.save();if(screenShake)ctx.translate((Math.random()-.5)*screenShake,(Math.random()-.5)*screenShake);const g=ctx.createRadialGradient(player.x,player.y,20,player.x,player.y,Math.max(W,H)*.7);g.addColorStop(0,'#13213a');g.addColorStop(1,'#060812');ctx.fillStyle=g;ctx.fillRect(-20,-20,W+40,H+40);ctx.strokeStyle='rgba(76,200,255,.055)';ctx.lineWidth=1;const grid=64,ox=(-elapsed*5)%grid,oy=(-elapsed*3)%grid;for(let x=ox;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=oy;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
  orbs.forEach(o=>{ctx.shadowBlur=16;ctx.shadowColor='#51f6df';ctx.fillStyle='#80fff0';ctx.beginPath();ctx.moveTo(o.x,o.y-o.r);ctx.lineTo(o.x+o.r,o.y);ctx.lineTo(o.x,o.y+o.r);ctx.lineTo(o.x-o.r,o.y);ctx.fill();ctx.shadowBlur=0});
  bullets.forEach(b=>{ctx.shadowBlur=14;ctx.shadowColor='#51f6df';ctx.fillStyle='#bafff7';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.shadowBlur=0});
  enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.rotate(elapsed*(e.brute?.3:-.7));ctx.shadowBlur=e.hit?22:10;ctx.shadowColor=e.brute?'#a06cff':'#ff3e6d';ctx.fillStyle=e.hit?'#fff':e.brute?'#6c3b92':'#6e1831';ctx.strokeStyle=e.brute?'#c174ff':'#ff557c';ctx.lineWidth=2;ctx.beginPath();const n=e.brute?8:6;for(let i=0;i<n;i++){const a=i/n*Math.PI*2,r=e.r*(i%2?.72:1);ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();if(e.brute){ctx.fillStyle='#161427';ctx.fillRect(e.x-22,e.y-e.r-12,44,4);ctx.fillStyle='#a96cff';ctx.fillRect(e.x-22,e.y-e.r-12,44*e.hp/e.max,4)}});
  rings.forEach(r=>{ctx.globalAlpha=Math.max(0,r.life);ctx.strokeStyle=r.color;ctx.lineWidth=5;ctx.shadowBlur=20;ctx.shadowColor=r.color;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.stroke();ctx.globalAlpha=1;ctx.shadowBlur=0});particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);ctx.globalAlpha=1});
  ctx.save();ctx.translate(player.x,player.y);const a=Math.atan2(mouse.y-player.y,mouse.x-player.x);ctx.rotate(a);ctx.shadowBlur=25;ctx.shadowColor=player.invuln?'#fff':'#51f6df';ctx.fillStyle=player.invuln?'#fff':'#44d8cf';ctx.beginPath();ctx.moveTo(21,0);ctx.lineTo(-11,-13);ctx.lineTo(-5,0);ctx.lineTo(-11,13);ctx.closePath();ctx.fill();ctx.fillStyle='#e8ffff';ctx.beginPath();ctx.arc(1,0,5,0,7);ctx.fill();ctx.restore();ctx.restore()}
function loop(t){const dt=Math.min((t-last)/1000,.033);last=t;if(running&&!paused)update(dt);draw();requestAnimationFrame(loop)}draw();
document.querySelectorAll('.ability canvas').forEach((c,i)=>{const x=c.getContext('2d'),colors=['#51f6df','#4cc8ff','#a06cff'];x.strokeStyle=colors[i];x.lineWidth=4;x.shadowBlur=12;x.shadowColor=colors[i];x.beginPath();if(i===0){x.moveTo(18,52);x.lineTo(53,17);x.moveTo(25,53);x.lineTo(55,23)}else if(i===1){x.arc(36,36,18,0,Math.PI*1.7);x.lineTo(47,27)}else{for(let a=0;a<7;a++){const r=a%2?10:23,aa=-Math.PI/2+a*Math.PI/3.5;x.lineTo(36+Math.cos(aa)*r,36+Math.sin(aa)*r)}x.closePath()}x.stroke()});
