const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const minimap = document.querySelector('#minimap');
const mapCtx = minimap.getContext('2d');
const WORLD = { w: 3000, h: 2200 };
const camera = { x: 0, y: 0 };
const MAP_SHAPE = [[180,40],[1080,40],[1210,120],[1780,70],[1940,35],[2790,80],[2960,270],[2930,820],[2990,980],[2945,1640],[2860,1760],[2900,2020],[2700,2160],[1910,2180],[1760,2090],[1190,2160],[990,2080],[260,2150],[55,1950],[90,1430],[35,1260],[95,730],[45,500]];
const terrain = [
  {type:'water', points:[[160,260],[480,180],[720,310],[650,560],[390,650],[130,520]]},
  {type:'water', points:[[2180,1450],[2480,1320],[2800,1440],[2870,1760],[2650,1940],[2290,1840],[2110,1650]]},
  {type:'water', points:[[1130,1660],[1370,1510],[1600,1600],[1660,1900],[1430,2050],[1160,1940]]},
  {type:'wall', x:840,y:360,w:390,h:42}, {type:'wall',x:1190,y:360,w:42,h:290},
  {type:'wall', x:1830,y:720,w:42,h:430}, {type:'wall',x:1830,y:1108,w:390,h:42},
  {type:'wall', x:520,y:1220,w:430,h:42}, {type:'wall',x:910,y:1010,w:42,h:252},
  {type:'rock',x:1530,y:470,r:92}, {type:'rock',x:2450,y:520,r:115},
  {type:'rock',x:480,y:940,r:86}, {type:'rock',x:1530,y:1280,r:105},
  {type:'rock',x:2520,y:1050,r:78}, {type:'rock',x:720,y:1790,r:120}
];
function tracePolygon(context, points){context.beginPath();points.forEach(([x,y],i)=>i?context.lineTo(x,y):context.moveTo(x,y));context.closePath()}
function pointInPolygon(x,y,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const [xi,yi]=points[i],[xj,yj]=points[j];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside}return inside}
function pointSegmentDistance(px,py,ax,ay,bx,by){const dx=bx-ax,dy=by-ay,length=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/length));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}
function polygonEdgeDistance(x,y,points){let closest=Infinity;for(let i=0,j=points.length-1;i<points.length;j=i++)closest=Math.min(closest,pointSegmentDistance(x,y,...points[j],...points[i]));return closest}
function circleRectCollision(x,y,r,rect){const cx=Math.max(rect.x,Math.min(x,rect.x+rect.w)),cy=Math.max(rect.y,Math.min(y,rect.y+rect.h));return Math.hypot(x-cx,y-cy)<r}
function blocked(x,y,r=14){
  if(!pointInPolygon(x,y,MAP_SHAPE)||polygonEdgeDistance(x,y,MAP_SHAPE)<r)return true;
  if(terrain.some(t=>t.type==='water'?(pointInPolygon(x,y,t.points)||polygonEdgeDistance(x,y,t.points)<r):t.type==='wall'?circleRectCollision(x,y,r,t):Math.hypot(x-t.x,y-t.y)<r+t.r*.94))return true;
  return false;
}
function projectileBlocked(x,y){return terrain.some(t=>t.type==='wall'?circleRectCollision(x,y,2,t):t.type==='rock'&&Math.hypot(x-t.x,y-t.y)<t.r*.94)}
const NAV_CELL=70,NAV_COLS=Math.ceil(WORLD.w/NAV_CELL),NAV_ROWS=Math.ceil(WORLD.h/NAV_CELL);
let flowMap=new Int32Array(NAV_COLS*NAV_ROWS).fill(-1);
function navIndex(x,y){return y*NAV_COLS+x}
function rebuildFlow(){
  flowMap.fill(-1);const sx=Math.max(0,Math.min(NAV_COLS-1,Math.floor(player.x/NAV_CELL))),sy=Math.max(0,Math.min(NAV_ROWS-1,Math.floor(player.y/NAV_CELL))),queue=[[sx,sy]];flowMap[navIndex(sx,sy)]=0;
  for(let head=0;head<queue.length;head++){const [x,y]=queue[head],cost=flowMap[navIndex(x,y)]+1;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=NAV_COLS||ny>=NAV_ROWS||flowMap[navIndex(nx,ny)]!==-1)continue;const wx=(nx+.5)*NAV_CELL,wy=(ny+.5)*NAV_CELL;if(blocked(wx,wy,16))continue;flowMap[navIndex(nx,ny)]=cost;queue.push([nx,ny])}}
}
function flowAngle(e,directAngle){
  const cx=Math.floor(e.x/NAV_CELL),cy=Math.floor(e.y/NAV_CELL);let best=Infinity,target=null;for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const x=cx+dx,y=cy+dy;if(x<0||y<0||x>=NAV_COLS||y>=NAV_ROWS)continue;const value=flowMap[navIndex(x,y)];if(value>=0&&value<best){best=value;target={x:(x+.5)*NAV_CELL,y:(y+.5)*NAV_CELL}}}return target?Math.atan2(target.y-e.y,target.x-e.x):directAngle;
}
function hasClearPath(from,to,r){const length=dist(from,to),steps=Math.ceil(length/28);for(let i=1;i<=steps;i++){const t=i/steps;if(blocked(from.x+(to.x-from.x)*t,from.y+(to.y-from.y)*t,r))return false}return true}
function moveEnemy(e,directAngle,distance){
  e.losClock=(e.losClock||0)-1;if(e.losClock<=0){e.losClock=10;e.hasLos=hasClearPath(e,player,e.r)}const angle=e.hasLos?directAngle:flowAngle(e,directAngle);for(const offset of [0,.28,-.28,.6,-.6,1.05,-1.05,Math.PI/2,-Math.PI/2]){const nx=e.x+Math.cos(angle+offset)*distance,ny=e.y+Math.sin(angle+offset)*distance;if(!blocked(nx,ny,e.r)){e.x=nx;e.y=ny;return}}
}


const scenery = Array.from({length: 96}, (_, i) => {
  const x = 90 + ((i * 811) % (WORLD.w - 180));
  const y = 90 + ((i * 457) % (WORLD.h - 180));
  return {x, y, type: i % 4 ? 'crystal' : 'vent', size: 14 + (i * 13) % 25, rot: (i * 1.71) % 6.28};
});
let crates=[
  {x:1080,y:790},{x:1730,y:560},{x:2620,y:1260},{x:1740,y:1850},{x:420,y:1510}
].map((c,i)=>({...c,id:i,hp:28,max:28,opened:false,hit:0}));
const ui = Object.fromEntries(['timer','kills','level','healthText','healthBar','xpLevel','xpText','xpBar','slots','cards','startModal','instructionsModal','statsModal','pauseModal','levelModal','endModal','newLevel','endStats','bestTime','totalTime','bestKills','totalKills','phaseLabel','waveBanner','waveCaption','waveTitle','charactersModal','mapsModal','endEyebrow','endTitle','augmentSlots','itemCount','augmentCount','levelDescription','scoutGames','warriorGames','druidGames','hudCoins','menuCoins','coinToasts','bossHud','bossName','bossHealthText','bossHealthBar','bossEta'].map(id=>[id,document.getElementById(id)]));
let W=0,H=0,dpr=1,last=0,freezeUntil=0,running=false,paused=true,elapsed=0,spawnClock=0,shotClock=0,screenShake=0,flowClock=0,statsClock=0,saveClock=0,directorPhase=-1,waveNumber=0,waveRemaining=0,waveBreak=0,bannerTimer=0,bossTierSpawned=0,eliteBudget=3+Math.floor(Math.random()*3),eliteSpawned=0,eliteNextAt=65+Math.random()*25,levelChoicesQueued=0,bossChoicesQueued=0,awardedMinutes=0;
const keys={};const mouse={x:innerWidth*.7,y:innerHeight*.5};
const player={x:WORLD.w/2,y:WORLD.h/2,r:15,speed:250,hp:100,maxHp:100,xp:0,level:1,nextXp:24,kills:0,invuln:0};
const scoutAssets={ready:false,atlas:null,images:{}};
// Hand-measured regions in the irregular 1536 × 1024 presentation atlas.
const SCOUT_ATLAS={player:{x:164,y:22,w:142,h:108},bullet:{x:1009,y:40,w:72,h:58},qProjectile:{x:1195,y:27,w:145,h:78},muzzle:{x:254,y:330,w:50,h:66},eRing:{x:1142,y:407,w:160,h:168},rFlash:{x:270,y:617,w:230,h:268}};
function buildAtlasSprite(image,region){
  const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});canvas.width=region.w;canvas.height=region.h;context.drawImage(image,region.x,region.y,region.w,region.h,0,0,region.w,region.h);
  // The atlas has a smooth opaque backdrop. Remove it in memory using the
  // colour interpolated from each crop's clear edges; no asset files are made.
  const pixels=context.getImageData(0,0,region.w,region.h),source=new Uint8ClampedArray(pixels.data),at=(x,y,c)=>source[(y*region.w+x)*4+c];
  for(let y=0;y<region.h;y++)for(let x=0;x<region.w;x++){const fx=x/(region.w-1),fy=y/(region.h-1),index=(y*region.w+x)*4;let difference=0;for(let c=0;c<3;c++){const horizontal=at(0,y,c)*(1-fx)+at(region.w-1,y,c)*fx,vertical=at(x,0,c)*(1-fy)+at(x,region.h-1,c)*fy,delta=source[index+c]-(horizontal+vertical)/2;difference+=delta*delta}pixels.data[index+3]=Math.max(0,Math.min(255,(Math.sqrt(difference)-7)*255/22))}context.putImageData(pixels,0,0);return canvas
}
function preloadScoutAssets(){
  const atlas=new Image();scoutAssets.atlas=atlas;atlas.onload=()=>{try{if(atlas.naturalWidth!==1536||atlas.naturalHeight!==1024)throw new Error(`nieoczekiwany rozmiar ${atlas.naturalWidth}×${atlas.naturalHeight}`);Object.entries(SCOUT_ATLAS).forEach(([key,region])=>scoutAssets.images[key]=buildAtlasSprite(atlas,region));scoutAssets.ready=true;drawSelectionPreviews()}catch(error){scoutAssets.ready=false;console.warn('Nie udało się przygotować atlasu Zwiadowcy; używam grafiki proceduralnej.',error)}};atlas.onerror=()=>{scoutAssets.ready=false;console.warn('Nie udało się załadować atlasu Zwiadowcy; używam grafiki proceduralnej.')};atlas.src='assets/player/scout_atlas.png'
}
preloadScoutAssets();
let chosenCharacter=localStorage.getItem('swarmfall-character')||'scout';
const characterDefs={scout:{name:'Zwiadowca',hp:100,speed:250,cost:0,abilities:['SALWA','ODRZUT','WYBUCH']},warrior:{name:'Wojownik',hp:130,speed:220,cost:30,abilities:['WIR OSTRZA','TELEPORT','SZAŁ']},druid:{name:'Druid',hp:110,speed:235,cost:60,abilities:['LECZENIE','PĘD','ODNOWA']}};
function loadUnlocked(){try{return new Set(['scout',...JSON.parse(localStorage.getItem('swarmfall-unlocked')||'[]')])}catch{return new Set(['scout'])}}
let unlockedCharacters=loadUnlocked();if(!unlockedCharacters.has(chosenCharacter))chosenCharacter='scout';
let enemies=[],bullets=[],enemyBullets=[],orbs=[],loot=[],particles=[],rings=[],playerEchoes=[],damageNumbers=[];
const skills={q:{cd:0,max:5},e:{cd:0,max:9},r:{cd:0,max:28}};
const itemDefs=[
  {id:'speed',name:'Buty',icon:'♢',desc:'Zwiększają prędkość ruchu.',color:'#a06cff'},
  {id:'vital',name:'Tarcza',icon:'⬡',desc:'Zwiększa maksymalne zdrowie.',color:'#ff6688'},
  {id:'rapid',name:'Łuk',icon:'➶',desc:'Zwiększa szybkość strzelania.',color:'#4cc8ff'},
  {id:'power',name:'Miecz',icon:'†',desc:'Zwiększa obrażenia pocisków.',color:'#51f6df'},
  {id:'multi',name:'Nabój',icon:'●',desc:'Pozwala wystrzeliwać więcej pocisków.',color:'#ffd467'},
  {id:'cooldown',name:'Medalion',icon:'◉',desc:'Skraca czas odnowienia umiejętności.',color:'#68d8ff'},
  {id:'magnet',name:'Sakwa',icon:'⌒',desc:'Zwiększa zasięg zbierania doświadczenia.',color:'#6df59d'},
  {id:'lifesteal',name:'Strzykawka',icon:'╱',desc:'Leczy niewielką ilość zdrowia po zabiciu.',color:'#ff8eab'},
  {id:'vault',name:'Skarbiec',icon:'▣',desc:'Generuje dodatkową monetę za każdą minutę przetrwania.',color:'#ffd45c',rare:true,max:1}
];
function itemIconSvg(id,augment=false){
  const shapes={
    speed:'<path d="M12 8h11l2 15 9 8-3 9H10l-3-7 9-8z"/><path d="M39 13h8l3 13 7 7-4 8H36l-3-6 8-10z"/>',
    vital:'<path d="M32 5 54 14v16c0 14-9 24-22 29C19 54 10 44 10 30V14z"/><path d="M32 14v34M20 28h24"/>',
    rapid:'<path d="M19 8c19 12 19 36 0 48M19 8c-9 14-9 34 0 48M19 8l0 48M15 32h36"/><path d="m45 26 9 6-9 6"/>',
    power:'<path d="m36 5 9 9-22 28-8 2 2-8z"/><path d="m14 39 12 12M10 54l10-10M40 10l7-5 5 5-5 7"/>',
    multi:'<path d="M11 13h11v34H11zM27 7h11v40H27zM43 16h11v31H43z"/><path d="M11 47h11l-5 10zM27 47h11l-5 10zM43 47h11l-5 10z"/>',
    cooldown:'<circle cx="32" cy="32" r="24"/><circle cx="32" cy="32" r="15"/><path d="M32 17v16l11 7M32 4v7M32 53v7M4 32h7M53 32h7"/>',
    magnet:'<path d="M15 23h34l6 33H9z"/><path d="M21 24c0-16 22-16 22 0M20 36h24M27 36v10c0 7 10 7 10 0V36"/>',
    lifesteal:'<path d="m45 7 12 12-30 30-13 4 4-13z"/><path d="m39 13 12 12M18 40l7 7M9 55l-3 5M28 19l6 6M31 16l6 6"/>',
    vault:'<path d="M8 12h48v40H8z"/><path d="M15 19h34v26H15z"/><circle cx="32" cy="32" r="9"/><path d="M32 23v18M23 32h18M46 16v32"/>'
  };
  const frame=augment?'<path class="augment-frame" d="M32 3 60 32 32 61 4 32z"/><circle class="augment-node" cx="32" cy="3" r="2"/><circle class="augment-node" cx="60" cy="32" r="2"/><circle class="augment-node" cx="32" cy="61" r="2"/><circle class="augment-node" cx="4" cy="32" r="2"/>':'';
  return `<svg class="item-svg ${augment?'augment-svg':'item-svg-'+id}" viewBox="0 0 64 64" aria-hidden="true">${frame}<g class="item-shape">${shapes[id]}</g></svg>`
}
const items={},augments={};
function buildPower(id){const item=items[id]||0,aug=augments[id]||0,superScale=item===6?1.35:1;return item*(1+aug*.12)*superScale+aug*.3}
function refreshDerivedStats(healGrowth=false){const previous=player.maxHp;player.maxHp=Math.round(characterDefs[chosenCharacter].hp+buildPower('vital')*20);if(healGrowth&&player.maxHp>previous)player.hp=Math.min(player.maxHp,player.hp+player.maxHp-previous);else player.hp=Math.min(player.hp,player.maxHp)}

function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;const c=document.querySelector('#crosshair');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'});
addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='escape'){e.preventDefault();togglePause();return}keys[key]=true;if(!paused&&['q','e','r'].includes(key))cast(key)});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelector('#startBtn').onclick=start;document.querySelector('#continueBtn').onclick=continueGame;document.querySelector('#restartBtn').onclick=()=>location.reload();document.querySelector('#instructionsBtn').onclick=()=>{ui.startModal.classList.add('hidden');ui.instructionsModal.classList.remove('hidden')};document.querySelector('#backBtn').onclick=()=>{ui.instructionsModal.classList.add('hidden');ui.startModal.classList.remove('hidden')};document.querySelector('#statsBtn').onclick=showStats;document.querySelector('#statsBackBtn').onclick=()=>{ui.statsModal.classList.add('hidden');ui.startModal.classList.remove('hidden')};document.querySelector('#pauseBtn').onclick=togglePause;document.querySelector('#resumeBtn').onclick=togglePause;document.querySelector('#quitBtn').onclick=quitToMenu;
function openMenuPanel(panel){ui.startModal.classList.add('hidden');panel.classList.remove('hidden');panel.setAttribute('aria-hidden','false')}
function closeMenuPanel(panel){panel.classList.add('hidden');panel.setAttribute('aria-hidden','true');ui.startModal.classList.remove('hidden')}
function bindSelectionMenu(buttonId,panelId,backId){const button=document.getElementById(buttonId),panel=document.getElementById(panelId),back=document.getElementById(backId);button.onclick=()=>openMenuPanel(panel);back.onclick=()=>closeMenuPanel(panel)}
bindSelectionMenu('charactersBtn','charactersModal','charactersBackBtn');bindSelectionMenu('mapsBtn','mapsModal','mapsBackBtn');
function updateAbilityLabels(){document.querySelectorAll('.ability').forEach((el,i)=>el.querySelector('small').textContent=characterDefs[chosenCharacter].abilities[i])}
function renderCharacterCards(){document.querySelectorAll('.character-card').forEach(card=>{const id=card.dataset.character,def=characterDefs[id],unlocked=unlockedCharacters.has(id),selected=chosenCharacter===id;card.classList.toggle('selected',selected);card.classList.toggle('character-locked',!unlocked);card.querySelector('b').textContent=selected?'WYBRANO ✓':unlocked?'WYBIERZ':`${def.cost} MONET · ODBLOKUJ`})}
function selectCharacter(id){const def=characterDefs[id];if(!unlockedCharacters.has(id)){if((savedStats.coins||0)<def.cost){const card=document.querySelector(`[data-character="${id}"]`);card.classList.remove('cannot-afford');void card.offsetWidth;card.classList.add('cannot-afford');return}savedStats.coins-=def.cost;unlockedCharacters.add(id);localStorage.setItem('swarmfall-unlocked',JSON.stringify([...unlockedCharacters]));saveStats();awardUnlock(id)}chosenCharacter=id;localStorage.setItem('swarmfall-character',id);renderCharacterCards();player.speed=def.speed;const oldMax=player.maxHp;player.maxHp=def.hp+Math.round(buildPower('vital')*20);player.hp=Math.min(player.maxHp,player.hp+Math.max(0,player.maxHp-oldMax));updateAbilityLabels()}
function awardUnlock(id){const toast=document.createElement('div');toast.className='coin-toast unlock-toast';toast.innerHTML=`<div><strong>ODBLOKOWANO</strong><small>${characterDefs[id].name.toUpperCase()}</small></div>`;ui.coinToasts.appendChild(toast);setTimeout(()=>toast.remove(),1900)}
document.querySelectorAll('.character-card').forEach(card=>card.onclick=()=>selectCharacter(card.dataset.character));

const defaultStats={bestTime:0,totalTime:0,bestKills:0,totalKills:0,coins:0,characterGames:{scout:0,warrior:0,druid:0}};
function loadStats(){try{const data=JSON.parse(localStorage.getItem('swarmfall-stats')||'{}');return {...defaultStats,...data,characterGames:{...defaultStats.characterGames,...data.characterGames}}}catch{return {...defaultStats,characterGames:{...defaultStats.characterGames}}}}
let savedStats=loadStats();selectCharacter(chosenCharacter);
const SAVE_KEY='swarmfall-save-v1';
function getRunSave(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}}
function saveGame(){
  if(!running)return;const state={version:3,savedAt:Date.now(),elapsed,spawnClock,shotClock,directorPhase,waveNumber,waveRemaining,waveBreak,bossTierSpawned,eliteBudget,eliteSpawned,eliteNextAt,levelChoicesQueued,bossChoicesQueued,awardedMinutes,chosenCharacter,player:{...player},skills:{q:{...skills.q},e:{...skills.e},r:{...skills.r}},items:{...items},augments:{...augments},enemies:enemies.slice(-450),bullets:bullets.slice(-250),enemyBullets:enemyBullets.slice(-250),orbs:orbs.slice(-350),loot,crates,rings,levelPending:!ui.levelModal.classList.contains('hidden')};
  try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));refreshContinueButton()}catch(error){console.warn('Nie udało się zapisać gry:',error)}
}
function clearGameSave(){try{localStorage.removeItem(SAVE_KEY)}catch{}}
function refreshContinueButton(){const button=document.querySelector('#continueBtn'),hasSave=Boolean(getRunSave());button.disabled=!hasSave;button.classList.toggle('no-save',!hasSave);button.querySelector('.save-label').textContent=hasSave?'ZAPIS ZNALEZIONY':'BRAK ZAPISU'}
function continueGame(){
  const state=getRunSave();if(!state||!state.version)return;elapsed=state.elapsed||0;directorPhase=state.directorPhase??-1;waveNumber=state.waveNumber||0;waveRemaining=state.waveRemaining||0;waveBreak=state.waveBreak||0;bossTierSpawned=state.bossTierSpawned||0;eliteBudget=state.eliteBudget||eliteBudget;eliteSpawned=state.eliteSpawned||0;eliteNextAt=state.eliteNextAt||eliteNextAt;levelChoicesQueued=state.levelChoicesQueued||0;bossChoicesQueued=state.bossChoicesQueued||0;awardedMinutes=state.awardedMinutes??Math.floor((state.elapsed||0)/60);chosenCharacter=state.chosenCharacter||'scout';localStorage.setItem('swarmfall-character',chosenCharacter);spawnClock=state.spawnClock||0;shotClock=state.shotClock||0;Object.assign(player,state.player);Object.assign(skills,state.skills);Object.keys(items).forEach(k=>delete items[k]);Object.keys(augments).forEach(k=>delete augments[k]);const savedItems=state.items||state.levels||{};itemDefs.forEach(d=>{if(savedItems[d.id])items[d.id]=Math.min(d.max||6,savedItems[d.id]);if(state.augments?.[d.id])augments[d.id]=state.augments[d.id]});selectCharacter(chosenCharacter);refreshDerivedStats();enemies=state.enemies||[];bullets=state.bullets||[];enemyBullets=state.enemyBullets||[];orbs=state.orbs||[];loot=state.loot||[];crates=state.crates||crates;rings=state.rings||[];particles=[];renderSlots();ui.startModal.classList.add('hidden');running=true;paused=false;last=performance.now();rebuildFlow();updateUI();if(state.levelPending)showLevelUp();requestAnimationFrame(loop);
}

function saveStats(){try{localStorage.setItem('swarmfall-stats',JSON.stringify(savedStats))}catch{}updateCoinDisplays()}
function updateCoinDisplays(){const value=savedStats?.coins||0;if(ui.hudCoins)ui.hudCoins.textContent=value;if(ui.menuCoins)ui.menuCoins.textContent=value}
function awardCurrency(amount,reason){savedStats.coins=(savedStats.coins||0)+amount;saveStats();const toast=document.createElement('div');toast.className='coin-toast';toast.innerHTML=`<span class="coin-icon large"></span><div><strong>+${amount}</strong><small>${reason}</small></div>`;ui.coinToasts.appendChild(toast);for(let i=0;i<7;i++){const spark=document.createElement('i');spark.className='coin-spark';spark.style.setProperty('--x',`${(Math.random()-.5)*150}px`);spark.style.setProperty('--y',`${-35-Math.random()*90}px`);toast.appendChild(spark)}setTimeout(()=>toast.remove(),1900)}
function formatTime(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`}
function showStats(){savedStats=loadStats();ui.bestTime.textContent=formatTime(savedStats.bestTime);ui.totalTime.textContent=formatTime(savedStats.totalTime);ui.bestKills.textContent=savedStats.bestKills;ui.totalKills.textContent=savedStats.totalKills;ui.scoutGames.textContent=savedStats.characterGames.scout;ui.warriorGames.textContent=savedStats.characterGames.warrior;ui.druidGames.textContent=savedStats.characterGames.druid;updateCoinDisplays();ui.startModal.classList.add('hidden');ui.statsModal.classList.remove('hidden')}
function togglePause(){if(!running||!ui.levelModal.classList.contains('hidden')||!ui.endModal.classList.contains('hidden'))return;paused=!paused;if(paused)saveGame();ui.pauseModal.classList.toggle('hidden',!paused);keys.w=keys.a=keys.s=keys.d=false}
function start(){clearGameSave();awardedMinutes=0;selectCharacter(chosenCharacter);savedStats.characterGames[chosenCharacter]=(savedStats.characterGames[chosenCharacter]||0)+1;saveStats();player.hp=player.maxHp;ui.startModal.classList.add('hidden');running=true;paused=false;last=performance.now();startDirectorPhase(true);saveGame();requestAnimationFrame(loop)}
function enemyAt(x,y,type='melee'){
  const scale=1+Math.min(elapsed,900)*.0025,stats=SWARM_ENEMIES[type];
  return {x,y,type,r:stats.r,hp:stats.hp*scale,max:stats.hp*scale,speed:stats.speed,hit:0,attackCd:1+Math.random(),chargeCd:1.5+Math.random()*2,phase:Math.random()*6.28};
}
function spawnEnemy(typeOverride,forceElite=false){
  let x,y;for(let tries=0;tries<20;tries++){const a=Math.random()*Math.PI*2,d=Math.max(W,H)*(.58+Math.random()*.12);x=Math.max(35,Math.min(WORLD.w-35,player.x+Math.cos(a)*d));y=Math.max(35,Math.min(WORLD.h-35,player.y+Math.sin(a)*d));if(!blocked(x,y,28)&&dist({x,y},player)>350)break}if(blocked(x,y,28))return;
  const roll=Math.random();let type=typeOverride||'melee';if(!typeOverride){if(roll<.12)type='swarm';else if(roll<.24)type='exploder';else if(roll<.36)type='shooter';else if(roll<.47)type='charger';else if(roll>.93)type='brute'};
  if(type==='swarm'){for(let i=0;i<5+Math.floor(Math.random()*3);i++){const a=Math.random()*6.28,d=Math.random()*38,nx=x+Math.cos(a)*d,ny=y+Math.sin(a)*d;if(!blocked(nx,ny,8))enemies.push(enemyAt(nx,ny,'swarm'))}}else{const enemy=enemyAt(x,y,type);if(forceElite){enemy.elite=true;enemy.hp*=3.1;enemy.max=enemy.hp;enemy.r*=1.16;enemy.speed*=1.08}enemies.push(enemy)}
}
const BOSS_DATA=SWARM_BOSSES;
function spawnBoss(tier){
  const data=BOSS_DATA[tier],d=Math.min(W,H)*.55;let x=player.x,y=player.y;for(let tries=0;tries<30;tries++){const a=Math.random()*6.28;x=Math.max(100,Math.min(WORLD.w-100,player.x+Math.cos(a)*d));y=Math.max(100,Math.min(WORLD.h-100,player.y+Math.sin(a)*d));if(!blocked(x,y,data.r))break}enemies.push({x,y,type:data.type,bossTier:tier,bossName:data.name,r:data.r,hp:data.hp,max:data.hp,speed:data.speed,hit:0,attackCd:1.5,chargeCd:2,phase:0});bossTierSpawned=tier;showWaveBanner(data.name,`BOSS · ${tier*5}:00`);screenShake=14;freezeUntil=performance.now()+50;GameFeedback.boss();saveGame()
}
function isBoss(e){return Boolean(e.bossTier)}
function updateBoss(e,dt){
  const a=Math.atan2(player.y-e.y,player.x-e.x),d=dist(e,player);e.phase+=dt;e.attackCd-=dt;e.chargeCd-=dt;
  if(e.bossTier===1){if(e.chargeCd<=0&&d<650){e.chargeCd=4;e.dash=.8;e.dx=Math.cos(a);e.dy=Math.sin(a)}if(e.dash>0){e.dash-=dt;const nx=e.x+e.dx*310*dt,ny=e.y+e.dy*310*dt;if(!blocked(nx,ny,e.r)){e.x=nx;e.y=ny}}else moveEnemy(e,a,e.speed*dt);if(e.attackCd<=0){e.attackCd=2.6;rings.push({x:e.x,y:e.y,r:10,max:185,life:.65,color:'#ff5f72'});if(d<185&&player.invuln<=0){player.hp-=22;player.invuln=.7}}}
  else if(e.bossTier===2){if(d>340)moveEnemy(e,a,e.speed*dt);else moveEnemy(e,a+Math.PI/2,e.speed*.35*dt);if(e.attackCd<=0){e.attackCd=1.4;for(let i=-2;i<=2;i++){const aa=a+i*.18;enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(aa)*290,vy:Math.sin(aa)*290,r:8,life:4,boss:true})}burst(e.x,e.y,'#65b9ff',18)}}
  else{moveEnemy(e,a,e.speed*dt);if(e.attackCd<=0){e.attackCd=1.15;for(let i=0;i<12;i++){const aa=i/12*6.28+e.phase;enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(aa)*220,vy:Math.sin(aa)*220,r:7,life:4,boss:true})}rings.push({x:e.x,y:e.y,r:12,max:250,life:.8,color:'#c36cff'});burst(e.x,e.y,'#c36cff',25)}}
}
function rewardBoss(tier){awardCurrency(5,'POKONANY BOSS');if(tier===3){winMap();return}for(let i=0;i<tier;i++){player.level++;player.nextXp=Math.floor(player.nextXp*1.34);bossChoicesQueued++}if(!paused)showLevelUp(true)}
function directorState(){
  const cycle=Math.floor(elapsed/300),time=elapsed%300,difficulty=1+cycle*.1;
  if(time<120)return {id:cycle*3,name:`FAZA ${cycle*3+1} · NAPŁYW`,title:'NAPŁYW',size:Math.round(6*difficulty),rest:7,pool:['melee','melee','melee','melee','swarm','brute']};
  if(time<240)return {id:cycle*3+1,name:`FAZA ${cycle*3+2} · OSTRZAŁ`,title:'OSTRZAŁ',size:Math.round(7*difficulty),rest:8,pool:['shooter','shooter','melee','melee','exploder','swarm']};
  return {id:cycle*3+2,name:`FAZA ${cycle*3+3} · ELITA`,title:'ELITA',size:Math.round(5*difficulty),rest:10,pool:['charger','charger','brute','brute','shooter','exploder']};
}
function showWaveBanner(title,caption){ui.waveTitle.textContent=title;ui.waveCaption.textContent=caption;ui.waveBanner.classList.remove('hidden');bannerTimer=2.4}
function startDirectorPhase(initial=false){const d=directorState();directorPhase=d.id;waveNumber=1;waveRemaining=d.size;waveBreak=initial?2:3;showWaveBanner(d.title,`FAZA ${d.id+1}`)}
function beginWave(){const d=directorState();waveNumber++;waveRemaining=d.size}
function updateDirector(dt){
  if(eliteSpawned<eliteBudget&&elapsed>=eliteNextAt&&!enemies.some(e=>e.elite)){const pool=['melee','brute','shooter','charger','exploder'],type=pool[Math.floor(Math.random()*pool.length)];spawnEnemy(type,true);eliteSpawned++;eliteNextAt=65+eliteSpawned*(700/eliteBudget)+Math.random()*35;showWaveBanner('ELITA W RUINACH','WZMOCNIONY PRZECIWNIK')}
  const milestone=Math.min(3,Math.floor(elapsed/300));if(milestone>bossTierSpawned&&!enemies.some(isBoss))spawnBoss(milestone);if(enemies.some(isBoss))return;const d=directorState();if(d.id!==directorPhase)startDirectorPhase();if(bannerTimer>0){bannerTimer-=dt;if(bannerTimer<=0)ui.waveBanner.classList.add('hidden')}
  if(waveBreak>0){waveBreak-=dt;return}if(waveRemaining<=0){waveBreak=d.rest;beginWave();return}
  spawnClock-=dt;if(spawnClock<=0){spawnEncounter();waveRemaining--;spawnClock=.32}
}
function spawnEncounter(){const director=directorState(),type=director.pool[Math.floor(Math.random()*director.pool.length)];spawnEnemy(type);if(director.title==='ELITA'&&Math.random()<.18)spawnEnemy('melee')}

function updateEnemy(e,dt){
  if(isBoss(e)){updateBoss(e,dt);return}const direct=Math.atan2(player.y-e.y,player.x-e.x),d=dist(e,player);e.attackCd-=dt;e.chargeCd-=dt;
  if(e.type==='shooter'){
    if(d>390)moveEnemy(e,direct,e.speed*dt);else if(d<255)moveEnemy(e,direct+Math.PI,e.speed*.75*dt);
    else{e.strafe=(e.strafe||1);moveEnemy(e,direct+e.strafe*Math.PI/2,e.speed*.28*dt)}
    if(e.attackCd<=0&&d<560&&hasClearPath(e,player,4)){const a=Math.atan2(player.y-e.y,player.x-e.x);enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(a)*260,vy:Math.sin(a)*260,r:6,life:3,damage:e.elite?18:10});e.attackCd=1.75;burst(e.x,e.y,'#ffb45e',7)}
  }else if(e.type==='charger'){
    if(e.charging){const nx=e.x+e.chargeX*430*dt,ny=e.y+e.chargeY*430*dt;if(blocked(nx,ny,e.r)){e.charging=0;e.chargeCd=2.5;screenShake=3}else{e.x=nx;e.y=ny;e.charging-=dt}}
    else if(e.windup){e.windup-=dt;if(e.windup<=0){const a=Math.atan2(player.y-e.y,player.x-e.x);e.chargeX=Math.cos(a);e.chargeY=Math.sin(a);e.charging=.55;screenShake=5}}
    else if(e.chargeCd<=0&&d<480){e.windup=.65;e.chargeCd=4}else moveEnemy(e,direct,e.speed*dt);
  }else moveEnemy(e,direct,e.speed*dt);
}

function openCrate(crate){
  crate.opened=true;const roll=Math.random(),type=roll<.08?'coin':roll<.44?'health':roll<.8?'xp':'level';crate.reward=type;loot.push({x:crate.x,y:crate.y-8,type,r:9,bob:Math.random()*6.28});burst(crate.x,crate.y,type==='health'?'#ff6688':type==='xp'?'#51f6df':'#ffd467',20);saveGame()
}
function collectLoot(){loot.forEach(item=>{if(dist(item,player)>player.r+18)return;if(item.type==='health'&&player.hp>=player.maxHp)return;if(item.type==='health')player.hp=Math.min(player.maxHp,player.hp+35);else if(item.type==='xp')gainXp(15+Math.floor(player.level*2));else if(item.type==='coin')awardCurrency(1,'MONETA ZE SKRZYNKI');else gainXp(player.nextXp-player.xp);item.collected=true;burst(item.x,item.y,item.type==='health'?'#ff6688':item.type==='xp'?'#51f6df':'#ffd467',16);saveGame()});loot=loot.filter(item=>!item.collected)}
function hitCrates(){bullets.forEach(b=>{if(b.life<=0)return;const crate=crates.find(c=>!c.opened&&Math.hypot(b.x-c.x,b.y-c.y)<b.r+18);if(crate){crate.hp-=b.damage;b.life=0;crate.hit=.15;burst(b.x,b.y,'#d7a65a',6);if(crate.hp<=0)openCrate(crate)}})}
function playerDamage(base){return base*(1+.2*buildPower('power'))*(player.powerBuff>0?1.65:1)}
function healAllies(amount){player.hp=Math.min(player.maxHp,player.hp+amount)}
function shoot(){
  const a=Math.atan2(mouse.y+camera.y-player.y,mouse.x+camera.x-player.x),multi=buildPower('multi'),count=1+Math.floor(multi)+(Math.random()<multi%1?1:0);
  if(chosenCharacter==='warrior'){player.attackAnim=.28;player.attackAngle=a;let target=null,best=105,targetKind='enemy';enemies.forEach(e=>{const d=dist(e,player),ea=Math.atan2(e.y-player.y,e.x-player.x),diff=Math.abs(Math.atan2(Math.sin(ea-a),Math.cos(ea-a)));if(d<best&&diff<.8){best=d;target=e;targetKind='enemy'}});crates.filter(c=>!c.opened).forEach(c=>{const d=dist(c,player),ca=Math.atan2(c.y-player.y,c.x-player.x),diff=Math.abs(Math.atan2(Math.sin(ca-a),Math.cos(ca-a)));if(d<best&&diff<.8){best=d;target=c;targetKind='crate'}});if(target&&targetKind==='enemy'){target.hp-=playerDamage(18);target.hit=.08;healAllies(player.powerBuff>0?5:2.2);burst(target.x,target.y,'#ffcc78',9)}else if(target){target.hp-=playerDamage(18);target.hit=.15;burst(target.x,target.y,'#d7a65a',9);if(target.hp<=0)openCrate(target)}return}
  for(let i=0;i<count;i++){const spread=(i-(count-1)/2)*(chosenCharacter==='druid'?.09:.12),wave=chosenCharacter==='druid';bullets.push({x:player.x,y:player.y,vx:Math.cos(a+spread)*(wave?470:570),vy:Math.sin(a+spread)*(wave?470:570),r:wave?10:4,life:wave?2.1:1.3,damage:playerDamage(wave?12:14),pierce:wave?3:undefined,kind:wave?'boomerang':chosenCharacter==='scout'?'scoutBullet':'bullet',spin:0})}if(chosenCharacter==='scout')player.muzzleFlash=.09;burst(player.x+Math.cos(a)*22,player.y+Math.sin(a)*22,chosenCharacter==='druid'?'#7dffa0':'#51f6df',5)
}
function cast(k){
  const s=skills[k];if(s.cd>0)return;s.cd=s.max/(1+.12*buildPower('cooldown'));
  if(chosenCharacter==='warrior'){
    if(k==='q'){rings.push({x:player.x,y:player.y,r:8,max:145,life:.5,color:'#ffb85c'});enemies.forEach(e=>{if(dist(e,player)<145)e.hp-=playerDamage(48)});healAllies(player.powerBuff>0?12:6);screenShake=7}
    else if(k==='e'){const a=Math.atan2(mouse.y+camera.y-player.y,mouse.x+camera.x-player.x);for(let d=190;d>20;d-=10){const nx=player.x+Math.cos(a)*d,ny=player.y+Math.sin(a)*d;if(!blocked(nx,ny,player.r)){const ox=player.x,oy=player.y;for(let i=0;i<7;i++)playerEchoes.push({x:ox+(nx-ox)*i/6,y:oy+(ny-oy)*i/6,angle:a,life:.38-i*.025});burst(ox,oy,'#ffcc78',22);rings.push({x:ox,y:oy,r:4,max:48,life:.35,color:'#ffb85c'});player.x=nx;player.y=ny;player.teleportAnim=.42;rings.push({x:nx,y:ny,r:4,max:72,life:.48,color:'#fff0a6'});burst(nx,ny,'#fff0a6',25);screenShake=7;break}}}
    else{player.powerBuff=9;rings.push({x:player.x,y:player.y,r:8,max:110,life:.7,color:'#ff744f'});screenShake=8}
  }else if(chosenCharacter==='druid'){
    if(k==='q'){healAllies(28);rings.push({x:player.x,y:player.y,r:5,max:175,life:.7,color:'#70ff9a'});burst(player.x,player.y,'#70ff9a',20)}
    else if(k==='e'){player.speedBuff=6;burst(player.x,player.y,'#9dffcf',16)}
    else{player.hp=player.maxHp;skills.q.cd=0;skills.e.cd=0;rings.push({x:player.x,y:player.y,r:8,max:260,life:1,color:'#d3ff8c'});burst(player.x,player.y,'#d3ff8c',35)}
  }else if(k==='q'){const a=Math.atan2(mouse.y+camera.y-player.y,mouse.x+camera.x-player.x);for(let i=-2;i<=2;i++){const aa=a+i*.11;bullets.push({x:player.x,y:player.y,vx:Math.cos(aa)*720,vy:Math.sin(aa)*720,r:7,life:.7,damage:playerDamage(30),pierce:2})}screenShake=6}
  else if(k==='e'){rings.push({x:player.x,y:player.y,r:5,max:190,life:.5,lifeMax:.5,color:'#4cc8ff',effect:'scoutE'});enemies.forEach(e=>{if(dist(e,player)<190){e.hp-=35;const a=Math.atan2(e.y-player.y,e.x-player.x);e.x+=Math.cos(a)*70;e.y+=Math.sin(a)*70}});burst(player.x,player.y,'#51f6df',18);player.invuln=1}
  else{rings.push({x:player.x,y:player.y,r:10,max:500,life:1,lifeMax:1,color:'#b66cff',effect:'scoutR'});enemies.forEach(e=>{if(dist(e,player)<500)e.hp-=110});screenShake=14;for(let i=0;i<60;i++)burst(player.x,player.y,i%2?'#a06cff':'#51f6df',1)}
}

function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function burst(x,y,color,n=8){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=Math.random()*120+25;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.3,color,size:Math.random()*3+1})}}
function update(dt){elapsed+=dt;const survivedMinutes=Math.floor(elapsed/60);if(survivedMinutes>awardedMinutes){const minutes=survivedMinutes-awardedMinutes,earned=minutes*(items.vault?2:1);awardedMinutes=survivedMinutes;awardCurrency(earned,items.vault?'SKARBIEC · CZAS PRZETRWANIA':earned===1?'MINUTA PRZETRWANIA':'CZAS PRZETRWANIA')}saveClock+=dt;if(saveClock>=2){saveClock=0;saveGame()}flowClock-=dt;if(flowClock<=0){rebuildFlow();flowClock=.4}statsClock+=dt;if(statsClock>=1){savedStats.totalTime+=Math.floor(statsClock);statsClock%=1;saveStats()}player.invuln=Math.max(0,player.invuln-dt);player.powerBuff=Math.max(0,(player.powerBuff||0)-dt);player.speedBuff=Math.max(0,(player.speedBuff||0)-dt);player.attackAnim=Math.max(0,(player.attackAnim||0)-dt);player.teleportAnim=Math.max(0,(player.teleportAnim||0)-dt);playerEchoes.forEach(e=>e.life-=dt);playerEchoes=playerEchoes.filter(e=>e.life>0);Object.values(skills).forEach(s=>s.cd=Math.max(0,s.cd-dt));let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(dx,dy)||1,speed=player.speed*(1+.1*buildPower('speed'))*(player.speedBuff>0?1.55:1);const nextX=player.x+dx/l*speed*dt,nextY=player.y+dy/l*speed*dt;if(!blocked(nextX,player.y,player.r))player.x=nextX;if(!blocked(player.x,nextY,player.r))player.y=nextY;camera.x=Math.max(0,Math.min(WORLD.w-W,player.x-W/2));camera.y=Math.max(0,Math.min(WORLD.h-H,player.y-H/2));shotClock-=dt;if(shotClock<=0){shoot();shotClock=.62/Math.pow(1.14,buildPower('rapid'))}updateDirector(dt)
  bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;b.spin=(b.spin||0)+dt*10;if(projectileBlocked(b.x,b.y)){b.life=0;burst(b.x,b.y,'#8ca1b5',5)}});enemyBullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(projectileBlocked(b.x,b.y))b.life=0;if(b.life>0&&dist(b,player)<b.r+player.r&&player.invuln<=0){b.life=0;player.hp-=b.boss?14:(b.damage||10);player.invuln=.5;screenShake=7;freezeUntil=performance.now()+35;GameFeedback.hurt();burst(player.x,player.y,'#ff9d57',10)}});enemyBullets=enemyBullets.filter(b=>b.life>0);hitCrates();crates.forEach(c=>c.hit=Math.max(0,c.hit-dt));collectLoot();
  enemies.forEach(e=>{updateEnemy(e,dt);e.hit=Math.max(0,e.hit-dt);if(dist(e,player)<e.r+player.r&&player.invuln<=0){const damage=(isBoss(e)?24:e.type==='brute'||e.type==='charger'?16:e.type==='swarm'?5:9)*(e.elite?1.65:1);player.hp-=damage;player.invuln=.55;screenShake=9;freezeUntil=performance.now()+40;GameFeedback.hurt();burst(player.x,player.y,'#ff5577',12)}});
  bullets.forEach(b=>enemies.forEach(e=>{if(b.life>0&&e.hp>0&&dist(b,e)<b.r+e.r&&e.hit<=0){const crit=Math.random()<.1,dmg=b.damage*(crit?1.8:1);e.hp-=dmg;e.hit=.09;if(crit||dmg>=24||Math.random()<.22)damageNumbers.push({x:e.x+(Math.random()-.5)*10,y:e.y-e.r*.55,value:Math.round(dmg),crit,life:.65});if(isBoss(e)&&dmg>=30){freezeUntil=performance.now()+35;screenShake=Math.max(screenShake,5);GameFeedback.heavy()}else GameFeedback.hit();b.pierce=(b.pierce||0)-1;if(b.pierce<0)b.life=0;burst(e.x,e.y,'#58e9e0',4)}}));
  enemies.filter(e=>e.hp<=0).forEach(e=>{player.kills++;player.hp=Math.min(player.maxHp,player.hp+buildPower('lifesteal')*.8);savedStats.totalKills++;saveStats();const value=isBoss(e)?20:e.type==='brute'?6:e.type==='swarm'?1:3;orbs.push({x:e.x,y:e.y,r:5,value,vx:0,vy:0});if(e.elite)loot.push({x:e.x,y:e.y-8,type:'level',r:12,bob:Math.random()*6.28,elite:true});if(isBoss(e)){rings.push({x:e.x,y:e.y,r:10,max:400,life:1,color:BOSS_DATA[e.bossTier].color});for(let i=0;i<70;i++)burst(e.x,e.y,BOSS_DATA[e.bossTier].color,1);rewardBoss(e.bossTier)}else if(e.type==='exploder'){rings.push({x:e.x,y:e.y,r:8,max:145,life:.55,color:'#ff8b38'});if(dist(e,player)<145&&player.invuln<=0){player.hp-=18*(e.elite?1.65:1);player.invuln=.6;screenShake=12}for(let i=0;i<30;i++)burst(e.x,e.y,i%2?'#ff8b38':'#ffe26d',1)}else burst(e.x,e.y,e.type==='brute'?'#b56cff':'#ff5577',e.type==='swarm'?7:14)});enemies=enemies.filter(e=>e.hp>0);
  const magnet=105*Math.pow(1.32,buildPower('magnet'));orbs.forEach(o=>{const d=dist(o,player);if(d<magnet){const a=Math.atan2(player.y-o.y,player.x-o.x),v=200+(magnet-d)*4;o.x+=Math.cos(a)*v*dt;o.y+=Math.sin(a)*v*dt}if(d<player.r+10){o.dead=true;gainXp(o.value)}});orbs=orbs.filter(o=>!o.dead);
  damageNumbers.forEach(n=>{n.y-=28*dt;n.life-=dt});damageNumbers=damageNumbers.filter(n=>n.life>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95;p.life-=dt});particles=particles.filter(p=>p.life>0);rings.forEach(r=>{r.r+=(r.max-r.r)*9*dt;r.life-=dt});rings=rings.filter(r=>r.life>0);bullets=bullets.filter(b=>b.life>0);screenShake*=.87;if(player.hp<=0)gameOver();updateUI()}
function gainXp(n){player.xp+=n;burst(player.x,player.y,'#51f6df',3);while(player.xp>=player.nextXp){player.xp-=player.nextXp;player.level++;player.nextXp=Math.floor(player.nextXp*1.34);levelChoicesQueued++}if(levelChoicesQueued>0&&!paused)showLevelUp()}
function upgradeCandidates(bossMode){
  const itemTypes=Object.keys(items),augmentTypes=Object.keys(augments),cards=[];
  if(bossMode)itemDefs.filter(d=>!d.rare&&items[d.id]===5).forEach(d=>cards.push({kind:'super',def:d,key:'super-'+d.id}));
  itemDefs.filter(d=>!d.rare&&(items[d.id]||0)<5&&(items[d.id]||itemTypes.length<3)).forEach(d=>cards.push({kind:'item',def:d,key:'item-'+d.id}));
  itemDefs.filter(d=>!d.rare&&(augments[d.id]||augmentTypes.length<3)).forEach(d=>cards.push({kind:'augment',def:d,key:'augment-'+d.id}));
  const rare=!bossMode&&!items.vault&&itemTypes.length<3&&Math.random()<.1?{kind:'rare',def:itemDefs.find(d=>d.id==='vault'),key:'rare-vault'}:null,supers=cards.filter(c=>c.kind==='super'),rest=cards.filter(c=>c.kind!=='super').sort(()=>Math.random()-.5);return [...supers,...(rare?[rare]:[]),...rest].slice(0,3)
}
function showLevelUp(forceBoss=false){
  const bossMode=forceBoss||bossChoicesQueued>0;paused=true;ui.newLevel.textContent=player.level;ui.levelDescription.textContent=bossMode?'Nagroda za bossa. Przedmiot na 5. poziomie może otrzymać wyjątkowe superulepszenie.':'Wybierz przedmiot albo augment. Przedmioty mają maksymalnie 5 poziomów.';ui.levelModal.classList.remove('hidden');saveGame();const picks=upgradeCandidates(bossMode);ui.cards.innerHTML=picks.map(c=>{const d=c.def,lvl=c.kind==='augment'?(augments[d.id]||0)+1:c.kind==='super'?6:(items[d.id]||0)+1,label=c.kind==='super'?'SUPERULEPSZENIE':c.kind==='augment'?'AUGMENT':c.kind==='rare'?'RZADKI PRZEDMIOT':'PRZEDMIOT',name=c.kind==='augment'?`Augment: ${d.name}`:c.kind==='super'?`${d.name} — Mityczny`:d.name;return `<button class="card ${c.kind}" data-key="${c.key}" style="--card:${d.color}"><div class="rarity">${label}</div><div class="card-art ${d.id}" style="--glow:${d.color}"><i></i>${itemIconSvg(d.id,c.kind==='augment')}<i></i></div><h3>${name}</h3><p>${d.desc}${c.kind==='augment'?' Słabszy efekt, ale wzmacnia też odpowiadający mu przedmiot.':''}</p><span class="level">${c.kind==='augment'?'POZIOM '+lvl:c.kind==='super'?'POZIOM SPECJALNY':c.kind==='rare'?'UNIKAT · 1/1':'POZIOM '+lvl}</span></button>`}).join('');ui.cards.querySelectorAll('.card').forEach(card=>card.onclick=()=>chooseUpgrade(card.dataset.key,bossMode))
}
function chooseUpgrade(key,bossMode){
  const [kind,id]=key.split('-'),oldMax=player.maxHp;if(kind==='augment')augments[id]=(augments[id]||0)+1;else if(kind==='super')items[id]=6;else if(kind==='rare')items[id]=1;else items[id]=(items[id]||0)+1;refreshDerivedStats(true);if(id==='vital'&&player.maxHp===oldMax)player.hp=Math.min(player.maxHp,player.hp+5);if(bossMode)bossChoicesQueued=Math.max(0,bossChoicesQueued-1);else levelChoicesQueued=Math.max(0,levelChoicesQueued-1);ui.levelModal.classList.add('hidden');renderSlots();paused=false;if(bossChoicesQueued>0)showLevelUp(true);else if(levelChoicesQueued>0)showLevelUp(false);saveGame()
}
function renderBuildSlots(target,entries,kind){target.innerHTML='';for(let i=0;i<3;i++){const entry=entries[i],el=document.createElement('div');el.className='slot '+kind+(entry?' filled':'');if(entry){const d=itemDefs.find(x=>x.id===entry[0]),level=entry[1];el.style.color=d.color;el.innerHTML=`${itemIconSvg(d.id,kind==='augment')}<b>${d.rare?'UNIKAT':kind==='augment'?'×'+level:'LV '+level}</b>`;el.title=d.name}target.appendChild(el)}}
function renderSlots(){const itemEntries=Object.entries(items),augmentEntries=Object.entries(augments);renderBuildSlots(ui.slots,itemEntries,'item-slot');renderBuildSlots(ui.augmentSlots,augmentEntries,'augment-slot');ui.itemCount.textContent=itemEntries.length+' / 3';ui.augmentCount.textContent=augmentEntries.length+' / 3'}renderSlots();

function updateUI(){const stage=Math.min(3,Math.floor((elapsed%300)/120)+1),untilBoss=Math.max(0,300-(elapsed%300)),boss=enemies.find(isBoss);ui.phaseLabel.textContent=`RUINY · ETAP ${stage}/3`;ui.bossEta.textContent=boss?'BOSS W WALCE':`BOSS ZA ${formatTime(untilBoss)}`;ui.bossHud.classList.toggle('hidden',!boss);if(boss){ui.bossName.textContent=boss.bossName.toUpperCase();ui.bossHealthText.textContent=Math.ceil(Math.max(0,boss.hp/boss.max*100))+'%';ui.bossHealthBar.style.width=Math.max(0,boss.hp/boss.max*100)+'%';ui.bossHealthBar.style.background=BOSS_DATA[boss.bossTier].color}ui.timer.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;ui.kills.textContent=player.kills;ui.level.textContent=ui.xpLevel.textContent=player.level;ui.healthText.textContent=`${Math.ceil(player.hp)} / ${player.maxHp}`;ui.healthBar.style.width=Math.max(0,player.hp/player.maxHp*100)+'%';ui.xpText.textContent=`${player.xp} / ${player.nextXp} XP`;ui.xpBar.style.width=player.xp/player.nextXp*100+'%';document.querySelector('#coordinates').textContent=`X ${String(Math.round(player.x)).padStart(4,'0')} · Y ${String(Math.round(player.y)).padStart(4,'0')}`;for(const [k,s] of Object.entries(skills)){const el=document.querySelector(`[data-key="${k.toUpperCase()}"]`);el.classList.toggle('cooldown',s.cd>0);el.querySelector('.cd').textContent=s.cd>0?s.cd.toFixed(s.cd<10?1:0):''}}
function winMap(){if(!running)return;running=false;clearGameSave();paused=true;savedStats.bestTime=Math.max(savedStats.bestTime,Math.floor(elapsed));savedStats.bestKills=Math.max(savedStats.bestKills,player.kills);saveStats();ui.endEyebrow.textContent='MAPA UKOŃCZONA';ui.endTitle.innerHTML='ZWYCIĘSTWO';ui.endStats.textContent=`Pokonano Serce Otchłani • ${player.kills} eliminacji • poziom ${player.level}`;ui.endModal.classList.remove('hidden')}
function quitToMenu(){if(!running)return;running=false;paused=true;clearGameSave();location.reload()}
function gameOver(){if(!running)return;running=false;clearGameSave();paused=true;savedStats.bestTime=Math.max(savedStats.bestTime,Math.floor(elapsed));savedStats.bestKills=Math.max(savedStats.bestKills,player.kills);saveStats();ui.pauseModal.classList.add('hidden');ui.endStats.textContent=`Przetrwano ${ui.timer.textContent} • ${player.kills} eliminacji • poziom ${player.level}`;ui.endModal.classList.remove('hidden')}
function drawTerrain(){terrain.forEach(t=>{ctx.save();if(t.type==='water'){tracePolygon(ctx,t.points);const water=ctx.createLinearGradient(t.points[0][0],t.points[0][1],t.points[2][0],t.points[2][1]);water.addColorStop(0,'#082b3b');water.addColorStop(1,'#0d5265');ctx.fillStyle=water;ctx.fill();ctx.clip();ctx.strokeStyle='rgba(88,222,229,.16)';ctx.lineWidth=3;for(let y=0;y<WORLD.h;y+=24){ctx.beginPath();ctx.moveTo(0,y+Math.sin(elapsed+y)*5);ctx.lineTo(WORLD.w,y);ctx.stroke()}ctx.restore();ctx.save();tracePolygon(ctx,t.points);ctx.strokeStyle='#25788a';ctx.lineWidth=5;ctx.stroke()}else if(t.type==='wall'){ctx.fillStyle='#263346';ctx.strokeStyle='#64748a';ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor='#000';ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeRect(t.x,t.y,t.w,t.h);ctx.fillStyle='#151e2d';for(let x=t.x+12;x<t.x+t.w-8;x+=34)for(let y=t.y+10;y<t.y+t.h-8;y+=30)ctx.fillRect(x,y,18,7)}else{const g=ctx.createRadialGradient(t.x-t.r*.3,t.y-t.r*.35,5,t.x,t.y,t.r);g.addColorStop(0,'#435064');g.addColorStop(.45,'#263246');g.addColorStop(1,'#111a28');ctx.fillStyle=g;ctx.strokeStyle='#536176';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<11;i++){const a=i/11*Math.PI*2,rr=t.r*(.78+(i%4)*.07);ctx.lineTo(t.x+Math.cos(a)*rr,t.y+Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#73819655';ctx.beginPath();ctx.moveTo(t.x-t.r*.45,t.y-t.r*.3);ctx.lineTo(t.x+t.r*.1,t.y-t.r*.05);ctx.lineTo(t.x+t.r*.42,t.y+t.r*.32);ctx.stroke()}ctx.restore()})}
function drawScenery(s){
  ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.rot);
  if(s.type==='crystal'){ctx.shadowBlur=16;ctx.shadowColor='rgba(43,192,191,.35)';ctx.fillStyle='#122f3b';ctx.strokeStyle='#277a83';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-s.size);ctx.lineTo(s.size*.55,4);ctx.lineTo(s.size*.25,s.size*.65);ctx.lineTo(-s.size*.38,s.size*.45);ctx.lineTo(-s.size*.55,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(0,-s.size);ctx.lineTo(0,s.size*.45);ctx.lineTo(s.size*.55,4);ctx.stroke()}
  else{ctx.fillStyle='#131d2e';ctx.strokeStyle='#344860';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,s.size,0,7);ctx.fill();ctx.stroke();ctx.strokeStyle='#51f6df44';for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.moveTo(s.size*.3,0);ctx.lineTo(s.size*.78,0);ctx.stroke()}ctx.fillStyle='#050912';ctx.beginPath();ctx.arc(0,0,s.size*.3,0,7);ctx.fill()}
  ctx.restore();
}
function drawLoot(item){const y=item.y+Math.sin(elapsed*4+item.bob)*4,color=item.type==='health'?'#ff6688':item.type==='xp'?'#51f6df':'#ffd467';ctx.save();ctx.translate(item.x,y);ctx.shadowBlur=20;ctx.shadowColor=color;ctx.fillStyle=color;if(item.type==='health'){ctx.fillRect(-3,-10,6,20);ctx.fillRect(-10,-3,20,6)}else if(item.type==='xp'){ctx.rotate(Math.PI/4);ctx.fillRect(-7,-7,14,14)}else if(item.type==='coin'){ctx.rotate(elapsed*1.8);ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*11,Math.sin(a)*11)}ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#fff0a0';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#33280d';ctx.fillRect(-2,-5,4,10);ctx.fillRect(-5,-2,10,4)}else{ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?5:11;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill()}ctx.restore()}
function drawCrate(c){ctx.save();ctx.translate(c.x,c.y);ctx.shadowBlur=c.opened?5:14;ctx.shadowColor=c.reward==='health'?'#ff6688':c.reward==='level'?'#ffd467':'#d99b45';ctx.fillStyle=c.hit?'#fff':c.opened?'#151b24':'#49351e';ctx.strokeStyle=c.opened?'#394657':'#d39a48';ctx.lineWidth=2;ctx.fillRect(-17,-14,34,28);ctx.strokeRect(-17,-14,34,28);ctx.fillStyle=c.opened?'#0b0e14':'#8c612c';ctx.fillRect(-3,-14,6,28);ctx.fillRect(-17,-3,34,6);if(c.opened){ctx.rotate(-.5);ctx.fillStyle='#293342';ctx.fillRect(-18,-21,36,7)}else{ctx.fillStyle='#ffd071';ctx.beginPath();ctx.arc(0,0,4,0,7);ctx.fill()}ctx.restore()}
function drawEnemy(e){
  const angle=Math.atan2(player.y-e.y,player.x-e.x),bob=Math.sin(elapsed*7+e.phase);
  ctx.save();ctx.translate(e.x,e.y);ctx.rotate(angle);
  if(e.elite){ctx.save();ctx.rotate(-angle);ctx.strokeStyle='#80f7ff';ctx.shadowBlur=18;ctx.shadowColor='#45dfff';ctx.lineWidth=2;ctx.globalAlpha=.55+.25*Math.sin(elapsed*13+e.phase);for(let i=0;i<3;i++){const a=i/3*Math.PI*2+elapsed*.7,r=e.r*(1.35+.12*Math.sin(elapsed*5+i));ctx.beginPath();ctx.arc(0,0,r,a,a+.8);ctx.stroke();ctx.fillStyle='#d9ffff';ctx.fillRect(Math.cos(a)*r-1,Math.sin(a)*r-1,3,3)}ctx.restore()}
  if(!drawEnemyModel(ctx,e,{time:elapsed,hit:e.hit>0,bossData:BOSS_DATA})){
    const brute=e.type==='brute';ctx.scale(1+bob*.04,1+bob*.04);ctx.shadowBlur=e.hit?24:14;ctx.shadowColor=brute?'#a06cff':'#ff3e6d';ctx.fillStyle=e.hit?'#fff':brute?'#3e255e':'#411629';ctx.strokeStyle=brute?'#c781ff':'#ff557c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.r*1.18,0);ctx.bezierCurveTo(e.r*.45,-e.r*.9,-e.r*.5,-e.r,-e.r*.85,-e.r*.35);ctx.lineTo(-e.r*1.25,-e.r*.7);ctx.lineTo(-e.r*.92,0);ctx.lineTo(-e.r*1.25,e.r*.7);ctx.bezierCurveTo(-e.r*.5,e.r,e.r*.45,e.r*.9,e.r*1.18,0);ctx.fill();ctx.stroke();ctx.fillStyle=brute?'#d4a0ff':'#ff9aae';ctx.beginPath();ctx.ellipse(e.r*.35,-e.r*.22,e.r*.2,e.r*.11,-.25,0,7);ctx.ellipse(e.r*.35,e.r*.22,e.r*.2,e.r*.11,.25,0,7);ctx.fill();
  }
  ctx.restore();
  if(isBoss(e)){const w=150,y=e.y-e.r-27;ctx.fillStyle='rgba(4,6,12,.9)';ctx.fillRect(e.x-w/2,y,w,10);ctx.fillStyle=BOSS_DATA[e.bossTier].color;ctx.fillRect(e.x-w/2+2,y+2,(w-4)*Math.max(0,e.hp/e.max),6);ctx.fillStyle='#fff';ctx.font='700 11px Chakra Petch';ctx.textAlign='center';ctx.fillText(e.bossName,e.x,y-6)}
  else if(e.elite||e.type==='brute'||e.type==='charger'){const width=e.elite?58:44;ctx.fillStyle='#101522';ctx.fillRect(e.x-width/2,e.y-e.r-14,width,5);ctx.fillStyle=e.elite?'#64efff':e.type==='charger'?'#62a4ff':'#a96cff';ctx.fillRect(e.x-width/2,e.y-e.r-14,width*Math.max(0,e.hp/e.max),5)}
}
function drawCharacterModel(context,id,x,y,scale=1,angle=0,time=elapsed){
  context.save();context.translate(x,y);context.rotate(angle);context.scale(scale,scale);
  if(id==='warrior'){const pulse=1+Math.sin(time*5)*.03;context.scale(pulse,pulse);context.shadowBlur=24;context.shadowColor=player.powerBuff>0?'#ff4f3f':'#ffb85c';context.fillStyle='#38251f';context.strokeStyle=player.powerBuff>0?'#ff6655':'#ffcc78';context.lineWidth=2.5;context.beginPath();context.moveTo(19,0);context.lineTo(8,-15);context.lineTo(-10,-13);context.lineTo(-18,-5);context.lineTo(-18,5);context.lineTo(-10,13);context.lineTo(8,15);context.closePath();context.fill();context.stroke();context.fillStyle='#ffe1a0';context.beginPath();context.arc(1,0,6,0,7);context.fill();context.strokeStyle='#fff0bd';context.lineWidth=4;context.beginPath();context.moveTo(5,-7);context.lineTo(25,-20);context.moveTo(21,-23);context.lineTo(29,-15);context.stroke();context.fillStyle='#a8693e';context.fillRect(-22,-3,13,6);context.strokeStyle='#ff9e52';context.lineWidth=2;context.beginPath();context.moveTo(-8,-12);context.lineTo(2,-18);context.lineTo(12,-13);context.moveTo(-8,12);context.lineTo(2,18);context.lineTo(12,13);context.stroke();context.fillStyle='#6c3328';context.beginPath();context.moveTo(-13,-10);context.lineTo(-28,-15);context.lineTo(-25,0);context.lineTo(-13,4);context.closePath();context.fill();context.strokeStyle='#ffc870';context.stroke();context.fillStyle='#29140f';context.beginPath();context.arc(-24,-8,4,0,7);context.fill()}
  else if(id==='druid'){context.shadowBlur=25;context.shadowColor='#70ff9a';context.fillStyle='#123a2b';context.strokeStyle='#82ffab';context.lineWidth=2.5;context.beginPath();for(let i=0;i<8;i++){const a=i/8*6.28,r=i%2?13:19;context.lineTo(Math.cos(a)*r,Math.sin(a)*r)}context.closePath();context.fill();context.stroke();context.fillStyle='#d9ffbd';context.beginPath();context.arc(0,0,6,0,7);context.fill();context.strokeStyle='#a5ff83';context.lineWidth=3;context.beginPath();context.moveTo(-4,-13);context.quadraticCurveTo(-16,-27,-24,-19);context.moveTo(4,-13);context.quadraticCurveTo(16,-27,24,-19);context.stroke();context.fillStyle='#70ff9a';context.beginPath();context.ellipse(19,7,8,3,.5,0,7);context.ellipse(19,-7,8,3,-.5,0,7);context.fill();context.strokeStyle='#d4ff9f';context.lineWidth=2;context.beginPath();context.moveTo(-10,9);context.lineTo(-22,20);context.lineTo(-27,16);context.moveTo(11,9);context.lineTo(23,20);context.lineTo(28,16);context.stroke();context.save();context.rotate(time*.7);for(let i=0;i<3;i++){context.rotate(2.094);context.fillStyle='#64d982';context.beginPath();context.ellipse(0,-25,5,2,.6,0,7);context.fill()}context.restore();context.strokeStyle='#8e633f';context.lineWidth=3;context.beginPath();context.moveTo(-15,-18);context.lineTo(-20,18);context.stroke();context.fillStyle='#b7ff8e';context.beginPath();context.arc(-15,-19,4,0,7);context.fill()}
  else{context.shadowBlur=28;context.shadowColor='#51f6df';context.fillStyle='#0b2630';context.strokeStyle='#61fff0';context.lineWidth=2;context.beginPath();context.moveTo(23,0);context.lineTo(7,-12);context.lineTo(-10,-15);context.lineTo(-5,-6);context.lineTo(-18,-4);context.lineTo(-18,4);context.lineTo(-5,6);context.lineTo(-10,15);context.lineTo(7,12);context.closePath();context.fill();context.stroke();context.fillStyle='#9afff5';context.beginPath();context.moveTo(18,0);context.lineTo(2,-4);context.lineTo(2,4);context.closePath();context.fill();context.fillStyle='#eaffff';context.beginPath();context.arc(-3,0,5,0,7);context.fill();context.strokeStyle='#4cc8ff';context.lineWidth=3;context.beginPath();context.moveTo(-10,-10);context.lineTo(-24,-15);context.moveTo(-10,10);context.lineTo(-24,15);context.stroke();context.fillStyle='#173d54';context.strokeStyle='#65e9ff';context.lineWidth=2;context.beginPath();context.moveTo(-7,-14);context.lineTo(-20,-22);context.lineTo(-29,-12);context.lineTo(-19,-6);context.closePath();context.fill();context.stroke();context.beginPath();context.moveTo(-7,14);context.lineTo(-20,22);context.lineTo(-29,12);context.lineTo(-19,6);context.closePath();context.fill();context.stroke();context.fillStyle='#4cc8ff';context.fillRect(7,-3,18,6);context.fillStyle='#dfffff';context.beginPath();context.arc(23,0,3,0,7);context.fill()}
  context.restore()
}
function drawRotatedSprite(context,image,x,y,width,height,angle=0,alpha=1){context.save();context.translate(x,y);context.rotate(angle);context.globalAlpha*=alpha;context.drawImage(image,-width/2,-height/2,width,height);context.restore()}
function drawScoutModel(context,x,y,scale,angle,time){if(!scoutAssets.ready)return false;context.save();context.translate(x,y);context.rotate(angle);context.scale(scale,scale);if(player.moving){context.globalAlpha=.65+Math.sin(time*32)*.18;context.fillStyle='#8effff';context.shadowBlur=16;context.shadowColor='#37cfff';context.beginPath();context.moveTo(-25,-6);context.lineTo(-38,0);context.lineTo(-25,6);context.fill()}context.globalAlpha=1;context.drawImage(scoutAssets.images.player,-35,-27,70,54);if(player.muzzleFlash>0){context.globalAlpha=Math.min(1,player.muzzleFlash/.06);context.globalCompositeOperation='lighter';context.drawImage(scoutAssets.images.muzzle,22,-18,30,36)}context.restore();return true}
function drawScoutEffect(r,overlay=false){if(!scoutAssets.ready||!r.visualKind)return;const progress=1-r.life/(r.lifeMax||1),fade=Math.min(1,r.life*4),image=r.visualKind==='scoutE'?scoutAssets.images.eRing:scoutAssets.images.rFlash;ctx.save();ctx.globalCompositeOperation='lighter';ctx.globalAlpha=fade*(overlay?.28:.72);ctx.shadowBlur=overlay?12:24;ctx.shadowColor='#55ffff';if(r.visualKind==='scoutE'){const size=Math.max(18,r.r*2.06);ctx.drawImage(image,r.x-size/2,r.y-size/2,size,size)}else{const flash=progress<.28?Math.sin(progress/.28*Math.PI):Math.max(0,1-progress),size=Math.max(45,r.r*2.02);ctx.globalAlpha*=.4+flash*.6;ctx.drawImage(image,r.x-size/2,r.y-size/2,size,size)}ctx.restore()}
function drawPlayer(){const a=Math.atan2(mouse.y+camera.y-player.y,mouse.x+camera.x-player.x);playerEchoes.forEach(e=>{ctx.save();ctx.globalAlpha=Math.max(0,e.life)*.45;drawCharacterModel(ctx,'warrior',e.x,e.y,1,e.angle);ctx.restore()});if(player.speedBuff>0){ctx.strokeStyle='#9dffcf';ctx.globalAlpha=.5;ctx.beginPath();ctx.arc(player.x,player.y,25+Math.sin(elapsed*8)*3,0,7);ctx.stroke();ctx.globalAlpha=1}if(chosenCharacter!=='scout'||!drawScoutModel(ctx,player.x,player.y,1,a,elapsed))drawCharacterModel(ctx,chosenCharacter,player.x,player.y,1,a);if(chosenCharacter==='warrior'&&player.attackAnim>0){const progress=1-player.attackAnim/.28,aa=(player.attackAngle||a)-1.05+progress*2.1;ctx.save();ctx.translate(player.x,player.y);ctx.rotate(aa);ctx.shadowBlur=18;ctx.shadowColor='#ffb85c';ctx.strokeStyle='#fff0b0';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,42,-.5,.5);ctx.stroke();ctx.strokeStyle='#ff7b49';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,50,-.42,.42);ctx.stroke();ctx.restore()}if(player.teleportAnim>0){ctx.save();ctx.globalAlpha=player.teleportAnim/.42;ctx.strokeStyle='#fff4bd';ctx.lineWidth=2;ctx.beginPath();ctx.arc(player.x,player.y,30+(1-player.teleportAnim/.42)*32,0,7);ctx.stroke();ctx.restore()}}

function drawSkillEffect(r){
  const progress=1-r.life/r.lifeMax,fade=Math.min(1,r.life/r.lifeMax*2);ctx.save();ctx.translate(r.x,r.y);ctx.globalCompositeOperation='lighter';ctx.globalAlpha=fade;ctx.shadowBlur=24;ctx.shadowColor=r.effect==='scoutE'?'#51f6df':'#b66cff';
  if(r.effect==='scoutE'){
    ctx.rotate(elapsed*2.8);ctx.strokeStyle='#8ffff4';ctx.lineWidth=4;ctx.setLineDash([18,10]);ctx.beginPath();ctx.arc(0,0,r.r,0,Math.PI*2);ctx.stroke();ctx.rotate(-elapsed*5.6);ctx.strokeStyle='#4cc8ff';ctx.lineWidth=2;ctx.setLineDash([7,13]);ctx.beginPath();ctx.arc(0,0,r.r*.72,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillStyle='#dfffff';ctx.fillRect(r.r*.86,-2,8,4)}
  }else{
    const flash=Math.max(0,1-progress*4),glow=ctx.createRadialGradient(0,0,0,0,0,55+r.r*.18);glow.addColorStop(0,`rgba(255,255,255,${flash})`);glow.addColorStop(.28,`rgba(81,246,223,${flash*.75})`);glow.addColorStop(1,'rgba(160,108,255,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,55+r.r*.18,0,Math.PI*2);ctx.fill();for(let ring=0;ring<3;ring++){ctx.strokeStyle=ring===1?'#d8c3ff':'#71fff1';ctx.lineWidth=ring===1?3:2;ctx.globalAlpha=fade*(1-ring*.22);ctx.beginPath();ctx.arc(0,0,r.r*(1-ring*.13),0,Math.PI*2);ctx.stroke()}ctx.rotate(elapsed*1.7);ctx.globalAlpha=fade;for(let i=0;i<14;i++){ctx.rotate(Math.PI/7);ctx.fillStyle=i%2?'#51f6df':'#c49aff';const distance=r.r*(.5+.35*progress);ctx.beginPath();ctx.moveTo(distance,-3);ctx.lineTo(distance+18+progress*22,0);ctx.lineTo(distance,3);ctx.fill()}
  }ctx.restore()
}

function drawSkillEffect(r){
  const progress=1-r.life/r.lifeMax,fade=Math.min(1,r.life/r.lifeMax*2);ctx.save();ctx.translate(r.x,r.y);ctx.globalCompositeOperation='lighter';ctx.globalAlpha=fade;ctx.shadowBlur=24;ctx.shadowColor=r.effect==='scoutE'?'#51f6df':'#b66cff';
  if(r.effect==='scoutE'){
    ctx.rotate(elapsed*2.8);ctx.strokeStyle='#8ffff4';ctx.lineWidth=4;ctx.setLineDash([18,10]);ctx.beginPath();ctx.arc(0,0,r.r,0,Math.PI*2);ctx.stroke();ctx.rotate(-elapsed*5.6);ctx.strokeStyle='#4cc8ff';ctx.lineWidth=2;ctx.setLineDash([7,13]);ctx.beginPath();ctx.arc(0,0,r.r*.72,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillStyle='#dfffff';ctx.fillRect(r.r*.86,-2,8,4)}
  }else{
    const flash=Math.max(0,1-progress*4),glow=ctx.createRadialGradient(0,0,0,0,0,55+r.r*.18);glow.addColorStop(0,`rgba(255,255,255,${flash})`);glow.addColorStop(.28,`rgba(81,246,223,${flash*.75})`);glow.addColorStop(1,'rgba(160,108,255,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,55+r.r*.18,0,Math.PI*2);ctx.fill();for(let ring=0;ring<3;ring++){ctx.strokeStyle=ring===1?'#d8c3ff':'#71fff1';ctx.lineWidth=ring===1?3:2;ctx.globalAlpha=fade*(1-ring*.22);ctx.beginPath();ctx.arc(0,0,r.r*(1-ring*.13),0,Math.PI*2);ctx.stroke()}ctx.rotate(elapsed*1.7);ctx.globalAlpha=fade;for(let i=0;i<14;i++){ctx.rotate(Math.PI/7);ctx.fillStyle=i%2?'#51f6df':'#c49aff';const distance=r.r*(.5+.35*progress);ctx.beginPath();ctx.moveTo(distance,-3);ctx.lineTo(distance+18+progress*22,0);ctx.lineTo(distance,3);ctx.fill()}
  }ctx.restore()
}

function drawMinimap(){const mw=minimap.width,mh=minimap.height,sx=mw/WORLD.w,sy=mh/WORLD.h;mapCtx.clearRect(0,0,mw,mh);mapCtx.fillStyle='#03070d';mapCtx.fillRect(0,0,mw,mh);tracePolygon(mapCtx,MAP_SHAPE.map(([x,y])=>[x*sx,y*sy]));mapCtx.fillStyle='#0b1b29';mapCtx.fill();mapCtx.strokeStyle='#315467';mapCtx.stroke();mapCtx.strokeStyle='#183247';mapCtx.lineWidth=1;for(let x=0;x<mw;x+=22){mapCtx.beginPath();mapCtx.moveTo(x,0);mapCtx.lineTo(x,mh);mapCtx.stroke()}for(let y=0;y<mh;y+=15){mapCtx.beginPath();mapCtx.moveTo(0,y);mapCtx.lineTo(mw,y);mapCtx.stroke()}terrain.forEach(t=>{if(t.type==='water'){mapCtx.fillStyle='#0d5064';tracePolygon(mapCtx,t.points.map(([x,y])=>[x*sx,y*sy]));mapCtx.fill()}else if(t.type==='wall'){mapCtx.fillStyle='#738398';mapCtx.fillRect(t.x*sx,t.y*sy,t.w*sx,t.h*sy)}else{mapCtx.fillStyle='#3b4657';mapCtx.beginPath();mapCtx.arc(t.x*sx,t.y*sy,t.r*sx,0,7);mapCtx.fill()}});mapCtx.fillStyle='#355064';scenery.filter((_,i)=>i%3===0).forEach(s=>mapCtx.fillRect(s.x*sx,s.y*sy,1.5,1.5));crates.filter(c=>!c.opened).forEach(c=>{mapCtx.fillStyle='#d9a34d';mapCtx.fillRect(c.x*sx-1,c.y*sy-1,3,3)});loot.forEach(i=>{mapCtx.fillStyle=i.type==='health'?'#ff6688':i.type==='xp'?'#51f6df':'#ffd467';mapCtx.fillRect(i.x*sx-1,i.y*sy-1,3,3)});enemies.forEach(e=>{mapCtx.fillStyle=isBoss(e)?BOSS_DATA[e.bossTier].color:({shooter:'#ffb45e',charger:'#62a4ff',exploder:'#ff7638',swarm:'#ed83ff'}[e.type]||'#ff5277');const size=isBoss(e)?7:e.type==='swarm'?2:3;mapCtx.fillRect(e.x*sx-size/2,e.y*sy-size/2,size,size)});mapCtx.strokeStyle='#51f6df55';mapCtx.strokeRect(camera.x*sx,camera.y*sy,W*sx,H*sy);mapCtx.shadowBlur=8;mapCtx.shadowColor='#51f6df';mapCtx.fillStyle='#9ffff3';mapCtx.beginPath();mapCtx.arc(player.x*sx,player.y*sy,3.5,0,7);mapCtx.fill();mapCtx.shadowBlur=0}
function draw(){ctx.save();if(screenShake)ctx.translate((Math.random()-.5)*screenShake,(Math.random()-.5)*screenShake);ctx.fillStyle='#070b15';ctx.fillRect(0,0,W,H);ctx.translate(-camera.x,-camera.y);
  const bg=ctx.createRadialGradient(player.x,player.y,40,player.x,player.y,900);bg.addColorStop(0,'#173144');bg.addColorStop(.6,'#102232');bg.addColorStop(1,'#09131e');tracePolygon(ctx,MAP_SHAPE);ctx.fillStyle=bg;ctx.shadowBlur=30;ctx.shadowColor='#02040a';ctx.fill();ctx.shadowBlur=0;ctx.save();tracePolygon(ctx,MAP_SHAPE);ctx.clip();
  ctx.strokeStyle='rgba(77,148,173,.045)';ctx.lineWidth=1;for(let x=0;x<WORLD.w;x+=120){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.h);ctx.stroke()}for(let y=0;y<WORLD.h;y+=120){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.w,y);ctx.stroke()}ctx.restore();drawTerrain();
  tracePolygon(ctx,MAP_SHAPE);ctx.strokeStyle='#315467';ctx.lineWidth=12;ctx.stroke();ctx.strokeStyle='#51f6df22';ctx.lineWidth=2;ctx.stroke();
  scenery.forEach(s=>{if(s.x>camera.x-60&&s.x<camera.x+W+60&&s.y>camera.y-60&&s.y<camera.y+H+60)drawScenery(s)});
  crates.forEach(drawCrate);loot.forEach(drawLoot);orbs.forEach(o=>{ctx.shadowBlur=16;ctx.shadowColor='#51f6df';ctx.fillStyle='#80fff0';ctx.beginPath();ctx.moveTo(o.x,o.y-o.r);ctx.lineTo(o.x+o.r,o.y);ctx.lineTo(o.x,o.y+o.r);ctx.lineTo(o.x-o.r,o.y);ctx.fill();ctx.shadowBlur=0});
  bullets.forEach(b=>{ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.atan2(b.vy,b.vx)+Math.sin(b.spin*.7)*.18);ctx.shadowBlur=18;ctx.shadowColor=b.kind==='boomerang'?'#70ff9a':'#51f6df';if(b.kind==='boomerang'){ctx.strokeStyle='#baffc9';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,15,-1.1,1.1);ctx.stroke();ctx.strokeStyle='#3fd77b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-2,0,10,-1.05,1.05);ctx.stroke();ctx.fillStyle='#e4ffd9';ctx.beginPath();ctx.moveTo(7,-14);ctx.lineTo(18,-8);ctx.lineTo(10,-4);ctx.fill()}else{ctx.fillStyle='#bafff7';ctx.beginPath();ctx.ellipse(0,0,8,3,0,0,7);ctx.fill()}ctx.restore()});enemyBullets.forEach(b=>{ctx.shadowBlur=18;ctx.shadowColor='#ff8b38';ctx.fillStyle='#ffd078';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.strokeStyle='#ff7a3d';ctx.beginPath();ctx.moveTo(b.x-b.vx*.045,b.y-b.vy*.045);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.shadowBlur=0});enemies.forEach(drawEnemy);
  rings.forEach(r=>{if(r.effect){drawSkillEffect(r);return}ctx.globalAlpha=Math.max(0,r.life);ctx.strokeStyle=r.color;ctx.lineWidth=5;ctx.shadowBlur=20;ctx.shadowColor=r.color;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.stroke();ctx.globalAlpha=1;ctx.shadowBlur=0});particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);ctx.globalAlpha=1});damageNumbers.forEach(n=>{ctx.save();ctx.globalAlpha=Math.min(1,n.life*2.5);ctx.textAlign='center';ctx.font=n.crit?'800 17px Chakra Petch':'700 12px Chakra Petch';ctx.fillStyle=n.crit?'#ffe071':'#e8f7ff';ctx.shadowBlur=n.crit?10:4;ctx.shadowColor=n.crit?'#ff9d35':'#51f6df';ctx.fillText(n.crit?'✦ '+n.value:n.value,n.x,n.y);ctx.restore()});drawPlayer();ctx.restore();drawMinimap()}

function drawSelectionPreviews(){
  ['scout','warrior','druid'].forEach(id=>{const canvas=document.querySelector(`#${id}Preview`),c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,g=c.createRadialGradient(w*.5,h*.5,10,w*.5,h*.5,w*.42);g.addColorStop(0,id==='warrior'?'#533529':id==='druid'?'#174632':'#1d5260');g.addColorStop(1,'#050b14');c.fillStyle=g;c.fillRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.055)';for(let x=0;x<w;x+=42){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<h;y+=42){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}if(id==='scout'&&scoutAssets.ready)drawRotatedSprite(c,scoutAssets.images.player,w*.5,h*.5,230,178,0);else drawCharacterModel(c,id,w*.5,h*.5,4.3,0,0)});
  const map=document.querySelector('#mapPreviewCanvas'),mc=map.getContext('2d'),mw=map.width,mh=map.height,sx=mw/WORLD.w,sy=mh/WORLD.h,mg=mc.createLinearGradient(0,0,mw,mh);mg.addColorStop(0,'#102a3a');mg.addColorStop(1,'#050b13');mc.fillStyle='#03060b';mc.fillRect(0,0,mw,mh);tracePolygon(mc,MAP_SHAPE.map(([x,y])=>[x*sx,y*sy]));mc.fillStyle=mg;mc.shadowBlur=18;mc.shadowColor='#000';mc.fill();mc.shadowBlur=0;terrain.forEach(t=>{if(t.type==='water'){tracePolygon(mc,t.points.map(([x,y])=>[x*sx,y*sy]));mc.fillStyle='#0b5b70';mc.fill();mc.strokeStyle='#38a1ad';mc.stroke()}else if(t.type==='wall'){mc.fillStyle='#718097';mc.fillRect(t.x*sx,t.y*sy,Math.max(2,t.w*sx),Math.max(2,t.h*sy))}else{mc.fillStyle='#3d4a5d';mc.beginPath();mc.arc(t.x*sx,t.y*sy,Math.max(4,t.r*sx),0,7);mc.fill()}});scenery.filter((_,i)=>i%3===0).forEach(o=>{mc.fillStyle=o.type==='crystal'?'#287d83':'#445166';mc.fillRect(o.x*sx,o.y*sy,2,2)});crates.forEach(c=>{mc.fillStyle='#d9a34d';mc.fillRect(c.x*sx-2,c.y*sy-2,4,4)});mc.strokeStyle='#56e9dd';mc.lineWidth=2;tracePolygon(mc,MAP_SHAPE.map(([x,y])=>[x*sx,y*sy]));mc.stroke()
}
updateCoinDisplays();addEventListener('beforeunload',()=>saveGame());addEventListener('visibilitychange',()=>{if(document.hidden)saveGame()});refreshContinueButton();drawSelectionPreviews();
function loop(t){const dt=Math.min((t-last)/1000,.033);last=t;if(running&&!paused&&t>=freezeUntil)update(dt);draw();requestAnimationFrame(loop)}draw();
document.querySelectorAll('.ability canvas').forEach((c,i)=>{const x=c.getContext('2d'),colors=['#51f6df','#4cc8ff','#a06cff'];x.strokeStyle=colors[i];x.lineWidth=4;x.shadowBlur=12;x.shadowColor=colors[i];x.beginPath();if(i===0){x.moveTo(18,52);x.lineTo(53,17);x.moveTo(25,53);x.lineTo(55,23)}else if(i===1){x.arc(36,36,18,0,Math.PI*1.7);x.lineTo(47,27)}else{for(let a=0;a<7;a++){const r=a%2?10:23,aa=-Math.PI/2+a*Math.PI/3.5;x.lineTo(36+Math.cos(aa)*r,36+Math.sin(aa)*r)}x.closePath()}x.stroke()});
