(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.SwarmI18n=api})(typeof globalThis!=='undefined'?globalThis:this,root=>{
  'use strict';
  const STORAGE_KEY='swarmfall-language';
  const pl={
    'account.cloud':'POSTĘP W CHMURZE','account.title':'TWOJE KONTO','account.subtitle':'Zaloguj się, aby zapisywać postępy, statystyki i odblokowane elementy na koncie.','account.checking':'SPRAWDZANIE SESJI…','account.loginTab':'LOGOWANIE','account.registerTab':'REJESTRACJA','account.identifier':'LOGIN LUB E-MAIL','account.login':'LOGIN','account.email':'E-MAIL','account.password':'HASŁO','account.passwordHint':'Minimum 8 znaków.','account.signIn':'ZALOGUJ SIĘ','account.create':'UTWÓRZ KONTO','account.logout':'WYLOGUJ','account.info':'INFORMACJA','account.understand':'ROZUMIEM',
    'errors.emptyIdentifier':'Wpisz login lub adres e-mail.','errors.emptyLogin':'Wpisz login.','errors.invalidLogin':'Login musi mieć od 3 do 24 znaków i może zawierać litery, cyfry, kropkę, myślnik lub podkreślenie.','errors.emptyEmail':'Wpisz adres e-mail.','errors.invalidEmail':'Podaj prawidłowy adres e-mail.','errors.emptyPassword':'Wpisz hasło.','errors.shortPassword':'Hasło musi mieć minimum 8 znaków.','errors.longPassword':'Hasło może mieć maksymalnie 128 znaków.','errors.taken':'Login lub e-mail jest już zajęty.','errors.credentials':'Nieprawidłowy login/e-mail lub hasło.','errors.network':'Brak połączenia z siecią.','errors.server':'Serwer kont jest chwilowo niedostępny.','errors.expired':'Sesja wygasła. Zaloguj się ponownie.','errors.conflictDetail':'Konflikt zapisu: nowszy postęp istnieje na innym urządzeniu.','account.saving':'ZAPISYWANIE…','account.saved':'ZAPISANO','account.saveError':'OFFLINE / NIE ZAPISANO','account.conflict':'KONFLIKT ZAPISU','account.loggedOut':'Wylogowano.',
    'menu.tagline':'Pokonuj kolejne fale, zbieraj doświadczenie i rozwijaj postać.','menu.newGame':'NOWA GRA','menu.continue':'KONTYNUUJ','menu.noSave':'BRAK ZAPISU','menu.saveFound':'ZAPIS ZNALEZIONY','menu.characters':'POSTACIE','menu.maps':'MAPY','menu.instructions':'JAK GRAĆ','menu.stats':'STATYSTYKI','menu.achievements':'OSIĄGNIĘCIA','menu.settings':'OPCJE','menu.multiplayer':'MULTIPLAYER','menu.playFriends':'GRAJ ZE ZNAJOMYMI','menu.coins':'TWOJE MONETY','menu.back':'← WRÓĆ DO MENU',
    'hud.phase':'ETAP','hud.bossIn':'BOSS ZA {time}','hud.kills':'ELIMINACJE','hud.level':'POZIOM','hud.health':'ŻYCIE','hud.minimap':'MINIMAPA','hud.position':'POZYCJA','hud.items':'PRZEDMIOTY','hud.augments':'AUGMENTY','hud.pause':'PAUZA','hud.newWave':'NOWA FALA','hud.event':'WYDARZENIE','hud.healthAria':'Punkty życia','hud.teamHealthAria':'Zdrowie drużyny','hud.minimapAria':'Minimapa obszaru','hud.equipmentAria':'Ekwipunek','hud.abilitiesAria':'Umiejętności','hud.pauseAria':'Wstrzymaj grę','hud.gameAria':'Pole gry Swarmfall','hud.coinsAria':'Stan monet',
    'game.youDied':'NIE ŻYJESZ','game.spectating':'OBSERWUJESZ SOJUSZNIKA','game.spectatingName':'OBSERWUJESZ: {name}','game.connectionLost':'UTRACONO POŁĄCZENIE','game.reconnecting':'PONOWNE ŁĄCZENIE…','game.gameOver':'KONIEC GRY','game.matchOver':'KONIEC MECZU','game.teamDefeated':'Cała drużyna została pokonana.','game.retry':'SPRÓBUJ PONOWNIE','game.paused':'GRA WSTRZYMANA','game.resume':'WRÓĆ DO GRY','game.quit':'ZAKOŃCZ GRĘ','game.levelUp':'NOWY POZIOM','game.chooseUpgrade':'WYBIERZ WZMOCNIENIE','game.reroll':'PRZERZUĆ','game.wave':'FALA','game.worldEvent':'WYDARZENIE ŚWIATA','game.achievement':'OSIĄGNIĘCIE',
    'multiplayer.title':'GRAJ RAZEM','multiplayer.subtitle':'Stwórz prywatne lobby albo dołącz do znajomego za pomocą kodu.','multiplayer.create':'STWÓRZ LOBBY','multiplayer.createHelp':'Wygeneruj kod i zaproś graczy','multiplayer.join':'DOŁĄCZ DO LOBBY','multiplayer.joinHelp':'Wpisz kod otrzymany od gospodarza','multiplayer.code':'KOD LOBBY','multiplayer.codePlaceholder':'NP. A7K2Q9','multiplayer.copy':'KOPIUJ KOD','multiplayer.copied':'SKOPIOWANO ✓','multiplayer.host':'GOSPODARZ','multiplayer.player':'GRACZ','multiplayer.players':'GRACZE W LOBBY','multiplayer.ready':'GOTOWY','multiplayer.notReady':'OCZEKUJE','multiplayer.cancelReady':'ANULUJ GOTOWOŚĆ','multiplayer.start':'START GRY','multiplayer.leave':'OPUŚĆ','multiplayer.backLobby':'WRÓĆ DO LOBBY','multiplayer.yourLobby':'TWOJE LOBBY','multiplayer.joinedLobby':'DOŁĄCZONO DO LOBBY','multiplayer.mapHost':'MAPA · WYBIERA GOSPODARZ','multiplayer.character':'TWOJA POSTAĆ','multiplayer.invalidCode':'Kod lobby musi mieć 6 znaków.','multiplayer.noConnection':'Brak połączenia z serwerem multiplayer.','multiplayer.copyFailed':'Nie udało się skopiować kodu lobby.','multiplayer.replaced':'Ta karta została zastąpiona przez nowsze połączenie.','multiplayer.reconnectExpired':'Sesja ponownego łączenia wygasła.','multiplayer.matchWithoutYou':'MECZ ROZPOCZĄŁ SIĘ BEZ CIEBIE · DOŁĄCZ DO NOWEGO LOBBY','multiplayer.waitingPlayers':'OCZEKIWANIE NA POZOSTAŁYCH GRACZY…','multiplayer.waitingProgress':'OCZEKIWANIE NA POZOSTAŁYCH GRACZY… {ready} / {required}','multiplayer.loading':'PRZYGOTOWYWANIE MECZU · ŁADOWANIE ZASOBÓW','multiplayer.loadFailed':'NIE UDAŁO SIĘ ZAŁADOWAĆ ZASOBÓW · PONÓW','multiplayer.waterRuins':'WODA · RUINY','multiplayer.fogPoison':'MGŁA · TRUCIZNA',
    'settings.language':'JĘZYK','settings.help':'Wybierz język interfejsu. Zmiana zostanie zapisana.','settings.polish':'POLSKI','settings.english':'ENGLISH',
    'assets.title':'ŁADOWANIE ZASOBÓW','assets.preparing':'PRZYGOTOWYWANIE FINALNYCH GRAFIK…','assets.retry':'PONÓW',
    'characters.scout':'Zwiadowca','characters.warrior':'Wojownik','characters.druid':'Druid','characters.range':'DYSTANS','characters.melee':'WALKA WRĘCZ','characters.support':'WSPARCIE','characters.selected':'WYBRANO ✓','characters.unlock':'{cost} MONET · ODBLOKUJ','characters.scoutDesc':'Automatyczne działko, odrzut i potężny wybuch obszarowy.','characters.warriorDesc':'Leczy się atakami, teleportuje po użyciu E i czasowo wzmacnia obrażenia.','characters.druidDesc':'Strzela falami, leczy sojuszników i zwiększa ich mobilność.',
    'maps.ruins':'Zalane ruiny','maps.toxic':'Toksyczne pustkowie','maps.available':'DOSTĘPNA','maps.locked':'ZABLOKOWANA','maps.selected':'WYBRANO ✓','maps.unlockToxic':'UKOŃCZ ZALANE RUINY','maps.ruinsDesc':'Średniej wielkości teren ze skałami, wodą i pozostałościami murów.','maps.toxicDesc':'Skażone plamy, trująca mgła, pułapki oraz nowe odmiany przeciwników i bossów.',
    'instructions.title':'JAK GRAĆ','instructions.movement':'RUCH','instructions.movementDesc':'Poruszaj się po strefie i omijaj wodę, skały oraz mury.','instructions.attack':'ATAK','instructions.attackDesc':'Celuj myszką. Broń automatycznie strzela w stronę kursora.','instructions.abilities':'UMIEJĘTNOŚCI','instructions.abilitiesDesc':'Q uruchamia salwę, E odrzuca wrogów, a R powoduje potężny wybuch.','instructions.evolution':'EWOLUCJA','instructions.evolutionDesc':'Zbieraj rdzenie XP i wybieraj jedną z trzech kart po awansie.','instructions.coins':'MONETY','instructions.coinsDesc':'Otrzymujesz 1 monetę za każdą minutę przetrwania oraz 5 monet za pokonanie bossa.',
    'stats.title':'TWOJE STATYSTYKI','stats.bestTime':'NAJDŁUŻSZA GRA','stats.totalTime':'ŁĄCZNY CZAS GRY','stats.bestKills':'REKORD ELIMINACJI','stats.totalKills':'ŁĄCZNE ELIMINACJE','stats.scoutGames':'GRY · ZWIADOWCA','stats.warriorGames':'GRY · WOJOWNIK','stats.druidGames':'GRY · DRUID',
    'achievements.title':'OSIĄGNIĘCIA','achievements.progress':'POSTĘP KONTA','achievements.subtitle':'Nagrody można odebrać tylko raz. Postęp jest zapisany na Twoim koncie.','common.none':'brak','common.unique':'UNIKAT','common.locked':'ZABLOKOWANE','common.active':'AKTYWNE','common.possible':'MOŻLIWE'
  };
  const en={...pl,
    'account.cloud':'CLOUD PROGRESS','account.title':'YOUR ACCOUNT','account.subtitle':'Sign in to save progress, statistics, and unlocks to your account.','account.checking':'CHECKING SESSION…','account.loginTab':'SIGN IN','account.registerTab':'REGISTER','account.identifier':'LOGIN OR EMAIL','account.password':'PASSWORD','account.passwordHint':'At least 8 characters.','account.signIn':'SIGN IN','account.create':'CREATE ACCOUNT','account.logout':'LOG OUT','account.info':'INFORMATION','account.understand':'GOT IT',
    'errors.emptyIdentifier':'Enter your login or email address.','errors.emptyLogin':'Enter a login.','errors.invalidLogin':'Login must be 3–24 characters and may contain letters, numbers, dots, hyphens, or underscores.','errors.emptyEmail':'Enter an email address.','errors.invalidEmail':'Enter a valid email address.','errors.emptyPassword':'Enter a password.','errors.shortPassword':'Password must contain at least 8 characters.','errors.longPassword':'Password may contain at most 128 characters.','errors.taken':'This login or email is already in use.','errors.credentials':'Incorrect login, email, or password.','errors.network':'No network connection.','errors.server':'The account server is temporarily unavailable.','errors.expired':'Your session expired. Sign in again.','errors.conflictDetail':'Save conflict: newer progress exists on another device.','account.saving':'SAVING…','account.saved':'SAVED','account.saveError':'OFFLINE / NOT SAVED','account.conflict':'SAVE CONFLICT','account.loggedOut':'Logged out.',
    'menu.tagline':'Defeat wave after wave, collect experience, and grow stronger.','menu.newGame':'NEW GAME','menu.continue':'CONTINUE','menu.noSave':'NO SAVE','menu.saveFound':'SAVE FOUND','menu.characters':'CHARACTERS','menu.maps':'MAPS','menu.instructions':'HOW TO PLAY','menu.stats':'STATISTICS','menu.achievements':'ACHIEVEMENTS','menu.settings':'OPTIONS','menu.playFriends':'PLAY WITH FRIENDS','menu.coins':'YOUR COINS','menu.back':'← BACK TO MENU',
    'hud.phase':'STAGE','hud.bossIn':'BOSS IN {time}','hud.kills':'KILLS','hud.level':'LEVEL','hud.health':'HEALTH','hud.minimap':'MINIMAP','hud.position':'POSITION','hud.items':'ITEMS','hud.pause':'PAUSE','hud.newWave':'NEW WAVE','hud.event':'EVENT','hud.healthAria':'Health points','hud.teamHealthAria':'Team health','hud.minimapAria':'Area minimap','hud.equipmentAria':'Equipment','hud.abilitiesAria':'Abilities','hud.pauseAria':'Pause game','hud.gameAria':'Swarmfall game area','hud.coinsAria':'Coin balance',
    'game.youDied':'YOU ARE DEAD','game.spectating':'SPECTATING TEAMMATE','game.spectatingName':'SPECTATING: {name}','game.connectionLost':'CONNECTION LOST','game.reconnecting':'RECONNECTING…','game.gameOver':'GAME OVER','game.matchOver':'MATCH OVER','game.teamDefeated':'The entire team has been defeated.','game.retry':'TRY AGAIN','game.paused':'GAME PAUSED','game.resume':'RESUME GAME','game.quit':'QUIT GAME','game.levelUp':'NEW LEVEL','game.chooseUpgrade':'CHOOSE AN UPGRADE','game.reroll':'REROLL','game.wave':'WAVE','game.worldEvent':'WORLD EVENT','game.achievement':'ACHIEVEMENT',
    'multiplayer.title':'PLAY TOGETHER','multiplayer.subtitle':'Create a private lobby or join a friend using a lobby code.','multiplayer.create':'CREATE LOBBY','multiplayer.createHelp':'Generate a code and invite players','multiplayer.join':'JOIN LOBBY','multiplayer.joinHelp':'Enter the code received from the host','multiplayer.code':'LOBBY CODE','multiplayer.codePlaceholder':'E.G. A7K2Q9','multiplayer.copy':'COPY CODE','multiplayer.copied':'COPIED ✓','multiplayer.host':'HOST','multiplayer.player':'PLAYER','multiplayer.players':'PLAYERS IN LOBBY','multiplayer.ready':'READY','multiplayer.notReady':'WAITING','multiplayer.cancelReady':'CANCEL READY','multiplayer.start':'START GAME','multiplayer.leave':'LEAVE','multiplayer.backLobby':'BACK TO LOBBY','multiplayer.yourLobby':'YOUR LOBBY','multiplayer.joinedLobby':'JOINED LOBBY','multiplayer.mapHost':'MAP · HOST SELECTS','multiplayer.character':'YOUR CHARACTER','multiplayer.invalidCode':'Lobby code must contain 6 characters.','multiplayer.noConnection':'No connection to the multiplayer server.','multiplayer.copyFailed':'Could not copy the lobby code.','multiplayer.replaced':'This tab was replaced by a newer connection.','multiplayer.reconnectExpired':'The reconnect session expired.','multiplayer.matchWithoutYou':'THE MATCH STARTED WITHOUT YOU · JOIN A NEW LOBBY','multiplayer.waitingPlayers':'WAITING FOR OTHER PLAYERS…','multiplayer.waitingProgress':'WAITING FOR OTHER PLAYERS… {ready} / {required}','multiplayer.loading':'PREPARING MATCH · LOADING ASSETS','multiplayer.loadFailed':'FAILED TO LOAD ASSETS · RETRY','multiplayer.waterRuins':'WATER · RUINS','multiplayer.fogPoison':'FOG · POISON',
    'settings.language':'LANGUAGE','settings.help':'Choose the interface language. Your selection is saved.','settings.polish':'POLISH','settings.english':'ENGLISH','assets.title':'LOADING ASSETS','assets.preparing':'PREPARING FINAL GRAPHICS…','assets.retry':'RETRY',
    'characters.scout':'Scout','characters.warrior':'Warrior','characters.range':'RANGED','characters.melee':'MELEE','characters.support':'SUPPORT','characters.selected':'SELECTED ✓','characters.unlock':'UNLOCK · {cost} COINS','characters.scoutDesc':'An automatic weapon, knockback, and a powerful area blast.','characters.warriorDesc':'Heals through attacks, teleports with E, and temporarily boosts damage.','characters.druidDesc':'Fires piercing waves, heals allies, and improves their mobility.',
    'maps.ruins':'Flooded Ruins','maps.toxic':'Toxic Wasteland','maps.available':'AVAILABLE','maps.locked':'LOCKED','maps.selected':'SELECTED ✓','maps.unlockToxic':'COMPLETE FLOODED RUINS','maps.ruinsDesc':'A medium-sized battlefield filled with rocks, water, and ruined walls.','maps.toxicDesc':'Toxic pools, poisonous fog, traps, and new enemy and boss variants.',
    'instructions.title':'HOW TO PLAY','instructions.movement':'MOVEMENT','instructions.movementDesc':'Move through the zone while avoiding water, rocks, and walls.','instructions.attack':'ATTACK','instructions.attackDesc':'Aim with the mouse. Your weapon automatically fires toward the cursor.','instructions.abilities':'ABILITIES','instructions.abilitiesDesc':'Q fires a volley, E knocks enemies back, and R creates a powerful blast.','instructions.evolution':'EVOLUTION','instructions.evolutionDesc':'Collect XP cores and choose one of three cards when you level up.','instructions.coins':'COINS','instructions.coinsDesc':'Earn 1 coin for every minute survived and 5 coins for defeating a boss.',
    'stats.title':'YOUR STATISTICS','stats.bestTime':'LONGEST RUN','stats.totalTime':'TOTAL PLAY TIME','stats.bestKills':'KILL RECORD','stats.totalKills':'TOTAL KILLS','stats.scoutGames':'RUNS · SCOUT','stats.warriorGames':'RUNS · WARRIOR','stats.druidGames':'RUNS · DRUID','achievements.progress':'ACCOUNT PROGRESS','achievements.subtitle':'Rewards can only be claimed once. Progress is saved to your account.','common.none':'none','common.unique':'UNIQUE','common.locked':'LOCKED','common.active':'ACTIVE','common.possible':'POSSIBLE'
  };
  const dictionaries={pl:Object.freeze(pl),en:Object.freeze(en)},listeners=new Set();let language;
  try{language=root.localStorage?.getItem(STORAGE_KEY)==='en'?'en':'pl'}catch{language='pl'}
  const interpolate=(value,params={})=>value.replace(/\{(\w+)\}/g,(_,key)=>params[key]??`{${key}}`);
  function t(key,params){const value=dictionaries[language][key]??dictionaries.pl[key];return typeof value==='string'?interpolate(value,params):key}
  function has(key){return typeof dictionaries.pl[key]==='string'&&typeof dictionaries.en[key]==='string'}
  function apply(scope=root.document){if(!scope?.querySelectorAll)return;const nodes=scope.querySelectorAll('[data-i18n],[data-i18n-placeholder],[data-i18n-aria-label],[data-i18n-title]');for(const node of nodes){if(node.dataset.i18n)node.textContent=t(node.dataset.i18n);if(node.dataset.i18nPlaceholder)node.placeholder=t(node.dataset.i18nPlaceholder);if(node.dataset.i18nAriaLabel)node.setAttribute('aria-label',t(node.dataset.i18nAriaLabel));if(node.dataset.i18nTitle)node.title=t(node.dataset.i18nTitle)}root.document.documentElement.lang=language;for(const button of scope.querySelectorAll('[data-language]'))button.classList.toggle('active',button.dataset.language===language)}
  function setLanguage(next){language=next==='en'?'en':'pl';try{root.localStorage?.setItem(STORAGE_KEY,language)}catch{}apply();for(const callback of listeners)callback(language);if(root.dispatchEvent&&root.CustomEvent)root.dispatchEvent(new root.CustomEvent('swarm-language-changed',{detail:{language}}));return language}
  function onChange(callback){listeners.add(callback);return()=>listeners.delete(callback)}
  function bind(scope=root.document){if(!scope?.querySelectorAll)return;for(const button of scope.querySelectorAll('[data-language]'))if(!button.dataset.i18nBound){button.dataset.i18nBound='1';button.addEventListener('click',()=>setLanguage(button.dataset.language))}apply(scope)}
  if(root.document)Promise.resolve().then(()=>bind(root.document));
  return{STORAGE_KEY,dictionaries,getLanguage:()=>language,setLanguage,t,has,apply,onChange,bind};
});
