(function(root){
  'use strict';
  const BASE='assets/maps/ruins/',paths={ground:'ground/ground_tile.png',water:'water/water_tile.png',waterOverlay:'water/water_overlay.png',wallHorizontal:'walls/wall_horizontal.png',wallVertical:'walls/wall_vertical.png',rock1:'rocks/rock_01.png',rock2:'rocks/rock_02.png',rock3:'rocks/rock_03.png',rock4:'rocks/rock_04.png',crystal1:'scenery/crystal_01.png',crystal2:'scenery/crystal_02.png',crystal3:'scenery/crystal_03.png',vent1:'scenery/vent_01.png',vent2:'scenery/vent_02.png',crateClosed:'crates/crate_closed.png',crateOpen:'crates/crate_open.png'};
  const images={},patterns=new WeakMap();let preloadPromise;
  function preload(){if(preloadPromise)return preloadPromise;preloadPromise=Promise.all(Object.entries(paths).map(([key,path])=>new Promise(resolve=>{const image=new Image(),source=BASE+path;images[key]={image,source,ready:false,failed:false};image.onload=()=>{images[key].ready=true;resolve(true)};image.onerror=()=>{images[key].failed=true;console.warn(`Failed to load ruins map asset: ${source}`);resolve(false)};image.src=source})));return preloadPromise}
  function ready(key){return images[key]?.ready&&images[key].image.naturalWidth>0}
  function pattern(context,key){if(!ready(key))return null;let cache=patterns.get(context);if(!cache){cache={};patterns.set(context,cache)}return cache[key]||(cache[key]=context.createPattern(images[key].image,'repeat'))}
  function hash(x,y){return(Math.imul(Math.round(x),73856093)^Math.imul(Math.round(y),19349663))>>>0}
  function polygon(context,points){context.beginPath();points.forEach(([x,y],i)=>i?context.lineTo(x,y):context.moveTo(x,y));context.closePath()}
  function resetComposite(context){context.globalAlpha=1;context.globalCompositeOperation='source-over'}
  function drawGround(context,shape,world){const fill=pattern(context,'ground');if(!fill)return false;context.save();resetComposite(context);polygon(context,shape);context.clip();context.fillStyle=fill;context.fillRect(0,0,world.w,world.h);context.restore();return true}
  function drawWater(context,item,world){const tile=pattern(context,'water');if(!tile)return false;context.save();resetComposite(context);polygon(context,item.points);context.clip();context.fillStyle=tile;context.fillRect(0,0,world.w,world.h);const overlay=pattern(context,'waterOverlay');if(overlay){context.globalAlpha=.48;context.fillStyle=overlay;context.fillRect(0,0,world.w,world.h)}context.restore();context.save();resetComposite(context);polygon(context,item.points);context.strokeStyle='rgba(75,220,229,.62)';context.lineWidth=4;context.shadowBlur=9;context.shadowColor='rgba(52,205,218,.35)';context.stroke();context.restore();return true}
  function drawWall(context,item){const horizontal=item.w>=item.h,key=horizontal?'wallHorizontal':'wallVertical';if(!ready(key))return false;const image=images[key].image,scale=horizontal?item.h/image.height:item.w/image.width,tileLength=(horizontal?image.width:image.height)*scale,total=horizontal?item.w:item.h;context.save();resetComposite(context);context.beginPath();context.rect(item.x,item.y,item.w,item.h);context.clip();for(let offset=0;offset<total;offset+=tileLength){const length=Math.min(tileLength,total-offset),sourceLength=length/scale;if(horizontal)context.drawImage(image,0,0,sourceLength,image.height,item.x+offset,item.y,length,item.h);else context.drawImage(image,0,0,image.width,sourceLength,item.x,item.y+offset,item.w,length)}context.restore();return true}
  const RUINS_ROCK_RENDER_SCALE=2.02;
  function drawRock(context,item){const key='rock'+(hash(item.x,item.y)%4+1);if(!ready(key))return false;const diameter=item.r*RUINS_ROCK_RENDER_SCALE;context.save();resetComposite(context);context.drawImage(images[key].image,item.x-diameter/2,item.y-diameter/2,diameter,diameter);context.restore();return true}
  function drawTerrainObject(context,item,world){return item.type==='water'?drawWater(context,item,world):item.type==='wall'?drawWall(context,item):drawRock(context,item)}
  function drawScenery(context,item){const count=item.type==='crystal'?3:item.type==='vent'?2:0;if(!count)return false;const key=item.type+(hash(item.x,item.y)%count+1);if(!ready(key))return false;const size=item.size*2.4;context.save();resetComposite(context);context.translate(item.x,item.y);context.rotate(item.rot);context.drawImage(images[key].image,-size/2,-size/2,size,size);context.restore();return true}
  function drawCrate(context,crate){const key=crate.opened?'crateOpen':'crateClosed';if(!ready(key))return false;const image=images[key].image;context.save();resetComposite(context);context.translate(crate.x,crate.y);context.shadowBlur=crate.opened?5:14;context.shadowColor=crate.reward==='health'?'#ff6688':crate.reward==='level'?'#ffd467':'#d99b45';context.drawImage(image,-24,-24,48,48);if(crate.hit){context.save();context.filter='brightness(2.2) saturate(0)';context.globalAlpha=.4;context.drawImage(image,-24,-24,48,48);context.restore()}context.restore();return true}
  function renderRuinsMapPreview(context,width,height,{crates=[]}={}){const map=root.SWARM_SHARED_MAPS?.ruins||root.SWARM_MAPS?.ruins;if(!map)return false;const sx=width/3000,sy=height/2200,points=p=>p.map(([x,y])=>[x*sx,y*sy]);context.save();context.clearRect(0,0,width,height);context.fillStyle='#05020b';context.fillRect(0,0,width,height);polygon(context,points(map.shape));context.fillStyle='#190d2c';context.fill();for(const item of map.terrain){if(item.type==='water'){polygon(context,points(item.points));context.fillStyle='#08768d';context.fill();context.strokeStyle='#45e5ed';context.stroke()}else if(item.type==='wall'){context.fillStyle='#512365';context.fillRect(item.x*sx,item.y*sy,item.w*sx,item.h*sy);context.strokeStyle='#d252d8';context.strokeRect(item.x*sx,item.y*sy,item.w*sx,item.h*sy)}else{const radius=item.r*.84*Math.min(sx,sy);context.fillStyle='#51215f';context.strokeStyle='#e04bd8';context.beginPath();context.arc(item.x*sx,item.y*sy,Math.max(2,radius),0,Math.PI*2);context.fill();context.stroke()}}for(const crate of crates){context.fillStyle='#e6a94d';context.fillRect(crate.x*sx-2,crate.y*sy-2,4,4)}polygon(context,points(map.shape));context.strokeStyle='#9a53d8';context.lineWidth=2;context.stroke();context.restore();return true}
  root.SwarmMapVisuals={preload,drawGround,drawTerrainObject,drawScenery,drawCrate,renderRuinsMapPreview,rockVariant:item=>hash(item.x,item.y)%4+1,RUINS_ROCK_RENDER_SCALE,_assetState:images};preload().then(()=>root.dispatchEvent(new Event('swarm-map-visuals-ready')));
})(window);
