(function(root){
  'use strict';
  const BASE='assets/maps/ruins/',paths={ground:'ground/ground_tile.png',water:'water/water_tile.png',waterOverlay:'water/water_overlay.png',wallHorizontal:'walls/wall_horizontal.png',wallVertical:'walls/wall_vertical.png',rock1:'rocks/rock_01.png',rock2:'rocks/rock_02.png',rock3:'rocks/rock_03.png',rock4:'rocks/rock_04.png',crystal1:'scenery/crystal_01.png',crystal2:'scenery/crystal_02.png',crystal3:'scenery/crystal_03.png',vent1:'scenery/vent_01.png',vent2:'scenery/vent_02.png',crateClosed:'crates/crate_closed.png',crateOpen:'crates/crate_open.png'};
  const images={},patterns=new WeakMap();let preloadPromise;
  function preload(){if(preloadPromise)return preloadPromise;preloadPromise=Promise.all(Object.entries(paths).map(([key,path])=>new Promise(resolve=>{const image=new Image(),source=BASE+path;images[key]={image,source,ready:false,failed:false};image.onload=()=>{images[key].ready=true;resolve(true)};image.onerror=()=>{images[key].failed=true;console.warn(`Failed to load ruins map asset: ${source}`);resolve(false)};image.src=source})));return preloadPromise}
  function ready(key){return images[key]?.ready&&images[key].image.naturalWidth>0}
  function pattern(context,key){if(!ready(key))return null;let cache=patterns.get(context);if(!cache){cache={};patterns.set(context,cache)}return cache[key]||(cache[key]=context.createPattern(images[key].image,'repeat'))}
  function hash(x,y){return(Math.imul(Math.round(x),73856093)^Math.imul(Math.round(y),19349663))>>>0}
  function polygon(context,points){context.beginPath();points.forEach(([x,y],i)=>i?context.lineTo(x,y):context.moveTo(x,y));context.closePath()}
  function resetComposite(context){context.globalAlpha=1;context.globalCompositeOperation='source-over'}
  function drawGround(context,shape,world){const fill=pattern(context,'ground');if(!fill)return false;context.save();resetComposite(context);polygon(context,shape);context.clip();context.fillStyle=fill;context.fillRect(0,0,world.w,world.h);context.restore();return true}
  function drawWater(context,item,world){const tile=pattern(context,'water');if(!tile)return false;context.save();resetComposite(context);polygon(context,item.points);context.clip();context.fillStyle=tile;context.fillRect(0,0,world.w,world.h);const overlay=pattern(context,'waterOverlay');if(overlay){context.globalAlpha=.48;context.fillStyle=overlay;context.fillRect(0,0,world.w,world.h)}context.restore();context.save();resetComposite(context);polygon(context,item.points);context.strokeStyle='rgba(75,220,229,.62)';context.lineWidth=4;context.shadowBlur=9;context.shadowColor='rgba(52,205,218,.35)';context.stroke();context.restore();return true}
  function drawWall(context,item){const key=item.w>=item.h?'wallHorizontal':'wallVertical';if(!ready(key))return false;const image=images[key].image,horizontal=item.w>=item.h,stepX=horizontal?image.width:item.w,stepY=horizontal?item.h:image.height;context.save();resetComposite(context);context.beginPath();context.rect(item.x,item.y,item.w,item.h);context.clip();for(let y=item.y;y<item.y+item.h;y+=stepY)for(let x=item.x;x<item.x+item.w;x+=stepX){const w=Math.min(stepX,item.x+item.w-x),h=Math.min(stepY,item.y+item.h-y);context.drawImage(image,0,0,image.width*w/stepX,image.height*h/stepY,x,y,w,h)}context.restore();return true}
  function drawRock(context,item){const key='rock'+(hash(item.x,item.y)%4+1);if(!ready(key))return false;const diameter=item.r*2.4;context.save();resetComposite(context);context.drawImage(images[key].image,item.x-diameter/2,item.y-diameter/2,diameter,diameter);context.restore();return true}
  function drawTerrainObject(context,item,world){return item.type==='water'?drawWater(context,item,world):item.type==='wall'?drawWall(context,item):drawRock(context,item)}
  function drawScenery(context,item){const count=item.type==='crystal'?3:item.type==='vent'?2:0;if(!count)return false;const key=item.type+(hash(item.x,item.y)%count+1);if(!ready(key))return false;const size=item.size*2.4;context.save();resetComposite(context);context.translate(item.x,item.y);context.rotate(item.rot);context.drawImage(images[key].image,-size/2,-size/2,size,size);context.restore();return true}
  function drawCrate(context,crate){const key=crate.opened?'crateOpen':'crateClosed';if(!ready(key))return false;context.save();resetComposite(context);context.translate(crate.x,crate.y);context.globalAlpha=crate.hit?.72:1;context.shadowBlur=crate.opened?5:14;context.shadowColor=crate.reward==='health'?'#ff6688':crate.reward==='level'?'#ffd467':'#d99b45';context.drawImage(images[key].image,-24,-24,48,48);if(crate.hit){context.globalCompositeOperation='screen';context.globalAlpha=.55;context.fillStyle='#fff';context.fillRect(-18,-15,36,30)}context.restore();return true}
  root.SwarmMapVisuals={preload,drawGround,drawTerrainObject,drawScenery,drawCrate,_assetState:images};preload();
})(window);
