(() => {
  const byId=id=>document.getElementById(id),modal=byId('multiplayerModal'),actions=byId('multiplayerActions'),joinForm=byId('joinLobbyForm'),codeInput=byId('lobbyCodeInput'),message=byId('lobbyMessage'),room=byId('lobbyRoom'),readyBtn=byId('lobbyReadyBtn'),startBtn=byId('lobbyStartBtn');
  const installationId=localStorage.getItem('swarmfall-installation-id')||crypto.randomUUID(),unlocked=(()=>{try{return['scout',...JSON.parse(localStorage.getItem('swarmfall-unlocked')||'[]')]}catch{return['scout']}})();localStorage.setItem('swarmfall-installation-id',installationId);
  let socket,lobby=null,retry=0,gameStarting=false,identity=null;const channel=SwarmSocketState.createControlChannel();let pendingReconnect=(()=>{try{return JSON.parse(sessionStorage.getItem('swarmfall-multiplayer-session')||'null')}catch{return null}})();
  window.SwarmSocket={send,on:channel.on,getLobby:()=>lobby,getIdentity:()=>identity,getHandshakeState:channel.getHandshakeState,getLastHelloAck:channel.getLastHelloAck,isOpen:()=>socket?.readyState===WebSocket.OPEN&&channel.getHandshakeState()==='authenticated'};
  const characterName=id=>({scout:'Zwiadowca',warrior:'Wojownik',druid:'Druid'}[id]||id),mapName=id=>id==='toxic'?'Toksyczne pustkowie':'Zalane ruiny';
  function send(type,data={}){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type,...data}));else showError('Brak połączenia z serwerem multiplayer.')}
  function connect(){const protocol=location.protocol==='https:'?'wss:':'ws:';channel.beginConnection();socket=new WebSocket(`${protocol}//${location.host}`);socket.onopen=()=>{retry=0;const resumeIdentity=identity||pendingReconnect;send('hello',{installationId,resume:resumeIdentity?{playerId:resumeIdentity.playerId,reconnectToken:resumeIdentity.reconnectToken}:undefined,unlocked,maps:['ruins',...(window.Achievements?.isComplete('map_1')?['toxic']:[])]})};socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.type==='helloAck'){identity={playerId:data.playerId,reconnectToken:data.reconnectToken,connectionId:data.connectionId,connectionGeneration:data.connectionGeneration};if(data.lobbyCode){pendingReconnect={lobbyCode:data.lobbyCode,playerId:data.playerId,reconnectToken:data.reconnectToken};sessionStorage.setItem('swarmfall-multiplayer-session',JSON.stringify(pendingReconnect))}}else if(data.type==='resumeRejected'){identity=null;pendingReconnect=null;sessionStorage.removeItem('swarmfall-multiplayer-session')}else if(data.type==='lobbyState'){lobby=data.lobby;if(identity){pendingReconnect={lobbyCode:lobby.code,playerId:identity.playerId,reconnectToken:identity.reconnectToken};sessionStorage.setItem('swarmfall-multiplayer-session',JSON.stringify(pendingReconnect))}if(!lobby.started){gameStarting=false;byId('endModal')?.classList.add('hidden');byId('startModal').classList.add('hidden');modal.classList.remove('hidden')}renderRoom()}else if(data.type==='joinError'||data.type==='error')showError(data.message);else if(data.type==='gameStarted')launchGame(data.lobby);channel.publish(data);if(data.type==='resumeRejected')socket.close()};socket.onclose=event=>{channel.invalidate(event.code===4001?'superseded':'closed');if(event.code===4001||event.code===4003){showError(event.code===4001?'Ta karta została zastąpiona przez nowsze połączenie.':'Sesja reconnect wygasła.');return}if(retry++<8)setTimeout(connect,Math.min(5000,400*2**retry))}}
  function showError(text){message.textContent=text;message.className='lobby-message error'}
  function me(){return lobby?.players.find(player=>player.id===identity?.playerId)}
  function setView(view){actions.classList.toggle('hidden',view!=='actions');joinForm.classList.toggle('hidden',view!=='join');room.classList.toggle('hidden',view!=='room');message.textContent='';message.className='lobby-message'}
  function copyPreviews(){byId('lobbyMapPicker').querySelectorAll('canvas[data-map-preview]').forEach(canvas=>canvas.getContext('2d').drawImage(byId(canvas.dataset.mapPreview==='toxic'?'toxicMapPreview':'mapPreviewCanvas'),0,0,canvas.width,canvas.height));byId('lobbyCharacterPicker').querySelectorAll('canvas[data-character-preview]').forEach(canvas=>canvas.getContext('2d').drawImage(byId(`${canvas.dataset.characterPreview}Preview`),0,0,canvas.width,canvas.height))}
  function renderPickers(player){const host=player.host,mapIds=['ruins',...(window.Achievements?.isComplete('map_1')?['toxic']:[])];byId('lobbyMapPicker').querySelector('div').innerHTML=(host?mapIds:[lobby.map]).map(id=>`<button type="button" data-lobby-map="${id}" class="visual-pick ${lobby.map===id?'selected':''}" ${host?'':'disabled'}><canvas class="pick-preview" data-map-preview="${id}" width="320" height="150"></canvas><b>${mapName(id)}</b><small>${id==='toxic'?'MGŁA · TRUCIZNA':'WODA · RUINY'}</small></button>`).join('');byId('lobbyMapPicker').querySelectorAll('[data-lobby-map]').forEach(button=>button.onclick=()=>send('selectMap',{map:button.dataset.lobbyMap}));byId('lobbyCharacterPicker').querySelector('div').innerHTML=unlocked.map(id=>`<button type="button" data-lobby-character="${id}" class="visual-pick ${player.character===id?'selected':''}"><canvas class="pick-preview" data-character-preview="${id}" width="320" height="150"></canvas><b>${characterName(id)}</b><small>${id==='warrior'?'WALKA WRĘCZ':id==='druid'?'WSPARCIE':'DYSTANS'}</small></button>`).join('');byId('lobbyCharacterPicker').querySelectorAll('[data-lobby-character]').forEach(button=>button.onclick=()=>send('selectCharacter',{character:button.dataset.lobbyCharacter}));copyPreviews()}
  function renderRoom(){if(!lobby)return;const player=me();if(!player)return;setView('room');byId('activeLobbyCode').textContent=lobby.code;byId('lobbyRole').textContent=player.host?'TWOJE LOBBY':'DOŁĄCZONO DO LOBBY';byId('lobbyPlayerCount').textContent=`${lobby.players.length} / 4`;byId('lobbyPlayerList').innerHTML=lobby.players.map(p=>`<li><i class="${p.ready?'ready':''}"></i><span>${p.name}<small>${characterName(p.character)}</small></span><b>${p.host?'GOSPODARZ':p.ready?'GOTOWY':'OCZEKUJE'}</b></li>`).join('');renderPickers(player);readyBtn.classList.toggle('hidden',player.host);readyBtn.classList.toggle('selected',player.ready);readyBtn.textContent=player.ready?'ANULUJ GOTOWOŚĆ':'GOTOWY';startBtn.classList.toggle('hidden',!player.host);startBtn.disabled=!lobby.players.filter(p=>!p.host).every(p=>p.ready)}
  function launchGame(nextLobby){if(gameStarting)return;gameStarting=true;lobby=nextLobby;const player=me();sessionStorage.setItem('swarmfall-lobby-map',lobby.map);sessionStorage.setItem('swarmfall-multiplayer-session',JSON.stringify({lobbyCode:lobby.code,playerId:identity.playerId,reconnectToken:identity.reconnectToken}));localStorage.setItem('swarmfall-character',player.character);modal.classList.add('hidden');byId('startBtn').click()}
  byId('multiplayerBtn').onclick=()=>{byId('startModal').classList.add('hidden');modal.classList.remove('hidden');setView(lobby?'room':'actions');if(lobby)renderRoom()};byId('createLobbyBtn').onclick=()=>send('createLobby',{character:localStorage.getItem('swarmfall-character')||'scout'});byId('showJoinLobbyBtn').onclick=()=>{setView('join');codeInput.focus()};joinForm.onsubmit=event=>{event.preventDefault();const code=codeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,'');if(code.length!==6)return showError('Kod lobby musi mieć 6 znaków.');send('joinLobby',{code,character:localStorage.getItem('swarmfall-character')||'scout'})};codeInput.oninput=()=>codeInput.value=codeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,'');readyBtn.onclick=()=>send('playerReady',{ready:!me().ready});startBtn.onclick=()=>send('startGame');byId('copyLobbyCodeBtn').onclick=()=>navigator.clipboard?.writeText(lobby.code);byId('multiplayerBackBtn').onclick=()=>{modal.classList.add('hidden');byId('startModal').classList.remove('hidden');setView('actions')};if(pendingReconnect)setTimeout(()=>{if(!lobby){sessionStorage.removeItem('swarmfall-multiplayer-session');sessionStorage.removeItem('swarmfall-lobby-map');modal.classList.add('hidden');byId('startModal').classList.remove('hidden')}},12000);connect()
})();
