(() => {
  let session=null,multiplayerMode=false,currentMatchId=null,multiplayerUpgradeOpen=false,authoritativePlayerId=null,connectionGeneration=0,lastAppliedHelloAck=null,state=null,previous=null,receivedAt=0,sendClock=0,lastLevelRound=0,lastWaveSeq=0,lastExplosionSeq=0,inputSeq=0,abilityInputSeq=0,serverPaused=false,pauseReason=null,cooldownFrozenAt=0,cooldownFrozenServerNow=0,localMenuOpen=false,localPauseRequested=false,pauseInfo={paused:false,requested:0,required:0,requesterIds:[]},isDead=false,isSpectator=false,spectatorTargetId=null,deathOverlayUntil=0,hasSeenLocalState=false;
  let predictionState=SwarmClientUtils.createPredictionState(),remotePlayers=[],effectiveSpeed=0,remoteVisuals=new Map(),localAttackSeq=0,localAbilitySeq=0,pendingInputs=[];
  let previousEnemies=new Map(),enemyVisuals=new Map(),bulletVisuals=new Map(),enemyBulletVisuals=new Map(),orbVisuals=new Map();
  const cooldownElements={},debugPerformance=localStorage.getItem('swarmfall-debug-multiplayer')==='1',snapshotIntervals=SwarmClientUtils.createIntervalWindow(50),debugMetrics={frames:0,slow33:0,slow50:0,reconcileErrorTotal:0,reconciles:0,hardCorrections:0,lastReportAt:performance.now()};
  try{session=JSON.parse(sessionStorage.getItem('swarmfall-multiplayer-session')||'null')}catch{}
  const socket=()=>window.SwarmSocket;
  function clearPredictionHistory(){predictionState.pending=[];pendingInputs=[]}
  function recordSnapshotArrival(now){snapshotIntervals.observe(now)}
  function recordFrame(dt){if(!debugPerformance)return;debugMetrics.frames++;if(dt>1/30)debugMetrics.slow33++;if(dt>.05)debugMetrics.slow50++;const now=performance.now();if(now-debugMetrics.lastReportAt>=1000){const intervals=snapshotIntervals.summary();console.debug('[MP CLIENT PERF]',{frameAvgMs:(now-debugMetrics.lastReportAt)/Math.max(1,debugMetrics.frames),framesOver33:debugMetrics.slow33,framesOver50:debugMetrics.slow50,rtt:socket()?.getRtt?.(),clockOffset:socket()?.getClockOffset?.(),snapshotIntervalAvg:intervals.average,snapshotJitterMax:intervals.jitterMax,reconcileErrorAvg:debugMetrics.reconciles?debugMetrics.reconcileErrorTotal/debugMetrics.reconciles:0,hardCorrections:debugMetrics.hardCorrections,predictionPending:predictionState.pending.length});snapshotIntervals.reset();Object.assign(debugMetrics,{frames:0,slow33:0,slow50:0,reconcileErrorTotal:0,reconciles:0,hardCorrections:0,lastReportAt:now})}}
  function estimatedServerNow(){return socket()?.estimatedServerNow?.(state?.serverTime,receivedAt)??NaN}
  function getSession(){if(session)return session;try{session=JSON.parse(sessionStorage.getItem('swarmfall-multiplayer-session')||'null')}catch{}return session}
  function isActive(){return Boolean(getSession()&&authoritativePlayerId&&running&&socket()?.isOpen())}
  function isMultiplayerMode(){return multiplayerMode}
  function resetMatchRuntime(){
    multiplayerUpgradeOpen=false;running=false;paused=true;predictionState=SwarmClientUtils.createPredictionState();pendingInputs=[];movementInput.clear();state=null;previous=null;lastLevelRound=0;lastWaveSeq=0;lastExplosionSeq=0;remotePlayers=[];previousEnemies.clear();remoteVisuals.clear();enemyVisuals.clear();bulletVisuals.clear();enemyBulletVisuals.clear();orbVisuals.clear();localAttackSeq=0;localAbilitySeq=0;isDead=false;isSpectator=false;spectatorTargetId=null;deathOverlayUntil=0;hasSeenLocalState=false;serverPaused=false;pauseReason=null;cooldownFrozenAt=0;cooldownFrozenServerNow=0;localMenuOpen=false;localPauseRequested=false;pauseInfo={paused:false,requested:0,required:0,requesterIds:[]};enemies=[];bullets=[];enemyBullets=[];orbs=[];loot=[];rings=[];playerEchoes=[];particles=[];damageNumbers=[];hideDeathUi();renderTeamHud([]);ui.levelModal.classList.add('hidden');ui.pauseModal.classList.add('hidden');document.getElementById('quitBtn').textContent='ZAKOŃCZ GRĘ';document.getElementById('quitBtn').onclick=quitToMenu;ui.endModal.classList.add('hidden');document.getElementById('multiplayerWaiting').classList.add('hidden');document.getElementById('multiplayerPauseStatus').classList.add('hidden');
  }
  function leaveMultiplayerLobby(){multiplayerMode=true;resetMatchRuntime();currentMatchId=null;lastAppliedHelloAck=null;session=null;sessionStorage.removeItem('swarmfall-multiplayer-session');sessionStorage.removeItem('swarmfall-lobby-map');const restart=document.getElementById('restartBtn');restart.textContent='SPRÓBUJ PONOWNIE';restart.onclick=()=>location.reload();document.getElementById('multiplayerConnectionStatus').classList.add('hidden');multiplayerMode=false}
  function abortMultiplayerSession(reason,clearSession=true){multiplayerMode=true;resetMatchRuntime();currentMatchId=null;authoritativePlayerId=null;connectionGeneration=0;lastAppliedHelloAck=null;if(clearSession){session=null;sessionStorage.removeItem('swarmfall-multiplayer-session');sessionStorage.removeItem('swarmfall-lobby-map')}document.getElementById('multiplayerConnectionStatus').classList.add('hidden');const restart=document.getElementById('restartBtn');restart.textContent='SPRÓBUJ PONOWNIE';restart.onclick=()=>location.reload();document.getElementById('multiplayerModal')?.classList.add('hidden');document.getElementById('startModal')?.classList.remove('hidden');multiplayerMode=false;return reason}
  function accept(message){
    if(message.type==='helloAck'){if(!SwarmSocketState.shouldApplyHelloAck(lastAppliedHelloAck,message))return;const identityChanged=authoritativePlayerId&&authoritativePlayerId!==message.playerId;lastAppliedHelloAck={playerId:message.playerId,connectionId:message.connectionId,connectionGeneration:message.connectionGeneration};authoritativePlayerId=message.playerId;connectionGeneration=message.connectionGeneration;document.getElementById('multiplayerConnectionStatus').classList.add('hidden');const sequences=SwarmRemoteVisuals.resumeSequences(inputSeq,abilityInputSeq,message);inputSeq=sequences.inputSeq;abilityInputSeq=sequences.abilityInputSeq;predictionState=SwarmClientUtils.createPredictionState();pendingInputs=[];localMenuOpen=false;localPauseRequested=false;ui.pauseModal.classList.add('hidden');if(identityChanged){remoteVisuals.clear();enemyVisuals.clear();bulletVisuals.clear();enemyBulletVisuals.clear();orbVisuals.clear()}session=getSession();return}
    if(message.type==='resumeRejected'){abortMultiplayerSession(message.reason||'resumeRejected',true);return}
    if(message.type==='leftLobby'){leaveMultiplayerLobby();return}
    if(!getSession()||!authoritativePlayerId)return;
    if(message.type==='accountProgress'){window.SwarmAccount?.reconcileServerProgress?.(message);return}
    if(message.type==='lobbyState'&&!message.lobby?.started&&currentMatchId){resetMatchRuntime();currentMatchId=null;multiplayerMode=true;return}
    if(message.type==='gameStarted'){
      const nextMatchId=message.matchId||message.lobby?.matchId,reconnecting=Boolean(currentMatchId&&nextMatchId===currentMatchId);multiplayerMode=true;if(!reconnecting)resetMatchRuntime();currentMatchId=nextMatchId;running=true;paused=true;document.getElementById('multiplayerWaiting').classList.add('hidden');pendingInputs=[];
    }
    if(!SwarmSocketState.shouldAcceptMatchMessage(currentMatchId,message))return;
    if(message.type==='gameState'){if(message.state?.matchId!==currentMatchId)return;previous=state;state=message.state;receivedAt=performance.now();if(debugPerformance)recordSnapshotArrival(receivedAt);applyState()}
    if(message.type==='upgradeWaiting')document.getElementById('multiplayerWaiting').classList.remove('hidden');
    if(message.type==='levelResume'){endCooldownFreeze();serverPaused=false;pauseReason=null;paused=false;document.getElementById('multiplayerWaiting').classList.add('hidden')}
    if(message.type==='pauseState'){if(message.matchId&&currentMatchId&&message.matchId!==currentMatchId)return;pauseInfo=message;const presentation=SwarmRemoteVisuals.pauseUiState(message,authoritativePlayerId),status=document.getElementById('multiplayerPauseStatus'),wasPaused=serverPaused;serverPaused=Boolean(message.paused||message.upgradePaused);paused=serverPaused;pauseReason=message.pauseReason||null;localPauseRequested=presentation.localRequested;status.textContent=presentation.text;status.classList.toggle('hidden',!presentation.showStatus);if(serverPaused&&!wasPaused)clearPredictionHistory();if(serverPaused)beginCooldownFreeze();else endCooldownFreeze();if(SwarmRemoteVisuals.upgradePauseUiState(message,multiplayerUpgradeOpen).clearStaleUpgrade){multiplayerUpgradeOpen=false;ui.levelModal.classList.add('hidden');upgradeOfferKeys=[];upgradeRerolled=[];levelChoicesQueued=0;bossChoicesQueued=0;document.getElementById('multiplayerWaiting').classList.add('hidden')}if(localMenuOpen)showPauseUi(serverPaused&&pauseReason==='manual');else ui.pauseModal.classList.add('hidden')}
    if(message.type==='upgradeOffer'&&message.round===lastLevelRound){upgradeOfferKeys=message.offer.slice(0,3);upgradeRerolled.push(message.index);renderUpgradeOffer(bossChoicesQueued>0)}
    if(message.type==='upgradeAccepted'){multiplayerUpgradeOpen=false;applyAuthoritativeBuild(message);ui.levelModal.classList.add('hidden');document.getElementById('multiplayerWaiting').classList.remove('hidden')}
    if(message.type==='gameOver')showMultiplayerGameOver();
    if(message.type==='levelUp'&&!isDead&&message.round>lastLevelRound){multiplayerUpgradeOpen=true;lastLevelRound=message.round;beginCooldownFreeze();serverPaused=true;pauseReason='upgrade';clearPredictionHistory();localMenuOpen=false;localPauseRequested=false;ui.pauseModal.classList.add('hidden');document.getElementById('multiplayerPauseStatus').classList.add('hidden');paused=true;levelChoicesQueued=1;upgradeOfferKeys=Array.isArray(message.offer)?message.offer.slice(0,3):[];upgradeRerolled=[];showLevelUp(false)}
  }
  function applyAuthoritativeBuild(build){Object.keys(items).forEach(key=>delete items[key]);Object.assign(items,build.items||{});Object.keys(augments).forEach(key=>delete augments[key]);for(const id of build.augments||[])augments[id]=1;if(Number.isFinite(build.hp))player.hp=build.hp;if(Number.isFinite(build.stats?.maxHp))player.maxHp=build.stats.maxHp;if(Number.isFinite(build.stats?.speed))effectiveSpeed=build.stats.speed;renderSlots()}
  function hideDeathUi(){document.getElementById('multiplayerDeathOverlay')?.classList.add('hidden');document.getElementById('multiplayerSpectatorLabel')?.classList.add('hidden')}
  function beginCooldownFreeze(){if(cooldownFrozenAt)return;cooldownFrozenAt=performance.now();cooldownFrozenServerNow=estimatedServerNow()}
  function endCooldownFreeze(){const shift=SwarmRemoteVisuals.cooldownFreezeShift(cooldownFrozenAt,performance.now());if(!shift)return;for(const value of[player.serverCooldowns])if(value)for(const key of['qReadyAt','eReadyAt','rReadyAt'])if(Number.isFinite(value[key]))value[key]+=shift;cooldownFrozenAt=0;cooldownFrozenServerNow=0}
  function exitMultiplayer(){if(!multiplayerMode)return false;movementInput.clear();localMenuOpen=false;localPauseRequested=false;ui.pauseModal.classList.add('hidden');socket()?.send('leaveLobby');return true}
  function showPauseUi(globalPause){const modal=ui.pauseModal,eyebrow=modal.querySelector('.eyebrow'),title=modal.querySelector('h2'),copy=modal.querySelector('p'),resumeButton=document.getElementById('resumeBtn'),presentation=SwarmRemoteVisuals.localMenuPresentation(globalPause);eyebrow.textContent=presentation.eyebrow;title.textContent=presentation.title;copy.textContent=globalPause?'Gra została zatrzymana za zgodą drużyny. Zamknięcie menu wznowi mecz.':localPauseRequested?`${pauseInfo.requested} / ${pauseInfo.required} GRACZY · Oczekiwanie na zgodę nie blokuje lokalnego menu.`:'Gra drużyny trwa. Możesz wrócić albo opuścić mecz.';resumeButton.textContent=presentation.resume;document.getElementById('quitBtn').textContent=presentation.quit;document.getElementById('quitBtn').onclick=exitMultiplayer;SwarmRemoteVisuals.setLocalMenuLayer(modal,true)}
  function showMultiplayerGameOver(){if(!running&&ui.endModal&&!ui.endModal.classList.contains('hidden'))return;multiplayerMode=true;running=false;paused=true;serverPaused=true;pauseReason=null;cooldownFrozenAt=0;cooldownFrozenServerNow=0;localMenuOpen=false;localPauseRequested=false;clearPredictionHistory();movementInput.clear();spectatorTargetId=null;deathOverlayUntil=0;hideDeathUi();ui.levelModal.classList.add('hidden');ui.pauseModal.classList.add('hidden');document.getElementById('multiplayerWaiting').classList.add('hidden');document.getElementById('multiplayerPauseStatus').classList.add('hidden');ui.endTitle.textContent='KONIEC MECZU';ui.endStats.textContent='Cała drużyna została pokonana.';const restartButton=document.getElementById('restartBtn');restartButton.textContent='WRÓĆ DO LOBBY';restartButton.onclick=()=>{socket().send('returnToLobby');multiplayerMode=false;state=null;previous=null;pendingInputs=[];isDead=false;isSpectator=false;serverPaused=false;renderTeamHud([]);ui.endModal.classList.add('hidden');document.getElementById('multiplayerModal').classList.remove('hidden')};ui.endModal.classList.remove('hidden')}
  function renderTeamHud(players){const hud=document.getElementById('multiplayerTeamHud');if(!hud)return;const rows=SwarmRemoteVisuals.teamHudData(players,authoritativePlayerId);hud.classList.toggle('hidden',!rows.length);hud.innerHTML=rows.map(row=>`<div class="team-member ${row.status==='DEAD'?'dead':''}"><header><b>${row.name}${row.local?' · YOU':''}</b><span>${row.status==='DEAD'?'DEAD':`${Math.ceil(row.hp)} / ${Math.ceil(row.maxHp)}`}</span></header><i><b style="width:${row.ratio*100}%"></b></i></div>`).join('')}
  function enterDeathSpectator(){multiplayerUpgradeOpen=false;upgradeOfferKeys=[];upgradeRerolled=[];levelChoicesQueued=0;bossChoicesQueued=0;clearPredictionHistory();movementInput.clear();localMenuOpen=false;ui.levelModal.classList.add('hidden');ui.pauseModal.classList.add('hidden');document.getElementById('multiplayerWaiting').classList.add('hidden');deathOverlayUntil=performance.now()+3000;const overlay=document.getElementById('multiplayerDeathOverlay');overlay?.classList.remove('hidden');screenShake=Math.max(screenShake,5)}
  function applyState(){
    if(!state)return;
    elapsed=state.time;player.level=state.level;player.xp=state.xp;player.nextXp=state.nextXp;serverPaused=Boolean(state.paused);pauseReason=state.pauseReason||null;paused=serverPaused;if(state.ended){showMultiplayerGameOver();return}
    if(!serverPaused)document.getElementById('multiplayerWaiting').classList.add('hidden');renderTeamHud(state.players);
    if(state.wave&&state.wave.seq!==lastWaveSeq){lastWaveSeq=state.wave.seq;showWaveBanner(state.wave.title,`FAZA ${state.wave.phase+1}`)}
    for(const event of state.explosions||[])if(event.seq>lastExplosionSeq){lastExplosionSeq=event.seq;rings.push({x:event.x,y:event.y,r:8,max:event.r||145,life:.45,color:'#ff7938'})}for(const current of state.players){
      const old=previous?.players?.find(p=>p.id===current.id);
      if(old&&(current.abilitySeq||0)!==(old.abilitySeq||0))playMultiplayerAbilityVisual(current.character,current.lastAbility,current,old);
    }
    const classification=SwarmRemoteVisuals.classifyPlayers(state.players,authoritativePlayerId),mine=classification.local;
    if(mine){
      const wasDead=isDead,firstLocalState=!hasSeenLocalState;hasSeenLocalState=true;isDead=mine.alive===false;if(isDead&&!wasDead&&!firstLocalState)enterDeathSpectator();if(isDead&&firstLocalState){deathOverlayUntil=0;hideDeathUi()}isSpectator=isDead&&deathOverlayUntil===0&&state.players.some(other=>other.id!==authoritativePlayerId&&other.alive!==false);if(isDead)pendingInputs=[];if(!isDead)spectatorTargetId=null;
      if(!isDead){const oldMine=previous?.players?.find(p=>p.id===authoritativePlayerId),confirmedDash=mine.character==='warrior'&&mine.lastAbility==='e'&&(mine.abilitySeq||0)!==(oldMine?.abilitySeq||0),result=SwarmClientUtils.reconcileSnapshot(predictionState,player,{tick:state.tick,x:mine.x,y:mine.y,lastProcessedInputSeq:mine.lastProcessedInputSeq,serverTime:state.serverTime},{mapId:chosenMap,radius:player.r,collision:SwarmCollision,confirmedDash});if(result.applied){player.x=result.position.x;player.y=result.position.y;if(debugPerformance){debugMetrics.reconciles++;debugMetrics.reconcileErrorTotal+=result.error||0;if(result.hard)debugMetrics.hardCorrections++}}pendingInputs=predictionState.pending}
      player.hp=mine.hp;if(Number.isFinite(mine.coins)){player.coins=mine.coins;ui.hudCoins.textContent=mine.coins}player.maxHp=mine.maxHp;player.kills=mine.kills;effectiveSpeed=mine.speed||characterDefs[chosenCharacter].speed;
      if(mine.attackSeq!==localAttackSeq){localAttackSeq=mine.attackSeq;player.attackAnim=mine.character==='scout'?SCOUT_ATTACK_DURATION:mine.character==='warrior'?WARRIOR_ATTACK_DURATION:.28;player.attackAngle=mine.facing}
      if(mine.abilitySeq!==localAbilitySeq){localAbilitySeq=mine.abilitySeq;player.skillAnim=mine.lastAbility;player.skillAnimTime=mine.lastAbility==='r'?1.4:mine.lastAbility==='e'?1.1:.7}
      if(mine.cooldowns){player.serverCooldowns=mine.cooldowns}if(mine.items)applyAuthoritativeBuild(mine)
    }
    previousEnemies=new Map((previous?.enemies||[]).map(e=>[e.id,e]));
    remotePlayers=classification.remote;if(!classification.valid){authoritativePlayerId=null;pendingInputs=[];console.error('Multiplayer ownership invariant failed; input disabled.');return}SwarmRemoteVisuals.update(remoteVisuals,remotePlayers,receivedAt);
    SwarmRemoteVisuals.updateEntities(enemyVisuals,state.enemies,receivedAt);SwarmRemoteVisuals.updateEntities(bulletVisuals,state.bullets,receivedAt);SwarmRemoteVisuals.updateEntities(enemyBulletVisuals,state.enemyBullets||[],receivedAt);SwarmRemoteVisuals.updateEntities(orbVisuals,state.orbs||[],receivedAt);
    enemies=state.enemies.map(e=>({...e,type:e.type||'melee',hit:SwarmRemoteVisuals.damageFlash(previousEnemies.get(e.id),e)}));
    bullets=state.bullets.map(b=>({...b,r:b.r||4,kind:b.kind||'scoutBullet'}));enemyBullets=(state.enemyBullets||[]).map(b=>({...b,r:b.r||6}));orbs=(state.orbs||[]).map(o=>({...o,r:5,vx:0,vy:0}));loot=state.loot||[];crates=(state.crates||[]).map(c=>({...c,hit:((previous?.crates||[]).find(old=>old.id===c.id)?.hitSeq!==c.hitSeq ? .15 : 0)}));
    if(isDead&&deathOverlayUntil===0){const watched=SwarmRemoteVisuals.selectSpectatorTarget(state.players,authoritativePlayerId,mine||player,spectatorTargetId);if(watched){spectatorTargetId=watched.id;isSpectator=true}}updateUI();
  }
  function updateVisualEffects(dt){
    player.attackAnim=Math.max(0,(player.attackAnim||0)-dt);player.teleportAnim=Math.max(0,(player.teleportAnim||0)-dt);player.skillAnimTime=Math.max(0,(player.skillAnimTime||0)-dt);
    playerEchoes.forEach(e=>e.life-=dt);playerEchoes=playerEchoes.filter(e=>e.life>0);rings.forEach(r=>{r.r+=(r.max-r.r)*9*dt;r.life-=dt});rings=rings.filter(r=>r.life>0);
    particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.95;p.vy*=.95;p.life-=dt});particles=particles.filter(p=>p.life>0);
    screenShake*=Math.pow(.87,dt*60);if(screenShake<.05)screenShake=0;
    if(bannerTimer>0){bannerTimer-=dt;if(bannerTimer<=0)ui.waveBanner.classList.add('hidden')}
  }
  function updateCooldownUI(){for(const [key,skill]of Object.entries(skills)){const element=cooldownElements[key]||(cooldownElements[key]=document.querySelector(`[data-key="${key.toUpperCase()}"]`));if(!element)continue;element.classList.toggle('cooldown',skill.cd>0);const label=element.querySelector('.cd'),text=skill.cd>0?skill.cd.toFixed(skill.cd<10?1:0):'';if(label.textContent!==text)label.textContent=text}}
  function frame(dt){
    recordFrame(dt);if(!multiplayerMode)return;const ready=isActive(),connectionStatus=document.getElementById('multiplayerConnectionStatus');connectionStatus.classList.toggle('hidden',ready);updateVisualEffects(dt);if(!ready){pendingInputs=[];return}sendClock-=dt;
    const gameplayEnabled=SwarmRemoteVisuals.gameplayEnabled({isDead,serverPaused,localMenuOpen}),serverNow=cooldownFrozenAt?cooldownFrozenServerNow:estimatedServerNow(),cooldowns=player.serverCooldowns,movement=window.SwarmMovementInput.resolve();if(cooldowns){skills.q.cd=Math.max(0,(cooldowns.qReadyAt-serverNow)/1000);skills.e.cd=Math.max(0,(cooldowns.eReadyAt-serverNow)/1000);skills.r.cd=Math.max(0,(cooldowns.rReadyAt-serverNow)/1000);updateCooldownUI()}
    if(sendClock<=0){const aim=Math.atan2(mouse.y+camera.y-player.y,mouse.x+camera.x-player.x),neutral=!gameplayEnabled,input={up:neutral?false:movement.up,down:neutral?false:movement.down,left:neutral?false:movement.left,right:neutral?false:movement.right,aim,seq:++inputSeq};socket().send('playerInput',{...input,inputSeq:input.seq});sendClock=1/25}
    if(gameplayEnabled){const dx=movement.dx,dy=movement.dy,speed=effectiveSpeed||characterDefs[chosenCharacter].speed,predicted=SwarmClientUtils.predictInput(predictionState,player,{seq:inputSeq,dx,dy,predictedAt:serverNow},dt,{mapId:chosenMap,radius:player.r,speed,collision:SwarmCollision});player.x=predicted.x;player.y=predicted.y;pendingInputs=predictionState.pending}
    if(state){const now=performance.now();remotePlayers=[...remoteVisuals.values()].map(visual=>SwarmRemoteVisuals.sample(visual,now,72));enemies=SwarmRemoteVisuals.sampleEntities(enemyVisuals,now).map(current=>({...current,type:current.type||'melee',spawnProgress:SwarmClientUtils.spawnProgress(current.spawnedAt,estimatedServerNow(),current.spawnDuration),hit:SwarmRemoteVisuals.damageFlash(previousEnemies.get(current.id),current)}));bullets=SwarmRemoteVisuals.sampleEntities(bulletVisuals,now).map(current=>({...current,r:current.r||4,kind:current.kind||'scoutBullet'}));enemyBullets=SwarmRemoteVisuals.sampleEntities(enemyBulletVisuals,now).map(current=>({...current,r:current.r||6}));orbs=SwarmRemoteVisuals.sampleEntities(orbVisuals,now).map(current=>({...current,r:5,vx:0,vy:0}));if(deathOverlayUntil&&now>=deathOverlayUntil){document.getElementById('multiplayerDeathOverlay')?.classList.add('hidden');deathOverlayUntil=0;isSpectator=isDead;const target=SwarmRemoteVisuals.selectSpectatorTarget(remotePlayers,authoritativePlayerId,player,spectatorTargetId);if(target)spectatorTargetId=target.id}if(isSpectator){const watched=SwarmRemoteVisuals.selectSpectatorTarget(remotePlayers,authoritativePlayerId,player,spectatorTargetId);if(watched){spectatorTargetId=watched.id;const targetX=Math.max(0,Math.min(WORLD.w-W,watched.x-W/2)),targetY=Math.max(0,Math.min(WORLD.h-H,watched.y-H/2));camera.x=SwarmRemoteVisuals.cameraFollowStep(camera.x,targetX,8,dt);camera.y=SwarmRemoteVisuals.cameraFollowStep(camera.y,targetY,8,dt);const label=document.getElementById('multiplayerSpectatorLabel');label.textContent=`SPECTATING: ${(watched.name||watched.character||'TEAMMATE').toUpperCase()}`;label.classList.remove('hidden')}else spectatorTargetId=null}else if(!isDead){const targetX=Math.max(0,Math.min(WORLD.w-W,player.x-W/2)),targetY=Math.max(0,Math.min(WORLD.h-H,player.y-H/2));camera.x=SwarmRemoteVisuals.cameraFollowStep(camera.x,targetX,14,dt);camera.y=SwarmRemoteVisuals.cameraFollowStep(camera.y,targetY,14,dt)}}
  }
  function levelShown(){}
  function pressAbility(ability){if(!isActive()||!SwarmRemoteVisuals.gameplayEnabled({isDead,serverPaused,localMenuOpen}))return false;const readyAt=player.serverCooldowns?.[`${ability}ReadyAt`],now=cooldownFrozenAt?cooldownFrozenServerNow:estimatedServerNow();if(!SwarmMechanics.canAttemptAbility({readyAt,now,hasBloodPrice:Boolean(augments.blood_price),hp:player.hp,maxHp:player.maxHp}))return false;const aim=Math.atan2(mouse.y+camera.y-player.y,mouse.x+camera.x-player.x);socket().send('abilityPress',{ability,aim,seq:++abilityInputSeq});return true}
  function toggleLocalMenu(){if(!multiplayerMode||!running)return false;localMenuOpen=!localMenuOpen;movementInput.clear();if(localMenuOpen){if(!isDead&&isActive()&&pauseReason!=='upgrade'){localPauseRequested=true;socket().send('pauseRequest',{requested:true})}showPauseUi(serverPaused&&pauseReason==='manual');return true}SwarmRemoteVisuals.setLocalMenuLayer(ui.pauseModal,false);if(isActive()&&serverPaused&&pauseReason==='manual')socket().send('resumeGame');else if(isActive()&&localPauseRequested)socket().send('pauseRequest',{requested:false});localPauseRequested=false;return true}
  function choiceMade(choice){if(!isActive()||isDead)return false;socket().send('upgradeChoice',{choice});return true}
  function requestReroll(index){if(isActive()&&!isDead)socket().send('rerollUpgrade',{index})}
  function shouldDrawLocalPlayer(){return!multiplayerMode||!isDead}
  function drawPlayers(context){remotePlayers.filter(other=>other.alive!==false).forEach(other=>drawCharacterActor(context,{x:other.x,y:other.y,character:other.character,facing:other.facing,animation:other.animation,animationTime:other.animationTime,name:other.name||'GRACZ',hp:other.hp,maxHp:other.maxHp,attackAnim:other.attackAnim}))}
  window.SwarmMultiplayerSync={abortMultiplayerSession,isMultiplayerMode,isActive,frame,pressAbility,toggleLocalMenu,exitMultiplayer,levelShown,choiceMade,requestReroll,shouldDrawLocalPlayer,drawPlayers};
  const currentSocket=socket(),existingAck=currentSocket?.getLastHelloAck?.();if(existingAck)accept(existingAck);currentSocket?.on?.(accept);
})();
