(() => {
  const fallbackText={'multiplayer.invalidCode':'Kod lobby musi mieć 6 znaków.','multiplayer.noConnection':'Brak połączenia z serwerem multiplayer.'},t=(key,params)=>globalThis.SwarmI18n?.t?.(key,params)||fallbackText[key]||key,byId=id=>document.getElementById(id),modal=byId('multiplayerModal'),actions=byId('multiplayerActions'),joinForm=byId('joinLobbyForm'),codeInput=byId('lobbyCodeInput'),message=byId('lobbyMessage'),room=byId('lobbyRoom'),readyBtn=byId('lobbyReadyBtn'),startBtn=byId('lobbyStartBtn');
  const createInstallationId=()=>{if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();const bytes=new Uint8Array(16);if(globalThis.crypto?.getRandomValues)globalThis.crypto.getRandomValues(bytes);else for(let i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256);return Array.from(bytes,byte=>byte.toString(16).padStart(2,'0')).join('')};
  const installationId=localStorage.getItem('swarmfall-installation-id')||createInstallationId(),unlocked=(()=>{try{return[...new Set(['scout',...JSON.parse(localStorage.getItem('swarmfall-unlocked')||'[]')])]}catch{return['scout']}})();localStorage.setItem('swarmfall-installation-id',installationId);
  let socket,lobby=null,retry=0,pingId=0,pingRtt=null,pingSamples=[],gameStarting=false,preparingId=null,localAssetsReady=false,assetsReadySentGeneration=0,identity=null,connectEpoch=0,reconnectTimer=null;const channel=SwarmSocketState.createControlChannel(),clock=globalThis.SwarmClientUtils?.createClockSync?.()||{observe:()=>null,estimatedServerNow:(fallback,receivedAt)=>Number.isFinite(fallback)?fallback+Math.max(0,(globalThis.performance?.now?.()??Date.now())-receivedAt):NaN,getOffset:()=>null};let pendingReconnect=(()=>{try{const value=JSON.parse(sessionStorage.getItem('swarmfall-multiplayer-session')||'null');return SwarmSaveState.isReconnectSession(value)?value:null}catch{return null}})();
  window.SwarmSocket={send,on:channel.on,getLobby:()=>lobby,getIdentity:()=>identity,getHandshakeState:channel.getHandshakeState,getLastHelloAck:channel.getLastHelloAck,isOpen:()=>socket?.readyState===WebSocket.OPEN&&channel.getHandshakeState()==='authenticated',estimatedServerNow:(fallback,receivedAt)=>clock.estimatedServerNow(fallback,receivedAt),getClockOffset:clock.getOffset,getRtt:()=>pingRtt};
  const characterName=id=>t(`characters.${id}`),mapName=id=>t(`maps.${id}`);
  function send(type,data={}){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type,...data}));else showError(t('multiplayer.noConnection'))}
  function connect(){
    const protocol=location.protocol==='https:'?'wss:':'ws:',epoch=++connectEpoch,ws=new WebSocket(`${protocol}//${location.host}`);socket=ws;channel.beginConnection();
    const current=()=>socket===ws&&connectEpoch===epoch;
    ws.onopen=()=>{if(!current())return;const resumeIdentity=pendingReconnect;ws.send(JSON.stringify({type:'hello',installationId,resume:resumeIdentity?{playerId:resumeIdentity.playerId,reconnectToken:resumeIdentity.reconnectToken}:undefined,unlocked,maps:['ruins',...(window.Achievements?.isComplete('map_1')?['toxic']:[])]}))};
    ws.onmessage=event=>{if(!current())return;let data;try{data=JSON.parse(event.data)}catch{return}if(data.type==='pong'){const sent=Number(data.clientTime),now=globalThis.performance?.now?.()??Date.now(),sample=clock.observe({clientTime:sent,serverTime:Number(data.serverTime),receivedAt:now});if(sample){const rawRtt=now-sent;pingSamples.push(rawRtt);if(pingSamples.length>5)pingSamples.shift();const sorted=[...pingSamples].sort((a,b)=>a-b),median=sorted[Math.floor(sorted.length/2)];pingRtt=SwarmClientUtils.smoothRtt(pingRtt,median,.25);if(localStorage.getItem('swarmfall-debug-multiplayer')==='1')console.debug('[MP PING]',{rawRtt,displayedRtt:pingRtt,samples:[...pingSamples]});const display=byId('multiplayerPing'),quality=SwarmClientUtils.pingQuality(pingRtt);display.textContent=`PING ${Math.round(pingRtt)} ms`;display.className=`multiplayer-ping ${quality}`}return}if(data.type==='helloAck'){retry=0;identity={playerId:data.playerId,reconnectToken:data.reconnectToken,connectionId:data.connectionId,connectionGeneration:data.connectionGeneration};if(data.lobbyCode){pendingReconnect={lobbyCode:data.lobbyCode,playerId:data.playerId,reconnectToken:data.reconnectToken};sessionStorage.setItem('swarmfall-multiplayer-session',JSON.stringify(pendingReconnect))}}else if(data.type==='resumeRejected'){identity=null;pendingReconnect=null;lobby=null;preparingId=null;localAssetsReady=false;assetsReadySentGeneration=0;sessionStorage.removeItem('swarmfall-multiplayer-session');sessionStorage.removeItem('swarmfall-lobby-map');sessionStorage.removeItem('swarmfall-lobby-characters');byId('assetLoading').classList.add('hidden');byId('assetLoading').setAttribute('aria-busy','false')}else if(data.type==='leftLobby'){byId('multiplayerPing').className='multiplayer-ping hidden';lobby=null;pendingReconnect=null;preparingId=null;sessionStorage.removeItem('swarmfall-multiplayer-session');sessionStorage.removeItem('swarmfall-lobby-map');sessionStorage.removeItem('swarmfall-lobby-characters');modal.classList.add('hidden');byId('startModal').classList.remove('hidden')}else if(data.type==='lobbyState'){const wasStarted=lobby?.started;lobby=data.lobby;if(identity){pendingReconnect={lobbyCode:lobby.code,playerId:identity.playerId,reconnectToken:identity.reconnectToken};sessionStorage.setItem('swarmfall-multiplayer-session',JSON.stringify(pendingReconnect))}if(!lobby.started&&!lobby.preparing){gameStarting=false;byId('endModal')?.classList.add('hidden');byId('startModal').classList.add('hidden');modal.classList.remove('hidden')}renderRoom()}else if(data.type==='gamePreparing')prepareGame(data.lobby,data.matchId);else if(data.type==='assetsReadyState')showPreparingProgress(data);else if(data.type==='joinError'||data.type==='error')showError(data.message);else if(data.type==='gameStarted')launchGame(data.lobby,data.matchId);channel.publish(data);if(data.type==='resumeRejected')ws.close()};
    ws.onclose=event=>{if(!current())return;channel.invalidate(event.code===4001?'superseded':'closed');if(event.code===4001||event.code===4003){showError(t(event.code===4001?'multiplayer.replaced':'multiplayer.reconnectExpired'));return}if(retry++<8)reconnectTimer=setTimeout(connect,Math.min(5000,400*2**retry))};
    ws.onerror=()=>{if(!current())return};
  }
  async function copyLobbyCode(){const button=byId('copyLobbyCodeBtn'),ok=await SwarmClientUtils.copyLobbyCode(lobby?.code||'',{clipboard:navigator.clipboard,document});if(!ok)return showError(t('multiplayer.copyFailed'));button.textContent=t('multiplayer.copied');setTimeout(()=>button.textContent=t('multiplayer.copy'),1500)}
  function showError(text){message.textContent=text;message.className='lobby-message error'}
  function me(){return lobby?.players.find(player=>player.id===identity?.playerId)}
  function setView(view){actions.classList.toggle('hidden',view!=='actions');joinForm.classList.toggle('hidden',view!=='join');room.classList.toggle('hidden',view!=='room');message.textContent='';message.className='lobby-message'}
  window.SwarmRefreshLobbyPreviews=()=>{if(lobby)copyPreviews()};
  function copyPreviews(){byId('lobbyMapPicker').querySelectorAll('canvas[data-map-preview]').forEach(canvas=>canvas.getContext('2d').drawImage(byId(canvas.dataset.mapPreview==='toxic'?'toxicMapPreview':'mapPreviewCanvas'),0,0,canvas.width,canvas.height));byId('lobbyCharacterPicker').querySelectorAll('canvas[data-character-preview]').forEach(canvas=>canvas.getContext('2d').drawImage(byId(`${canvas.dataset.characterPreview}Preview`),0,0,canvas.width,canvas.height))}
  function renderPickers(player){const host=player.host,mapIds=['ruins',...(window.Achievements?.isComplete('map_1')?['toxic']:[])];byId('lobbyMapPicker').querySelector('div').innerHTML=(host?mapIds:[lobby.map]).map(id=>`<button type="button" data-lobby-map="${id}" class="visual-pick ${lobby.map===id?'selected':''}" ${host?'':'disabled'}><canvas class="pick-preview" data-map-preview="${id}" width="320" height="150"></canvas><b>${mapName(id)}</b><small>${t(id==='toxic'?'multiplayer.fogPoison':'multiplayer.waterRuins')}</small></button>`).join('');byId('lobbyMapPicker').querySelectorAll('[data-lobby-map]').forEach(button=>button.onclick=()=>send('selectMap',{map:button.dataset.lobbyMap}));byId('lobbyCharacterPicker').querySelector('div').innerHTML=unlocked.map(id=>`<button type="button" data-lobby-character="${id}" class="visual-pick ${player.character===id?'selected':''}"><canvas class="pick-preview" data-character-preview="${id}" width="320" height="150"></canvas><b>${characterName(id)}</b><small>${t(`characters.${id==='warrior'?'melee':id==='druid'?'support':'range'}`)}</small></button>`).join('');byId('lobbyCharacterPicker').querySelectorAll('[data-lobby-character]').forEach(button=>button.onclick=()=>send('selectCharacter',{character:button.dataset.lobbyCharacter}));copyPreviews()}
  function renderRoom(){if(!lobby)return;const player=me();if(!player)return;setView('room');byId('activeLobbyCode').textContent=lobby.code;byId('lobbyRole').textContent=player.host?t('multiplayer.yourLobby'):t('multiplayer.joinedLobby');byId('lobbyPlayerCount').textContent=`${lobby.players.length} / 4`;byId('lobbyPlayerList').innerHTML=lobby.players.map(p=>`<li><i class="${p.ready?'ready':''}"></i><span>${p.name}<small>${characterName(p.character)}</small></span><b>${p.host?t('multiplayer.host'):p.ready?t('multiplayer.ready'):t('multiplayer.notReady')}</b></li>`).join('');renderPickers(player);readyBtn.classList.toggle('hidden',player.host);readyBtn.classList.toggle('selected',player.ready);readyBtn.textContent=player.ready?t('multiplayer.cancelReady'):t('multiplayer.ready');startBtn.classList.toggle('hidden',!player.host);startBtn.disabled=!lobby.players.filter(p=>!p.host).every(p=>p.ready)}
  function assetOverlay(status,progress=0,failed=false){const overlay=byId('assetLoading');overlay.classList.remove('hidden');overlay.setAttribute('aria-busy',failed?'false':'true');byId('assetLoadingStatus').textContent=status;byId('assetLoadingBar').style.width=`${Math.round(progress*100)}%`;byId('assetLoadingPercent').textContent=`${Math.round(progress*100)}%`;byId('assetLoadingRetry').classList.toggle('hidden',!failed)}
  function acknowledgeAssetsReady(matchId){const generation=identity?.connectionGeneration||0;if(!generation||assetsReadySentGeneration===generation)return;assetsReadySentGeneration=generation;send('assetsReady',{matchId})}
  async function prepareGame(nextLobby,matchId,manual=false){if(preparingId===matchId&&!manual){if(localAssetsReady)acknowledgeAssetsReady(matchId);return}preparingId=matchId;localAssetsReady=false;assetsReadySentGeneration=0;gameStarting=false;lobby=nextLobby;const characters=[...new Set(lobby.players.map(member=>member.character).filter(Boolean))],player=me(),spec={map:lobby.map,character:player?.character,characters};sessionStorage.setItem('swarmfall-lobby-map',lobby.map);sessionStorage.setItem('swarmfall-lobby-characters',JSON.stringify(characters));modal.classList.add('hidden');assetOverlay(t('multiplayer.loading'));byId('assetLoadingRetry').onclick=()=>prepareGame(nextLobby,matchId,true);try{const wait=manual?SwarmAssets.retryFailed:SwarmAssets.waitForRequired;await wait(spec,{onProgress:state=>{if(preparingId===matchId)assetOverlay(t('multiplayer.loading'),state.progress)}});if(preparingId!==matchId)return;localAssetsReady=true;assetOverlay(t('multiplayer.waitingPlayers'),1);acknowledgeAssetsReady(matchId)}catch{if(preparingId===matchId)assetOverlay(t('multiplayer.loadFailed'),0,true)}}
  function showPreparingProgress(state){if(state.matchId!==preparingId||!localAssetsReady)return;assetOverlay(t('multiplayer.waitingProgress',state),1)}
  function launchGame(nextLobby,matchId){if(gameStarting||preparingId&&preparingId!==matchId)return;gameStarting=true;preparingId=null;localAssetsReady=false;assetsReadySentGeneration=0;lobby=nextLobby;const player=me(),characters=[...new Set(lobby.players.map(member=>member.character).filter(Boolean))];sessionStorage.setItem('swarmfall-lobby-map',lobby.map);sessionStorage.setItem('swarmfall-lobby-characters',JSON.stringify(characters));sessionStorage.setItem('swarmfall-multiplayer-session',JSON.stringify({lobbyCode:lobby.code,playerId:identity.playerId,reconnectToken:identity.reconnectToken}));localStorage.setItem('swarmfall-character',player.character);modal.classList.add('hidden');window.SwarmGameStart.multiplayer()}
  byId('multiplayerBtn').onclick=()=>{byId('startModal').classList.add('hidden');modal.classList.remove('hidden');setView(lobby?'room':'actions');if(lobby)renderRoom()};byId('createLobbyBtn').onclick=()=>send('createLobby',{character:localStorage.getItem('swarmfall-character')||'scout'});byId('showJoinLobbyBtn').onclick=()=>{setView('join');codeInput.focus()};joinForm.onsubmit=event=>{event.preventDefault();const code=codeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,'');if(code.length!==6)return showError(t('multiplayer.invalidCode'));send('joinLobby',{code,character:localStorage.getItem('swarmfall-character')||'scout'})};codeInput.oninput=()=>codeInput.value=codeInput.value.toUpperCase().replace(/[^A-Z0-9]/g,'');readyBtn.onclick=()=>send('playerReady',{ready:!me().ready});startBtn.onclick=()=>send('startGame');byId('copyLobbyCodeBtn').onclick=copyLobbyCode;byId('multiplayerBackBtn').onclick=()=>{if(lobby)return send('leaveLobby');modal.classList.add('hidden');byId('startModal').classList.remove('hidden');setView('actions')};globalThis.SwarmI18n?.onChange?.(()=>{if(lobby)renderRoom()});globalThis.setInterval?.(()=>{if(socket?.readyState===WebSocket.OPEN&&channel.getHandshakeState()==='authenticated'){const clientTime=globalThis.performance?.now?.()??Date.now();send('ping',{id:++pingId,clientTime})}},1500);connect()
})();
