(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SwarmSaveState=api})(typeof globalThis!=='undefined'?globalThis:this,()=>{
  const SAVE_VERSION=3,limits={enemies:450,bullets:250,enemyBullets:250,orbs:350,loot:100,crates:100,rings:150,poisonClouds:100,traps:100,eventHistory:100,upgradeOfferKeys:3,upgradeRerolled:3,runKillTypes:32};
  function validNumber(value,min=-1e7,max=1e7){return Number.isFinite(value)&&value>=min&&value<=max}
  function plain(value){return Boolean(value&&typeof value==='object'&&!Array.isArray(value))}
  function safeTree(value,depth=0){if(depth>8)return false;if(value===null||typeof value==='string'||typeof value==='boolean')return true;if(typeof value==='number')return validNumber(value,-1e15,1e15);if(Array.isArray(value))return value.length<=500&&value.every(item=>safeTree(item,depth+1));if(!plain(value)||Object.keys(value).length>150)return false;return Object.values(value).every(item=>safeTree(item,depth+1))}
  function entity(value){return plain(value)&&validNumber(value.x)&&validNumber(value.y)&&(!('r'in value)||validNumber(value.r,0,1000))&&(!('hp'in value)||validNumber(value.hp,-1e5,1e7))}
  const entityArrays=new Set(['enemies','bullets','enemyBullets','orbs','loot','crates','rings','poisonClouds','traps']);
  function validArray(save,key){const value=save[key];return value===undefined||Array.isArray(value)&&value.length<=limits[key]&&(!entityArrays.has(key)||value.every(entity))}
  function isReconnectSession(value){const code=value?.lobbyCode||value?.code;return plain(value)&&typeof code==='string'&&/^[A-Z2-9]{6}$/.test(code)&&typeof value.playerId==='string'&&value.playerId.length>0&&value.playerId.length<=80&&typeof value.reconnectToken==='string'&&value.reconnectToken.length>0&&value.reconnectToken.length<=128}
  function validateSingleplayerSave(value){if(!plain(value)||!safeTree(value)||value.mode!=='singleplayer'||value.version!==SAVE_VERSION||!validNumber(value.elapsed,0)||!plain(value.player)||!validNumber(value.player.x)||!validNumber(value.player.y)||!validNumber(value.player.hp,-1e5,1e7)||!validNumber(value.player.maxHp,1,1e7)||!['scout','warrior','druid'].includes(value.chosenCharacter)||!['ruins','toxic'].includes(value.chosenMap)||!['normal','hard','nightmare'].includes(value.chosenMode||'normal'))return false;return Object.keys(limits).every(key=>validArray(value,key))&&['enemies','bullets','orbs'].every(key=>Array.isArray(value[key]))}
  function startupFlow(multiplayerSession,save){if(isReconnectSession(multiplayerSession))return'multiplayer-reconnect';return validateSingleplayerSave(save)?'singleplayer-continue':'fresh-menu'}
  return{SAVE_VERSION,validateSingleplayerSave,isReconnectSession,startupFlow}
});
