(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SwarmSaveState=api})(typeof globalThis!=='undefined'?globalThis:this,()=>{
  const SAVE_VERSION=3,SAVE_LIMITS={enemies:450,bullets:250,enemyBullets:250,orbs:350,loot:100,crates:100,rings:150,poisonClouds:100,traps:100,eventHistory:100,upgradeOfferKeys:3,upgradeRerolled:3,runKillTypes:32};
  const CHARACTERS=new Set(['scout','warrior','druid']),MAPS=new Set(['ruins','toxic']),MODES=new Set(['normal','hard','nightmare','endless']),ITEMS=new Set(['speed','vital','rapid','power','multi','cooldown','magnet','lifesteal','scope','crystal','blade','powder','spikes','adrenaline','bottle','lens','totem','vault']),AUGMENTS=new Set(['executor','giant_hunter','last_chance','glass_cannon','perfectionist','recycling','blood_price','second_chamber','gambler','greed_curse','parasite']),ENEMIES=new Set(['melee','brute','shooter','charger','exploder','swarm','toxic','trapper']);
  function validNumber(value,min=-1e7,max=1e7){return Number.isFinite(value)&&value>=min&&value<=max}
  function plain(value){return Boolean(value&&typeof value==='object'&&!Array.isArray(value))}
  function safeTree(value,depth=0){if(depth>8)return false;if(value===null||typeof value==='string'||typeof value==='boolean')return true;if(typeof value==='number')return validNumber(value,-1e15,1e15);if(Array.isArray(value))return value.length<=500&&value.every(item=>safeTree(item,depth+1));if(!plain(value)||Object.keys(value).length>150)return false;return Object.values(value).every(item=>safeTree(item,depth+1))}
  function entity(value){return plain(value)&&validNumber(value.x)&&validNumber(value.y)&&(!('r'in value)||validNumber(value.r,0,1000))&&(!('hp'in value)||validNumber(value.hp,-1e5,1e7))}
  const entityArrays=new Set(['enemies','bullets','enemyBullets','orbs','loot','crates','rings','poisonClouds','traps']);
  function validUpgradeKey(value){if(typeof value!=='string'||value.length<3||value.length>50)return false;const split=value.indexOf('-'),kind=value.slice(0,split),id=value.slice(split+1);return kind==='item'&&ITEMS.has(id)||kind==='super'&&ITEMS.has(id)||kind==='rare'&&id==='vault'||kind==='augment'&&AUGMENTS.has(id)}
  function validArray(save,key){const value=save[key];if(value===undefined)return true;if(!Array.isArray(value)||value.length>SAVE_LIMITS[key])return false;if(entityArrays.has(key))return value.every(entity);if(key==='upgradeOfferKeys')return value.every(validUpgradeKey);if(key==='upgradeRerolled')return value.every(item=>Number.isInteger(item)&&item>=0&&item<=2)&&new Set(value).size===value.length;if(key==='runKillTypes')return value.every(item=>typeof item==='string'&&ENEMIES.has(item));return true}
  function validBuild(value,allowed,max){return value===undefined||plain(value)&&Object.entries(value).every(([key,level])=>allowed.has(key)&&Number.isInteger(level)&&level>=0&&level<=max)}
  function limitSaveCollections(value){const result={...value};for(const[key,limit]of Object.entries(SAVE_LIMITS))if(Array.isArray(result[key])){let values=result[key];if(key==='upgradeOfferKeys')values=values.filter(validUpgradeKey);else if(key==='upgradeRerolled')values=[...new Set(values.filter(item=>Number.isInteger(item)&&item>=0&&item<=2))];else if(key==='runKillTypes')values=values.filter(item=>typeof item==='string'&&ENEMIES.has(item));result[key]=['crates','upgradeOfferKeys','upgradeRerolled','runKillTypes'].includes(key)?values.slice(0,limit):values.slice(-limit)}return result}
  function isReconnectSession(value){const code=value?.lobbyCode||value?.code;return plain(value)&&typeof code==='string'&&/^[A-Z2-9]{6}$/.test(code)&&typeof value.playerId==='string'&&value.playerId.length>0&&value.playerId.length<=80&&typeof value.reconnectToken==='string'&&value.reconnectToken.length>0&&value.reconnectToken.length<=128}
  function validateSingleplayerSave(value){if(!plain(value)||!safeTree(value)||value.mode!=='singleplayer'||value.version!==SAVE_VERSION||!validNumber(value.elapsed,0)||!plain(value.player)||!validNumber(value.player.x)||!validNumber(value.player.y)||!validNumber(value.player.hp,-1e5,1e7)||!validNumber(value.player.maxHp,1,1e7)||!CHARACTERS.has(value.chosenCharacter)||!MAPS.has(value.chosenMap)||!MODES.has(value.chosenMode||'normal')||!validBuild(value.items,ITEMS,6)||!validBuild(value.levels,ITEMS,6)||!validBuild(value.augments,AUGMENTS,1))return false;return Object.keys(SAVE_LIMITS).every(key=>validArray(value,key))&&['enemies','bullets','orbs'].every(key=>Array.isArray(value[key]))}
  function sanitizeSingleplayerSave(value){if(!validateSingleplayerSave(value))return null;const result={...value,items:{...(value.items||value.levels||{})},augments:{...(value.augments||{})},upgradeOfferKeys:[...(value.upgradeOfferKeys||[])]};delete result.levels;delete result.items.vault;delete result.augments.greed_curse;result.upgradeOfferKeys=result.upgradeOfferKeys.filter(key=>key!=='rare-vault'&&key!=='item-vault'&&key!=='augment-greed_curse');return result}
  function startupFlow(multiplayerSession,save){if(isReconnectSession(multiplayerSession))return'multiplayer-reconnect';return validateSingleplayerSave(save)?'singleplayer-continue':'fresh-menu'}
  return{SAVE_VERSION,SAVE_LIMITS,limitSaveCollections,validateSingleplayerSave,sanitizeSingleplayerSave,isReconnectSession,startupFlow}
});
