'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),{performance}=require('node:perf_hooks'),DATA=require('./shared-game-data'),MAPS=require('./shared-map-data');
const PORT=Number(process.env.PORT)||8080,TICK_RATE=30,SNAPSHOT_RATE=20,MAX_PLAYERS=4,GRACE_MS=15000,LOBBY_TTL=30*60e3,GAME_TTL=2*60*60e3,alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const publicFiles=new Set(['index.html','style.css','game.js','enemy-data.js','map-data.js','enemy-visuals.js','feedback.js','achievements.js','upgrade-data.js','settings-data.js','save-state.js','shared-game-data.js','shared-map-data.js','multiplayer-socket-state.js','multiplayer.js','multiplayer-visual-state.js','multiplayer-game.js']);
const allowedMessages=new Set(['hello','createLobby','joinLobby','leaveLobby','selectMap','selectCharacter','playerReady','startGame','playerInput','abilityPress','upgradeChoice','rerollUpgrade','pauseRequest','resumeGame','returnToLobby']);
const limits={hello:500,createLobby:1500,joinLobby:700,leaveLobby:500,selectMap:250,selectCharacter:250,playerReady:200,startGame:500,playerInput:25,abilityPress:80,upgradeChoice:250,rerollUpgrade:250,pauseRequest:75,resumeGame:300,returnToLobby:500};
const finite=(n,min,max)=>Number.isFinite(n)&&n>=min&&n<=max,short=(v,n)=>typeof v==='string'&&v.length>0&&v.length<=n;
function activeUpgradePlayers(lobby){if(!lobby?.game)return[];return lobby.players.filter(member=>member.connected&&lobby.game.players[member.id]?.alive)}
function syncPaused(game){game.paused=Boolean(game.upgradePaused||game.manualPaused);return game.paused}
function clearPlayerInputs(game){for(const player of Object.values(game?.players||{}))player.input={}}
function resumeAfterUpgrade(lobby){const active=activeUpgradePlayers(lobby),game=lobby.game;if(game&&(game.upgradePaused||game.paused&&!game.manualPaused)&&active.length>0&&active.every(member=>member.choiceRound===game.levelRound)){game.upgradePaused=false;return true}return false}
function pauseState(lobby){const game=lobby.game,active=activeUpgradePlayers(lobby),requesterIds=active.filter(member=>game.pauseRequests.has(member.id)).map(member=>member.id);return{paused:Boolean(game.manualPaused||game.networkPaused),upgradePaused:Boolean(game.upgradePaused),pauseReason:game.upgradePaused?'upgrade':game.networkPaused?'network':game.manualPaused?'manual':null,requested:requesterIds.length,required:active.length,requesterIds}}
function pointInPolygon(x,y,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const[xi,yi]=points[i],[xj,yj]=points[j];if((yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)inside=!inside}return inside}
function blocked(map,x,y,r){const data=MAPS[map];if(!finite(x,0,3000)||!finite(y,0,2200)||!data||!pointInPolygon(x,y,data.shape))return true;return(data.terrain||[]).some(t=>t.type==='water'?pointInPolygon(x,y,t.points):t.type==='rock'?Math.hypot(x-t.x,y-t.y)<r+t.r*.84:x+r>t.x&&x-r<t.x+t.w&&y+r>t.y&&y-r<t.y+t.h)}
function createSpatialGrid(entities,cellSize=140){const cells=new Map();for(const entity of entities){const radius=entity.r||0,minX=Math.floor((entity.x-radius)/cellSize),maxX=Math.floor((entity.x+radius)/cellSize),minY=Math.floor((entity.y-radius)/cellSize),maxY=Math.floor((entity.y+radius)/cellSize);for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++){const key=`${x},${y}`,cell=cells.get(key)||[];cell.push(entity);cells.set(key,cell)}}return{cells,cellSize}}
function spatialCandidates(grid,x,y){return grid.cells.get(`${Math.floor(x/grid.cellSize)},${Math.floor(y/grid.cellSize)}`)||[]}
function newStats(character){const base=DATA.characters[character];return{damage:base.damage,fireRate:base.fireRate,speed:base.speed,maxHp:base.hp,projectileSpeed:base.projectileSpeed,projectileSize:character==='druid'?10:4,projectileLife:character==='druid'?2.1:1.3,projectiles:1,pierce:0,critChance:.1,critDamage:1.8,lifesteal:0,thorns:0,magnet:70,powder:0,totem:0,vault:0,cooldowns:{qReadyAt:0,eReadyAt:0,rReadyAt:0}}}
function applyUpgrade(player,key){const [kind,id]=String(key).split('-');if(kind==='augment'){if(!DATA.augments.includes(id)||player.augments.includes(id)||player.augments.length>=3)return false;player.augments.push(id);if(id==='glass_cannon'){player.stats.damage*=1.4;player.stats.maxHp=Math.round(player.stats.maxHp*.75);player.hp=Math.min(player.hp,player.stats.maxHp)}if(id==='greed_curse')player.stats.greed=true;if(id==='second_chamber')player.secondChamber=0;if(id==='last_chance')player.lastChance=0;if(id==='perfectionist'){player.perfectionTime=0;player.perfectionStacks=0}return true}if(kind!=='item'||!DATA.items[id])return false;const level=player.items[id]||0;if(level>=DATA.items[id].max||!level&&Object.keys(player.items).length>=3)return false;player.items[id]=level+1;switch(id){case'speed':player.stats.speed*=1.1;break;case'vital':player.stats.maxHp+=20;player.hp+=20;break;case'rapid':player.stats.fireRate/=1.14;break;case'power':player.stats.damage*=1.2;break;case'multi':player.stats.projectiles++;break;case'cooldown':player.cooldownScale*=.9;break;case'lens':player.stats.projectileSize*=1.12;break;case'scope':player.stats.projectileLife+=.22;break;case'crystal':player.stats.critChance+=.035;player.stats.critDamage+=.12;break;case'lifesteal':player.stats.lifesteal+=.8;break;case'spikes':player.stats.thorns+=8;break;case'adrenaline':player.stats.adrenaline=(player.stats.adrenaline||0)+.1;break;case'bottle':player.stats.regen=(player.stats.regen||0)+.15;break;case'magnet':player.stats.magnet+=35;break;case'powder':player.stats.powder+=.035;break;case'totem':player.stats.totem+=.1;break;case'vault':player.stats.vault=1;break;case'blade':player.stats.pierce++;break}return true}
class GameServer{
 constructor(now=()=>Date.now(),random=Math.random){this.now=now;this.random=random;this.lobbies=new Map();this.connectionsById=new Map();this.sessionsByPlayerId=new Map();this.debugEnabled=process.env.MP_DEBUG==='1'}
 debug(event,connection){if(this.debugEnabled)console.log('[MP]',event,{playerId:connection?.playerId||null,connectionId:connection?.connectionId||null,generation:connection?.connectionGeneration||0})}
 addClient(send=()=>{}){const connection={connectionId:crypto.randomUUID(),playerId:null,connectionGeneration:0,state:'pending',send,sendRaw:null,lobby:'',lastSeen:this.now(),rates:{},unlocked:['scout'],maps:['ruins'],disconnectAt:0};this.connectionsById.set(connection.connectionId,connection);this.debug('new connection',connection);return connection}
 currentConnection(playerId){const session=this.sessionsByPlayerId.get(playerId);return session?this.connectionsById.get(session.connectionId):null}
 isCurrentConnection(connection){const session=connection?.playerId&&this.sessionsByPlayerId.get(connection.playerId);return Boolean(connection?.state==='authenticated'&&session&&session.connectionId===connection.connectionId&&session.generation===connection.connectionGeneration)}
 emit(client,type,data={}){try{client?.send({type,...data})}catch{}}
 broadcast(lobby,type,data={}){const payload={type,...data},serialized=type==='gameState'?JSON.stringify(payload):null;lobby.players.forEach(member=>{const client=this.currentConnection(member.id);if(serialized&&client?.sendRaw)client.sendRaw(serialized);else try{client?.send(payload)}catch{}})}
 view(lobby){return{code:lobby.code,map:lobby.map,started:Boolean(lobby.game),matchId:lobby.game?.matchId||null,players:lobby.players.map(({id,name,host,ready,character,connected})=>({id,name,host,ready,character,connected}))}}
 publish(lobby){lobby.updatedAt=this.now();this.broadcast(lobby,'lobbyState',{lobby:this.view(lobby)})}
 rate(client,type){const now=this.now(),last=client.rates[type];if(last!==undefined&&now-last<limits[type])return false;client.rates[type]=now;return true}
 validate(client,msg){if(!msg||typeof msg!=='object'||Array.isArray(msg)||!allowedMessages.has(msg.type)||!this.rate(client,msg.type))return false;if(msg.type==='playerInput')return ['up','down','left','right'].every(k=>msg[k]===undefined||typeof msg[k]==='boolean')&&finite(msg.aim,-Math.PI*4,Math.PI*4)&&Number.isSafeInteger(msg.inputSeq)&&msg.inputSeq>=0;if(msg.type==='abilityPress')return ['q','e','r'].includes(msg.ability)&&Number.isSafeInteger(msg.seq)&&msg.seq>0&&finite(msg.aim,-Math.PI*4,Math.PI*4);if(msg.type==='pauseRequest')return typeof msg.requested==='boolean';if(msg.type==='joinLobby')return short(msg.code,6)&&/^[A-Z2-9]{6}$/.test(msg.code);if(msg.type==='selectMap')return['ruins','toxic'].includes(msg.map);if(msg.type==='selectCharacter')return['scout','warrior','druid'].includes(msg.character);if(msg.type==='upgradeChoice')return short(msg.choice,50);if(msg.type==='rerollUpgrade')return Number.isInteger(msg.index)&&msg.index>=0&&msg.index<3;if(msg.type==='hello')return short(msg.installationId,80)&&Array.isArray(msg.unlocked)&&msg.unlocked.length<=3&&(!msg.resume||typeof msg.resume==='object'&&short(msg.resume.playerId,80)&&short(msg.resume.reconnectToken,128));return true}
 authenticate(connection,msg){if(connection.state!=='pending')return;this.debug(msg.resume?'resume':'hello',connection);let session,resume=false;if(msg.resume){session=this.sessionsByPlayerId.get(msg.resume.playerId);const member=[...this.lobbies.values()].some(lobby=>lobby.players.some(player=>player.id===msg.resume.playerId&&(player.connected||this.now()-player.disconnectAt<=GRACE_MS)));if(!session||session.reconnectToken!==msg.resume.reconnectToken||!member){this.emit(connection,'resumeRejected',{reason:'expired'});connection.state='closed';connection.close?.(4003,'Resume rejected');return}resume=true}else{const playerId=crypto.randomUUID();session={playerId,reconnectToken:crypto.randomBytes(32).toString('base64url'),generation:0,connectionId:null};this.sessionsByPlayerId.set(playerId,session)}const old=this.connectionsById.get(session.connectionId);session.generation++;session.connectionId=connection.connectionId;connection.playerId=session.playerId;connection.connectionGeneration=session.generation;connection.state='authenticated';connection.unlocked=['scout',...msg.unlocked.filter(x=>['warrior','druid'].includes(x))];connection.maps=['ruins',...(msg.maps?.includes('toxic')?['toxic']:[])];if(old&&old!==connection){old.state='superseded';this.debug('replacement',connection);this.debug('supersede',old);old.supersede?.()}for(const found of this.lobbies.values()){const member=found.players.find(player=>player.id===session.playerId);if(!member)continue;member.connected=true;member.disconnectAt=0;connection.lobby=found.code;if(found.game?.players[member.id]){found.game.players[member.id].input={};found.game.networkPaused=false;this.updateSimulationPause(found)}break}const game=connection.lobby&&this.lobbies.get(connection.lobby)?.game,player=game?.players?.[session.playerId];this.emit(connection,'helloAck',{playerId:session.playerId,reconnectToken:session.reconnectToken,connectionId:connection.connectionId,connectionGeneration:session.generation,lobbyCode:connection.lobby||'',lastProcessedInputSeq:player?.lastProcessedInputSeq||0,lastAbilityInputSeq:player?.lastAbilityInputSeq||0,resume});if(connection.lobby){const found=this.lobbies.get(connection.lobby),member=found.players.find(item=>item.id===session.playerId);this.emit(connection,'lobbyState',{lobby:this.view(found)});if(found.game){if(found.game.ended)this.emit(connection,'gameOver',{reason:'allPlayersDead',matchId:found.game.matchId});else this.emit(connection,'gameStarted',{lobby:this.view(found),matchId:found.game.matchId});this.emit(connection,'pauseState',pauseState(found));if(found.game.upgradePaused&&player?.alive){if(member?.choiceRound===found.game.levelRound)this.emit(connection,'upgradeWaiting',{round:found.game.levelRound});else this.emit(connection,'levelUp',{round:found.game.levelRound,level:found.game.level,offer:player.offer||[]})}}}}
 code(){let c;do{c=Array.from({length:6},()=>alphabet[Math.floor(Math.random()*alphabet.length)]).join('')}while(this.lobbies.has(c));return c}
 handle(client,msg){if(!this.validate(client,msg))return this.emit(client,'error',{message:'Nieprawidłowa lub zbyt częsta wiadomość.'});client.lastSeen=this.now();if(msg.type!=='hello'&&!this.isCurrentConnection(client))return this.emit(client,'error',{message:'Połączenie nie ma aktualnego ownership gracza.'});if(msg.type==='hello')return this.authenticate(client,msg);let lobby=this.lobbies.get(client.lobby),member=lobby?.players.find(p=>p.id===client.playerId);
  if(msg.type==='createLobby'){if(lobby?.game)return this.emit(client,'error',{message:'Nie można opuścić aktywnego meczu.'});this.leave(client,true);const code=this.code(),created={code,map:'ruins',createdAt:this.now(),updatedAt:this.now(),players:[{id:client.playerId,name:'Gospodarz',host:true,ready:true,character:'scout',connected:true,choiceRound:0}],game:null};this.lobbies.set(code,created);client.lobby=code;return this.publish(created)}
  if(msg.type==='joinLobby'){if(lobby?.game)return this.emit(client,'joinError',{message:'Nie można opuścić aktywnego meczu.'});const target=this.lobbies.get(msg.code);if(!target||target.game||target.players.length>=MAX_PLAYERS)return this.emit(client,'joinError',{message:target?.players.length>=MAX_PLAYERS?'Lobby jest pełne.':'Nie znaleziono dostępnego lobby.'});this.leave(client,true);target.players.push({id:client.playerId,name:`Gracz ${target.players.length+1}`,host:false,ready:false,character:'scout',connected:true,choiceRound:0});client.lobby=target.code;return this.publish(target)}
  if(msg.type==='leaveLobby'&&lobby&&!lobby.game){this.leave(client,true);return this.emit(client,'leftLobby')}
  if(!lobby||!member)return this.emit(client,'error',{message:'Nie należysz do lobby.'});
  if(msg.type==='selectMap'&&member.host&&!lobby.game&&client.maps.includes(msg.map)){lobby.map=msg.map;lobby.players.forEach(p=>{if(!p.host)p.ready=false});return this.publish(lobby)}
  if(msg.type==='selectCharacter'&&!lobby.game&&client.unlocked.includes(msg.character)){member.character=msg.character;if(!member.host)member.ready=false;return this.publish(lobby)}
  if(msg.type==='playerReady'&&!member.host&&!lobby.game){member.ready=Boolean(msg.ready);return this.publish(lobby)}
  if(msg.type==='startGame'&&member.host&&!lobby.game&&lobby.players.every(p=>p.connected&&(p.host||p.ready))){this.start(lobby);this.broadcast(lobby,'gameStarted',{lobby:this.view(lobby),matchId:lobby.game.matchId});return this.broadcast(lobby,'pauseState',pauseState(lobby))}
  if(msg.type==='playerInput'&&lobby.game&&!lobby.game.ended&&!lobby.game.paused&&lobby.game.players[client.playerId]){const p=lobby.game.players[client.playerId];if(msg.inputSeq<=p.lastProcessedInputSeq)return;p.lastProcessedInputSeq=msg.inputSeq;return p.input={up:!!msg.up,down:!!msg.down,left:!!msg.left,right:!!msg.right,aim:msg.aim,received:true,inputSeq:msg.inputSeq}}
  if(msg.type==='abilityPress'&&lobby.game&&!lobby.game.ended&&!lobby.game.paused){const p=lobby.game.players[client.playerId];if(!p||!p.alive||msg.seq<=p.lastAbilityInputSeq)return; p.lastAbilityInputSeq=msg.seq;return this.castAbility(lobby,p,msg.ability,msg.aim)}
  if(msg.type==='pauseRequest'&&lobby.game&&!lobby.game.ended&&!lobby.game.upgradePaused&&!lobby.game.manualPaused){const p=lobby.game.players[client.playerId];if(!p?.alive)return;msg.requested?lobby.game.pauseRequests.add(p.id):lobby.game.pauseRequests.delete(p.id);return this.updateManualPause(lobby)}
  if(msg.type==='resumeGame'&&lobby.game?.manualPaused&&lobby.game.players[client.playerId]?.alive){this.resumeManualPause(lobby);return this.broadcast(lobby,'pauseState',pauseState(lobby))}
  if(msg.type==='rerollUpgrade'&&(lobby.game?.upgradePaused||lobby.game?.paused&&!lobby.game?.manualPaused)){const p=lobby.game.players[client.playerId];if(!p?.alive||member.choiceRound===lobby.game.levelRound||p.rerolled?.includes(msg.index)||!p.offer[msg.index])return this.emit(client,'error',{message:'Wymiana jest niedostępna.'});const blocked=new Set(p.offer),replacement=this.offer(p,blocked,1)[0];if(!replacement)return this.emit(client,'error',{message:'Brak innej karty.'});p.rerolled=p.rerolled||[];p.rerolled.push(msg.index);p.offer[msg.index]=replacement;return this.emit(client,'upgradeOffer',{round:lobby.game.levelRound,offer:p.offer,index:msg.index,matchId:lobby.game.matchId})}
  if(msg.type==='upgradeChoice'&&(lobby.game?.upgradePaused||lobby.game?.paused&&!lobby.game?.manualPaused)){const p=lobby.game.players[client.playerId];if(!p?.alive||member.choiceRound===lobby.game.levelRound||!p.offer.includes(msg.choice)||!applyUpgrade(p,msg.choice))return this.emit(client,'error',{message:'Ten upgrade nie jest dostępny.'});member.choiceRound=lobby.game.levelRound;p.offer=[];this.emit(client,'upgradeAccepted',{matchId:lobby.game.matchId,items:p.items,augments:p.augments,stats:{maxHp:p.stats.maxHp,speed:p.stats.speed},hp:p.hp});if(!this.resumeUpgradeIfReady(lobby))this.emit(client,'upgradeWaiting',{round:lobby.game.levelRound,matchId:lobby.game.matchId});return}
  if(msg.type==='returnToLobby'&&lobby.game?.ended){lobby.game=null;lobby.players.forEach(p=>p.ready=p.host);return this.publish(lobby)}
 }
 start(lobby){const players={};lobby.players.filter(m=>m.connected).forEach((m,i)=>{const stats=newStats(m.character);players[m.id]={id:m.id,name:m.name,character:m.character,x:1500+Math.cos(i*Math.PI/2)*55,y:1100+Math.sin(i*Math.PI/2)*55,hp:stats.maxHp,alive:true,kills:0,input:{},shot:0,items:{},augments:[],stats,cooldownScale:1,offer:[],rerolled:[],facing:0,attackSeq:0,abilitySeq:0,lastAbility:'',lastAbilityInputSeq:0,lastProcessedInputSeq:0}});lobby.game={matchId:crypto.randomUUID(),createdAt:this.now(),tick:0,time:0,level:1,xp:0,nextXp:24,paused:false,upgradePaused:false,manualPaused:false,networkPaused:false,simulationPausedAt:0,pauseRequests:new Set(),ended:false,levelRound:0,players,enemies:[],bullets:[],enemyBullets:[],orbs:[],loot:[],hazards:[],crates:(MAPS[lobby.map].crates||[]).map((c,i)=>({id:`c${i}`,x:c.x,y:c.y,hp:28,maxHp:28,opened:false})),spawn:0,bossAt:300,directorPhase:-1,waveNumber:0,waveRemaining:0,waveBreak:0,waveSeq:0,waveTitle:'NAPŁYW',snapshotClock:0}}
 updateSimulationPause(lobby){const g=lobby.game,wasPaused=g.paused,nextPaused=Boolean(g.upgradePaused||g.manualPaused||g.networkPaused),now=this.now();if(!wasPaused&&nextPaused){g.simulationPausedAt=now;clearPlayerInputs(g)}else if(wasPaused&&!nextPaused){const shift=Math.max(0,now-(g.simulationPausedAt||now));for(const player of Object.values(g.players))for(const key of['qReadyAt','eReadyAt','rReadyAt'])if(player.stats.cooldowns[key]>0)player.stats.cooldowns[key]+=shift;g.simulationPausedAt=0;clearPlayerInputs(g)}g.paused=nextPaused;return nextPaused}
 resumeUpgradeIfReady(lobby){if(!resumeAfterUpgrade(lobby))return false;this.updateSimulationPause(lobby);this.broadcast(lobby,'levelResume',{round:lobby.game.levelRound,matchId:lobby.game.matchId});this.broadcast(lobby,'pauseState',pauseState(lobby));return true}
 updateManualPause(lobby){const g=lobby.game,active=activeUpgradePlayers(lobby),activeIds=new Set(active.map(member=>member.id));for(const id of g.pauseRequests)if(!activeIds.has(id))g.pauseRequests.delete(id);const consensus=active.length>0&&active.every(member=>g.pauseRequests.has(member.id));if(!g.manualPaused)g.manualPaused=consensus;this.updateSimulationPause(lobby);this.broadcast(lobby,'pauseState',pauseState(lobby));return g.manualPaused}
 resumeManualPause(lobby){const g=lobby.game;g.manualPaused=false;g.pauseRequests.clear();this.updateSimulationPause(lobby)}
 offer(player,blocked=new Set(),limit){const candidates=Object.keys(DATA.items).filter(id=>(player.items[id]||0)<DATA.items[id].max&&((player.items[id]||0)>0||Object.keys(player.items).length<3)).map(id=>`item-${id}`);const aug=DATA.augments.filter(id=>!player.augments.includes(id)&&player.augments.length<3).map(id=>`augment-${id}`);const pool=[...candidates,...aug].filter(key=>!blocked.has(key));if(player.augments.includes('gambler'))pool.sort((a,b)=>(player.items[b.slice(5)]?1:0)-(player.items[a.slice(5)]?1:0)||this.random()-.5);else pool.sort(()=>this.random()-.5);return pool.slice(0,limit||(player.augments.includes('gambler')?2:3))}
 disconnect(client){if(!this.isCurrentConnection(client)){this.debug('disconnect ignored old generation',client);client.state='closed';this.connectionsById.delete(client.connectionId);return false}this.debug('disconnect accepted',client);client.state='closed';client.disconnectAt=this.now();const lobby=this.lobbies.get(client.lobby),m=lobby?.players.find(p=>p.id===client.playerId);if(m){m.connected=false;m.disconnectAt=this.now();if(lobby.game?.players[m.id])lobby.game.players[m.id].input={};this.resumeUpgradeIfReady(lobby);if(lobby.game){this.updateManualPause(lobby);if(!activeUpgradePlayers(lobby).length){lobby.game.networkPaused=true;this.updateSimulationPause(lobby);this.broadcast(lobby,'pauseState',pauseState(lobby))}}this.publish(lobby)}return true}
 leave(client,immediate=false){const lobby=this.lobbies.get(client.lobby);if(!lobby)return;const m=lobby.players.find(p=>p.id===client.playerId);if(immediate||!lobby.game)lobby.players=lobby.players.filter(p=>p.id!==client.playerId);else if(m){m.connected=false;m.disconnectAt=this.now()}client.lobby='';this.migrate(lobby);if(!lobby.players.length)this.lobbies.delete(lobby.code);else this.publish(lobby)}
 migrate(lobby){if(!lobby.players.some(p=>p.host&&p.connected)){lobby.players.forEach(p=>p.host=false);const next=lobby.players.find(p=>p.connected);if(next){next.host=true;next.ready=true}}}
 cleanup(){const now=this.now();for(const lobby of this.lobbies.values()){for(const m of [...lobby.players])if(!m.connected&&now-m.disconnectAt>GRACE_MS){lobby.players=lobby.players.filter(p=>p!==m);if(lobby.game)delete lobby.game.players[m.id]}this.migrate(lobby);const active=lobby.players.some(p=>p.connected),expired=!active&&now-lobby.updatedAt>GRACE_MS||!lobby.game&&now-lobby.updatedAt>LOBBY_TTL||lobby.game&&now-lobby.game.createdAt>GAME_TTL;this.resumeUpgradeIfReady(lobby);if(lobby.game){lobby.game.networkPaused=!activeUpgradePlayers(lobby).length;this.updateSimulationPause(lobby);this.updateManualPause(lobby)}if(!lobby.players.length||expired)this.lobbies.delete(lobby.code)}for(const[id,connection]of this.connectionsById)if(connection.state==='closed'&&now-connection.disconnectAt>GRACE_MS)this.connectionsById.delete(id);for(const[playerId,session]of this.sessionsByPlayerId)if(!this.lobbies.values().some(lobby=>lobby.players.some(player=>player.id===playerId))&&!this.isCurrentConnection(this.currentConnection(playerId)))this.sessionsByPlayerId.delete(playerId)}
 tick(lobby,dt){const g=lobby.game;if(!g||g.paused||g.ended)return;g.tick++;g.time+=dt;this.tickDirector(lobby,dt);for(const p of Object.values(g.players))this.tickPlayer(lobby,p,dt);for(const e of g.enemies)this.tickEnemy(lobby,e,dt);this.tickProjectiles(lobby,dt);this.tickPickups(lobby,dt);const dead=g.enemies.filter(e=>e.hp<=0);dead.forEach(e=>{g.orbs.push({id:crypto.randomUUID(),x:e.x,y:e.y,value:e.xp})});g.enemies=g.enemies.filter(e=>e.hp>0);if(g.ended||this.endIfDefeated(lobby))return;if(g.time>=g.bossAt&&!g.enemies.some(e=>e.type==='boss')){this.spawnEnemy(lobby,'boss');g.bossAt+=300}if(g.xp>=g.nextXp){const overflow=g.xp-g.nextXp,recycle=Object.values(g.players).some(p=>p.augments.includes('recycling'));g.xp=recycle?Math.floor(overflow*.6):0;g.level++;g.nextXp=Math.floor(g.nextXp*1.34);g.manualPaused=false;g.pauseRequests.clear();g.upgradePaused=true;this.updateSimulationPause(lobby);g.levelRound++;this.broadcast(lobby,'pauseState',pauseState(lobby));for(const m of lobby.players){m.choiceRound=0;const p=g.players[m.id];if(p){p.offer=[];p.rerolled=[]}}for(const m of activeUpgradePlayers(lobby)){const p=g.players[m.id];p.offer=this.offer(p);this.emit(this.currentConnection(m.id),'levelUp',{round:g.levelRound,level:g.level,offer:p.offer,matchId:g.matchId})}}g.snapshotClock+=dt;if(g.snapshotClock<1/SNAPSHOT_RATE)return;g.snapshotClock%=1/SNAPSHOT_RATE;this.broadcast(lobby,'gameState',{state:{matchId:g.matchId,serverTime:this.now(),tick:g.tick,time:g.time,level:g.level,xp:g.xp,nextXp:g.nextXp,paused:g.paused,pauseReason:g.upgradePaused?'upgrade':g.manualPaused?'manual':null,ended:g.ended,players:Object.values(g.players).map(p=>({id:p.id,name:p.name,character:p.character,x:p.x,y:p.y,hp:p.hp,maxHp:p.stats.maxHp,alive:p.alive,kills:p.kills,speed:p.stats.speed*(p.speedBuff>0?1.55:1),facing:p.facing,attackSeq:p.attackSeq,abilitySeq:p.abilitySeq,lastAbility:p.lastAbility,lastProcessedInputSeq:p.lastProcessedInputSeq,cooldowns:p.stats.cooldowns,items:p.items,augments:p.augments})),enemies:g.enemies.map(({id,type,x,y,hp,maxHp,r,elite})=>({id,type,x,y,hp,maxHp,r,elite})),bullets:g.bullets.map(({id,ownerId,x,y,vx,vy,r,kind,crit})=>({id,ownerId,x,y,vx,vy,r,kind,crit})),enemyBullets:g.enemyBullets.map(({id,x,y,vx,vy,r})=>({id,x,y,vx,vy,r})),orbs:g.orbs.map(({id,x,y,value})=>({id,x,y,value})),loot:g.loot.map(({id,x,y,type})=>({id,x,y,type})),crates:g.crates.map(({id,x,y,hp,maxHp,opened})=>({id,x,y,hp,maxHp,opened})),wave:{seq:g.waveSeq,title:g.waveTitle,phase:g.directorPhase,waveNumber:g.waveNumber,remaining:g.waveRemaining}}})}
 directorState(lobby){const g=lobby.game,cycle=Math.floor(g.time/300),time=g.time%300,difficulty=(1+cycle*.1)*(lobby.map==='toxic'?1.4:1),restScale=lobby.map==='toxic'?.7:1;if(time<120)return{id:cycle*3,title:'NAPŁYW',size:Math.round(6*difficulty),rest:7*restScale,pool:['melee','melee','melee','melee','swarm','brute']};if(time<240)return{id:cycle*3+1,title:'OSTRZAŁ',size:Math.round(7*difficulty),rest:8*restScale,pool:['shooter','shooter','melee','melee','exploder','swarm']};return{id:cycle*3+2,title:'ELITA',size:Math.round(5*difficulty),rest:10*restScale,pool:['charger','charger','brute','brute','shooter','exploder']}}
 tickDirector(lobby,dt){const g=lobby.game;if(g.enemies.some(e=>e.type==='boss'))return;const d=this.directorState(lobby);if(d.id!==g.directorPhase){g.directorPhase=d.id;g.waveNumber=1;g.waveRemaining=d.size;g.waveBreak=g.directorPhase===0?2:3;g.waveTitle=d.title;g.waveSeq++}if(g.waveBreak>0){g.waveBreak-=dt;return}if(g.waveRemaining<=0){g.waveBreak=d.rest;g.waveNumber++;g.waveRemaining=d.size;g.waveSeq++;return}g.spawn-=dt;if(g.spawn<=0){const pool=lobby.map==='toxic'?[...d.pool,'toxic','toxic','trapper']:d.pool;this.spawnEnemy(lobby,pool[Math.floor(this.random()*pool.length)]);g.waveRemaining--;g.spawn=.32}}
 spawnEnemy(lobby,type){
  const g=lobby.game,pool=['melee','melee','shooter','charger','brute','exploder','swarm'],kind=type||pool[Math.floor(this.random()*pool.length)],d=DATA.enemies[kind];
  const living=Object.values(g.players).filter(p=>p.alive&&lobby.players.find(m=>m.id===p.id)?.connected!==false),anchor=living[Math.floor(this.random()*living.length)]||{x:1500,y:1100};
  let x=anchor.x,y=anchor.y;for(let tries=0;tries<20;tries++){const a=this.random()*Math.PI*2,distance=620+this.random()*130,nx=Math.max(35,Math.min(2965,anchor.x+Math.cos(a)*distance)),ny=Math.max(35,Math.min(2165,anchor.y+Math.sin(a)*distance));if(!blocked(lobby.map,nx,ny,d.r)){x=nx;y=ny;break}}
  const greed=Object.values(g.players).some(p=>p.augments.includes('greed_curse')),scale=1+Math.min(g.time,900)*.0025,count=kind==='swarm'?5+Math.floor(this.random()*3):1;
  for(let i=0;i<count;i++){const a=this.random()*Math.PI*2,distance=kind==='swarm'?this.random()*38:0,nx=x+Math.cos(a)*distance,ny=y+Math.sin(a)*distance;if(blocked(lobby.map,nx,ny,d.r))continue;const hp=d.hp*scale*(greed?1.2:1);g.enemies.push({id:crypto.randomUUID(),type:kind,ai:d.ai,x:nx,y:ny,hp,maxHp:hp,r:d.r,speed:d.speed,damage:d.damage,xp:d.xp,shot:1})}
 }
 tickPlayer(lobby,p,dt){
  p.shot-=dt;p.secondChamber=(p.secondChamber||0)-dt;if(!p.alive)return;p.facing=Number.isFinite(p.input.aim)?p.input.aim:p.facing;p.invuln=Math.max(0,(p.invuln||0)-dt);const g=lobby.game,i=p.input,dx=(i.right?1:0)-(i.left?1:0),dy=(i.down?1:0)-(i.up?1:0),moving=Math.hypot(dx,dy)>.1,len=Math.hypot(dx,dy)||1;
  p.stillTime=moving?0:(p.stillTime||0)+dt;p.totemReady=p.stats.totem>0&&p.stillTime>=2;p.perfectionTime=(p.perfectionTime||0)+dt;p.perfectionStacks=p.augments.includes('perfectionist')?Math.min(5,Math.floor(p.perfectionTime/20)):0;
  if(p.stats.regen)this.heal(p,p.stats.regen*dt);if(p.speedBuff>0)p.speedBuff-=dt;const speed=p.stats.speed*(p.speedBuff>0?1.55:1),nx=p.x+dx/len*speed*dt,ny=p.y+dy/len*speed*dt;if(!blocked(lobby.map,nx,p.y,15))p.x=nx;if(!blocked(lobby.map,p.x,ny,15))p.y=ny;
  if(i.received&&p.character==='warrior'&&p.shot<=0){const target=this.aimTarget(g,p,105,i.aim);p.attackSeq++;if(target){this.damageEnemy(lobby,target,p.stats.damage,p,'attack');this.heal(p,p.powerBuff>0?5:2.2)}else{const crate=g.crates.find(c=>!c.opened&&Math.hypot(c.x-p.x,c.y-p.y)<105);if(crate){crate.hp-=p.stats.damage;if(crate.hp<=0)this.openCrate(g,crate)}}p.shot=p.stats.fireRate}else if(i.received&&p.shot<=0){this.firePlayer(lobby,p,i.aim,false);p.shot=p.stats.fireRate;if(p.augments.includes('second_chamber')&&p.secondChamber<=0){this.firePlayer(lobby,p,i.aim,true);p.secondChamber=4}}
  if(lobby.map==='toxic'&&(MAPS.toxic.toxicZones||[]).some(z=>Math.hypot(p.x-z.x,p.y-z.y)<z.r))this.damagePlayer(lobby,p,5*dt,null,'toxic');
 }
 aimTarget(g,p,range,aim){let result=null,best=range;for(const e of g.enemies){const d=Math.hypot(e.x-p.x,e.y-p.y),a=Math.atan2(e.y-p.y,e.x-p.x),diff=Math.abs(Math.atan2(Math.sin(a-aim),Math.cos(a-aim)));if(d<best&&diff<.8){best=d;result=e}}return result}
 firePlayer(lobby,p,aim,second){const g=lobby.game;if(!second)p.attackSeq++;const count=p.stats.projectiles;for(let n=0;n<count;n++){const spread=(n-(count-1)/2)*(p.character==='druid'?.09:.12),a=aim+spread,crit=this.random()<p.stats.critChance,totem=p.totemReady?1+p.stats.totem:1,perfect=1+(p.perfectionStacks||0)*.08,adrenaline=1+(1-p.hp/p.stats.maxHp)*(p.stats.adrenaline||0);g.bullets.push({id:crypto.randomUUID(),ownerId:p.id,x:p.x,y:p.y,vx:Math.cos(a)*p.stats.projectileSpeed,vy:Math.sin(a)*p.stats.projectileSpeed,r:p.stats.projectileSize,life:p.stats.projectileLife,damage:p.stats.damage*totem*perfect*adrenaline*(crit?p.stats.critDamage:1),crit,pierce:p.stats.pierce+(p.character==='druid'?3:0),kind:p.character==='druid'?'boomerang':'scoutBullet',second})}}
 castAbility(lobby,p,key,aim){const def=DATA.characters[p.character].abilities[key],now=this.now(),readyKey=`${key}ReadyAt`,cooling=now<p.stats.cooldowns[readyKey];if(cooling){if(!p.augments.includes('blood_price')||p.hp<=p.stats.maxHp*.12+1)return false;this.damagePlayer(lobby,p,p.stats.maxHp*.12,null,'blood_price',true)}p.stats.cooldowns[readyKey]=now+def.cooldown*p.cooldownScale*1000;p.abilitySeq++;p.lastAbility=key;const g=lobby.game;if(p.character==='scout'){if(key==='q')for(let n=-2;n<=2;n++)g.bullets.push({id:crypto.randomUUID(),ownerId:p.id,x:p.x,y:p.y,vx:Math.cos(aim+n*.11)*720,vy:Math.sin(aim+n*.11)*720,r:7,life:.7,damage:30,pierce:2,kind:'scoutBullet'});else for(const e of g.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<def.radius){this.damageEnemy(lobby,e,def.damage,p,`ability-${key}`);if(key==='e'){p.invuln=1;const a=Math.atan2(e.y-p.y,e.x-p.x),nx=e.x+Math.cos(a)*70,ny=e.y+Math.sin(a)*70;if(!blocked(lobby.map,nx,ny,e.r)){e.x=nx;e.y=ny}}}}else if(p.character==='warrior'){if(key==='q'){for(const e of g.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<def.radius)this.damageEnemy(lobby,e,def.damage,p,'ability-q');this.heal(p,p.powerBuff>0?12:6)}if(key==='e'){for(let d=190;d>20;d-=10){const nx=p.x+Math.cos(aim)*d,ny=p.y+Math.sin(aim)*d;if(!blocked(lobby.map,nx,ny,15)){p.x=nx;p.y=ny;break}}}if(key==='r')p.powerBuff=9}else{if(key==='q')for(const ally of Object.values(g.players))if(ally.alive&&Math.hypot(ally.x-p.x,ally.y-p.y)<175)this.heal(ally,28);if(key==='e')for(const ally of Object.values(g.players))if(ally.alive&&Math.hypot(ally.x-p.x,ally.y-p.y)<220)ally.speedBuff=6;if(key==='r'){for(const ally of Object.values(g.players))if(ally.alive)this.heal(ally,ally.stats.maxHp);p.stats.cooldowns.qReadyAt=now;p.stats.cooldowns.eReadyAt=now}}return true}
 damageEnemy(lobby,e,raw,owner,source){if(e.hp<=0)return 0;let damage=raw;if(owner){if(owner.powerBuff>0)damage*=1.65;if(owner.augments.includes('executor')&&e.hp/e.maxHp<.25)damage*=1.3;if(owner.augments.includes('giant_hunter'))damage*=e.type==='boss'||e.elite?1.35:.9}const dealt=Math.min(e.hp,damage);e.hp-=damage;e.lastHit={ownerId:owner?.id||null,source};if(e.hp<=0&&owner){owner.kills++;if(owner.stats.lifesteal)this.heal(owner,owner.stats.lifesteal*(owner.augments.includes('parasite')?2:1));if(owner.stats.powder&&this.random()<owner.stats.powder){for(const other of lobby.game.enemies)if(other!==e&&Math.hypot(other.x-e.x,other.y-e.y)<90)this.damageEnemy(lobby,other,12*(owner.items.powder||1),owner,'powder')}}return dealt}
 damagePlayer(lobby,p,amount,source,kind,bypass=false){if(!p.alive||!bypass&&(p.invuln||0)>0)return 0;const damage=Math.min(p.hp,amount);p.hp-=amount;p.perfectionTime=0;p.perfectionStacks=0;if(p.hp<=0){if(!bypass&&p.augments.includes('last_chance')&&(p.lastChance||0)<=0){p.hp=1;p.lastChance=180;if(p.items.spikes)for(const e of lobby.game.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<220)this.damageEnemy(lobby,e,60,p,'last_chance')}else{p.hp=0;p.alive=false;p.input={};p.offer=[];lobby.game.pauseRequests.delete(p.id);if(!this.endIfDefeated(lobby)){this.resumeUpgradeIfReady(lobby);this.updateManualPause(lobby)}}}return damage}
 endIfDefeated(lobby){const g=lobby.game;if(!g||g.ended||Object.values(g.players).some(p=>p.alive))return false;g.ended=true;g.upgradePaused=false;g.manualPaused=false;g.pauseRequests.clear();g.simulationPausedAt=0;g.paused=false;clearPlayerInputs(g);this.broadcast(lobby,'gameOver',{reason:'allPlayersDead',matchId:g.matchId});return true}
 heal(p,amount){if(p.augments.includes('parasite'))amount*=.5;p.hp=Math.min(p.stats.maxHp,p.hp+amount)}
 tickEnemy(lobby,e,dt){const g=lobby.game,players=Object.values(g.players).filter(p=>p.alive&&lobby.players.find(m=>m.id===p.id)?.connected!==false);if(!players.length)return;let target=null,best=Infinity;for(const p of players){const d=Math.hypot(p.x-e.x,p.y-e.y);if(d<best){best=d;target=p}}e.targetId=target.id;e.attack=(e.attack||0)-dt;e.special=(e.special||0)-dt;const angle=Math.atan2(target.y-e.y,target.x-e.x),move=scale=>{const nx=e.x+Math.cos(angle)*e.speed*dt*scale,ny=e.y+Math.sin(angle)*e.speed*dt*scale;if(!blocked(lobby.map,nx,e.y,e.r))e.x=nx;if(!blocked(lobby.map,e.x,ny,e.r))e.y=ny};
  if(e.ai==='shooter'){if(best>260)move(1);if(e.attack<=0&&best<560){g.enemyBullets.push({id:crypto.randomUUID(),ownerId:e.id,x:e.x,y:e.y,vx:Math.cos(angle)*260,vy:Math.sin(angle)*260,r:6,life:3,damage:e.damage});e.attack=1.75}}
  else if(e.ai==='charger'){if(e.charging>0){const nx=e.x+e.chargeX*430*dt,ny=e.y+e.chargeY*430*dt;if(blocked(lobby.map,nx,ny,e.r))e.charging=0;else{e.x=nx;e.y=ny;e.charging-=dt}}else if(e.special<=0&&best<470){e.chargeX=Math.cos(angle);e.chargeY=Math.sin(angle);e.charging=.55;e.special=3}else move(1)}
  else if(e.ai==='trapper'){move(.8);if(e.special<=0){g.hazards.push({id:crypto.randomUUID(),type:'trap',x:e.x,y:e.y,r:28,life:12});e.special=4}}
  else if(e.ai==='toxic'){move(1);if(e.special<=0){g.hazards.push({id:crypto.randomUUID(),type:'toxic',x:e.x,y:e.y,r:48,life:4});e.special=2.4}}
  else if(e.ai==='boss'){move(1);if(e.special<=0){for(let n=0;n<12;n++){const a=n*Math.PI/6;g.enemyBullets.push({id:crypto.randomUUID(),ownerId:e.id,x:e.x,y:e.y,vx:Math.cos(a)*210,vy:Math.sin(a)*210,r:8,life:4,damage:14})}e.special=3}}
  else move(e.ai==='swarm'?1.1:1);
  if(best<e.r+15&&e.attack<=0){if(e.ai==='exploder'){for(const p of players)if(Math.hypot(p.x-e.x,p.y-e.y)<145)this.damagePlayer(lobby,p,e.damage,e,'explosion');e.hp=0;e.lastHit={ownerId:null,source:'explosion'}}else{this.damagePlayer(lobby,target,e.damage,e,'contact');if(target.stats.thorns)this.damageEnemy(lobby,e,target.stats.thorns,target,'thorns')}e.attack=e.ai==='swarm'?.55:1}
 }
 tickProjectiles(lobby,dt){const g=lobby.game,enemyGrid=createSpatialGrid(g.enemies);for(const b of g.bullets){if(b.kind==='boomerang'&&!b.returning&&b.life<.9){b.vx*=-1;b.vy*=-1;b.returning=true}b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(blocked(lobby.map,b.x,b.y,b.r))b.life=0;for(const e of spatialCandidates(enemyGrid,b.x,b.y))if(b.life>0&&e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){this.damageEnemy(lobby,e,b.damage,g.players[b.ownerId],'projectile');if(--b.pierce<0)b.life=0}for(const c of g.crates)if(b.life>0&&!c.opened&&Math.hypot(b.x-c.x,b.y-c.y)<b.r+18){c.hp-=b.damage;b.life=0;if(c.hp<=0)this.openCrate(g,c)}}g.bullets=g.bullets.filter(b=>b.life>0);for(const b of g.enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(blocked(lobby.map,b.x,b.y,b.r))b.life=0;for(const p of Object.values(g.players))if(b.life>0&&p.alive&&Math.hypot(b.x-p.x,b.y-p.y)<b.r+15){this.damagePlayer(lobby,p,b.damage,null,'projectile');b.life=0}}g.enemyBullets=g.enemyBullets.filter(b=>b.life>0)}
 openCrate(g,c){c.opened=true;const roll=this.random(),type=roll<.08?'coin':roll<.44?'health':roll<.8?'xp':'level';g.loot.push({id:crypto.randomUUID(),x:c.x,y:c.y-8,type,value:type==='xp'?15:type==='health'?35:1})}
 tickPickups(lobby,dt){const g=lobby.game,players=Object.values(g.players).filter(p=>p.alive&&lobby.players.find(m=>m.id===p.id)?.connected!==false);for(const orb of g.orbs){let nearest=null,best=Infinity;for(const p of players){const d=Math.hypot(p.x-orb.x,p.y-orb.y);if(d<best){best=d;nearest=p}}if(nearest&&best<nearest.stats.magnet){const a=Math.atan2(nearest.y-orb.y,nearest.x-orb.x),speed=best<35?700:260;const step=Math.min(best,speed*dt);orb.x+=Math.cos(a)*step;orb.y+=Math.sin(a)*step;if(best<18||step>=best){g.xp+=orb.value;orb.collected=true}}}g.orbs=g.orbs.filter(o=>!o.collected);for(const item of g.loot){const p=players.find(x=>Math.hypot(x.x-item.x,x.y-item.y)<24);if(!p)continue;if(item.type==='health')this.heal(p,item.value);else if(item.type==='xp')g.xp+=item.value;else if(item.type==='coin')p.coins=(p.coins||0)+item.value*(p.augments.includes('greed_curse')?2:1);else if(item.type==='level')g.xp=g.nextXp;item.collected=true}g.loot=g.loot.filter(x=>!x.collected);for(const h of g.hazards){h.life-=dt;for(const p of players)if(Math.hypot(p.x-h.x,p.y-h.y)<h.r)this.damagePlayer(lobby,p,(h.type==='trap'?6:5)*dt,null,h.type)}g.hazards=g.hazards.filter(h=>h.life>0);for(const p of players){p.lastChance=Math.max(0,(p.lastChance||0)-dt);p.powerBuff=Math.max(0,(p.powerBuff||0)-dt);p.coinClock=(p.coinClock||0)+dt;if(p.coinClock>=60){p.coins=(p.coins||0)+1+(p.stats.vault?1:0);p.coinClock-=60}}}
}
function createFixedStepper(step=1/TICK_RATE,maxSteps=5,maxGap=.25){let accumulator=0;return elapsed=>{accumulator+=Math.min(maxGap,Math.max(0,elapsed));const steps=Math.min(maxSteps,Math.floor(accumulator/step));accumulator-=steps*step;if(steps===maxSteps)accumulator=Math.min(accumulator,step);return steps}}
function createStaticHandler(){return(req,res)=>{let name;try{name=req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]).slice(1)}catch{res.writeHead(400);return res.end('Bad Request')}if(!publicFiles.has(name)){res.writeHead(404);return res.end('Not found')}fs.readFile(path.join(__dirname,name),(error,data)=>{if(error){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8','cache-control':'no-cache'});res.end(data)})}}
function createHttpServer(core=new GameServer()){const server=http.createServer(createStaticHandler());const{WebSocketServer}=require('ws'),wss=new WebSocketServer({server,maxPayload:4096});wss.on('connection',ws=>{let alive=true;const client=core.addClient(payload=>{if(ws.readyState===1)ws.send(typeof payload==='string'?payload:JSON.stringify(payload))});client.sendRaw=payload=>{if(ws.readyState===1)ws.send(payload)};client.close=(code,reason)=>ws.close(code,reason);client.supersede=()=>ws.close(4001,'Superseded');ws.on('pong',()=>alive=true);ws.on('message',(raw,isBinary)=>{if(isBinary||raw.length>4096)return ws.close(1008,'Invalid payload');try{core.handle(client,JSON.parse(raw.toString()))}catch{core.emit(client,'error',{message:'Nieprawidłowa wiadomość.'})}});ws.on('close',()=>core.disconnect(client));client.heartbeat=()=>{if(!alive)return ws.terminate();alive=false;ws.ping()}});const heartbeat=setInterval(()=>core.connectionsById.forEach(c=>{if(core.isCurrentConnection(c))c.heartbeat?.()}),10000),stepper=createFixedStepper(),step=1/TICK_RATE;let lastLoop=performance.now();const gameLoop=setInterval(()=>{const now=performance.now(),steps=stepper((now-lastLoop)/1000);lastLoop=now;for(let i=0;i<steps;i++)core.lobbies.forEach(l=>core.tick(l,step))},8),cleanup=setInterval(()=>core.cleanup(),5000);for(const t of[heartbeat,gameLoop,cleanup])t.unref();server.on('close',()=>{clearInterval(heartbeat);clearInterval(gameLoop);clearInterval(cleanup);wss.close()});return{server,wss,core}}
if(require.main===module){const{server}=createHttpServer();server.listen(PORT,()=>console.log(`Swarmfall server: http://localhost:${PORT}`))}
module.exports={GameServer,createHttpServer,createStaticHandler,publicFiles,activeUpgradePlayers,resumeAfterUpgrade,createFixedStepper,createSpatialGrid,spatialCandidates,applyUpgrade,blocked,DATA,TICK_RATE,SNAPSHOT_RATE};
