'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT)||8080,TICK_RATE=25,ROOT=__dirname,MAX_PLAYERS=4;
const lobbies=new Map(),clients=new Map(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const publicFiles=new Set(['index.html','style.css','game.js','enemy-data.js','map-data.js','enemy-visuals.js','feedback.js','achievements.js','upgrade-data.js','settings-data.js','multiplayer.js','multiplayer-game.js']);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
function staticHandler(req,res){const name=req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]).slice(1);if(!publicFiles.has(name)){res.writeHead(404);return res.end('Not found')}fs.readFile(path.join(ROOT,name),(error,data)=>{if(error){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(name)]||'application/octet-stream','cache-control':'no-cache'});res.end(data)})}
const server=http.createServer(staticHandler);
function frame(payload){const data=Buffer.from(JSON.stringify(payload));let header;if(data.length<126)header=Buffer.from([0x81,data.length]);else if(data.length<65536)header=Buffer.from([0x81,126,data.length>>8,data.length&255]);else{header=Buffer.alloc(10);header[0]=0x81;header[1]=127;header.writeBigUInt64BE(BigInt(data.length),2)}return Buffer.concat([header,data])}
function send(client,type,data={}){if(client?.socket&&!client.socket.destroyed)client.socket.write(frame({type,...data}))}
function broadcast(lobby,type,data={}){lobby.players.forEach(player=>send(clients.get(player.id),type,data))}
function parseFrames(client,chunk){client.buffer=Buffer.concat([client.buffer,chunk]);while(client.buffer.length>=2){let length=client.buffer[1]&127,offset=2;if(length===126){if(client.buffer.length<4)return;length=client.buffer.readUInt16BE(2);offset=4}if(length===127)return client.socket.destroy();const masked=Boolean(client.buffer[1]&128);if(masked)offset+=4;if(client.buffer.length<offset+length)return;let payload=client.buffer.subarray(offset,offset+length);if(masked){const mask=client.buffer.subarray(offset-4,offset);payload=Buffer.from(payload);for(let i=0;i<payload.length;i++)payload[i]^=mask[i%4]}const opcode=client.buffer[0]&15;client.buffer=client.buffer.subarray(offset+length);if(opcode===8)return client.socket.end();if(opcode===9){client.socket.write(Buffer.from([0x8a,0]));continue}if(opcode===1){try{handle(client,JSON.parse(payload.toString()))}catch{send(client,'error',{message:'Nieprawidłowa wiadomość.'})}}}}
function lobbyView(lobby){return{code:lobby.code,map:lobby.map,started:Boolean(lobby.game),players:lobby.players.map(({id,name,host,ready,character,connected})=>({id,name,host,ready,character,connected}))}}
function publishLobby(lobby){broadcast(lobby,'lobbyState',{lobby:lobbyView(lobby)})}
function code(){let value;do{value=Array.from({length:6},()=>alphabet[Math.floor(Math.random()*alphabet.length)]).join('')}while(lobbies.has(value));return value}
function leave(client){const lobby=lobbies.get(client.lobby);if(!lobby)return;const player=lobby.players.find(p=>p.id===client.id);if(player)player.connected=false;client.lobby='';if(!lobby.game){setTimeout(()=>{if(!player?.connected){lobby.players=lobby.players.filter(p=>p.id!==client.id);if(player?.host&&lobby.players[0]){lobby.players[0].host=true;lobby.players[0].ready=true}if(!lobby.players.length)lobbies.delete(lobby.code);else publishLobby(lobby)}},10000)}else publishLobby(lobby)}
function createGame(lobby){const players={};lobby.players.forEach((p,i)=>players[p.id]={id:p.id,name:p.name,character:p.character,x:1500+Math.cos(i*Math.PI/2)*55,y:1100+Math.sin(i*Math.PI/2)*55,hp:p.character==='warrior'?130:p.character==='druid'?110:100,maxHp:p.character==='warrior'?130:p.character==='druid'?110:100,kills:0,input:{},shot:0});lobby.game={tick:0,time:0,level:1,xp:0,nextXp:24,paused:false,levelRound:0,players,enemies:[],bullets:[],spawn:0}}
function validCharacter(client,id){return Array.isArray(client.unlocked)&&client.unlocked.includes(id)}
function handle(client,msg){const lobby=lobbies.get(client.lobby),player=lobby?.players.find(p=>p.id===client.id);switch(msg.type){
 case'hello':{const old=clients.get(String(msg.clientId));if(old&&old!==client)old.socket.destroy();clients.delete(client.id);client.id=String(msg.clientId||client.id).slice(0,80);client.unlocked=['scout',...(Array.isArray(msg.unlocked)?msg.unlocked:[])].filter(x=>['scout','warrior','druid'].includes(x));clients.set(client.id,client);for(const found of lobbies.values()){const reconnect=found.players.find(p=>p.id===client.id);if(reconnect){reconnect.connected=true;client.lobby=found.code;send(client,'lobbyState',{lobby:lobbyView(found)});if(found.game)send(client,'gameStarted',{lobby:lobbyView(found)});break}}break}
 case'createLobby':leave(client);{const id=code(),created={code:id,map:'ruins',players:[{id:client.id,name:'Gospodarz',host:true,ready:true,character:validCharacter(client,msg.character)?msg.character:'scout',connected:true}],game:null};lobbies.set(id,created);client.lobby=id;publishLobby(created)}break;
 case'joinLobby':leave(client);{const target=lobbies.get(String(msg.code||'').toUpperCase());if(!target||target.game)return send(client,'joinError',{message:'Nie znaleziono dostępnego lobby.'});if(target.players.length>=MAX_PLAYERS)return send(client,'joinError',{message:'Lobby jest pełne.'});target.players.push({id:client.id,name:`Gracz ${target.players.length+1}`,host:false,ready:false,character:validCharacter(client,msg.character)?msg.character:'scout',connected:true});client.lobby=target.code;publishLobby(target)}break;
 case'selectMap':if(player?.host&&!lobby.game&&['ruins','toxic'].includes(msg.map)){lobby.map=msg.map;lobby.players.forEach(p=>{if(!p.host)p.ready=false});publishLobby(lobby)}break;
 case'selectCharacter':if(player&&!lobby.game&&validCharacter(client,msg.character)){player.character=msg.character;if(!player.host)player.ready=false;publishLobby(lobby)}break;
 case'playerReady':if(player&&!player.host&&!lobby.game){player.ready=Boolean(msg.ready);publishLobby(lobby)}break;
 case'startGame':if(player?.host&&!lobby.game&&lobby.players.length&&lobby.players.filter(p=>!p.host).every(p=>p.ready)){createGame(lobby);broadcast(lobby,'gameStarted',{lobby:lobbyView(lobby)})}break;
 case'playerInput':if(lobby?.game?.players[client.id])lobby.game.players[client.id].input={up:!!msg.up,down:!!msg.down,left:!!msg.left,right:!!msg.right,aim:Number(msg.aim)||0,q:!!msg.q,e:!!msg.e,r:!!msg.r};break;
 case'upgradeChoice':if(lobby?.game?.paused&&player){player.choiceRound=lobby.game.levelRound;player.upgrade=String(msg.choice||'').slice(0,60);if(lobby.players.filter(p=>p.connected).every(p=>p.choiceRound===lobby.game.levelRound))lobby.game.paused=false}break;
 }}
server.on('upgrade',(req,socket)=>{if((req.headers.upgrade||'').toLowerCase()!=='websocket')return socket.destroy();const accept=crypto.createHash('sha1').update(req.headers['sec-websocket-key']+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`);const client={id:crypto.randomUUID(),socket,buffer:Buffer.alloc(0),lobby:'',unlocked:['scout']};clients.set(client.id,client);socket.on('data',chunk=>parseFrames(client,chunk));socket.on('close',()=>{leave(client);clients.delete(client.id)});socket.on('error',()=>{})});
const MAP_TERRAIN={ruins:[{type:'wall',x:840,y:360,w:390,h:42},{type:'wall',x:1190,y:360,w:42,h:290},{type:'wall',x:1830,y:720,w:42,h:430},{type:'wall',x:1830,y:1108,w:390,h:42},{type:'rock',x:1530,y:470,r:77},{type:'rock',x:2450,y:520,r:97},{type:'rock',x:1530,y:1280,r:88}],toxic:[{type:'wall',x:620,y:430,w:480,h:38},{type:'wall',x:2030,y:620,w:38,h:460},{type:'rock',x:1480,y:620,r:88},{type:'rock',x:2290,y:1510,r:101}]};
function serverBlocked(map,x,y,r){if(x<35+r||y<35+r||x>2965-r||y>2165-r)return true;return(MAP_TERRAIN[map]||[]).some(t=>t.type==='rock'?Math.hypot(x-t.x,y-t.y)<r+t.r:x+r>t.x&&x-r<t.x+t.w&&y+r>t.y&&y-r<t.y+t.h)}
function spawnEnemy(game){const angle=Math.random()*Math.PI*2,distance=650;game.enemies.push({id:crypto.randomUUID(),x:1500+Math.cos(angle)*distance,y:1100+Math.sin(angle)*distance,hp:35,maxHp:35,r:13,speed:72})}
function tickLobby(lobby,dt){const g=lobby.game;if(!g||g.paused)return;g.tick++;g.time+=dt;g.spawn-=dt;if(g.spawn<=0){spawnEnemy(g);g.spawn=Math.max(.35,1.5-g.time/300)}
 for(const p of Object.values(g.players)){const input=p.input||{},dx=(input.right?1:0)-(input.left?1:0),dy=(input.down?1:0)-(input.up?1:0),len=Math.hypot(dx,dy)||1,speed=p.character==='warrior'?220:p.character==='druid'?235:250;const nx=p.x+dx/len*speed*dt,ny=p.y+dy/len*speed*dt;if(!serverBlocked(lobby.map,nx,p.y,15))p.x=nx;if(!serverBlocked(lobby.map,p.x,ny,15))p.y=ny;p.shot-=dt;p.q=(p.q||0)-dt;p.e=(p.e||0)-dt;p.r=(p.r||0)-dt;if(input.q&&p.q<=0){p.q=5;for(const e of g.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<160)e.hp-=30}if(input.e&&p.e<=0){p.e=9;for(const e of g.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<190){const a=Math.atan2(e.y-p.y,e.x-p.x),ex=e.x+Math.cos(a)*55,ey=e.y+Math.sin(a)*55;if(!serverBlocked(lobby.map,ex,ey,e.r)){e.x=ex;e.y=ey}}}if(input.r&&p.r<=0){p.r=28;for(const e of g.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<450)e.hp-=90}if(p.shot<=0){g.bullets.push({id:crypto.randomUUID(),owner:p.id,x:p.x,y:p.y,vx:Math.cos(input.aim)*570,vy:Math.sin(input.aim)*570,life:1.3,damage:p.character==='druid'?12:14});p.shot=.62}}
 for(const e of g.enemies){let target=null,best=Infinity;for(const p of Object.values(g.players)){const d=Math.hypot(p.x-e.x,p.y-e.y);if(d<best){best=d;target=p}}if(target){const a=Math.atan2(target.y-e.y,target.x-e.x);const ex=e.x+Math.cos(a)*e.speed*dt,ey=e.y+Math.sin(a)*e.speed*dt;if(!serverBlocked(lobby.map,ex,e.y,e.r))e.x=ex;if(!serverBlocked(lobby.map,e.x,ey,e.r))e.y=ey;if(best<e.r+15&&target.hp>0)target.hp=Math.max(0,target.hp-12*dt)}}
 for(const b of g.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of g.enemies)if(b.life>0&&e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<e.r+5){e.hp-=b.damage;b.life=0}}
 const dead=g.enemies.filter(e=>e.hp<=0);for(const e of dead){const owner=Object.values(g.players)[Math.floor(Math.random()*Object.keys(g.players).length)];if(owner)owner.kills++;g.xp+=3}g.enemies=g.enemies.filter(e=>e.hp>0);g.bullets=g.bullets.filter(b=>b.life>0);
 if(g.xp>=g.nextXp){g.xp-=g.nextXp;g.level++;g.nextXp=Math.floor(g.nextXp*1.34);g.paused=true;g.levelRound++;lobby.players.forEach(p=>p.choiceRound=0);broadcast(lobby,'levelUp',{round:g.levelRound,level:g.level})}
 broadcast(lobby,'gameState',{state:{tick:g.tick,time:g.time,level:g.level,xp:g.xp,nextXp:g.nextXp,paused:g.paused,players:Object.values(g.players),enemies:g.enemies,bullets:g.bullets}})}
const gameLoop=setInterval(()=>lobbies.forEach(lobby=>tickLobby(lobby,1/TICK_RATE)),1000/TICK_RATE);gameLoop.unref();
if(require.main===module)server.listen(PORT,()=>console.log(`Swarmfall server: http://localhost:${PORT}`));
module.exports={server,lobbies,tickLobby};
